### ISSUE TITLE
Incomplete License Conversion? 

### ISSUE THREAD

**Issue by kphillisjr** [paulrosen/abcjs#100]
A few years ago this project was re-licensed from the GNU General Public License version 3 to MIT License( see: c18c8e25a1883852bb37c898b76a232deb6aee6b ), but the conversion was incomplete. Is there any chance to get most of the remaining files updated to use the MIT License header?

Also, as a quick note, The sprintf library used by this project is no longer under GPL Licensing ( see: https://github.com/alexei/sprintf.js )

**Comment by paulrosen** [comment]
Ok, done.
