### ISSUE TITLE
TimingCallbacks clarification/bug?

### ISSUE THREAD

**Issue by dbadb** [paulrosen/abcjs#1000]
I was dabbling with getting performance info from abcjs using the TimingCallbacks feature.  Seems to work but for the fact that the midiPitches array is always empty.  This can also be seen in the output of the example found [here](https://paulrosen.github.io/abcjs/animation/timing-callbacks.html#eventcallback) (at bottom).

Is this a work-in-progress, a bug or perhaps a misunderstanding on my part?

Thanks!

**Comment by dbadb** [comment]
Upon inspection of synth-controller.js, this interesting comment perhaps lights the path: 

`Need to create the TimingCallbacks after priming the midi so that the midi data is available for the callbacks.`

**Comment by paulrosen** [comment]
midiPitches is only set if you do the setUpAudio call. That call is also done if you initialize the synth

**Comment by dbadb** [comment]
thanks for the clarification! closing issue.
