### ISSUE TITLE
Changing Clef on next line.

### ISSUE THREAD

**Issue by huyla1903** [paulrosen/abcjs#1002]
Hi, I put a [K: C clef=bass] at the end of second [V:V1]
that I want the third [V:V1] start with Bass clef sign instead of Treble Clef sign.

Also for the fourth group, upper line should start with Bass Clef sign until I change it back to Bass Clef sign in the middle with [K: C clef=treble].
Don't know what I'm doing wrong here. I just start using this for a week. So please correct me. Appreciate any help!

```music-abc
X: 1
T: Marche Slav
C: Pyotr Ilyich Tchaikovsky
C: 1840-1893
R: Moderato
M: 4/4
L: 1/4
K: C
V: V1 clef = treble
V: Vc clef = bass
[V:V1] ("5" E2 "4" _D "3"C/"2"B,/ | A,3) ("2" B,/C/ | "5" E) (E _D C/B,/ | A,3) z |
w: | A
[V:Vc] z "1""5"[A,,E,] z [A,,F,] | z [A,,E,] [A,,E,] [A,,E,] | z [A,,E,] z [A,,F,] | z [A,,E,] [A,,E,] [A,,E,] |
w: AE AF
[V:V1] "2" B, D C B, | "1"A,/"2"^G,/"1"A,/"2"B,/ "3" C A, | "5" E/E/ ^D C B,/A,/ | "2" B,4 [K: C clef=bass] |
[V:Vc] z [A,,F,] z [A,,F,] | z [A,,E,] z [A,,E,] | z [A,,F,] z [A,,F,] | z "1""2"[D,E,] "1""3"[C,E,] "1""4"[B,,E,] |
w: | | | DE CE BE
[V:V1] ("5" E2 ^D C/B,/ | A,3) ("2" B,/C/ | E) (E ^D C/B,/ | A,3) z |
w: E
[V:Vc] z [A,,E,] z [A,,F,] | z [A,,E,] [A,,E,] [A,,E,] | z [A,,E,] z [A,,F,] | z [A,,E,] [A,,E,] [A,,E,] |
w: AE AF
[V:V1] "2" B, D C B, | "1"A,/"2"^G,/"1"A,/B,/ C A, [K: C clef=treble] | E/E/ ^D C B,/A,/ |
[V:Vc] z [A,,F,] z [A,,F,] | z [A,,E,] z [A,,E,] | z4 |
[V:V1] z4 | "3""1"[A,2C2] "4""2" [B,2D2] | [A,4C4] |]
[V:Vc] E,/E,/ ^D, C, B,,/A,,/ | E,2 E,2 | "1""5"[A,,4E,4] |]
```

**Comment by paulrosen** [comment]
I'm not sure but at first glance it works if you put the changes on different lines. Here's an excerpt of the above:
```
V:V1
K: C clef=bass
("5" E2 ^D C/B,/ | A,3) ("2" B,/C/ | E) (E ^D C/B,/ | A,3) z |
w: E
```

**Comment by huyla1903** [comment]
> I'm not sure but at first glance it works if you put the changes on different lines. Here's an excerpt of the above:
> 
> ```
> V:V1
> K: C clef=bass
> ("5" E2 ^D C/B,/ | A,3) ("2" B,/C/ | E) (E ^D C/B,/ | A,3) z |
> w: E
> ```

Yes it works for me. Appreciated.
