### ISSUE TITLE
Cannot click to select barline

### ISSUE THREAD

**Issue by woody-li** [paulrosen/abcjs#1004]
When clicked at barline, the nearly note is automatically selected.
But barlines can be selected with arrow keys.

So is it the right behavior?
If so, is it possible to add an option to control?

**Comment by paulrosen** [comment]
There is a parameter that might help you:
```
renderAbc(e;, abc { selectTypes: true }`
```
See https://paulrosen.github.io/abcjs/visual/dragging.html

**Comment by woody-li** [comment]
Got it, thanks
