### ISSUE TITLE
0 note-length doesn't work with chords

### ISSUE THREAD

**Issue by ShacharHarshuv** [paulrosen/abcjs#1035]
The cod `C0` produces:

![image](https://github.com/user-attachments/assets/2e95b08f-1767-43a0-9d92-6f661bd7a019)

With no errors

The code `[CE]1` produces:

![image](https://github.com/user-attachments/assets/b7b1319a-1f21-4138-8a12-9b71389e6497)

With no errors.

Therefore - I expect `[CE]0` to display a duration-less chord, but the "0" is not interpreted. It's defaulting to an eight, and have the following error "Music Line:1:5: Unknown character ignored: [CE]0"

I believe this is a bug (or an uncompleted feature). Also - is there a workaround for this that I'm not aware of?

**Comment by paulrosen** [comment]
That is a bug! It will be fixed soon. Thanks for the report.
