### ISSUE TITLE
Accents and lyrics are misplaced when stems are forced up

### ISSUE THREAD

**Issue by alex-drumrudiments** [paulrosen/abcjs#1036]
Hi Paul, when stem=up, the accents and lyrics are sometimes positioned as if the stems are down.

<img width="351" alt="Screenshot 2024-07-21 at 18 50 15" src="https://github.com/user-attachments/assets/5d5aef54-d84d-4a5d-8260-19e10a4b94d1">

This was not the case in the previous version I was using (4.2.3). The issue was introduced in a recent version.

Thanks

**Comment by paulrosen** [comment]
That does look like a bug.

Do you have the abc string you used to produce the above?
