### ISSUE TITLE
Problem with chords

### ISSUE THREAD

**Issue by Shiehallion** [paulrosen/abcjs#105]
Hi Paul! 
First: Thank you for the ABC Notation Plugin! It's a great idea!
But I have problems with chords. The tune without chords looks good:

[abcjs engraver="{ staffwidth:600 }"]
X: 1
T: Far From Home
R: reel
M: 4/4 L: 1/8
K: G
|:GEDE G2GA | B2BA Bcd2 | GEDE G2GB | A2AB AGED |
| GEDE G2GA | B2BA Bcd2 | edef gedc | BGAF G4 :|
|:g2ge f2fd | edef edB2 | gedB G2GB | A2AB AGED |
| GEDE G2GA | B2BA Bcd2 | edef gedc | BGAF G4 :|
[/abcjs]
﻿
<img width="604" alt="grafik" src="https://user-images.githubusercontent.com/31062317/29353744-8cb57ea4-826b-11e7-9c3b-f5f3857fb435.png">

But when I add chords it looks so:

[abcjs engraver="{ staffwidth:600 }"]
X: 1
T: Far From Home
R: reel
M: 4/4 L: 1/8
K: G
|:"G"GEDE G2GA | B2BA Bcd2 | "G"GEDE "Em"G2GB | "Am"A2AB "D7"AGED |
| "G"GEDE G2GA | "Bm"B2BA Bcd2 | "C"edef "(G)"gedc | "D7"BGAF "G"G4 :|
|:"Em"g2ge "D"f2fd | "C"edef "G"edB2 | gedB "Em"G2GB | "Am"A2AB "D7"AGED |
| "G"GEDE G2GA | "Bm"B2BA Bcd2 | "C"edef "(G)"gedc | "D7"BGAF "G"G4 :|
[/abcjs]

<img width="646" alt="grafik" src="https://user-images.githubusercontent.com/31062317/29353828-ca04f640-826b-11e7-800d-bcf5b9899739.png">

I suppose that wordpress misinterprets the quote mark. Without [abcjs] and [/abcjs] the page shows wrong quote marks: 

|:“G“GEDE G2GA | B2BA Bcd2 | „G“GEDE „Em“G2GB | „Am“A2AB „D7″AGED |
| „G“GEDE G2GA | „Bm“B2BA Bcd2 | „C“edef „(G)“gedc | „D7″BGAF „G“G4 :|
|:“Em“g2ge „D“f2fd | „C“edef „G“edB2 | gedB „Em“G2GB | „Am“A2AB „D7″AGED |
| „G“GEDE G2GA | „Bm“B2BA Bcd2 | „C“edef „(G)“gedc | „D7″BGAF „G“G4 :|

All other plugins are deactivated!

Thanks for your help!
Greeting, Klaus

**Comment by paulrosen** [comment]
I think your guess is right. It must have something to do with the language that WP is set, too. What language is that?

Are you using the visual editor or the code-based editor? Can you see if entering the regular quote mark in the code editor works?

**Comment by Shiehallion** [comment]
Thank you for the quick answer!

The language is german. 
Normaly I work with the visual editor. In the code-based editor I see the correct quote marks ("). 

If you give me your private eMail, I can give you full access to my blog. (It’s nearly empty…)

Greetings,
Klaus



----------------------------------------
Klaus Kegebein
Datenbankentwicklung
----------------------------------------
Große Altefähre 13
D-23552 Lübeck
----------------------------------------
0177 · 652 82 14
0451 · 707 66 71
----------------------------------------
klaus@kegebein.de
http://kegebein.de
----------------------------------------

**Comment by Shiehallion** [comment]
Hi Paul,

can you do something about this?

Greetings
Klaus

**Comment by paulrosen** [comment]
Klaus, would you try the latest version of the plugin and see if that helps?

**Comment by Shiehallion** [comment]
Hi Paul,

yes, it works! Thank you very much!

Greetings,
Klaus




 


----------------------------------------
Klaus Kegebein
Datenbankentwicklung
----------------------------------------
Große Altefähre 13
D-23552 Lübeck
----------------------------------------
0177 · 652 82 14
0451 · 707 66 71
----------------------------------------
klaus@kegebein.de
http://kegebein.de
----------------------------------------

**Comment by paulrosen** [comment]
Cool! Well, there might be a few more unicode chars, so reopen this if you have any more problems.

**Comment by Shiehallion** [comment]
Hi Paul, 
I have a new problem with abc notation (version 5.0.0): Sometimes the notes are placed one above the other. Here is the tune:

[abcjs engraver="{ staffwidth:700 }"]
X: 1
R: polka
M: 2/4
L: 1/8
K: Dmaj
|:"D"fA BA|fA BA|d2 e>f|"A"ed BA|
"D"fA BA| fA BA|d2 e>f|"A"ed d2:|
|:"D"fa f>e| "Em"ed BA|"G"d2 e>f|"A"ed BA|
"D"fa f>e|"Em"ed BA|"G"d2 e>f |"A"ed d2:|
[/abcjs]

This is the output (Firefox 61.0.1):

<img width="562" alt="grafik" src="https://user-images.githubusercontent.com/31062317/43034840-502e3154-8ce4-11e8-9808-5de0bef630ea.png">

This time it has nothing to do with the chords. The error persists, even if I remove the chords.
Most other tunes are displayed correctly.

Thanks in advance for your help!

Greetings, Shiehallion

**Comment by Shiehallion** [comment]
http://www.kegebein.de/session-HL/egans-polka/
http://www.kegebein.de/session-HL/ballydesmond-polka-1/
http://www.kegebein.de/session-HL/ballydesmond-polka-2/

An other problem: 
It's nice to play the tunes in the browser, but it does not work on OS X. After clicking on the play-button I see only the »dotted circle«:

<img width="723" alt="grafik" src="https://user-images.githubusercontent.com/31062317/43079402-51367e58-8e8d-11e8-8042-ea05bf0431a8.png">

**Comment by paulrosen** [comment]
That could be a couple of things. Not all devices will play midi. In general, it works well on an actual computer, with a reasonably recent browser. OS X in particular, puts restrictions on playing sounds.

**Comment by Shiehallion** [comment]
Okay. I have to live with the fact that OS X is worse in ONE point.
But can you help with the wrong presentation of the score?

Greetings,
Shiehallion

**Comment by Shiehallion** [comment]
Hi Paul,
I found the reason for the destroyed presentation: It's the “>”.
For example:

X: 1
R: jig
M: 6/8
L: 1/8
K: Gmaj
|:D|"G"G2D "Em"G>AB|"C"c2B "D"A2G|"C"F>GE "D"D>ED|"Bm"F2G "D"A>Bc|
"G"B>AG "Em"B>cd|"C"e2A "D"A2G|"C"F>GE "D"D>GF|"G" G3 G2 :|

That is the code in “visuell mode”
When I change to “text mode”, I see this:

X: 1
R: jig
M: 6/8
L: 1/8
K: Gmaj
|:D|"G"G2D "Em"G&gt;AB|"C"c2B "D"A2G|"C"F&gt;GE "D"D&gt;ED|"Bm"F2G "D"A&gt;Bc|
"G"B&gt;AG "Em"B&gt;cd|"C"e2A "D"A2G|"C"F&gt;GE "D"D&gt;GF|"G" G3 G2 :|

“>” is replaced by “&gt;” – and this irritates the plugin.

Greetings, Klaus
