### ISSUE TITLE
How to click on the gap between notes and add cursor flickering in the gap?

### ISSUE THREAD

**Issue by f2elab** [paulrosen/abcjs#1057]

**Comment by paulrosen** [comment]
That's something you'll have to add yourself. You can put a click handler on the `svg` element and get the mouse coordinates of the click. To figure out where that is, be sure that you add `add_classes:true` to the parameters when calling `renderAbc`, then you can query all the notes.

It's not trivial, but all the coordinates are there.

**Comment by f2elab** [comment]
> That's something you'll have to add yourself. You can put a click handler on the `svg` element and get the mouse coordinates of the click. To figure out where that is, be sure that you add `add_classes:true` to the parameters when calling `renderAbc`, then you can query all the notes.
> 
> It's not trivial, but all the coordinates are there.

Okay, I have some ideas. Could you please ask how to obtain all abcEles and whether it is possible to add CSS effects to SVG? I added a border to. abcjs-note_delected, but it didn't work

**Comment by paulrosen** [comment]
First, did you add the classes, like this: `renderAbc("paper", abcString, { add_classes: true})`?

Then you can always check the exact name of the class that was added in the browser's dev tools. For instance, I just looked at a random chord in a random piece of music and the output was (paths truncated for clarity):
```
<g class="abcjs-note abcjs-d0-5 abcjs-p1 abcjs-p5 abcjs-p8 abcjs-l0 abcjs-m0 abcjs-mm0 abcjs-v0 abcjs-n0" fill="currentColor" stroke="none" data-name="note" selectable="false" data-index="0">
<path data-name="D" d="M ... z" class="abcjs-notehead"></path>
<path data-name="A" d="M ... z" class="abcjs-notehead"></path>
<path data-name="d" d="M ... z" class="abcjs-notehead"></path>
<path d="M ... z" class="abcjs-stem" data-name="stem"></path>
</g>
```
From that we can see it is a note, 
it is a half note "0-5" (replace the dash with a period you get "0.5")
it has the relative pitches of 1, 5, 8 (that is there are three notes in the chord)
it is on line 0
it is on measure 0 of that line
it is on measure 0 in the whole piece
it is on voice 0
it is on note 0

Then the 4 paths show that the notes are D, A, and d, and that it has a stem.

**Comment by f2elab** [comment]
> 首先，您是否添加了类，如下所示：`renderAbc("paper", abcString, { add_classes: true})`？
> 
> 然后，您可以随时检查在浏览器的开发工具中添加的类的确切名称。例如，我刚刚查看了一段随机音乐中的随机和弦，输出为（为清晰起见，路径被截断）：
> 
> ```
> <g class="abcjs-note abcjs-d0-5 abcjs-p1 abcjs-p5 abcjs-p8 abcjs-l0 abcjs-m0 abcjs-mm0 abcjs-v0 abcjs-n0" fill="currentColor" stroke="none" data-name="note" selectable="false" data-index="0">
> <path data-name="D" d="M ... z" class="abcjs-notehead"></path>
> <path data-name="A" d="M ... z" class="abcjs-notehead"></path>
> <path data-name="d" d="M ... z" class="abcjs-notehead"></path>
> <path d="M ... z" class="abcjs-stem" data-name="stem"></path>
> </g>
> ```
> 
> 从中我们可以看出它是一个音符， 它是一个半音符“0-5”（将破折号替换为句点，则得到“0.5”） 它的相对音高为 1、5、8（即和弦中有三个音符）它位于第 0 行 它 位于该行的第 0 小节 它位于整首曲子的第 0 小节 它位于第 0 声部 它位于第 0 个音符上
> 
> 然后 4 条路径显示音符为 D、A 和 d，并且它有一个符干。

Thank you very much for your detailed explanation, it was very helpful to me. I will continue to study it.
