### ISSUE TITLE
Responsive resize Height not scaling correctly

### ISSUE THREAD

**Issue by Nickno95** [paulrosen/abcjs#108]
When making the SVG responsive, instead of the height scaling off its original height, it becomes a square where the height is equal to whatever the width is. If the SVG is short, it adds a lot of white space on the bottom to square it out, if its longer than its width, it cuts off.
You can see it [here](https://paulrosen.net/responsive-abcjs/) where there is excess space between the SVG and "Try changing the browser width and see how the image reacts."

**Comment by paulrosen** [comment]
I see what you mean. I was experimenting with the styles and it looks like I see a simpler way to do this. I'll release an update soon.

**Comment by allan-farrell** [comment]
Is there a work around while we're waiting for a new release?

**Comment by paulrosen** [comment]
I'll have time to work on it this weekend. Hopefully there will be a release by Monday.

**Comment by allan-farrell** [comment]
Thanks! Be glad to help in any way can (i.e. if you need a tester )

**Comment by paulrosen** [comment]
I checked in a fix to the master branch, but I haven't created a release yet. It would be nice if you can see if that fixes your problem. Can you include all the JS files from master directly? Otherwise, I'll have a release shortly.

**Comment by allan-farrell** [comment]
I cloned the repo and built it. Fix looks good. http://47.55.219.148/trad/tune_sets/238
Visit that url and resize your browser to a small screen - the svg stack  nicely no space between them! Thanks.

**Comment by paulrosen** [comment]
That looks good! I'd have another breakpoint where there are two SVG on a line instead of jumping between one and three.

I'll be making the responsiveness a little more sophisticated in the next go round, so if you have any suggestions, let me know.

**Comment by paulrosen** [comment]
Fixed in 3.2.0
