### ISSUE TITLE
modelChanged not working

### ISSUE THREAD

**Issue by jisike** [paulrosen/abcjs#114]
I'm trying to use the modelChange callback/listener but its not working with the latest build:  abcjs_editor_latest-min.js. Here's my code:
  
```
var editor = new ABCJS.Editor("tune2", {
  render_options: {
    listener:  {
      highlight: selectionCallback,
      modelChanged: function(){
        console.log('modelChanged')
      }
    }
  }
})
```

**Comment by jisike** [comment]
Nevermind I got it working using editor.modelChanged = function(){}

**Comment by paulrosen** [comment]
Unfortunately, `modelChanged` is a vestige of an earlier, half-finished feature. The callback for `highlight` will work fine. (`modelChanged` was intended for allowing the user to drag the note and alert the editor of that.)
