### ISSUE TITLE
a moving cursor on music notation while playing MIDI file

### ISSUE THREAD

**Issue by kickmyassp** [paulrosen/abcjs#115]
Hello, 
I am a newbie on web programming and use abcjs to show music notation while MIDI file is played.
I need a moving "cursor" on the music notation to show the current playback position.  A simple vertical line will do for the cursor. 

Any help to accomplish this would be greatly appreciated. 
(My apology if this is not the place to ask for help.  As I said, I am a newbie fob)

**Comment by paulrosen** [comment]
Look at the documentation on this page: https://github.com/paulrosen/abcjs/blob/master/api.md

In particular, the command to render the midi has a parameter `midiParams`:
```
ABCJS.renderMidi(output, tunebookString, parserParams, midiParams, renderParams)
```
If you add `{ listener: callback }` then you will get a notification as the midi is playing. The callback function should look like this:
```
function midiListener(cntl, progress)
```

**Comment by kickmyassp** [comment]
Thanks for your response.  I read the documentation. Unfortunately I am lost with description of renderMidi(): "**Completely creates midi for the tunebook**".  Does it mean the function will do MIDI playback? Or does it create MIDI stream or file?

I am on mobile platform. In particular on iOS(iPhone),  while displaying the sheet music on the browser(safari),  I create MIDI sound through my own little sound synthesizer. 

I tried the following code and I got the music notation as expected but no sound.  

	ABCJS.renderAbc("notation", score, "{print:true}", "{paddingtop:0}", "{}");
        ABCJS.renderMidi("notation", score, "{}", "{}", "{}");

**Comment by paulrosen** [comment]
Sorry for the late reply...

First, don't use quotes around the parameters. That is, `"{print:true}"` should be `{print:true}`.

Second, I assume you must have an element on your page with the id of `notation`. You've specified that for both the engraving and the midi. You should have a separate element for each.

Third, there are two types of midi generation: a midi file that the user can download, and a midi control that will play the music in the browser. The latter has mixed results on mobile, but phones and browsers are getting better!

If, in the `midiParams`, you specify `generateDownload: true`, then the file will be created and a link to it will be presented to the user.

If, in the `midiParams`, you specify `generateInline: true`, then the controls will be presented. But it is not that simple! The controls will not be visible unless you give them some CSS. I have some sample CSS [here](https://github.com/paulrosen/abcjs/blob/master/abcjs-midi.css) Also, you need to supply the sound fonts on your server. There are instructions [here](https://github.com/paulrosen/abcjs/blob/master/midi.md).

**Comment by paulrosen** [comment]
There is now an example here: https://github.com/paulrosen/vue-abcjs-midi-demo
