### ISSUE TITLE
pauseAnimation() not working

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#117]
pauseAnimation is not working. When I try to use it I receive the following message "Uncaught TypeError: ABCJS.pauseAnimation is not a function".

To do a further check outside my application I just took the  animation.html example in abcjs-master and added a button with the call to pauseAnimation. I  got the same error so I assumed that it's not depending on my application. 
I just added a button with onclick="pause()" and below the pause() function.
		var pause = function () {
 			ABCJS.pauseAnimation(true);
		};

Start and stop are working fine, just pause function has a problem.

**Comment by paulrosen** [comment]
I see the problem. I should be coming up with an update soon.

**Comment by paulrosen** [comment]
Fixed in 3.2.0
