### ISSUE TITLE
Can't seem to get animate to work

### ISSUE THREAD

**Issue by groovy9** [paulrosen/abcjs#118]
I have a VueJS project that uses abcjs, and the notation and midi is all working fine, but I can't seem to get the animation to play.

I have the cursor class styled:
```
<style>
    .cursor { 
       border-left: 1px solid black; 
    } 
</style>
```
I'm passing add_classes to renderAbc (this.row, this.music etc are just pulling from VueJS's component data)
```
this.tune = ABCJS.renderAbc('music' + this.row, this.music, {}, {add_classes: true}, {});
```

I'm passing the animate bits to renderMidi:

```
ABCJS.renderMidi('midi' + this.row, this.music, {}, 
      { generateInline: true,
         animate: {
           listener: this.toggleAnimate,
           target: this.tune[0],
           qpm: this.tempo
         }
        }, {}); 
```

toggleAnimate  (methods is a VueJS bit where you define your component's functions which you then use with this.someFunc()):

```
methods: {
  toggleAnimate: function() {
      if(! this.started) {
         console.log('start animation')
         ABCJS.startAnimation($('#music' + this.row)[0], this.tune[0], { bpm: this.tempo })
         this.started = true
       } else {
         console.log('stop animation')
         ABCJS.stopAnimation()
         this.started = false
       }
   },
}
```

And of course I have the DIVs where everything shows up ok, aside from the animating.

```
<div>
   <div id="music0"></div>
   <div id="midi0"></div>
</div>
```

No errors in the console, 'start animation' fires when I click play, 'stop animation' fires when it finishes, the sheet music displays, the midi plays, but no cursor ever shows up.  

Any ideas?

**Comment by paulrosen** [comment]
I think you are mixing up two different animation styles. The top level `startAnimation()` is designed to be used when MIDI is not available. It is independently timed.
 
Check the parameters that are passed to the function that is called by `listener`. That should be the progress. Then inside that function you would manipulate the cursor. 

I was working on a simple demo when I got distracted a while ago. I'll post one as soon as I can.

**Comment by groovy9** [comment]
Ok, I changed toggleAnimate() to just console.log the argument:

```
animate: function(arg) {
   console.log('animate', arg)
}
```
But I only get two logs to the console, 'animate null' when I click play and 'animate object' at the end where object is an array whose length matches however many notes I have in the piece.

I'm also getting this on the console three times per play, even though the midi plays just fine, but maybe it's related:

```
Uncaught (in promise) DOMException: Unable to decode audio data
Promise (async)		
(anonymous)	@	abcjs_basic_midi_3.1.4-min.js:2
detectDecodeAudio	@	abcjs_basic_midi_3.1.4-min.js:2
hasSupport	@	abcjs_basic_midi_3.1.4-min.js:2
onCanPlayThrough	@	abcjs_basic_midi_3.1.4-min.js:2
```

**Comment by groovy9** [comment]
BTW, in case it's relevant, I'm using this (https://github.com/gleitz/midi-js-soundfonts) sound font directly from Github like so:

 ABCJS.midi.soundfontUrl = "http://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/"

Sounds good, works fine other than that decode audio data error.

**Comment by groovy9** [comment]
I've continued to dig, and it looks like maybe you have a bug in the code that generates the noteTimings member of your tune object.

For a short piece of 8 notes, I'm getting a noteTimings array with just a single array member and its 'seconds' member is NaN:

```
noteTimings: Array(1)
 0: 
  elements: Array(8)
    0: ze {__ob__: Observer}
    1: ze {__ob__: Observer}
    2: ze {__ob__: Observer}
    3: ze {__ob__: Observer}
    4: ze {__ob__: Observer}
    5: ze {__ob__: Observer}
    6: ze {__ob__: Observer}
    7: ze {__ob__: Observer}
    length: 8
    __proto__: Array(0)
   height: 58.297000000000004
   left: 49.051 
   seconds: NaN
   top: 22.559999999999995
   type: "event"
   width: 9.81
```

Here's the simple piece:

```
M: 4/4
K: C
Q: 180
L: 1/8
abcd|abcd||
```

I'm guessing noteTimings should have 8 array members for this piece, yes?

**Comment by paulrosen** [comment]
I will create a Vue app today that contains midi with animation and get back to you on what I find.

There are some errors that midi.js writes to the console. I haven't been able to track them down, but, as you said, they don't seem to affect the sound.

**Comment by groovy9** [comment]
I think I've identified the problem, but it's not yet clear where to fix it.  In getBeatLength(), it's looking for 
this.lines[i].staff[j].meter, which isn't there.  If I manually set it to { num: 4, den: 4}, it all starts working as advertised.  

```
this.getBeatLength = function() {
   for (var i = 0; i < this.lines.length; i++) {
     if (this.lines[i].staff) {
       for (var j = 0; j < this.lines[i].staff.length; j++) {
          console.log('meter?', this.lines[i].staff[j].meter) // undefined                                                
          this.lines[i].staff[j].meter = { num: 4, den: 4}
    ...
```

**Comment by groovy9** [comment]
Oh FFS, this is all user error.  I'm combining the ABC header and notes from separate strings, and had failed to notice I was passing the notes string to renderABC() rather than the complete song including the header with the meter in it.

So sorry for wasting your time!

**Comment by groovy9** [comment]
Incidentally, here's my working solution that just enlarges the current note and turns it blue. Works like a champ now.

```
<style>
  .cursor { 
     fill: blue;
     stroke: blue;
     stroke-width: 3px;
  }   
</style>
```



```
methods: {
    highlight: function(elements, options) {
      elements.forEach(function(e) {
        e.forEach(function(f) {
          if(options && options.remove)
            f.node.classList.remove('cursor')
          else
            f.node.classList.add('cursor')
        })
      })
    },
    animate: function(arg, arg2) {
      if(arg2)
        this.highlight(arg2.elements)
      if(arg)
        this.highlight(arg.elements, {remove: true})
    },
  },

```

```
this.tune = ABCJS.renderAbc('music' + this.row, this.piece, {}, {add_classes: true}, {});
ABCJS.renderMidi('midi' + this.row, this.music, {}, 
  { 
    generateInline: true,
    qpm: this.tempo,
    animate: {
      listener: this.animate,
      target: this.tune[0],
      qpm: this.tempo,
    }
  }, {}); 
```

**Comment by paulrosen** [comment]
Thanks for the code and your input. I created an example on github that will hopefully help someone else.
