### ISSUE TITLE
Feature request: SVG click event that receives the bar number of the piece

### ISSUE THREAD

**Issue by groovy9** [paulrosen/abcjs#119]
I'm working on a sheet music editor tool in which you can edit a specific bar of a piece.  It'd be great if I could attach a click event to the SVG that gets passed the bar number that was clicked so I could pop up a localized editor for the area of the music that was clicked.

I know I can already set up the textarea to highlight whatever note was clicked, but I'm working on a graphical editor that generates the ABC notation, so highlighting the notation doesn't really help.

In the meantime, I can use jquery to loop through the SVG path elements looking for the 'note' class and decoding the l0 m1 classes with it, but that's a rather brittle way to go about it.  If you later change any class names, it'll break, for example.

**Comment by paulrosen** [comment]
This is off the top of my head, but in the callback that you receive when the click event happens, can you see the SVG element that was clicked? If you use "use_classes" then it will have a class for the line number and the measure number.

The numbers start at zero and the measure number is the measure from the start of the line.

Does that help?

**Comment by groovy9** [comment]
I'm not sure what callback you're talking about.  I don't see one listed in the docs, unless I overlooked it.  I was going to manually add my own click callbacks by looping through the SVG elements with jQuery, which should work fine, I just thought it might be a nice feature addition.

**Comment by paulrosen** [comment]
Version 3.3.2 has some of this exposed in a more straightforward way. 

To set it up, do something like this:
```
import abcjs from 'abcjs';

const abcString = "X:1\n..........";

function highlightListenerCallback(abcElem,tuneNumber,classes) {
    const partOfOriginalString = abcString.slice(abcElem.startChar, abcElem.endChar);
    // the classes parameter has lots of interesting data about what was clicked on.
}

const tuneObjectArray = abcjs.renderAbc(
    "paper",
    abcString,
    { },
    {
        listener: { highlight: callback },
    },
    { }
);
```

Please close this issue if this answers your question, or clarify if I haven't understood the info you are looking for.
