### ISSUE TITLE
Can't expand tune to cover the whole line with responsive enabled.

### ISSUE THREAD

**Issue by rigobauer** [paulrosen/abcjs#121]
When you have a short notation, like two bars for example, and responsive set to cover almost the whole screen width, there's no way to make the staff expand to the right, so it appears short and align to the left. I haven't found a way to expand it or center it.
If you add a new line with just a bar, then it expands, but you have a new staff in the next line.

**Comment by paulrosen** [comment]
You can put `%%stretchlast` in the header of the tune.

**Comment by rigobauer** [comment]
Oh, man! You're totally right! I found a provisional way to tweak it adding an empty title in the header and a '\nT:' at the end of the music (it sucks, obviously). 

So much time checking the abc standard and I didn't see this superdescriptive parameter! My fault... Sorry!
