### ISSUE TITLE
Is there anyway to create basic drum notation?

### ISSUE THREAD

**Issue by rigobauer** [paulrosen/abcjs#122]
The only thing I really think is missing to make it usable for basic drum notation is a way to change the glyph of a note to use an 'x'. With that, you could draw hihat, ride, etc. There's more specific drum notation, but with that option, it would be enough for a lot of grooves and drum notation.

Is there any way to do that?

EDITED: After doing some research, looks like the %%beginsvg, %%endsvg and %%map are the way they solve it in other cases (but it's not part of the abc standard). Do you have any plans to implement this (os something similar) in a near future?

**Comment by paulrosen** [comment]
Look at this page: https://github.com/paulrosen/abcjs/blob/master/abc-notation.md

Notice the example for "alternate heads". Can you make that work?

**Comment by rigobauer** [comment]
Mmm... It works partially:

1. The style parameter is not working in the V: element.

2. Working with the decorator mode, I can't combine an decorated element with another one to use the same stem (like in a chord). I mean, this code...

X: 1
M: 4/4
L: 1/16
U:n=!style=x!
K:perc
V:ALL stem=up
[ng2F2]ng2

... doesn't combine the two ng2 and the F2 (inside []) in the same stem. If I remove the decorator, it works. This is needed for drum groove creation (is the most common notation). For example...

![captura de pantalla 2017-11-30 a las 8 27 50](https://user-images.githubusercontent.com/29883162/33418956-9fde2c98-d5a8-11e7-854d-cc2c650b9510.png)

**Comment by paulrosen** [comment]
Ok, I see the problem. 

Do you have a link to more information about that notation system?

**Comment by rigobauer** [comment]
This is a basic one...

http://drummagazine.com/drum-notation-guide/

**Comment by paulrosen** [comment]
Will be fixed in v3.3.0, out soon.

**Comment by osvi64** [comment]
Hi Paul. WHere can I found documentation about drum notation. I see that the example below is working, but I was not able to find the documentaion to understand it . PLease can you help?
