### ISSUE TITLE
stem=up cancelled when using %%barsperstaff

### ISSUE THREAD

**Issue by rigobauer** [paulrosen/abcjs#123]
If you have a V: with stem=up defined and are using %%barsperstaff, when it changes of line the stem=up is ignored and starts using the default value. You can check it with this example...

%%barsperstaff 2
X: 1
M: 4/4
L: 1/16
U:n=!style=x!
K:perc
V:ALL stem=up
c4 c4 c4 c4 | c4 c4 c4 c4 | c4 c4 c4 c4 |

... the third bar shows the stems down

**Comment by paulrosen** [comment]
Will be fixed in v3.3.0, out soon.
