### ISSUE TITLE
Unable to get MIDI from ABC

### ISSUE THREAD

**Issue by ekzhang** [paulrosen/abcjs#126]
Is it possible to use this library to parse a string in ABC notation into a MIDI string? I looked through the source and found the `midi/abc_midi_create.js` file, but its export function does not seem to be exposed in the API from the `ABCJS` object.

**Comment by paulrosen** [comment]
If you use the following command:
```
var abc = "X:1\n etc...";
ABCJS.renderMidi("midi", abc, {}, { generateDownload: true, generateInline: false })
```
Where:
```
<div id="midi"></div>
```
Then the element `#midi` will contain an `href` with a valid midi file.

Is that what you are looking for? If not, what is your use case?

**Comment by ekzhang** [comment]
Thank you, that was exactly what I was looking for!
