### ISSUE TITLE
Karma tests with PhantomJS can't execute because main index.js is not transpiled

### ISSUE THREAD

**Issue by rigobauer** [paulrosen/abcjs#128]
I'm creating a react-abcjs component generated using nwb toolpack, that uses Karma with PhantomJS for testing. When I try to run the tests, I get this fail...

PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  {
    "message": "SyntaxError: Expected an identifier but found 'abcjs' instead\nat webpack:///node_modules/abcjs/index.js:4:0 <- tests.webpack.js:6615",
    "str": "SyntaxError: Expected an identifier but found 'abcjs' instead\nat webpack:///node_modules/abcjs/index.js:4:0 <- tests.webpack.js:6615"
  }

After doing some research, the problem is that the main index.js that exports the module is not transpiled, so PhantomJS doesn't understand this line...

let abcjs = {};

... because if the 'let'. Considering that apparently this is the only problem in the file (the rest don't have ES6 stuff), I've solved it changing the line for...

var abcjs = {};

And now works ok.

If you think is ok, I'm going to create a Pull Request for this. As a side note, in case you think you're going to modify that file in the future, I think maybe is a good idea to include that file in the transpiling process and change the entry point of the module to the transpiled version.

**Comment by paulrosen** [comment]
Thanks. I've released v3.3.1
