### ISSUE TITLE
How to change soundfontUrl?

### ISSUE THREAD

**Issue by MilanObrtlik** [paulrosen/abcjs#132]
I cant find option how to change soundfontUrl. For now, i hacked compiled *.min.js file and replaced string "https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/" with my URL. Can you clarify how to change that url programmatically?

**Comment by paulrosen** [comment]
This should work:
```
ABCJS.midi.soundfontUrl = "/public/path/to/soundfonts";
```

That was broken in version 3.3.0, but fixed in 3.3.1.

**Comment by MilanObrtlik** [comment]
Are you sure? Can you check my code at https://www.csfp.cz/jede-sohaj-z-vidna ? I think i have v3.3.1, but im not able to change sounfontUrl programmatically.

**Comment by paulrosen** [comment]
Oh, I see. I was making a copy of the url, not setting it. I just added a new entry point:
```
ABCJS.midi.setSoundFont(url);
```
I'll try to get a release done in a few days so that you can use it.
