### ISSUE TITLE
Beam drawn over top of 8th note rest

### ISSUE THREAD

**Issue by nrotonda** [paulrosen/abcjs#133]
Is the following note sequence drawn correctly? I'm thinking the beam should not be drawn over top of the eighth rest note in the first frame.

```
X:1
T: 
M:6/8 
L:1/3072 
K:C 
| G1152 G384z384G384 | G384G192G192G192G192 G768G384 | z384G384G384 z384G384G384 |
```

**Comment by paulrosen** [comment]
If you put a space either before the "z" or after the "z" then the notes won't be beamed.

That type of beaming is desired in some cases.

Interesting use of the "L:" line!

**Comment by nrotonda** [comment]
Oh. Well thanks for getting back to me so quickly! Greatly appreciate it
