### ISSUE TITLE
Playing a music note by pressing a key with the cursor moving to the next music note

### ISSUE THREAD

**Issue by hks-adohkd** [paulrosen/abcjs#134]
I was just wondering if I can use the library for the following use case:

1. I want the cursor to point to a specific note
2. if the user pressed a button the note which the cursor is on will be played
3. the cursor moves on to the next note

please help, I read all the API of the library but it seems that I can't do such things.
if I can't do it with this library can you recommend another library, or at least point to me where I can ask this question.

**Comment by paulrosen** [comment]
This library gets you half of the way there. 

It will draw the music for you, and there is a way to figure out where to draw the cursor. 

You would have to write the code to handle the button click and play the tone, and move the cursor.

**Comment by hks-adohkd** [comment]
how can I draw the cursor on a specific note? I can't find something similar in the API

**Comment by paulrosen** [comment]
If you go to: https://configurator.abcjs.net/classes you can play around with the selection classes. For instance, to find the first note, click on "l0", "m0", and "n0". (That's line 0, measure 0, note 0)

The code  used to make the note blue is at the bottom of the page. You can change that to do whatever you want.

**Comment by ThorsenRune** [comment]
> I was just wondering if I can use the library for the following use case:
> 1. I want the cursor to point to a specific note
Hi, I was trying to accomplish the same using Animation: abcjs Configurator with show cursor and Interactive: abcjs Configurator with Inline Midi.
 Unfortunately its not sufficiently clear to me how the two javascript snippets can be combined to accomplish this. Did hks-adohkd accomplish this or could the documentation be clarified?

**Comment by paulrosen** [comment]
I'm closing some old issues due to inactivity.
