### ISSUE TITLE
Multi line lyrics are not aligned properly

### ISSUE THREAD

**Issue by Secrice** [paulrosen/abcjs#135]
C
w:1.
w:2.

![2018-02-23 6 57 08](https://user-images.githubusercontent.com/2404820/36588432-668ff0aa-18cb-11e8-9cfc-a60d6d380fee.png)

`<text x="57.551" y="96.6773125" text-anchor="middle" font-family="&quot;Times New Roman&quot;" font-size="17px" stroke="none" fill="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; text-decoration: none;" font-style="normal" font-weight="bold" text-decoration="none" class="abc-lyric l0 m0 v0" font=""><tspan style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" dy="-4.689875000000001">1. </tspan><tspan dy="20.4" x="57.551" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">2. </tspan><tspan dy="20.4" x="57.551" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></tspan></text>`

Each lyric character has space at the end of the string like this. "1. " "2. "
I can get proper aligned lyrics if I remove space from web inspector. "1." "2."
I think last line is not aligned properly because browser does not render last empty white space.

**Comment by paulrosen** [comment]
Thanks! I fixed it and it will be in v3.3.3, which is coming soon.
