### ISSUE TITLE
The Lyric of the second line is printed on first line if first line is empty.

### ISSUE THREAD

**Issue by Secrice** [paulrosen/abcjs#137]
CDEF |
w: A B - C
w: D E F G
w: H I J K

![2018-02-25 10 50 34](https://user-images.githubusercontent.com/2404820/36642142-5117b334-1a7e-11e8-9f5e-7cf9d0b73918.png)

"F" and "J" are printed on wrong place.

**Comment by Secrice** [comment]
w: ~ A B C
w: D E F G

D is not bottom aligned to others(E F G)

![2018-02-26 1 13 12](https://user-images.githubusercontent.com/2404820/36653179-e32c6ec2-1af6-11e8-8044-2c120d0cc774.png)

**Comment by paulrosen** [comment]
Will be in version 3.3.4.
