### ISSUE TITLE
Importing abcjs from "abcjs" inside a react component produces error

### ISSUE THREAD

**Issue by kwonyounggu** [paulrosen/abcjs#139]
I have installed, imported and got an error as follows:
1. **npm install abcjs --save**
2. **import abcjs from "abcjs";** //in a react component
3. got the **following error message;**
   root_index_bundle.js:94192 **Uncaught ReferenceError: eve is not defined**
    at root_index_bundle.js:94192
    at Object.<anonymous> (root_index_bundle.js:94324)
    at e (root_index_bundle.js:92927)
    at Object.<anonymous> (root_index_bundle.js:92934)
    at e (root_index_bundle.js:92927)
    at Object.<anonymous> (root_index_bundle.js:92930)
    at e (root_index_bundle.js:92927)
    at root_index_bundle.js:92928
    at root_index_bundle.js:92929
    at t (root_index_bundle.js:92920)

Would you like to help me out with the error message ?

**Comment by paulrosen** [comment]
I'll try to reproduce. How did you create the app? Using `create-react-app`?

**Comment by mdahlgrengadd** [comment]
Have you seen this?

https://github.com/rigobauer/react-abcjs.git

**Comment by paulrosen** [comment]
I looked at @rigobauer 's repo and it looks like it is working in react in general.

I'm guessing there is something different in your build system that isn't compatible. Is your project publicly available? If so, I'll see if I can debug it.

(BTW, "eve" is related to Raphael, which is a dependency of abcjs. It it possible that your build system isn't pulling in the package's dependencies?)

**Comment by rigobauer** [comment]
The react-abcjs component was started using `nwb` (https://github.com/insin/nwb) but I've also tested abcjs in another project started with `create-react-app` and never found this problem.
Like Paul says, my first guess is also that it's related to the build system you're using...

**Comment by kwonyounggu** [comment]
Hello Paulrosen and Rigoburer,

Thank you very much for your comments.
I tried to put the following statement, import abcjs from "abcjs"; in a newly created project and found no problem. However the current project located https://github.com/kwonyounggu/webmondb having the same statement (import abcjs from "abcjs";)  produces the indicated error.  the file, package.json in the project has the following packages; 

 "dependencies": {
    "abcjs": "^3.3.4",
    "axios": "^0.16.1",
    "jquery": "^3.2.1",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.4",
    "midi-writer-js": "^1.5.2",
    "prop-types": "^15.5.10",
    "query-string": "^4.3.4",
    "react": "^16.2.0",
    "react-bootstrap": "^0.31.0",
    "react-dom": "^16.2.0",
    "react-facebook-login": "^3.7.2",
    "react-google-login-component": "^0.9.2",
    "react-loader": "^2.4.2",
    "react-recaptcha": "^2.3.5",
    "react-redux": "^5.0.5",
    "react-router-bootstrap": "^0.24.2",
    "react-router-dom": "^4.1.1",
    "react-spinkit": "^3.0.0",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.6",
    "redux-promise-middleware": "^4.3.0",
    "redux-thunk": "^2.2.0",
    "shortid": "^2.2.8",
    "validator": "^9.0.0",
    "xregexp": "^3.2.0"
  },

Once again thank you very much.

**Comment by kwonyounggu** [comment]
Hello Mdahlgrengadd,

Yes I saw https://github.com/rigobauer/react-abcjs.git but haven't installed yet because I thought that it may produce the same problem in my react-building.

Thank you very much.

**Comment by paulrosen** [comment]
Thanks, I'll try to reproduce it tomorrow.

**Comment by paulrosen** [comment]
I cloned your project and ran
```
npm install
npm run dev
```
I saw a different error: 
```
ERROR in ./~/react-facebook-login/dist/facebook-login.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign"
```
Is there another step to setting up the project?

**Comment by kwonyounggu** [comment]
Hello Paul,
Sorry to bother you.

I  used **npm run dev:server**, which states "webpack-dev-server --content-base src/main/webapp/ --open --host 192.168.1.97 --port 8081"
I believe that the host address in the statement needs to be replaced.

Thank you very much.

**Comment by kwonyounggu** [comment]
Found that the error came from webpack.config.js which the following property was missed,
module -> loaders -> include: SRC_DIR+"/webapps/js".

Thank you very much for your help so far.
