### ISSUE TITLE
Replace MIDI.js

### ISSUE THREAD

**Issue by surikov** [paulrosen/abcjs#141]
You can replace MIDI.js with WebAudioFont. It has 1500 digitized instruments and drums.
Example of sound 
https://surikov.github.io/webaudiofont/examples/dynamic.html

**Comment by paulrosen** [comment]
That looks really interesting! I'll explore it as soon as I get the next release out of the door.

**Comment by paulrosen** [comment]
The midi is being reworked and there will be a beta of a new system in version 5.8.0
