### ISSUE TITLE
Problem with Drum parameter

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#143]
Hi

I'm not able to make the drum parameter work. 
I took the the basic-midi.html file in the examples folder and I add the parameter copying it from the configurator. (I just added the " ").
Here the instruction I modified: 
**ABCJS.renderMidi("midi", abc, {  drum: "dddd 76 77 77 77 60 30 30 30", drumIntro: 2 } );**

In the configurator is working fine by I got the following error:

Uncaught ReferenceError: v is not defined
    at t.exports.getPickupLength (abcjs_midi_4.0.0-min.js:4)
    at r (abcjs_midi_4.0.0-min.js:4)
    at r (abcjs_midi_4.0.0-min.js:4)
    at abcjs_midi_4.0.0-min.js:4
    at Object.s.renderEngine (abcjs_midi_4.0.0-min.js:4)
    at Object.t.exports [as renderMidi] (abcjs_midi_4.0.0-min.js:4)
    at load (basic-midi.html:26)
    at onload (basic-midi.html:42)
getPickupLength @ abcjs_midi_4.0.0-min.js:4
r @ abcjs_midi_4.0.0-min.js:4
r @ abcjs_midi_4.0.0-min.js:4
(anonymous) @ abcjs_midi_4.0.0-min.js:4
s.renderEngine @ abcjs_midi_4.0.0-min.js:4
t.exports @ abcjs_midi_4.0.0-min.js:4
load @ basic-midi.html:26
onload @ basic-midi.html:42

Please can you help me in understanding what I'm doing wrong?

Thank You

**Comment by paulrosen** [comment]
Thanks for the bug report. I'll review it this evening.

**Comment by paulrosen** [comment]
Will be fixed in version 4.0.1.
