### ISSUE TITLE
When packed in a electron application, no text is displayed

### ISSUE THREAD

**Issue by vinzentt** [paulrosen/abcjs#144]
Hi,

first of all, huge thanks for this great library and your hard work. 

I have a problem when packaging it in a electron app. Inside the svg, all the text elements have a css attribute with display:none; I am using the very last version ie 4.0.0.

I tried to debug the code but maybe you will have an idea why this is hapenning. I'll do a PR as soon as I find the solution.

Thanks in advance for your help.

-- 
Vincent

**Comment by paulrosen** [comment]
Interesting. You're saying that "display:none" is actually in the DOM? The elements should look something like:
```
<text x="175" y="108" 
    text-anchor="middle" font-family="Helvetica" 
    font-size="16px" stroke="none" fill="#000000" 
    style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; text-decoration: none;" 
    font-style="normal" font-weight="normal" text-decoration="none" class="" font="">
        <tspan dy="5.758125000000007" 
            style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">Dm
        </tspan>
</text>
```
If not, it seems like it must be changed by something external to abcjs.

**Comment by vinzentt** [comment]
Yes the actual element in the DOM looks like this:

`<text x="257.8268351707205" y="51.185" text-anchor="middle" font-family="Helvetica" font-size="16px" stroke="none" fill="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; text-decoration: none; display: none;" font-style="normal" font-weight="normal" text-decoration="none" class="" font=""><tspan dy="5.763125000000002" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">F</tspan></text>`

Ok so I'm not looking in the right direction but when I'm running it in dev mode I have no problems, I see chords, tempo etc

**Comment by paulrosen** [comment]
I'm not sure what is adding "display: none;" to those SVG elements and I can't debug without seeing your code. I'm closing this issue, but feel free to reopen if you have more details.
