### ISSUE TITLE
Got problem with uising this package.

### ISSUE THREAD

**Issue by AARONkjLee** [paulrosen/abcjs#146]
I just did the exactly as sample midi-editor.html do, but the svg won't show.  Is that because abcjs_midi_4.0.1-min.js is not enough for the full function?  if then, what else should I included in the code?

**Comment by paulrosen** [comment]
That should be enough.

What browser/device are you using?

Is there any message in the browser's console?

**Comment by paulrosen** [comment]
I'm closing this because I don't have enough information to debug. Feel free to reopen if you can post your code or more information.

**Comment by AARONkjLee** [comment]
I have solved that. I had used <canvas>tag, which should be a <div> tag and use paper_id instead of using canvas_id in editor
