### ISSUE TITLE
Tuplets of 6 rendering problem

### ISSUE THREAD

**Issue by happyfanaticsalsero** [paulrosen/abcjs#147]
I've spotted what I believe to be an issue related to tuplets of 6 notes (notation in the standard is "(6:4:6" for a tuplet of 6 notes on the space of 4 notes). It seems the space of the notes is wrongly assigned as it always gets off axis when compared to another voice without the tuplets of 6.
I've got plenty of examples but I'll post one to start. Other ABC tools show the notation correct (for example, EasyABC).
(FYI - I'm using abcjs via the Wordpress plugin.)
`X:2
%%score 1 2
L:1/16
M:2/4
I:linebreak $
K:C
V:1 treble
V:2 bass
V:1
"^Larghetto" E2 | (6:4:6[CEA]CCCCC (6:4:6[CEA]CC[CEc]CC | (6:4:6[B,^GB]B,B,B,B,B, (6:4:6[B,GB]B,B,[B,Ed]B,B, | (6:4:6[A,Ec][A,E][A,E][A,E][A,E][A,E] (6:4:6eeeEEE | 
V:2
z2 | A,,8 | ^G,,8 | !f!(6:4:6A,,A,,A,,A,,A,,A,, (6:4:6C,C,C,C,C,C, | `

**Comment by paulrosen** [comment]
Will be in version 4.1.0
