### ISSUE TITLE
Problem with percussion on renderMidi

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#148]
I have this strange issue: when I use percussion explicitly (with a Voice with type drum) or when I use metronome option (ABCJS.renderMidi("midi", abc, { drum: "dddd 76 77 77 77 60 30 30 30", drumIntro: 2 } );)  , THE  FIRST TIME I press the play button, there are missing note on the audio. I can hear correctly the drum notes but I can't hear the piano note. After some bars I start to hear piano notes.
If I press play, then stop, and go back to the beginning button, it sounds perfectly.

As I told you, this happens with my song, but in the same way if I use metronome parameter, so I guess it' related to drum instrument rather than with my song.

Anyway I will attach below my song.

Just as workaround: is there a way to reset the song to the beginning via javascript? I found a way to start and stop (abcjs.midi.startPlaying(document.querySelector(".abcjs-inline-midi")); abcjs.midi.stopPlaying();), but I didn't find the way to reset. If it is, as workaround I can create an alternative but that start, stop, reset, and restart the song.

Thank so much you as usual, Osvaldo

Here my song:

X:3
M: 4/4
L: 1/4
%%score T1 T2
K: C
V:T2  clef=bass   perc name="Pulsazione 1/4"   snm="tac"
[V:T1]  c4  |
w:Semibreve(4/4) 
c2c2  |
w:Minima 2/4
cccc  |
w:SemiMinima  1/4 1/4 1/4 
c/2c/2 c/2c/2 c/2c/2 c/2c/2  |
w: Croma 1/8 1/8 1/8 1/8 1/8 1/8 1/8
 c/4c/4c/4c/4 c/4c/4c/4c/4 c/4c/4c/4c/4 c/4c/4c/4c/4|
w: SemiCroma 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 1/16 
 c/8c/8c/8c/8c/8c/8c/8c/8  c/8c/8c/8c/8c/8c/8c/8c/8  c/8c/8c/8c/8c/8c/8c/8c/8  c/8c/8c/8c/8c/8c/8c/8c/8 |
w:BisCroma(1/32)
[V:T2]CCCC|
CCCC|
CCCC|
CCCC|
CCCC|
CCCC|

**Comment by paulrosen** [comment]
I've seen this sometimes, too. I think it has to do with network speed - I'm guessing the midi starts as soon as the first voice is loaded, and if the second voice isn't loaded in time then those notes don't sound. I will try to figure out what midi.js is doing and delay the start until everything is loaded.

For restarting, I just fixed that in the master branch, but I haven't released it yet. `stopPlaying()` should have reset the midi.

I'm going to get another release out this week, I hope.

In the meantime, you could actually prime the pump by playing anything else first that uses the instruments. They will stay loaded until the browser is refreshed.

**Comment by paulrosen** [comment]
This will be in version 4.1.0
