### ISSUE TITLE
Key signature is incorrect when visually transposed

### ISSUE THREAD

**Issue by TCPN** [paulrosen/abcjs#150]
I was trying the abcjs Configurator and found that key signatures were not correctly transposed to what they should be.
For example, "Money Lost" is D minor with one flat in its key signature. If it's transposed upward by 2 half-steps to E minor, it should have one sharp in its key signature. However there were three sharps in the transposed key signature when I input a 2 at the transpose field, looking like a #F minor or A major. Other than the key signature nothing looks wrong after transposed.

**Comment by paulrosen** [comment]
Whoops! That's a regression. I'll get it fixed on Monday.

**Comment by paulrosen** [comment]
Fixed in 4.1.1
