### ISSUE TITLE
Get null element when click the meter note.

### ISSUE THREAD

**Issue by woody-li** [paulrosen/abcjs#151]
![abc](https://user-images.githubusercontent.com/16889642/39746705-bc385b68-52dd-11e8-8f93-526bd610dbe1.png)
As the pic shows, it has got a null element in the setClass function when clicked the meter note in the SVG.
And then, it will throw exception after click any note in the SVG.

**Comment by paulrosen** [comment]
Ok, will fix in v5.0.1.

**Comment by paulrosen** [comment]
Fix is actually in v5.1.0
