### ISSUE TITLE
Getting the tune object in Nodejs

### ISSUE THREAD

**Issue by MattReimer** [paulrosen/abcjs#152]
Hi Paul, this is a really great library!

I have a question related to #110 

I've got a node app and I'm importing your library like so:

``` js
import abcjs from 'abcjs'
```

I noticed that `abcjs` only has `renderAbc()` but I'm just looking to parse the tune into an object I can do some stats on. What's the recommended way of getting the tuneobject?

Should I be importing the parser like:

```js
import abcparser from 'abcjs/src/parse'
```

or is there some other prefered way of doing this?

**Comment by paulrosen** [comment]
Off the top of my head, I'm not sure what the best way to do this is. I'll add some recommendations to the documentation. If you do this:

    const tunes = abcjs.renderAbc("paper", "X:1\netc...");

You will get an object that you can explore.

That does do the rendering, which you don't need, so if you are analyzing a metric boatload of tunes that might be slow, but maybe not too bad.

There is also a method that I use to do regression testing of abcjs that is documented here: https://github.com/paulrosen/abcjs/blob/master/docs/contributing.md

Note that it imports from a different entry point:

    import abcjs from 'abcjs/test';

Warning: this is stable for now, but I'm not sure how much that API might change in the future.

I'm interested in how you decide to interface with abcjs, so let me know how this works for you.

**Comment by MattReimer** [comment]
Interesting. Thanks for getting back to me. 

That `abcjs/test` workaround looks like what I need. I'm just wondering if exposing the parser to the `abcjs` object might be something worth considering. It would allow us to separate the parse and render steps a bit and do some work in between. It might open up some really interesting possibilities.

_Some background_: I'm looking to create a database of tunes with a focus on taxonomy so that users can sort/search/filter quickly to create books and sets. To do this I'm going to store the original tune string in the `nosql` database but I was thinking of breaking out fields to make things easier to index so a DB record might look like this:

```js
{
  // The headers are JS objects parsed directly from the tune settings below
  Headers: [
    { T: "The farmer's bucket", K: "Am" },
    { T: "The farmer's bucket", K: "D" },
    { T: "The farmer's daughter's bucket", K: "C" },
  ],
  DefaultSetting: 0, // gets used when adding this to tunebook
  // These are the unmodified and complete ABC tunes in string format.
  Settings: [
    "T: The farmer's bucket\nK:Am...",
    "T: The farmer's bucket\nK:D...",
    "T: The farmer's daughter's bucket\nK:C...",
  ]
}
```

I'm waffling a bit on the data structure. Maybe I could just store your parsed object as a record instead and then just render it as a string when I need to.

**Comment by MattReimer** [comment]
Ok. I think I've got something I can use so I'll close out this issue. In case it helps anyone else, here's what I came up with:

```js
import Parse from 'abcjs/src/parse/abc_parse'

function dbParse(tuneabc){
  const parser = new Parse()
  parser.parse(tuneabc)
  const theTune = parser.getTune()
  const { metaText, media, version, lines, formatting } = theTune
  return {
    ...metaText,
    meter: theTune.getMeter(),
    barlength: theTune.getBarLength(),
    beatlength: theTune.getBeatLength(),
    tuneText: tuneabc
  }
}
```

Which produces something I plan to store and use as indeces in a db:

```json
{
  "title": "Money Lost",
  "tempo": {
    "duration": [
      0.25
    ],
    "bpm": 100
  },
  "composer": "Paul Rosen",
  "source": "Copyright 2007, Paul Rosen",
  "rhythm": "Klezmer",
  "meter": {
    "type": "specified",
    "value": [
      {
        "num": "3",
        "den": "4"
      }
    ]
  },
  "barlength": 0.75,
  "beatlength": 0.25,
  "tuneText": "X: 22\nT:Money Lost\nM:3/4\nL:1/8\nQ:1/4=100\nC:Paul Rosen\nS:Copyright 2007, Paul Rosen\nR:Klezmer\nK:Dm\nAde|:\"Dm\"(f2d)e gf|\"A7\"e2^c4|\"Gm\"B>>^c BA BG|\"A\"A3Ade|\"Dm\"(f2d)e gf|\"A7\"e2^c4|\n\"Gm\"A>>B \"A7\"AG FE|1\"Dm\"D3Ade:|2\"Dm\"D3DEF||:\"Gm\"(G2D)E FG|\"Dm\"A2F4|\"Gm\"B>>c \"A7\"BA BG|\n\"Dm\"A3 DEF|\"Gm\"(G2D)EFG|\"Dm\"A2F4|\"E°\"E>>Fy \"(A7)\"ED^C2|1\"Dm\"D3DEF:|2\"Dm\"D6||\n"
}
```

**Comment by paulrosen** [comment]
Thanks for the suggestion!

In the version 5.1.0 there will be an entry point:
```
import abcjs from 'abcjs';
var tunes = abcjs.parseOnly(tuneBook, params);
```
That will return an array if the string passed contains more than one tune. The params are the same params that can be passed to `renderAbc()`.
