### ISSUE TITLE
Gap between notes

### ISSUE THREAD

**Issue by Secrice** [paulrosen/abcjs#153]
Notes display is little bit changed after 5.1.1. I tested with same abc text with 4.1.1 and 5.1.1

1. Until version 4.1.1
![4 1 1](https://user-images.githubusercontent.com/2404820/40426122-374eacaa-5ed5-11e8-8b6b-26f8520c4c5e.png)
With version 4.1.1 all notes are printed. I think version 3.0 or lower may be same.

2. Version 5.1.1
![5 1 1](https://user-images.githubusercontent.com/2404820/40426141-44a18d0a-5ed5-11e8-9783-41342863486b.png)
With 5.1.1 some notes are not printed. I think the gap between notes seems to be unnecessarily wide.

Can I set the gap between notes?

**Comment by paulrosen** [comment]
What is the ABC string that you are using? What are the parameters that you are calling `renderAbc()` with?

There have been some differences, so I'll try to get to the bottom of this.

**Comment by Secrice** [comment]
I think it's related multiline lyric. You can check by erasing the lines one by one.

T: 구주를 생각만 해도
C: J. B. Dykes
K: G
M: 3/4
L: 1/4
"G"BBB | "Am"A2 "G"B | "Am"c2 "D"F | "G"G3 | "D"DDD |
w: 구 주 를 생 각 만 해 도 이 렇 게
w: 만 민 의 구 주 예 수 의 귀 하 신
w: 참 회 개 하 는 자 에 게 소 망 이
w: 예 수 의 넓 은 사 랑 을 어 찌 다
w: 사 랑 의 구 주 예 수 여 내 기 쁨
"G"B2 "A"A | "D"A3 | "Am"ccB | A2 "A7"G | "D"F2 E | D3 |
w: 좋 거 든 주 얼 굴 뵈 올 때 에 야
w: 이 름 은 천 지 에 있 는 이 름 중
w: 되 시 고 구 하 고 찾 는 자 에 게
w: 말 하 랴 주 사 랑 받 은 사 람 만
w: 되 시 고 이 제 로 부 터 영 원 히
"G"D "C"E "G"G | B2 "D"A | "G"G3 | "C"G3 | "G"G3 |]
w: 얼 마 나 좋 으 랴 ~ ~
w: 비 할 데 없 도 다 ~ ~
w: 기 쁨 이 되 신 다 ~ ~
w: 그 사 랑 알 도 다 ~ ~
w: 영 광 이 되 소 서 아 멘

**Comment by paulrosen** [comment]
Thanks, I've reproduced it. It doesn't have anything to do with the unicode characters either.

**Comment by paulrosen** [comment]
Will be fixed in version 5.1.2

**Comment by paulrosen** [comment]
Will be fixed in version 5.1.2
