### ISSUE TITLE
Midi Player on iPhone

### ISSUE THREAD

**Issue by furkanturan** [paulrosen/abcjs#156]
Hello Dears,

I've started using the abcjs very recently, and developed an ear training application for myself (for now). It basically gives me four random notes, and I try identifying them.

It works very well on desktop version, or on an Android phone I tested so far. However, the player do not play all the four notes on iPhone. If I increase the tempo (BPM) (either by qpm paremter, or with "Q:", then I can hear all the four notes, but with slower tempo I hear either two or one notes.

After spending time and experimenting with different ways of writing the sheet e.g. providing experimenting with X, L, M, Q parameters to the abc sheet, I could not find a solution, and started to think if might it be a bug in the midiplayer. Therefore, I would like to consult on you.

If you want to have a look my code and the application, you can check them here:

- Code: [https://github.com/furkanturan/furkanturan.github.io/tree/master/trainer](https://github.com/furkanturan/furkanturan.github.io/tree/master/trainer) 
- Application: [http://furkanturan.com/trainer](http://furkanturan.com/trainer)

Kind Regards,

**Comment by paulrosen** [comment]
Yes, the midi production is dependent on the hardware. I hope to improve that sometime this year, but there are a couple of issues that could be happening:

1) iPhones and some other platforms will not play sound unless the browser detects that the request came directly from a user's click or touch. I've tried to work around that, but I think there are still cases where the sound is suppressed.

2) The midi is generated dynamically and requires that the device is fast enough to stay ahead of the generation. If the browser tab isn't given enough CPU it will get weird.

3) The sounds are from an external soundfont that is loaded asynchronously. There could be network slowness or some other problem that causes intermittent errors.

I hope this gives you a clue. If you figure out exactly what is happening, let me know. I am too busy until September to look at it, but will at that time.

**Comment by furkanturan** [comment]
Thank you very much for a detailed answer, and giving hints to the potential cause of the problem. I wish that I can solve it.
