### ISSUE TITLE
Is there a way to show empty beat or pause or silence in ABC notations ?

### ISSUE THREAD

**Issue by shivrajsa** [paulrosen/abcjs#157]
To handle note timing we have below method
To shorten note : C/4
For longer note : C4

For long note, is there any way to show empty note instead of C4.
For example : C - - - 
Where '-' could be any other symbol or way to represent gap which is equivalent to single note time.

Also, to support less than one whole note gap
C -/2 - /3 -/7

Is there any way to write gaps in different way instead of giving integer value after note C4.

**Comment by paulrosen** [comment]
I'm not sure I follow what you are asking. Do you have a picture of what you'd like the output to look like?

**Comment by paulrosen** [comment]
Closed for lack of info. Please reopen if you have an example.
