### ISSUE TITLE
[Request for feature] Vertical bar in animations

### ISSUE THREAD

**Issue by raffadrummer** [paulrosen/abcjs#159]
Dear Paul, I would like to use abcjs as a teaching tool in a web application.

I appreciate the quality of rendering and the ease of use of the animation API.

I would like to add a vertical bar moving along the score according to the tempo,
as for instance happens with [Soundslice](https://www.soundslice.com/), see the [example video](https://www.youtube.com/watch?v=Qsq1A2RX-no).

Do you think it will be easy for me to add such feature, or would you consider to add it in a future release?

**Comment by paulrosen** [comment]
Is this what you want? https://configurator.abcjs.net/animation

Click "show cursor", then "start".

The code to implement that is shown at the bottom of the page.

If that's not flexible enough, you can use the `TimingCallbacks` object to get a callback at the same places that the animation routine does.

**Comment by raffadrummer** [comment]
I spent some time playing with `TimingCallbacks` but apparently the highest resolution of the callback is the played event, but as you can see from the example video I'm looking for a continuous (w.r.t. time) movement of the vertical line.
I'm not sure that patching `TimingCallbacks` to add a finer grain callback is the right thing to do.

What is your opinion?

**Comment by paulrosen** [comment]
Well, the problem with continuous play is that notes aren't written in an even time, so there isn't a correct "rate". I guess you could calculate the rate between each note and keep changing it? For instance, a whole note doesn't take up four times the space of a quarter note. And if there are two quarter notes, but one has a sharp on it, they won't take up the same space. And if you have lyrics or a chord symbol, that will change the spacing, too.

I see from the video, recalculating the speed is what they did.

Your request is reasonable as an option. I want to think about how to present it.

In the meantime, you can just keep calling `requestAnimationFrame` and merge that with the timing callback. That is - when you get a timing callback, you figure out the new rate for the cursor, and move the cursor with each of your own `requestAnimationFrame` calls. The trick for you will be to figure out where the next note is so you have a distance.

If you generate the music with `add_classes: true`, then you can look for `abcjs-nX`, where X is a number, the use `getBBox()` to see where the current and next note are.

I might do the above and incorporate it in TimingCallbacks, I don't know.

**Comment by paulrosen** [comment]
I'll leave this open - I might get to it in a month.

**Comment by paulrosen** [comment]
This is implemented - you can get a callback on each subdivided beat. That callback has an x-position that is interpolated between the two notes.
