### ISSUE TITLE
Control the way note velocities are selected

### ISSUE THREAD

**Issue by laertejjunior** [paulrosen/abcjs#162]
Is there any way to report the velocity of the note, something like this?
"%%MIDI beat 80 80 127 80"

var shaker = "%%MIDI drummap A 82  \n %Shaker" +
            "%%MIDI beat 80 80 127 80"+
            "%%score (V0)\n" +
            "V:V0 clef=perc stafflines=1\n" +
            "Q:1/4=80\n" +
            "M: 2/4\n" +
            "K:C perc\n" +
            "L: 1/16\n" +
            "|: AA!>!.AA AA!>!AA :|";

**Comment by paulrosen** [comment]
Not yet! I want to incorporate more of the `%%MIDI` commands - I hope to have time this fall. You've bumped this issue on my list.

**Comment by paulrosen** [comment]
Implemented in 5.3.0
