### ISSUE TITLE
Change color?

### ISSUE THREAD

**Issue by Nickno95** [paulrosen/abcjs#163]
I'd like to know what would be the easiest way to change the color of everything generated by the abc notation, so the notes, staff, text, etc. I want to use this but with a dark background, and the default black will be hard to see.

**Comment by paulrosen** [comment]
The generated music is just a regular SVG, so you can use CSS normally. If you want to just change everything to one other color, you can do something like:

```
<style>
    svg {
        fill: pink;
        stroke: pink;
    }
<style>
```
If you want more control, you can generate the music with `{ add_classes: true }`, then look at what classes are generated. For instance, to turn only the horizontal staff lines pink, do this instead:
```
<style>
    svg .abcjs-staff {
        fill: pink;
        stroke: pink;
    }
<style>
```

**Comment by paulrosen** [comment]
I did add a section to the api doc.

**Comment by chrisfargen** [comment]
Is abcjs still amenable to CSS styling as described above, or does it require JS intervention? Seems that with the current version, the attributes are overriding the CSS.
