### ISSUE TITLE
Printing abcjs demo page cuts off part of rendered notes

### ISSUE THREAD

**Issue by Askaholic** [paulrosen/abcjs#164]
I like to use the demo page at [https://abcjs.net/abcjs-editor.html](https://abcjs.net/abcjs-editor.html) to write up ABC and print the rendered notes to PDF. I know there are other websites for turning ABC into PDF, but I like this way because it's all in my browser. This was working great for a while, but now it seems the SVG isn't scaling to the page width anymore. As a result the right hand side of the image gets truncated. Even when I mess with the scaling through the Chrome developer tools, when printing, the scaled image is still truncated (even though it does get smaller... strange).

Again, this was working as expected in previous versions using the same device, so it's probably a side effect of something you changed in the last update.

As a side note, the selectionCallback parameter div at the bottom of the page also gets in the way of printing, although this is easy to remove with the dev tools. Just a thought if you wanted to make the page more printer friendly.

Browser: ChromeOS Version 65.0.3325.209 (Official Build) (32-bit)
Example:
![Imgur](https://i.imgur.com/pqVZgUY.png)

**Comment by paulrosen** [comment]
I hadn't planned on making that demo printer-friendly, but I did a couple quick things that should help.

I did make a simple app that is designed for editing and printing here: https://editor.drawthedots.com/

You might like that one better.

**Comment by Askaholic** [comment]
Oh cool! I'll try it out.
