### ISSUE TITLE
Hide warnings

### ISSUE THREAD

**Issue by borisrorsvort** [paulrosen/abcjs#168]
Is there a way/option to hide warning like this  ("element type overlay")?
![](https://user-images.githubusercontent.com/39081/44002777-971ce19e-9e48-11e8-9426-73271b4262d2.jpg)

**Comment by paulrosen** [comment]
Does your abc string contain two overlays on the same measure? Unfortunately that isn't yet supported, although it is on my short list to do.

As far as hiding the error, there isn't a supported way to do that. I think you could do it with css by searching for `text[stroke="#FF0000"]`
