### ISSUE TITLE
this abc parse error

### ISSUE THREAD

**Issue by match08** [paulrosen/abcjs#169]
X:1
Z:?
%%scale 0.85
%%pagewidth 20.99cm
%%leftmargin 1.90cm
%%rightmargin 1.27cm
%%score { ( 1 2 ) | ( 3 4 ) }
L:1/16
Q:1/4=120
M:9/16
I:linebreak $
K:D
V:1 treble nm="Piano" snm="Pno."
V:2 treble 
V:3 bass 
V:4 bass 
V:1
!p!"^Allegro non troppo""_15" !5!B!2!F!1!F !3!G!2!F!1!F !5!B!2!F!1!F | %1
 !5!c!2!F!1!F !3!G!2!F!1!F !5!c!2!F!1!F | %2
 !4!d/!1!B/"^non legato"!2!d/f/b/f/ d/f/d/B/!5!d/!4!B/ !2!F/B/F/D/!4!F/D/ |$ %3
 B, z z z !1!Bc dcB"^poco espress." | !2!^A3- ABc BcA | %5
 B/!2!F/!3!B/d/f/d/ !1!B/!5!d/!4!B/!2!F/!4!B/!2!F/ !1!D/!4!F/!2!D/B,/!3!D/B,/ | %6
"^1"!mf! !>!!4!!5!d6- d3- |$ d!3!B!2!B !3!cBB eB!2!B | !>!!3!!5!c6- c3- | c!3!A!2!A !3!BAA dAA | %10
"^2" !1!!3!B/d/B/!1!G/!4!B/!2!G/ !tenuto!E3 !3!e/g/e/c/!4!e/c/ |$ %11
 !1!A/!3!c/A/!2!F/!4!A/F/ !tenuto!D3 !2!d/f/d/B/!4!d/"_dim."B/ | %12
 !1!G/!4!B/!2!G/E/!5!G/!3!E/ !2!C/!4!E/!2!C/A,/!3!C/A,/ AFG | %13
"^3" DA,A, !3!B,!2!A,!1!A, !5!D!2!A,!1!A, |$ !5!E!2!A,!1!A, !3!B,!2!A,!1!A, !5!E!2!A,!1!A, | %15
 !3!F/!1!D/!2!F/"^non legato"A/d/B/ !2!^G/!4!B/G/E/!4!G/E/ !5!B,/E/B,/!2!^G,/!3!B,/G,/ | %16
!p!"^4" !5!A!2!E!1!E"_legato" !3!F!2!E!1!E !5!A!2!E!1!E | !5!B!2!E!1!E !3!F!2!E!1!E !5!B!2!E!1!E |$ %18
 x9 |!mf! E"^5"B,B, !2!=CB,B, E!1!B,!2!B, | !^!!1!C6- C3- | C!1!A,A, B,A,A, !3!DA,!2!A, |$ %22
 !^!!1!B,6- B,3- | B,!1!^G,G, !2!A,"^cre      -"!1!G,!2!G, !3!C"^scen"!1!G,!2!G, | %24
 !^!!1!^A,6-"^do" A,3 | %25
"^6" !4!D/!1!B,/!2!D/F/!1!D/!2!F/!<(! !5!B/!2!F/!4!B/!5!d/!1!B/!2!d/!<)! !>!g3 |$ %26
 !2!!5!C/A,/C/!3!E/C/E/ !5!A/!1!E/!2!A/c/!<(!!1!A/!2!c/ !>!f3 x10!<)!"^ten." | %27
"_*""_)" !2!B,/"_( )"G,/B,/D/!2!B,/"_( )"D/ !5!G/"_( )"D/!1!G/B/G/B/"^ten."!<(! !>!e3-!<)! | %28
"^7" e!1!F!2!F !3!G!2!F!1!F e!1!F!2!F |$ !>!!2!!5!d6- d3- | %30
 d!3!B"_piu"!2!B!f! !4!=c"_rit."!3!B!2!B g!2!B!4!B | !2!!3!^A3 !^!!fermata!f6- | %32
"^8" f/!1!B/"^a tempo"d/!3!f/b/f/ d/f/d/!1!B/!5!d/!4!B/ F/B/F/D/!2!F/!1!D/ |$ !^!d6- !1!d3- | %34
 d!3!c!2!c ^g!2!c!3!c !4!d!3!c!2!c | !1!!5!e!3!c!2!c ^a!2!!3!c!1!!4!d !3!!5!e!1!!4!d!2!!3!c | %36
 !4!fge !>!!4!d3 (3!2!d/!3!c/!5!d/(3!3!c/!5!d/!3!c/!1!B | !fermata!!3!B12 |] %38
V:2
 x9 | x9 | x9 |$ x9 | x9 | x9 | B!2!F!1!F GF!1!F !3!B!1!F!2!F |$ !>!!1!^G6- G3 | %8
 A!1!EE FEE A!1!E!2!E | !>!!1!F6- F3 | G z z z3 z3 |$ x9 | x9 | !3!!5!F3 z3 z3 |$ z9 | z9 | x9 | %17
 x9 |$ !4!c/!1!A/"^non legato"!2!c/e/a/f/ !2!^d/f/d/!>(!B/d/B/ !3!F/B/F/^D/!3!F/!>)!!2!D/ | %19
 !3!E3 z3 !^!!3!!5!G3- | G!3!E!2!E !3!FEE AEE | !^!!5!F6- F3- |$ F!3!D!2!D EDD G!2!D!3!D | %23
 !^!!5!E6- E3- | !1!E!3!C!2!C !3!DCC F!2!C!3!C | B, z z z3 z3 |$ A3 z16 | z9 | z9 |$ x9 | %30
 !^!G6- G3 | F3 ^A6 | x9 |$ B6- B3- | B6- B3 | ^A3 z AB cBA | B6 ^A3 | B12 |] %38
V:3
 B,,3"_ten.""^legato" z !3!B,C"_poco espress." DCB, | ^A,3- A,B,C B,CA, | B,3 z3 z3 |$ %3
 !1!B,!4!F,"^legato"!3!F, !1!G,!4!F,!3!F, !1!B,!4!F,!3!F, | %4
 !1!C!4!F,!3!F, !1!G,!4!F,!3!F, !1!C!4!F,!3!F, | %5
[K:treble] !1!D/!5!B,/!4!D/"^non legato"F/B/F/ D/F/D/"^cresc."B,/!1!D/!2!B,/[K:bass] !4!F,/!1!B,/F,/D,/F,/D,/ | %6
 B,,3"^legato" z !4!B,C DCB, |$ E3 z !4!E,F, ^G,F,E, | A,3 z !4!A,,B,, C,B,,A,, | %9
 D,3 z !4!D,,E,, F,,E,,D,, | %10
!f! G,,3"^non legato" !>!G,/B,/G,/E,/!1!G,/E,/ C,/!1!E,/!2!C,/A,,/C,/A,,/ |$ %11
 !tenuto!F,,3 !>!!2!F,/A,/F,/D,/F,/D,/ !5!B,,/D,/B,,/G,,/!1!B,,/G,,/ | %12
 !tenuto!E,,3 !>!!2!E,/G,/E,/C,/!1!E,/!2!C,/ A,,/C,/A,,/!5!F,,/!1!A,,/F,,/ | %13
!p! D,,3"^legato" z !4!D,,E,, F,,E,,D,, |$ !tenuto!C,,3 z !4!A,,B,, C,B,,A,, | %15
!<(! D,3-"_legato" D,!<)!!>(!!3!E,F, E,F,!>)!D, | !3!!5!E,3 z !4!A,B, C!1!B,A, | %17
 ^G,3- G,A,B, A,B,!2!G, |$!<(! A,3-"^legato" A,!<)!!2!B,=C B,C!2!A, | %19
 G,3 z"^legato" !4!E,F, G,F,E, | A,3 z !4!A,,B,, C,B,,A,, | D,3 z"_ten." !4!D,E, F,E,D, |$ %22
 G,3 z !1!G,F, E,F, G, | C,3 z !2!C,B,, ^A,,B,,C, | F,,3 z !2!F,E, D,E,F, | %25
!f! B,,3"^non legato" !4!D,/B,,/D,/F,/D,/F,/ B,/!4!G,/!2!B,/!1!E/!3!B,/!1!E/ |$ %26
 z3 !3!C,/A,,/C,/E,/!3!C,/!2!E,/ A,/!4!F,/A,/D/A,/D/ x10 | %27
[K:treble] !2!G/!1!B/G/!4!D/!1!G/!2!D/[K:bass] !4!B,/!1!D/B,/G,/!1!B,/G,/ E,/!1!G,/!2!E,/!3!C,/!1!E,/!2!C,/ | %28
 !4!^A,,3-"^legato" A,,!3!B,,C, F,,!1!B,,!3!A,, |$ B,,3 z3 B,,3 | !^!!3!E,6- E,3- | %31
 E,3- !fermata!E,6 | !^!D,2"^non legato""^sempre"!f! z z3 z3 |$ %33
 !4!B,/G,/B,/D/G/D/ B,/!1!D/!2!B,/!4!G,/!1!B,/!2!G,/ !5!D,/!1!G,/D,/!4!B,,/!1!D,/!2!B,,/ | %34
 !tenuto!^E,,3"^legato" z3 z3 | !tenuto!!4!F,,3 z !3!E,F, G,F,E, | D,2!2!E, F,2E, F,2F,, | %37
 !fermata!B,,12 |] %38
V:4
 x9 | x9 | x9 |$ x9 | x9 |[K:treble] x6[K:bass] x3 | x9 |$ x9 | x9 | x9 | x9 |$ x9 | x9 | x9 |$ %14
 x9 | x9 | C,3 z3 z3 | E,3 z3 z3 |$ A,,3 !4!F,6 | x9 | x9 | x9 |$ x9 | x9 | x9 | x9 |$ x19 | %27
[K:treble] x3[K:bass] x6 | x9 |$ %29
[I:staff -1] F[I:staff +1]B,B,[I:staff -1] D[I:staff +1]B,B,[I:staff -1] F[I:staff +1]B,B, | x9 | %31
 x9 | x9 |$ x9 | x9 | x9 | x9 | x12 |] %38

**Comment by paulrosen** [comment]
`linebreak` is not yet supported. Sorry. You can just replace the `$` with a new line, though.
