### ISSUE TITLE
abcjs blocks editor while rendering

### ISSUE THREAD

**Issue by bwl21** [paulrosen/abcjs#17]
I have a complex piece of music, it takes 2 seconds to draw the notes. The problem with this is, that during these 2 seconds the editor does not react on keystokes.

I could not find out if it is the genration of SVG or the rendition of SVG which takes this time.

Maybe we could do some of the following:
1. allow to render each voice in a separate call
2. apply a kind of caching of the symbols
3. try to apply webworkers

...

Any help or support by abcjs is very welcome.

**Comment by danielcajueiro** [comment]
Thank you very much for this amazing editor! Can you take a look at 
http://stackoverflow.com/questions/28658767/what-is-the-correct-way-to-add-the-music-editor-abcjs-to-my-website
Daniel

**Comment by dvdrndlph** [comment]
+1 for this feature. Performance really bogs down with longer tunes. Rendering one line at a time seems to be good granularity. Any hopes for an enhancement in this area in the near future?

Thanks again for the great library.

Cheers,
Dave

**Comment by paulrosen** [comment]
This is an old issue and there have been many changes since then. Is performance still an issue for you? If so, please reopen and paste in an ABC that demonstrates the issue.
