### ISSUE TITLE
Style Bug with repeat signs and numbered brackets

### ISSUE THREAD

**Issue by josyjanga** [paulrosen/abcjs#170]
There is an issue with using repeat signs and wanting the first part of the line having a numbered bracket above the bars. We cannot manage to get the start of the numbered brackets with the numbers 1 and 2 to the actual line, it's always rendered at the end of the previous line. 

Bad solutions we already tried: 
- Putting |1 to the next line results to open lines with the previous line
- adding |1 to the next line with keeping | in the previous line results obviously to a doubled pipe.

abcNotation:
"A7" [eg]>[df][eg][df] [ce]4 |
"D" [df]>[ce][Bd][GB] [FA]4 |
"A7" [GA]2[GA]2 [GA]>[GA][GB][Ac] |
"D" [Fd]>[Ec][Fd][Ge] [Af]4 |
"A7" [eg]>[df][eg][df] [ce]4 |
"D" [df]>[ce][Bd][GB] [FA]4 |
"A7" [GA]2[GA]2 [GA]>[GA][GB][Ac] |1
"D" [Fd]2[Af]2[Fd]2 z2 :|2
"D" [Fd]2[Af]2[Fd]2 [FA][FA] ||!

results to having 1 and 2 at the end of the lines:
![bildschirmfoto 2018-09-19 um 08 30 15](https://user-images.githubusercontent.com/5549075/45735607-b4819c80-bbe8-11e8-86fe-fe4e7b790e00.png)

We've used the same abc syntax in easyAbc and it's rendered fine:
![screenshot 2018-09-19 09 31 13](https://user-images.githubusercontent.com/5549075/45738627-4ee5de00-bbf1-11e8-91b8-37db74cb33ea.png)

**Comment by paulrosen** [comment]
I agree that is a bug, but I don't personally have a problem with a bar line starting the line - I've seen that in other music, so I always use your second work around.

There is a third workaround that might suit you better, though, and that is the "invisible barline", and it would be rendered like this:
```
"A7" [eg]>[df][eg][df] [ce]4 |
"D" [df]>[ce][Bd][GB] [FA]4 |
"A7" [GA]2[GA]2 [GA]>[GA][GB][Ac] |
"D" [Fd]>[Ec][Fd][Ge] [Af]4 |
"A7" [eg]>[df][eg][df] [ce]4 |
"D" [df]>[ce][Bd][GB] [FA]4 |
"A7" [GA]2[GA]2 [GA]>[GA][GB][Ac] |
"D" [|]1 [Fd]2[Af]2[Fd]2 z2 :|
"D" [|]2 [Fd]2[Af]2[Fd]2 [FA][FA] ||!
```

**Comment by josyjanga** [comment]
Thank you for your fast response! The invisible barline is a very good solution! We will use that 👍 

By the way - your work with the library is really great, keep up the good work 🥇

**Comment by narrenfrei** [comment]
The tip with the "invisible barlines" works if there is only one voice, but if there more voices grouped to one staff the brackets are printed twice:

```
X:1
T:Die Vöglein schlafen schon im Wald
%%score (1 | 2)
L:1/4
Q:1/4=120
M:4/4
K:D
V:1
 A |: d A F B | 
w: 1.~Die|Vög- lein schla- fen|
w: |ist schon Zeit zum|
 A G/F/ G A3/4 A/4 |
w: schon im _ Wåld, gua- te|
w: Schla- fen- * gehn, gua- te|
 [|]1 F z z A :|
w: Nåcht! Es|
w: |
 [|]2 F z A d [|] |
w: Nåcht! Ei- ne|
w: |
 A/ G/ F/ G/ A G | 
w: schö- ne gua- te Nåcht, herz-|
w: |
 F/ E/ F/ G/ A B3/4 A/4 | 
w: tau- send- schö- ner Schåtz, gua- te|
w: |
 A G3/4 F/4 G A | 
w: Nåcht, gua- te Nåcht, mein|
w: |
 F z |] 
w: Schåtz!|
w: |
V:2
 A |: F F D G | 
 F E/D/ E F3/4 F/4 |
 [|]1 D z z A :|
 [|]2 D z F A [|] |
 F/ E/ D/ E/ F E | 
 D/ C/ D/ E/ !breath!F G3/4 F/4 | 
 F E3/4 D/4 E F | 
 D z |] 
```

**Comment by narrenfrei** [comment]
@paulrosen Could you reopen this issue?
