### ISSUE TITLE
using beatCallback

### ISSUE THREAD

**Issue by iantbutler** [paulrosen/abcjs#172]
Hi there,

Any suggestions on how to get a beat count for animated midi playback. I want to be able to pause after x bars ... so was trying various ways in the midiListener callback to count beats but couldn't work it out. Is there a way to use beatCallback in renderMidi so I can get a beat count and work out when I'm at the end of a bar when the midi is playing and animating ... this is the basic set up I'm using for midi playback and animation:

```
const songs = ABCJS.renderAbc("paper", part, { add_classes: true, responsive: "resize", }, { format: { vocalfont: "Verdana 10"}});
ABCJS.renderMidi("midi", part,{
   midiListener: function(abcjsElement, currentEvent, context) {};
   animate: { listener: function(lastRange, currentRange, context) { 
            colorRange(lastRange, "#000000");
            colorRange(currentRange, "#3D9AFC");}
  , target: songs[0], generateDownload: true, generateInline: true },
});
```

	

thanks
Ian

**Comment by paulrosen** [comment]
This line is key:
```
   midiListener: function(abcjsElement, currentEvent, context) {};
```
Insert
```
console.log(currentEvent)
```
In the brackets and you'll see the data you need.
