### ISSUE TITLE
Show 8va/8vb above the stave.

### ISSUE THREAD

**Issue by woody-li** [paulrosen/abcjs#173]
I really like the abcjs library, it is truly great.
I got a question and haven't got any solution: 
How to show the 8va/8vb above the stave, and plays the notes one octave higher or lower.
Thanks.

**Comment by woody-li** [comment]
![stave](https://user-images.githubusercontent.com/16889642/46723482-8ef92780-ccaa-11e8-988f-bfd86e410f8a.png)

**Comment by paulrosen** [comment]
I don't have an explicit way to support it. I was looking through the ABC standard and I don't think it is part of the ABC notation. Is it? Do you have a link to the way it should be expressed? If so, I'll implement it.

In the meantime, you can have a couple of options:
1) You can express the clef as `K:C clef=treble+8` and it will show a little "8" above the clef.
2) You can use the annotation syntax to print the 8va (but it won't have any effect on playback) `"^8va--"`.

**Comment by woody-li** [comment]
Thanks for your reply.
I found the Octave clefs in ABC standard-2.2. But I'm not sure whether it is the one or not.
http://abcnotation.com/wiki/abc:standard:v2.2#octave_clefs
The clef setting clef=treble and clef=bass, followed by a ^8 or _8 suffix, draws an '8' above or below the clef, respectively; the abc code is at sounding pitch but on the typeset score the notes will appear one octave below or above where they would normally be positioned (NB ^8 lowers the notes on the staff and _8 raises them).

**Comment by paulrosen** [comment]
The `^8` and `_8` symbols will be in version 5.5.0. the `8va` symbol and dotted line aren't part of the ABC spec as far as I can tell, so I'm holding off on that part.

**Comment by paulrosen** [comment]
I'm closing some old issues due to inactivity. I have this feature on my list to do when I have time.

**Comment by salmonito** [comment]
It does not seem to reset the treble+8 back down an octave. Is this a bug:
X:1
T:Title
%%score [ 1 | 2 ]
L:1/8
M:3/4
I:linebreak 
K:F
V:1 treble 
L:1/16
V:2 bass
V:1
[K:clef=treble+8]c4c4c4| c4c4c4 |[K:clef=treble] c4c4c4 | 
V:1 clef=treble
c4c4c4:|
V:2
L:1/8
C6 | C6 | C6|
C6  :|
