### ISSUE TITLE
After visualTranspose, some accidental notes are supposed to be natural notes but not

### ISSUE THREAD

**Issue by kwonyounggu** [paulrosen/abcjs#177]
Hello Paul,

After visualTranspose, some accidental notes are supposed to be natural notes but it is not working in the way. For example, in C key there is a note B flat and it is transposed to A maj key which got a node G flat.

Mathmatically it is correct because G flat in A maj Key is equal to G. But I think that the note need to show G natural.

Would you like to advise this please?

Thank you very much for your works on abcjs.

**Comment by paulrosen** [comment]
Would you submit a small example ABC string and the parameters you used to call renderAbc()?

**Comment by kwonyounggu** [comment]
Hello Paul,

The example ABC String and renderAbc() are as below:

X: 1
T: Yesterday
M: 4/4
Q: 90
K: C
Z|:GFF6|z2AB ^cdef|e3/2d/d6|
z2dd c_BAG|_B2AA-A2G2|F2AG-G2D2|F2AA-A4:|
|:A4A4|d2e2f2ed|e3dc2dA-|A8|
A4A4|d2e2f2ed|e3dc2e2|f2c2_B2A2|
GFF6|z2AB ^cdef|e3/2d/d6|
z2dd c_BAG|_B2AA-A2G2|F2AG-G2D2|F2AA-A4:|
F2A2G2D2|F2AA-A4|];

this.abcEngine = abcjs.renderAbc
(
	this.abcSheetContainer, 
	this.abcString[0], 
	{
		add_classes: true,
		visualTranspose: this.visualTransposeAmount,
		staffwidth: (this.props.playMusicPanel.current.node.clientWidth - 20), 
		clickListener: (abcElement, tuneNumber, classes) => this.onNoteClick(abcElement, tuneNumber, classes)
	}
);

Thank you very much.

**Comment by paulrosen** [comment]
Will be fixed in version 5.5.0
