### ISSUE TITLE
displaying dynamic bars on each event is possible?

### ISSUE THREAD

**Issue by kwonyounggu** [paulrosen/abcjs#178]
Hello Paul,

Would it be possible to display the number of bars dynamically from abcString using the same tune on each event through the function renderAbc(...)?

Thank you very much.

**Comment by paulrosen** [comment]
I'm not sure what you are asking. Can you provide more details? 

If you are asking if you can get the number of bars that a particular abc string contains, then you would have to count them yourself from the object that is returned from the renderAbc call.

**Comment by kwonyounggu** [comment]
Sorry for the vague question.
I mean
eg1) if you want to display the music sheet with 4 bar base then renderAbc(...bar: 4) displays 
        ---- | ----| ----| ----|
        ---- | ----| ----| ----|
        etc

eg2) if you want to display the music sheet with 6 bar base then renderAbc(...bar: 6) displays
     ---- | ----| ----| ----| ----| ----|
     ---- | ----| ----| ----| ----| ----|
        etc  

eg3) if you want to display the music sheet with 3 bar base then renderAbc(...bar: 3) displays
     ---- | ----| ----| 
     ---- | ----| ----|
        etc  

If not available, it is OK.

Thank you very much for your time.

**Comment by paulrosen** [comment]
I think you are asking for:
```
%%barsperstaff 4
```
That is part of the ABC string, not a parameter.

You might want to look at the `wrap` parameter. That will do the number of bars you specify if there is enough room, and falls back to other methods if not. For instance:
```
renderAbc(str, { wrap: { minSpacing: 1, maxSpacing: 5, preferredMeasuresPerLine: 4 } });
```

**Comment by kwonyounggu** [comment]
Hello Paul,

I have tried two ways of changing the number of bars per staff and found the following results;
1. %%barsperstaff 5
   four bars written in abcString as 
    ----|----|----|----|
    ----|----|----|----|
   etc
    RESULT:  renderAbc(...) displays four bars per staff, no effect of the directives.

2. renderAbc(abcString, { wrap: { minSpacing: 1, maxSpacing: 5, preferredMeasuresPerLine: 5 } })
   where abcString contains four bars per staff.
   RESULT:  renderAbc(...) displays four bars per staff, no effect of the wrap.

It seems that changing the number of bars per staff programmatically regardless of how many bars are decleared in the abcString is not applicable at the moment.

Thank you very much for your help again.
