### ISSUE TITLE
Note and beam overlapping

### ISSUE THREAD

**Issue by miluxmilux** [paulrosen/abcjs#179]
Hi there!
I really like abcjs for the simplicity and efficiency, thanks for the good work! I am running into a small snippet, where a note and a beam are overlapping. Is this possibly a bug, or did I miss something somewhere ?
<img width="157" alt="note and beam overlapping" src="https://user-images.githubusercontent.com/4193144/49017849-28f92e80-f18a-11e8-8556-ae134e560969.png">

The code is simply : 
`^f^C^f`

**Comment by paulrosen** [comment]
It looks like a bug. I don't know of an easy workaround either. Thanks for the small snippet. I will try to have an update in a week.
