### ISSUE TITLE
Feature request: only play melody

### ISSUE THREAD

**Issue by josyjanga** [paulrosen/abcjs#180]
Hi Paul,
again thanks for your great work!
I have a question regarding the audio: there is an option with renderMidi for not playing the melody, configured with voicesOff. Documentation says "Play the metronome and accompaniment; do the animation callbacks, but don't play any melody lines".
What I would need is the other way around, an option for only playing the melody but not the accompaniment. Will this be possible in the future or do you see any option, how I could accomplish this?
Thank you. Lisi

**Comment by paulrosen** [comment]
I've had a request for this before and it would be fairly simple to do. I'm planning a small maintenance release this month and will add an option for that.

In the meantime, if you want to hack something, you can find `gChordTacet` in `abc_midi_flattener.js` and make sure it always remains `true`.

**Comment by paulrosen** [comment]
Will be added in version 5.5.0.
