### ISSUE TITLE
Feature Request: Show the note letters on the staff

### ISSUE THREAD

**Issue by johnkeeney** [paulrosen/abcjs#181]
Thanks for abcjs. I love it!

Like alot of (most?) Irish Music / Folk Music players I struggle to read staff notation, and the inline markup in abc notation makes it hard to read. 
It would be great if the note letter could be displayed on the staff.

I wrote a simple script that pre-processes abc text to add the note/letter as lyrics text, which is then displayed.
See https://sites.google.com/site/johnkeeney/code/abc2notes 
(I even added a simple demo using abcjs :-) )

It would be great if abcjs had a similar feature.

**Comment by paulrosen** [comment]
Since there's a work around and this isn't part of the ABC standard, I probably won't get to this. Sorry.
