### ISSUE TITLE
Move progress indicator when clicking on progress background 

### ISSUE THREAD

**Issue by macno** [paulrosen/abcjs#183]
Hi Paul,
I'd need to see the indicator in the correct position after clicking on the progress background even when the player is stopped

I pushed this commit in my branch [1], it's working but I had to remove this condition [2]. Is it safe? Why was it there in first place?

Thanks,
m.

[1] https://github.com/macno/abcjs/commit/58d3542a48e1a75589dcdd799d54e9e8b44bebb7
[2] https://github.com/macno/abcjs/commit/58d3542a48e1a75589dcdd799d54e9e8b44bebb7#diff-28b6e2b7762ea9d459894375fbb70748R342

**Comment by paulrosen** [comment]
Your change looks logical at a glance. 

That condition was put in fairly late with the commit "Fix bug in midi animation when starting and stopping the midi." I don't remember the exact problem.

I'm guessing that there was some kind of race condition where one can click wildly on the control and get into a funny state.

Anyway, I've been annoyed by the problem you're fixing, so I hope you create a pull request. I'm planning on doing a bit of midi work in the next couple of months.

**Comment by macno** [comment]
Absolutely, if it’s ok I’ll open a PR as soon as I return at office.
 next on I’ll work on drag/drop indicator across the progress bar.

**Comment by paulrosen** [comment]
Thanks for all this - I'm hoping to do a quick release just before the new year.

**Comment by macno** [comment]
Here's the PR #184

**Comment by paulrosen** [comment]
Will be fixed in v5.6.0
