### ISSUE TITLE
Tempo, how does it work?

### ISSUE THREAD

**Issue by macno** [paulrosen/abcjs#186]
Hi, I'm trying to change the bpm from the midi player, but even in your example[1] I'm not able to do it. How does it work?

Thanks

[1] https://configurator.abcjs.net/audio

**Comment by paulrosen** [comment]
I'll look at this next week - I think I never finished hooking this up when I got distracted from this project last time.

**Comment by gaspa** [comment]
Hi @paulrosen , did you take a look on this issue?
I'm currently trying to use the tempo feature of abc too.

What I found is that abc controls try to set MIDI.player.warp property, but that parameter is not used at all by MIDI.js internals. There is a bpm property that's (sadly) used only when a file is provided, not events as abcjs do.

In MIDI.js/js/player.js we fall into this load() case:

```
463:			if (args.events) {
464:				_midiEvents = args.events;
465:			        _midiFile = undefined;
466:				load();
```

and bpm property is used only here:

```
377:     if (_midiFile)
378:         _midiEvents = new Replayer(MidiFile(_midiFile), player.bpm);
```

Moreover, MIDI.js code diverted from the master, in the branch you are using as dependency the only used property is bpm, while in the master branch they renamed warp into timeWarp and added it to Replayer arguments. Seems MIDI.player doesn't take events anymore, though.

**Comment by paulrosen** [comment]
At the moment, this feature isn't completely hooked up. I plan to do some major reworking of the midi functionality soon, but I need an unbroken couple of weeks to work on it. Sorry.

**Comment by gaspa** [comment]
>  I plan to do some major reworking of the midi functionality soon,

Hi @paulrosen , any news about this?

**Comment by paulrosen** [comment]
There is new audio support and I think this is no longer an issue.
