### ISSUE TITLE
Abnormal preventDefault of mousemove eventListener

### ISSUE THREAD

**Issue by woody-li** [paulrosen/abcjs#188]
The select, drag and others mousemove events invalid in my project after upgraded abcjs to version 5.6.0.
Such as select some text in input element and so on. There's event.preventDefault() at abc_midi_controls.js, mousemove eventListener.

What's more, lots of event listeners were binded on document and body. Is it possible to change the listener to abc midi or paper element. The less listener callback called in this way, and I think it will be better for performance and development.

**Comment by paulrosen** [comment]
I think this pull request: https://github.com/paulrosen/abcjs/pull/187 might take care of it. I'll be trying to get an update out really soon.

I will revisit the way the event listeners are set, too.

Thanks!

**Comment by woody-li** [comment]
Oh, that's a good news.
Thank you for your efforts.

**Comment by paulrosen** [comment]
Will be fixed in 5.6.2
