### ISSUE TITLE
Flat beams and triplet brackets

### ISSUE THREAD

**Issue by davidrthorn** [paulrosen/abcjs#191]
Drums are standardly notated with flat beams (and stems up). Is there any way to force this behaviour in abcjs?

Not the issues that arise with triplet brackets when beams are not flat:

![screenshot 2019-01-27 at 14 33 07](https://user-images.githubusercontent.com/9431760/51802343-0a261f80-2241-11e9-9d2a-b357e398840c.png)

Ideally this would have flat beams that are always at the same height above the stave, with triplet brackets also always flat and above the beams.

Otherwise loving the library!

**Comment by paulrosen** [comment]
I don't think there is an ABC directive to force flat triplet braces. If you know of one, let me know. In the meantime, the fix I made should improve things for you.

**Comment by davidrthorn** [comment]
Awesome, thanks @paulrosen. What about forcing flat, vertically aligned beams on all notes? I know this works for grace notes in abcjs. This would definitely make it more powerful for drum kit applications:

![image](https://user-images.githubusercontent.com/9431760/51803160-a2280700-2249-11e9-8b3a-e32b8bdf9c73.png)

**Comment by paulrosen** [comment]
Actually there is a command for that:
```
%%flatbeams 1
```
I am not currently supporting it, but I will implement that for version 5.6.3, too.

**Comment by davidrthorn** [comment]
Greatly appreciated

**Comment by davidrthorn** [comment]
So weird, I'm still getting this when using 5.6.3. I'm using it in a react component with react-abc, but all that does is render using abcjs anyway.

![screenshot 2019-01-28 at 17 16 25](https://user-images.githubusercontent.com/9431760/51853647-af63f500-2320-11e9-8cec-a21e81390a24.png)
