### ISSUE TITLE
Old files in release packages

### ISSUE THREAD

**Issue by xaprb** [paulrosen/abcjs#193]
When I unzip a release I see what looks like all past versions of the library in the `bin` directory, which is starting to have a lot of files! I'd suggest considering only shipping the latest, for succinctness. I also see that there's a file named "latest" which doesn't look the same as the actual latest version. I haven't looked into it any deeper than glancing at the file sizes.

<img width="882" alt="screen shot 2019-01-28 at 9 07 26 am" src="https://user-images.githubusercontent.com/279875/51841249-30e56400-22dc-11e9-868b-d7af6c02bbe2.png">

**Comment by paulrosen** [comment]
Agreed! That needs to be cleaned up. I'll get around to it for the next release. In fact, the npm version doesn't need any of those minimized files at all. That is for people who want to include the script directly.

**Comment by paulrosen** [comment]
i removed all the "latest" files, since they were not kept up to date anyway. I did want to keep a copy of all the releases available, though.

**Comment by p-himik** [comment]
Regarding all of the releases - why does it have to be in the current branch? There are tags, there are GitHub releases, there are releases at npmjs.
My main issue with storing everything in `bin` is that software (IntelliJ IDEA in my case) tends to index *all* of these files. It makes indexing take a huge amount of time to finish.

**Comment by p-himik** [comment]
@paulrosen Ping. Any thoughts?

**Comment by paulrosen** [comment]
I'm trying to figure out a way that the files can remain as a permalink, but not carry them around. 

One quick workaround for you, though, is in WebStorm, right-click the `bin` folder, and click "mark as excluded". Then it won't index them or show them in global searches.

**Comment by p-himik** [comment]
You cannot exclude folders that are in the library folder - i.e. in `node_modules`. At least, it's not allowed in my version of IDEA.

GitHub allows you to permalink by using any branches/tags. E.g. here's the link to the README of the version 2.0: https://github.com/paulrosen/abcjs/blob/2.0/README.md

**Comment by p-himik** [comment]
Just to show that there's indeed an significant issue.
No "Mark Directory as" for the library directory subdirectories:
![image](https://user-images.githubusercontent.com/4410314/59258650-0a97e380-8c41-11e9-9d6d-28a8090505fa.png)

And this has been there for 12 minutes already, while using CPU that whole time (SSD, i7-4710HQ):
![image](https://user-images.githubusercontent.com/4410314/59258697-1edbe080-8c41-11e9-815f-6c23cfbd2247.png)

**Comment by paulrosen** [comment]
I use WebStorm and I don't see that - I wonder if there is a setting I set years ago that I don't remember. I create new apps that include abcjs fairly often, too.

Anyway, a quick fix is to just delete the `node_modules/abcjs/bin` folder altogether.

I have excluded the bin folder from being distributed in the next version and I'll release that sometime soon.

**Comment by p-himik** [comment]
Great, thank you!

WebStorm may be different in that regard by default. I've never used it, so I have no idea. But I couldn't find any relevant switch in IDEA.
