### ISSUE TITLE
How to animate from measure-note X to measure note Y

### ISSUE THREAD

**Issue by jepcolombia** [paulrosen/abcjs#196]
Hi Paul,
I would like to have  a tip on how , using both types of animations available, given a from/to measures do a specified animation to be able to implement partial playbacks.
Thanks a lot in advance

**Comment by paulrosen** [comment]
Have you seen these pages?

If you aren't doing midi:
https://configurator.abcjs.net/animation
(click the "Show cursor" checkbox, then the "start" button.)

If you are doing midi:
https://configurator.abcjs.net/audio
(click the "Animate" checkbox then click the start triangle on the audio control.)

I'm not sure what other info you need but let me know if I'm misinterpreting your question.

**Comment by jepcolombia** [comment]
Thanks Paul for your answer. I have been using and learning from your configurator ( it helps a lot), but I still can not figure out how to make a loop during a play back to go for example from measure 10 to 25 or re-start the playback at any desired measure or note ( I could take the "from" measure using an input field o using clickListener. The same for the "to" measure but do not know instrucctions to do this specific   playback. starAnimation or midi.startPlaying allways start from the beginning ?
Iam trying, for midi, the midi.setRandomProgress function and clickListener but I would like to know is there is a direct way to do this for basic and midi version.
Thank you very much!!

**Comment by paulrosen** [comment]
It sounds like you are using the midi playback, so this won't apply if so, but I just added a random access function to TimingCallback.

That is,
```
var timer = abcjs.TimingCallbacks(etc...)
timer.start();
...
timer.setProgress(0.5); // set the timing to the center
```

**Comment by paulrosen** [comment]
For the midi, `setRandomProgress` is what you want. I'm not sure I understand what isn't working. You send in a percentage, from 0 to 1.

**Comment by jepcolombia** [comment]
Yes setRandomProgress works but since i have to know the exact time to convert to a percentage I thought there were other direct way to do that. 
Thank you very much Paul for your help

**Comment by paulrosen** [comment]
I could add a conversion function - I've calculated all of that internally. I'm not sure what the UI would be, though. What do you have? The element that the user clicked on? The beat number? The measure number?

I'm going to be doing a similar function soon in a project, so once I start that I'll have some ideas about what it needs to look like. For our purposes, we probably won't allow a unit smaller than a measure.

**Comment by jepcolombia** [comment]
The element the user click on and the measure number would be great. The first one for user will and desires, and the second one for predifined segments like intro, bridge, endings, and predifined sections of a song. I will be looking forward to your function....many thanks again!!

**Comment by jepcolombia** [comment]
Hin Paul . Iam trying the random fuction
timer.setProgress(0.5); and doing console.log(timer) I can see currentBeat and currentEvent fields showing it  is working but the cursor does not move to the midle , it keeps going o resumes in the same position or animate from the beginning but not from middle.

**Comment by jepcolombia** [comment]
Hi Paul,
What about the function you were about to do for your project on animating specific segments?
I will appreciate a help on this!!

**Comment by paulrosen** [comment]
The newest version of abcjs has a reworked audio section - I haven't touched the old way for backwards compatibility, but look at the sample full-synth.html. You can see the info that is now being received on callback is a bit different.

Over the next couple versions I'll be incorporating more features to make the example simpler.

**Comment by jepcolombia** [comment]
Thanks Paul very much ..at first glance look like cursorControl is key on this, right?

**Comment by jepcolombia** [comment]
and synth-Control.js of course!!
