### ISSUE TITLE
"unhandled promise rejection" errors

### ISSUE THREAD

**Issue by fh413** [paulrosen/abcjs#197]
Thank you for your work.

When I call renderMidi with startPlaying:true, the slider start moving, without any sound, and I get numerous "unhandled promise rejection" errors (one by note ?).
When it is triggered from a button, everything is OK, but I don't want to trigger it from a button. I'd like the tune to begin as soon as the page is loaded.

Thank you for your help.

**Comment by paulrosen** [comment]
You are likely running into the autoplay protection in browsers. You need to initiate the sound in the handler for a user click, touch, or key press.

I don't have clear error handling in this case yet - sorry about that. This code was written before browsers started enforcing that. I will improve the error handling in an upcoming version.

**Comment by fh413** [comment]
Thank you
