### ISSUE TITLE
How to multi part from the middle of a tune.

### ISSUE THREAD

**Issue by ryohorie** [paulrosen/abcjs#198]
Hi, Thank you for great product.
I want to how to multi part from the middle of a tune.
for example,
```
X:1
T:Title
L:1/4
M:4/4
K:C
V:1 treble
V:2 bass
V:1
C D E F | G A B c |
C D E F | G A B c |
V:2
 
C, D, E, F, | G, A, B, C |
```
This source shows, first line 2part, second line 1part.
but I want first line 1part, second line 2part.
Is it possible?

**Comment by paulrosen** [comment]
First, declare
```
%%staffnonote 0
```
That will keep blank lines from being printed.

Second, create a placeholder for the measures that don't exist with the "invisible rest" `x`. So just below `V:2` should be:
```
x4|x4|
```

**Comment by ryohorie** [comment]
Thank you for your reply.
I did it!
This is a wonderful product. Thank you so much!
