### ISSUE TITLE
startAnimation won't work

### ISSUE THREAD

**Issue by remcohh** [paulrosen/abcjs#20]
I tried to implement startAnimation without success:

this is my code:
        song = "X:1\nT: test\nM: 4/4\nL: 1/8\nR: reel\nK: Emin\n|abca|cccc|";

        $( document ).ready(function() {
            tuneObjectArray = window.ABCJS.renderAbc("score" , song);
            window.ABCJS.startAnimation($("#score")[0], tuneObjectArray[0], {hideFinishedMeasures: "true",
            showCursor: true, bpm: true})
        });

it crashes on line 153 of abc_animation.js   
"cannot read property split of undefined"
it appears to crash on the bars but if I leave them out nothing happens.

**Comment by paulrosen** [comment]
Is this now resolved for you? I think all the problems in this area have been addressed.

**Comment by hoanvo** [comment]
Thanks Paulrosen for your great library. I am using renderMidi method to render midi, but I don't know which events for starting, finishing the rendering midi. Who helps me? Thanks!
