### ISSUE TITLE
Abnormal space between note and dynamic sign.

### ISSUE THREAD

**Issue by woody-li** [paulrosen/abcjs#200]
There's space between note and dynamic sign when **using annotation text**.
And it seems too close to the stave below.
Notes:
T: Test
M: 4/4
|E!p!BBA B2 "_legato"EB|B2 AB dBAG|FDAD BDAD|FDAD dAFD|
ECBA B2 EB|B2 AB defg|afe^c dBAF|DEFD E2|

The dynamic sign "p" is closer to the "B" note at the second line.

**Comment by paulrosen** [comment]
Interesting - The reason it is like that is that I put dynamic signs in the same "lane". For instance, imagine the following:
```
T: Test
M: 4/4
|E!p!BBA !crescendo(!B2 "_legato"EB|B2 !crescendo)!AB dBAG|FDAD BDAD|FDAD dAFD|
ECBA B2 EB|B2 AB defg|afe^c dBAF|DEFD E2|
```
I agree it looks odd. Perhaps there needs to be a post-processing step that collapses some lanes if they aren't needed.

**Comment by woody-li** [comment]
I've been thinking about this problem. 
If it's not easy to collapses lanes, is it possible to get a way to increase distance between staves?
So It looks only sparse and won't be ambiguous.

**Comment by paulrosen** [comment]
That one's easy:
```
%%staffsep 70
```
Experiment with different numbers.

**Comment by paulrosen** [comment]
closed for lack of activity
