### ISSUE TITLE
Feature request: startAnimation with parameter milliseconds

### ISSUE THREAD

**Issue by josyjanga** [paulrosen/abcjs#202]
Hi Paul,
thank you for updating the library constantly and bringing in new features.

I've got a request regarding the method ABCJS.startAnimation(outputElement, tuneObject, animationParams). **I would need to control the animated cursor and set it to another position (back and forth in time).** 
When I am using an external audio player for playing the midi, it would be really useful to have a new animation param to set a startpoint in milliseconds (or percentage). Even better would be a new method, next to pause and stop, for moving the animation cursor anytime to any progress. I saw you already did something similar with midi.setRandomProgress, but in my usecase I cannot use the default midi player and I have to make use of another audio output.

I didn't see any way to extend the animation features myself and accomplish what I would need. But maybe you can help me with that :-)
Thank you!

**Comment by paulrosen** [comment]
I created a new way to handle animation - I think the library should just do the timing and let the application handle what happens. So, if you can change, look at `new abcjs.TimingCallbacks(outputElement, timingParams)`. That will allow you to set callbacks for each event, each measure, each beat, and each line. That method does have a `setProgress(percent)` call.

You mentioned this at a good time, too. I'm about to do a similar thing, so I might be fixing bugs, and if there are tweaks you want, let me know.

The basic usage:
```
var tuneObj = abcjs.renderAbc(etc...);
var timer = new abcjs.TimingCallbacks(
  tuneObj[0], 
  {
    qpm: beatsPerMinute,
    extraMeasuresAtBeginning: numberOfBlankMeasures,
    beatCallback: beatCallback,
    eventCallback: eventCallback,
    lineEndCallback: lineEndCallback,
    lineEndAnticipation: numMillisecsBeforeEndOfLineForCallback
  });
```

**Comment by paulrosen** [comment]
Version 5.6.9 will have a slightly improved `timer.setProgress(percent)` functionality. If you have any problems with it for your application, please let me know.

**Comment by josyjanga** [comment]
Thank you Paul, I'm still using the older version 5.6.7, but setting the progress works like a charm :-)
`abctimer.setProgress(startInMilliseconds);`
