### ISSUE TITLE
Bug ? Notation do not display

### ISSUE THREAD

**Issue by pounia** [paulrosen/abcjs#203]
I am so frustrated.

When I first write a new post, the notation displays.
http://randomnotes.byethost7.com/wp/2019/03/07/hello3/

But if I modify anything, then whatever I do, it is gone ! I mean nothing shows, and I stare at a blank post...
http://randomnotes.byethost7.com/wp/2019/03/07/hello4/

Can you help ?

**Comment by pounia** [comment]
(continued) I've just installed a new wordpress site to test abcjs.
Downloaded the plugin, activated it.
Between the two previous posts, there is virtually no difference. Just tried to change one note to another. Failed. Went back to previous notation. Nothing shows.
I've repeated this process 4 times (same result)(new posts each time) before asking you.

**Comment by paulrosen** [comment]
I need to see your raw post to be sure, but my guess is that it has to do with character substitution. Are you preserving the newlines correctly? Did it insert extra newlines in the post? Can you go to the hello4 post, change to the "code editor", and paste the contents of the textarea?

**Comment by pounia** [comment]
Ok that worked. I am not used to the lastest versions of WP. And all that seemed fair and simple in WP in the past is now (to me) obscure and needlessly fancy. Seems the "pre formatting" wrecks everything and i need to type in code editor. Thanks. Just needed this quick help.
By the way, 1) can you insert variables in posts  in the middle of the abcs shortcode (random notes) 2) and is there a bass key display code ?

**Comment by pounia** [comment]
(can't edit messages on Github ?)
(continued)
http://randomnotes.byethost7.com/wp/2019/03/07/hello4/
WOrking now. Thanks again.
