### ISSUE TITLE
[1 with &\ 

### ISSUE THREAD

**Issue by Secrice** [paulrosen/abcjs#205]
C8 &\\
ABC DEF |

![스크린샷 2019-03-18 오후 7 59 12](https://user-images.githubusercontent.com/2404820/54525833-68a58980-49b8-11e9-9ea2-f610612bbc2c.png)

[1 C8 &\\
ABC DEF |

![스크린샷 2019-03-18 오후 7 59 19](https://user-images.githubusercontent.com/2404820/54525839-6cd1a700-49b8-11e9-81d1-65f8f5a6a710.png)

Please compare above two. (I don't know what should I call this in English)

**Comment by paulrosen** [comment]
Thanks! That's definitely a bug. I'll get to it soon.

**Comment by paulrosen** [comment]
Will be fixed in 5.6.9
