### ISSUE TITLE
Configuring abcjs_plugin-midi

### ISSUE THREAD

**Issue by hoejoe** [paulrosen/abcjs#206]
Is there a way to configure the MIDI output of abcjs_plugin-midi_xxx-min.js?
I integrate this script in the following way:
  
  <script type="text/javascript" src="js/midi/abcjs_plugin-midi_5.6.5-min.js"></script>
	<script type="text/javascript">
	window.ABCJS.plugin.render_before = false;
	window.ABCJS.plugin.render_options = {responsive: "resize",};
	window.ABCJS.plugin.abcjsParams = {program: 41, qpm: 100,};
	// window.ABCJS.renderMidi("midi", abc, {program: 41, qpm: 100, });
	// window.ABCJS.midi = {program: 41, qpm: 100, };
	// window.ABCJS.render = {program: 41, qpm: 100, };
	// window.ABCJS.plugin.debug = true;
	</script>

I've tried different variants, but unfortunately all without success.
Can you please give me a hint on how to proceed here?

Many thanks in advance!
Johannes Hölzl

**Comment by paulrosen** [comment]
All of the options for both creating the SVG and creating the audio control are in the same item now. So in your example it would be:
```
window.ABCJS.plugin.render_options = {responsive: "resize", program: 41, qpm: 100};
```

**Comment by hoejoe** [comment]
Many thanks for the quick answer and help!
