### ISSUE TITLE
Extract Measures

### ISSUE THREAD

**Issue by dannofield** [paulrosen/abcjs#207]
Hello Paul. All this work is awsome.
I have a little issue: ABCJS.extractMeasures is only returning measures for voice 0.
Sorry if I'm doing somthing wrong:
My ABC string Ex:

X: 1
T: Three bass lines
K: C
V: 1 clef=bass
[| CDEF GABc | cdef gabc' | c'bag fedc | cBAG FEDC |]
w: C D E F G A B c c d e f g a b c' c' b a g f e d c c B A G F E D C
V: 2 clef=bass middle=D
[| C,D,E,F, G,A,B,C | CDEF GABc | cBAG FEDC | CB,A,G, F,E,D,C, |]
w: C, D, E, F, G, A, B, C C D E F G A B c c B A G F E D C C B, A, G, F, E, D, C,
V: 3 clef=bass,,
[| C,,D,,E,,F,, G,,A,,B,,C, | C,D,E,F, G,A,B,C | CB,A,G, F,E,D,C, | C,B,,A,,G,, F,,E,,D,,C,, |]
w: C,, D,, E,, F,, G,, A,, B,, C, C, D, E, F, G, A, B, C C B, A, G, F, E, D, C, C, B,, A,, G,, F,, E,, D,, C,,

**Comment by paulrosen** [comment]
extractMeasures is a new feature that I've just recently added.

I was running into some complications for multiple voices, so, in the interest of getting it working for a single voice (which satisfied my immediate need), I am only doing the first voice.

I do want to revisit this and get the other voices working soon, but I can't give you an estimated date. Sorry.

**Comment by dannofield** [comment]
Thank you.
I would like to ask you something else.
Let's say I want to draw on top of the sheet music a osciloscope. How can I know the the lines sataff position, heigth of a line and height of the spaces?
I am attaching a picture so you can understan a little bit better.

The only useful measure I can see is 
tuneObjectArray = ABCJS.renderAbc(output, tunebookString, params);
tuneObjectArray [0].engraver.engraver.renderer.controller.staffgroups[0"].staffs[0].absoluteY

Thank you very much for your work.

![image](https://user-images.githubusercontent.com/19209484/55281805-147f9b00-5310-11e9-8f6b-dfc47b817114.png)
![Imagen2](https://user-images.githubusercontent.com/19209484/55281811-1fd2c680-5310-11e9-9e14-43ddbf066bde.png)

**Comment by paulrosen** [comment]
Look at https://configurator.abcjs.net/classes . If you add `{ add_classes: true }` to the render you can get a lot of info. In particular, look at `abcjs-top-line` to isolate where the staves were placed. 

It might be useful to you to render each line in a different SVG by adding: `{ oneSvgPerLine: true }`. Then you can easily know what line you are looking at.
