### ISSUE TITLE
Unexpected behaviour with responsive resize

### ISSUE THREAD

**Issue by jimc-hjones** [paulrosen/abcjs#211]
This may be easily solvable with better css,  but I've noted an odd feature with responsive resize. I'm using abcjs_plugin_5.6.5-min.js with a php script that lets the user select two or three tunes to be displayed in order.  In order that the size of the stave doesn't get too extreme on large screens and to give a reasonable chance of getting two tunes on the screen at once I've used this css for larger screen widths:
`
	div.abcrendered {
		width: 50%;
		max-width: 600px;
	}`
and these settings 
`<script src="js/abcjs_plugin_5.6.5-min.js" type="text/javascript"></script>`
`<script type="text/javascript">`
`    ABCJS.plugin.hide_abc = true;`
`    window.ABCJS.plugin.render_options = {responsive: "resize",};`
`</script>`

The odd thing about this is that if I resize the screen wider than 600px then although the stave stays at the desired width, the spacing between the tunes increases in proportion to the screen width. I know nothing about svg, but it seems as if although the actual graphic stops resizing when the div hits max-width, the height of the 'page' including white space carries on getting larger.  

Other than that: its great, its doing the job for me.

**Comment by paulrosen** [comment]
I'd have to experiment with this to tell. One thing to try is put an extra div between what you are sizing and the div that contains the abc.

And, the purpose of the plugin version is to use when you don't have much control over the page. You might be better off using the basic version instead and calling `renderAbc` yourself when you are ready. But if it is working for you, I guess you don't need to change it.

**Comment by jimc-hjones** [comment]
OK thanks. I'll try and produce a standalone file that reproduces the problem over the next few days. Adding an extra div outside everything didn't seem t make any difference.

**Comment by paulrosen** [comment]
The extra div I was suggesting is between, like this:

```
<div style=" width: 50%; max-width: 600px;">
  <div> <!-- extra div to be sure that abcjs doesn't interfere with your styling -->
    <div id="canvas">
    </div>
  </div>
</div>
```

**Comment by jimc-hjones** [comment]
Excellent.  I understand what you mean now.

Yes, that seems to work. If I wrap a div round the tunes with the style, rather than applying the style to the internal abcrendered div then I don't seem to get the issue. I'm sure there was a reason why I went deep into the rendered html, but I've forgotten what it was and no issues seem apparent now. 

If its of interest here's a zip with my test files.

[TestTune.zip](https://github.com/paulrosen/abcjs/files/3093392/TestTune.zip)

Thanks again for your assistance, regards, Jim C
