### ISSUE TITLE
Sync midi and highlight on ABCJS Demo page

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#212]
Hi, I started to use the https://abcjs.net/abcjs-editor.html as a music editor. This feature "notice that you can click on the drawn notes and see the place in the text where that note is defined" is great.  Would it be possible to synchronize the **midi** players position with the highlightning of notes and abc position? The idea is to be able  to quickly replay a specific bar that im working on.

**Comment by paulrosen** [comment]
That's an interesting idea but you'd have to implement it. 

You can get an event when there is a mouse up on the textarea.
You can seek to where you want in the audio control.

The trick is to figure out where in time the position in the abc string is. I don't know right off hand, but when you do the `renderAbc()` call you get a lot of information and you might be able to figure it out.

I'll experiment with it but I don't have time at the moment.

**Comment by samuelbradshaw** [comment]
I was able to use ABCJS to highlight the notes in the sheet music as they're playing in the MIDI. You can see an example here:
https://singpraises.net/text/305/the-light-divine
Is that what you're looking for? If so, I can create a simplified example that's separated from the rest of the page, if it would be helpful.

**Comment by ThorsenRune** [comment]
@samuelbradshaw
Thanks, It was actually the contrary; selecting a note should play it. However I am experimenting with selfhosting a branch of this wonderful ABCJS which works for my purpose to write small scores and found that kind of feature useless. 
Instead I have introduced a hack that restricts the current score rendering and playing to a selectable barnumber interval so I can work and replay specific bars only
