### ISSUE TITLE
Where are these files in midi/inc and midi/js?

### ISSUE THREAD

**Issue by gitAda16** [paulrosen/abcjs#213]
Hello, I got error "Module not found: Error: Can't resolve 'midi/js/player' '" When I'm running command 'npm run build', Where can I get these modules?

**Comment by paulrosen** [comment]
I'll double check the build process on a clean system to be sure there isn't a dependency I forgot.

Off the top of my head, two possibilities occur to me:

1) Did you do `npm install` first?
2) I have some files in a temp folder on my machine, but I didn't think I was using them. I'll double check.

**Comment by paulrosen** [comment]
I confirmed that the following works:
```
git clone git@github.com:paulrosen/abcjs.git
cd abcjs/
npm install
npm run build
```
