### ISSUE TITLE
strange drummap behaviour

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#214]
Hi, i find that using drummap remaps all voices. The following example with a voice V + remapped drum staves remaps the V as well.  I have tried to play around with the order to no avail. Is it a bug?
 I have tried it here:https://configurator.abcjs.net/interactive
% DRUMEXAMPLE-------------
X:1  % DRUMEXAMPLE 
V:V clef=treble name="Voice" snm="V"     transpose=-2             
%%MIDI program 1                     
%%score V (D D2)
M: 4/4                
L: 1/8                
Q:1/4=80
%Q:1/4=120              
K: C perc  
%%MIDI drummap A   41 % floor tom tom     
%%MIDI drummap e   50 % high tom tom
%%MIDI drummap B   47 % low-mid tom tom
%%MIDI drummap g 51 %Ride Cymbal 1          
%%MIDI drummap f 46 %Hi hat     
%%MIDI drummap c   38 %Acoustic Snare  (lower case)
%%MIDI drummap d 56 % Cowbell 
%%MIDI drummap F 41 %   bass drum
%%MIDI drummap a 49 %   Crash cymbal
V:D clef=perc name="Drums" snm="dr"   transpose=0
V:D2 clef=perc name="Drums" snm="dr"   transpose=0
[V:V]  ABcdefga | z8|
[V:D]  ffff ffff | cc ee BB AA|
[V:D2]  F2 c2 F F c2 | z8|

**Comment by paulrosen** [comment]
I will look into this - it sounds like a bug. There might be a workaround.

**Comment by paulrosen** [comment]
Similar functionality is in the `%%percmap` directive.
