### ISSUE TITLE
Is node installation required?

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#217]
Is it possible to edit the code without installing node?

**Comment by paulrosen** [comment]
You can use the minified versions without node.

Node is just used for minimizing and bundling. 

If you want to either copy all the source files into your project, or figure out your own minification system, then you don't need node, but I'm not sure why you would bother. Node is pretty easy to install.

**Comment by ThorsenRune** [comment]
Thanks, I found out some ugly workarounds, just for the sake of experimenting a bit. 
By substituting source lines like:
//var TuneBook = require('../api/abc_tunebook').TuneBook; 
import { tunebook } from '../api/abc_tunebook.js';
var TuneBook=tunebook.TuneBook;
it can be executed directly in a browser. I'm not sure if it's the correct way but it works for the sake of experimenting
