### ISSUE TITLE
Dynamics or loudness in midi

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#219]
Hi, I guess that dynamics ppp to fff are not reflected in midi. Am I correct? If so how can it be implemented?

**Comment by paulrosen** [comment]
That's right - I haven't implemented that yet. I am currently working on some midi improvements, but I don't have a time table. In the meantime, the volume is specified in abc_midi_flattener (look for "volume"). To know what the volume is supposed to be for a note, you'll have to add the information in the array that is passed in.

**Comment by ThorsenRune** [comment]
Thanks, actually I don't find its so important to implement it, I just wondered if it was.
However I'd really like to see muting&hiding voices implemented. I've raised the question here 
https://github.com/paulrosen/abcjs/issues/220

**Comment by ThorsenRune** [comment]
As I was reading the sourcecode I felt over the place where a the implementation could be made, so I implemented a Hack. Maybe I should sort it out and make a pull request some day, but not using node.js I've broken the source I think ;-)
