### ISSUE TITLE
abcjs delivers wrong endChar in case of a note with multiple pitches

### ISSUE THREAD

**Issue by bwl21** [paulrosen/abcjs#22]
If I have this abc file

    [CDE] FGA

and sequentially click on the renderd notes, I get the following results for startChar endChar

  C -> 6,6
  D -> 6,6
  E -> 6,6
  F -> 6,7
  G -> 7,8
  A -> 8,9

As you see, the chord yields wrong values. It should either yield the character position of the clicked note or of the entire chord.

You can also reproduce this in http://abcjs.net/abcjs-editor.html

**Comment by paulrosen** [comment]
This will be fixed in version 2.1

**Comment by paulrosen** [comment]
Fixed.
