### ISSUE TITLE
hide/mute voices

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#220]
Hi, while working on transcribing an arrangement I found the need to mute&hide voices so I could concentrate on one at a time. Until now I've been commenting each voice and line but its quite tedious. I  would expect the STAFF to work exactly like that  and tried to hack so voices not appearing e.g. %%staves V1 V3
would remove V2 from the midi and scorelayout but it doesn't appear to work like that.
Last night I found the multilineVars.score_is_present = true;  and figured to collect the voice IDs  used and I find that removing a voice from Tune in 
'engraver_controller.engraveABC(tune);' could do what I want but I can't figure out how 
Tune and multilineVars are connected. 
Can you point me in the right direction please?

**Comment by paulrosen** [comment]
There is limited support for it: you can call the midi with the option `{ chordsOff: true }` or `{ voicesOff: true }` but I know that's not what you're asking.

Something that is a little less tedious than commenting each line: a blank line signals the end of the tune, so if you put the voices you don't want on the bottom and precede them with a blank line then the won't appear.

I agree that you are suggesting a useful feature and it wouldn't be hard to implement.  I would first see if there is standard syntax for that in ABC. If not, then adding a new `%%MIDI` command would work.

I didn't try this - but if you put `%%MIDI program 150` in (the maximum value is 128), it might just "play the track silently".

**Comment by ThorsenRune** [comment]
Great ideas thanks, but I think the most logical and efficient would be the %%score implementation (I guess thats  the purpose of it !? or am I wrong).
Then you could have lines like for example
% %%staves V1 V3
 %%staves  V2 
% %%staves V1 V2 V3
And just (un)comment as you work along. 
If you can give an pointer to what the link between tune and multilineVars is? 
My idea is that in parsing multilineVars I can get the IDs for the voices to mute. Then before 'engraveABC' I would remove those id's whom are to be muted like:
delete: this.tunes[0].lines[0].staff[id].
I can see that if i pop the array then the last voice disappears from score and midi so it seems to work.
But I can't figure out how staff numbers relates to ID. (Or maybe the idea is far fetched)
Thanks for your help.

**Comment by paulrosen** [comment]
This seems to be the right directive: http://abcnotation.com/wiki/abc:standard:v2.1#instrumentation_directives

I haven't implemented it yet, but I will in the next round of MIDI changes.

**Comment by ThorsenRune** [comment]
Thanks, last night I was hacking away and it actually works quite nicely: As it's stylebreaking changes i've marked the places with 'RTHacks'
In abc_parse_directive.js @	case "score":  I make an array of the voices in the score
In abc_editor.js @ this.engraver_controller = new EngraverController: I remove the voices from the lines[n].staff, leaving only the ones collected before.
now for example
%%staves   V3 V1 
will only display and sound these voices.
Thanks Paul, great work you have done with ABCJS.

**Comment by musikboden** [comment]
Is this "mute or hide" voice implemented? 
I could really get good use of it at the moment.

**Comment by ThorsenRune** [comment]
Hi musikboden, I had made a hack for this, but after upgrading it doesn't work anymore. In my opinion the ABC notation ought be revised ( eg. using # for sharps in music).
I had implemented the hack so I could write in the header:
#staves    (  V3   Acc )  V2 ;#bars= 4 -8;  //show & play only partial score
# means directive as in most programming languages.
// is a comment
staves selects the  active voices to display/play
bars is selects the bars to display/play
However they are ugly hacks directly into the sourcecode (https://github.com/ThorsenRune/abcjs) as I dont know about how to override encapsulated anonymous functions. If you know let me know.
