### ISSUE TITLE
midiProps.soundfontUrl is not used in abc_tunebook_midi.js

### ISSUE THREAD

**Issue by rescawen** [paulrosen/abcjs#221]
Passing custom soundfontUrl does not change the url used when rendering midi

----

Call chain related to the issue:
- React-abc places soundfontUrl in midiProps
https://github.com/fuhton/react-abc/blob/master/src/defaults/props.js#L72

- React-abc passes midiProps to abc_tunebook_midi.js here:
https://github.com/fuhton/react-abc/blob/master/src/midi/index.js#L24

- abc_tunebook_midi.js ignores the parameter inside `midiProps` and does not call `midi.setSoundFont`
https://github.com/paulrosen/abcjs/blob/master/src/api/abc_tunebook_midi.js#L22

(midi.setSoundFont is defined here)
https://github.com/paulrosen/abcjs/blob/master/src/midi/abc_midi_controls.js#L136

----

Is this a bug or does the soundfontUrl have to be defined in a different place?

Thanks.

**Comment by paulrosen** [comment]
You need to call `abcjs.midi.setSoundFont("my/path")` right after importing abcjs. I think it was an error to show it being passed in as a parameter.
