### ISSUE TITLE
Unable to hide tempo note

### ISSUE THREAD

**Issue by samuelbradshaw** [paulrosen/abcjs#222]
It would be nice if I could hide the full tempo marking above generated sheet music. I have a tune fragment with this notation:
```
X:7
Q:1/4=84
M:4/4
L:1/8
K:F
c3 c dc AF | F4 D4 | C3 F AF cA | G6 z2 | yy
```

When rendered with abcjs, it looks like this:
<img width="759" alt="Screen Shot 2019-05-27 at 2 59 56 PM" src="https://user-images.githubusercontent.com/7323052/58439295-9da51b00-8090-11e9-8b2b-5e949b6498e4.png">

Based on the [abcjs Basic documentation](https://github.com/paulrosen/abcjs/blob/master/docs/api.md), I added a CSS rule to hide the tempo:
```
.abcjs-tempo {
  display: none;
}
```

This only hid part of the tempo marking, as seen below:
<img width="754" alt="Screen Shot 2019-05-27 at 3 00 32 PM" src="https://user-images.githubusercontent.com/7323052/58439418-29b74280-8091-11e9-9936-50bcfb38736c.png">

So I experimented a little more a web inspector, and noticed that the note had the classes `.abcjs-m0` and `.abcjs-n0`, so I tried this:
```
.abcjs-tempo, .abcjs-m0.abcjs-n0 {
  display: none;
}
```

But that ended up hiding both the tempo note and the first note of the tune:
<img width="757" alt="Screen Shot 2019-05-27 at 3 00 54 PM" src="https://user-images.githubusercontent.com/7323052/58439470-6f740b00-8091-11e9-9d29-c28ae9e17e8b.png">

The root of the problem seems to be that both the tempo note and the first note in the measure are drawn in the same `<path>`. (As a side note, the fact that both notes are in the same `<path>` also causes odd behavior when highlighting notes during playback – both notes become highlighted, as shown below.)
<img width="753" alt="Screen Shot 2019-05-27 at 3 14 38 PM" src="https://user-images.githubusercontent.com/7323052/58439605-2b353a80-8092-11e9-8fde-b6a4ff8e5994.png">

**Comment by paulrosen** [comment]
This is definitely a bug. I'll get to it soon.

**Comment by paulrosen** [comment]
Will be fixed in version 5.6.11

**Comment by samuelbradshaw** [comment]
Thanks!

**Comment by samuelbradshaw** [comment]
Tested and it works great!
