### ISSUE TITLE
Slurs don't render cleanly when note stem changes direction

### ISSUE THREAD

**Issue by samuelbradshaw** [paulrosen/abcjs#223]
I have a tune fragment with this notation:
```
X:1
Q:1/4=100
M:3/4
L:1/8
K:C
G2 | G2- G2 E2 | c4 B2 | (A2 e2) d2 | (c2 B2) z2 | yy
```

When rendered by abcjs, the second slur renders starting above the stem of the first note:
<img width="764" alt="Screen Shot 2019-05-27 at 10 15 54 PM" src="https://user-images.githubusercontent.com/7323052/58450663-19bd5400-80cd-11e9-909a-ad8931698fd1.png">

Ideally, I think it would render more like this:
<img width="764" alt="Screen Shot 2019-05-27 at 10 15 54 PM" src="https://user-images.githubusercontent.com/7323052/58450924-7ff6a680-80ce-11e9-8c42-4b7d462bd0b4.png">

Here's another example, going the other way (the first slur):
```
X:151
Q:1/4=96
M:3/4
L:1/4
K:Eb
E | E2 F | G2 B | (B A) G | F2 F | G2 c | (c B) G/=A/ | B2 =A | G2 yy
```
<img width="750" alt="Screen Shot 2019-05-27 at 10 37 00 PM" src="https://user-images.githubusercontent.com/7323052/58451262-f7790580-80cf-11e9-91c1-3ee82d273449.png">

**Comment by samuelbradshaw** [comment]
I couldn't find an authoritative convention, but I looked at a few examples. One thing in common seems to be that the slur always follows the direction of the notes – so, if the first note is lower than the last note, the slur goes up, and vice versa.

**Comment by paulrosen** [comment]
Will be fixed in version 5.6.12.

**Comment by samuelbradshaw** [comment]
Awesome!

**Comment by samuelbradshaw** [comment]
I tested this out, and my first sample looks good now, but slur in the second example still goes upward with the notes going downward. I would expect the end of the slur to sit on top of the note in this case, because the stem isn't in the way. The logic is tricky... :)

<img width="765" alt="Screen Shot 2019-07-09 at 5 43 16 PM" src="https://user-images.githubusercontent.com/7323052/60930088-3d99bb00-a271-11e9-8ee0-e6ccb5077d8f.png">

**Comment by paulrosen** [comment]
There are a lot of cases! I was going by the following:

<img width="410" alt="slur-logic" src="https://user-images.githubusercontent.com/69818/61014050-84f87800-a353-11e9-9498-1d3002939b89.png">

But I agree it would look better if the slur went to the A note. 

I'm happy to implement any "rule", but so far every time I implement something it breaks something else.

**Comment by paulrosen** [comment]
Will be a little improved in 5.7.1
