### ISSUE TITLE
Guitar tab/chord diagram

### ISSUE THREAD

**Issue by zhouhao27** [paulrosen/abcjs#224]
Is abcjs support guitar tab and chord diagram? Thanks.

**Comment by paulrosen** [comment]
I'm sorry, not yet. 

It would be a bit of work, but you could hack the chords yourself:

* Set the gchord font to something large that takes up the amount of space you want.
* After the music renders, look for elements with `.abcjs-chord` and get their innerText. That will be the chord, and replace that element with your diagram.

I'd love to have this implemented, but it will be a while before I get around to it.

**Comment by chrisfargen** [comment]
> Is abcjs support guitar tab and chord diagram? Thanks.

For others seeking these features, here's a hacky workaround. For tab, use the ABC-native `w:` keyword reserved for song lyrics. (Note: normal dashes have special meaning when following the `w:`, but you can use the em dash (—) to fill the space between numbers.

![thingy5](https://user-images.githubusercontent.com/2993720/79053007-1b6e0880-7c08-11ea-88f6-8b8bc817989e.jpg)

```
T: MAJOR ENDINGS
Q: 100
M: 4/4
L: 1/8
K: Gmaj transpose=-12
%
%%text Ending #1 (I-bII-I)
z (vF | "D7""^;H.O." G)uB vd2 v^du^B v^G(uF | "G""^;H.O." G)v^C uDvG, z2 "G6(sus2)b5;[3,x,2,2,2,x]" [G,EA_d]8 |
%
% TAB
%
w: — —  — — — — — — —  — — — x
w: — —  — — — — — — —  — — — 2
w: — —  4 7 8 5 — — —  — — — 2
w: 4 h5 — — — — 6 4 h5 — — — 2
w: — —  — — — — — — —  4 5 — x
w: — —  — — — — — — —  — — 3 3
%%text % blank line
%%text Ending #2 (I-ivdim7-I)
%
z (vF | "D7""^;H.O." G)uB vd2 vcu_e vfua | "G" vg(ua/2"^;P.O."g/2) vfug z2 "G maj7(9);[x,10,9,11,10,x]" [GBfa]8 |
%
% TAB
%
w: — —   — —  —  —  —  —  —  —  —   —  —  x
w: — —   — —  —  —  —  —  —  —  —   —  —  10
w: — —   — —  —  —  11 14 12 14 p12 11 12 11
w: — —   9 12 10 13 —  —  —  —  —   —  —  9
w: 9 h10 — —  —  —  —  —  —  —  —   —  —  10
w: — —   — —  —  —  —  —  —  —  —   —  —  x
```

**Comment by chrisfargen** [comment]
I've been working on this problem some more. If I were a more ambitious coder, I might try to integrate a parser that could read Jtab. The solutions here would involve a more succinct tab notation system than the ready-made, plain-text solutions in my previous post, but they would take more work to implement.

### ABC + Jtab (popular tab notation system):

```
%%vocalfont normal
K: Cmaj transpose=-12
% STANDARD NOTATION
B,CEG Bceg | b_bag ecAG
% GUITAR TAB (Jtab notation)
w: $5.2 3 $4.2 5 $3.4 5 $2.5 $1.3 7 6 5 $2.8 5 $3.5 $4.7 5
```

Rendered ABC:

![ardfgdfs3](https://user-images.githubusercontent.com/2993720/83431785-e317c900-a405-11ea-9f7f-f85ac6f11b28.jpg)

Rendered Jtab string ([see live Jtab editor](https://jtab.tardate.com/examples.htm)):

![ardfgdfs5](https://user-images.githubusercontent.com/2993720/83432281-a4ced980-a406-11ea-8ca0-73fd558bd20c.jpg)

----

### ABC + Marktab (less robust notation system)

```
%%vocalfont normal
K: Cmaj transpose=-12
% STANDARD NOTATION
B,CEG Bceg | b_bag ecAG
% GUITAR TAB (Marktab notation)
w: 5:2 3 4:2 5 3:4 5 2:5 1:3 7 6 5 2:8 5 3:5 4:7 5
```

Rendered ABC:

![ardfgdfs4](https://user-images.githubusercontent.com/2993720/83431899-15c1c180-a406-11ea-9a6a-bb802a836cce.jpg)

Rendered Marktab string ([see live Marktab editor](http://russplaysguitar.github.io/marktab-coffee/#5%3A2%203%204%3A2%205%203%3A4%205%202%3A5%201%3A3%207%206%205%202%3A8%205%203%3A5%204%3A7%205)):

![ardfgdfs6](https://user-images.githubusercontent.com/2993720/83432421-d6e03b80-a406-11ea-9e29-33267a12a0da.jpg)

**Comment by paulrosen** [comment]
That's an interesting approach. You could also include `{use_classes: true}` in the call to `abcRender` and have the css:
```
.abcjs-lyric {
  display: none;
}
```

**Comment by chrisfargen** [comment]
![gonzalo-major-abc2svg-tab](https://user-images.githubusercontent.com/2993720/86947632-037c2700-c11a-11ea-8983-a98ab6ac5ab1.png)

FYI, here's [how abc2xml does tablature](https://wim.vree.org/svgParse/abc2xml.html#tab). 

```
X:
T:
%%score [ 1 | 2 ]
L:1/8
M:4/4
K:Cmaj
%
% STANDARD NOTATION
V:1 treble transpose=-12
B,CEG Bceg | b_bag ecAG ||
%
% GUITAR TAB
V:2 tab octave=-1 nostems
!5!B,"^⚓"!5!C!4!E!4!G !3!B!3!c!2!e!1!g | !1!b!1!_b!1!a!2!g !2!e!3!c!4!A!4!G ||
```

For tab written in this way, note pitches are specified via classic ABC. The command line utility `abc2xml` calculates the proper string/fret for each note, and the algorithmic string/fret decisions can be overridden using `!1!` - `!6!` for strings 1 - 6, respectively.

Just thought I'd share this clever solution.

(Image generated via abc → abc2xml → xml2abc → abc2svg)

**Comment by chrisfargen** [comment]
Another great feature from abc2svg is the ability to include chord diagrams. There are default chord grips for most chord symbols, but the fingerings and shapes are user-configurable. You can include chord diagrams manually by using `%%deco` to bind the postscript function responsible for drawing a chord diagram (e.g., `/C7`) to a decoration (e.g., `!C7!`; example [here](http://abcplus.sourceforge.net/guitarchords.fmt)). Or you can use `%%diagram 1` to auto-populate the score with chord diagrams, as in the example below.

![out](https://user-images.githubusercontent.com/2993720/87378127-2748ce00-c55b-11ea-86d1-d053b7598f74.png)

Code for sample image [here](https://gist.github.com/chrisfargen/420e0a26028b9e099cf63b4190dd6358#file-sample-abc).

Original code [here](http://abcplus.sourceforge.net/guitarchords.fmt).

**Comment by chrisspen** [comment]
I'm interested in this as well. Note, [abc2xml.py](https://wim.vree.org/svgParse/abc2xml.html) has supported this for a while using `clef=tab`.

**Comment by chrisspen** [comment]
@chrisfargen That looks really interesting. Have you seen any way to also include finger numbers? An incredibly useful notation I've seen is to put [finger numbers in circles](https://www.guitartricks.com/helptab.php) underneath the tabs. That removes all ambiguity from tablature.

**Comment by chrisfargen** [comment]
Hi @chrisspen,

I would use `w:` and the special characters that are numbers in circles, but that might not work everywhere.

You could do that in abcjs with the hack described above.

![Screenshot (663)](https://user-images.githubusercontent.com/2993720/121260928-03336100-c880-11eb-908e-af19efbe0c19.png)

```
%%vocalfont 14
K: Cmaj transpose=-12
% STANDARD NOTATION
B,CEG Bceg | b_bag ecAG ||
% GUITAR TAB
w: – – – – – – – 3 | 7 6 5 – – – – –
w: – – – – – – 5 – | – – – 8 5 – – –
w: – – – – 4 5 – – | – – – – – 5 – –
w: – – 2 5 – – – – | – – – – – – 7 5
w: 2 3 – – – – – – | – – – – – – – –
w: – – – – – – – – | – – – – – – – –
w: | |
w:① ② ① ④ ③ ③ ③ ① | ④ ② ① ④ ① ① ③ ①
```

Here is how i would do it in abc2svg:

![Screenshot (661)](https://user-images.githubusercontent.com/2993720/121260145-f4987a00-c87e-11eb-8ff3-14a04d25ded6.png)

```
%%strtab
X:
T:
%%score [ 1 | 2 ]
L:1/8
M:4/4
K:Cmaj
%
% STANDARD NOTATION
V:1 treble transpose=-12
B,CEG Bceg | b_bag ecAG ||
%
% GUITAR TAB
V:2 tab octave=-1 strings=E2,A2,D3,G3,B3,E4 nostems 
!5!B,!5!C!4!E!4!G !3!B!3!c!2!e!1!g | !1!b!1!_b!1!a!2!g !2!e!3!c!4!A!4!G ||
w:① ② ① ④ ③ ③ ③ ① | ④ ② ① ④ ① ① ③ ①
```

**Comment by leocaseiro** [comment]
Seems that tabs are implemented https://paulrosen.github.io/abcjs/visual/tablature.html

**Comment by janvainer** [comment]
Hi @paulrosen, are there possibly any plans to give official support to the chord diagrams in the near future?
