### ISSUE TITLE
Add an API endpoint to add a tune to an existing stave

### ISSUE THREAD

**Issue by stephaneeybert** [paulrosen/abcjs#227]
Having an API endpoint to add one or several tunes to the array of tunes after the rendering has started so as to have new tunes appear on an existing sheet, on a stave that displays in one line without wrap, the oldest tunes disappearing in a fifo fashion. This would allow for rendering tunes issued by an abserver in a RxJS stream.

**Comment by paulrosen** [comment]
Can you provide a simple example app with an RxJS stream sending and ABC string so I can see how it would behave? 

Perhaps just have the stream print the ABC to the page and I can replace that with the visual music.

**Comment by paulrosen** [comment]
closed for lack of activity.
