### ISSUE TITLE
Feature request: offer an API endpoint to move the cursor above a given note index

### ISSUE THREAD

**Issue by stephaneeybert** [paulrosen/abcjs#228]
It'd be very handy to have an endpoint like `setAnimationCursorOnNote(index: number)` so that we could animate ourselves following live input from a keyboard.

**Comment by paulrosen** [comment]
If you are using the new `TimingCallbacks` entry point, you can use `TimingCallbacks.setProgress()` and pass in a percentage (a number between 0 and 1).

It would be difficult to figure out an index that is meaningful other than a percentage, particularly when you take repeats into account.

Let me know if that will solve your problem - if not, let me know what you'd like to pass in to that function.
