### ISSUE TITLE
The examples provided in the npm download fail

### ISSUE THREAD

**Issue by stephaneeybert** [paulrosen/abcjs#229]
Trying to open any example under the `node_modules/abcjs/examples/` directory fail as there is no `bin` directory, each example trying to import `node_modules/abcjs/bin/abcjs_basic_5.6.11-min.j`

**Comment by paulrosen** [comment]
Yes, you're right. I will remove the examples from the node_modules build - they aren't useful there. Those examples are for using the library with the minimized version.
