### ISSUE TITLE
Add marks on the sheet

### ISSUE THREAD

**Issue by zhaokewei** [paulrosen/abcjs#230]
Hi Paul, thank you for all this work.
I have a little issue. I want to draw some marks under the sheet music like image below. How to do it? Thank you very much. 
![webwxgetmsgimg](https://user-images.githubusercontent.com/15992876/59428596-4208ba80-8e10-11e9-8492-f7747184e8bb.jpg)

**Comment by paulrosen** [comment]
There are two ways that come to mind:

1) When drawing, use `{ add_classes: true }`. Also put the following in your ABC string: `%%staffsep 60px`. Then you can find your way around. For instance, that first note is `.querySelectorAll(".abcjs-l0.abcjs-m0.abcjs-n0")`. And there is extra space so there is room for your comment.

2) You can create the lines separately with `{ oneSvgPerLine: true }`. Then you can arrange them however you want. You probably still want to have the classes so you can figure out how to line stuff up.

**Comment by zhaokewei** [comment]
Thank you for your reply, you are handsome.  I meet another problem, the sheet generated by this library is diffent from the sheet generated by the EasyABC.

- **The abc string**:

```
X:697
T:Title
%%score 1 2
L:1/4
Q:1/4=99
M:3/4
I:linebreak $
K:Db
V:1 treble nm="钢琴, SmartMusic SoftSynth" snm="Pno."
V:2 bass nm="钢琴, SmartMusic SoftSynth" snm="Pno."
V:1
(9:8:9D3/8F3/8A3/8 d3/8f3/8a3/8 d'3/8a3/8f3/8 | f'2 d' | 
(9:8:9D3/8F3/8A3/8 d3/8f3/8a3/8 d'3/8a3/8f3/8 |$ f'2 d' | 
(9:8:9g'3/8a'3/8b'3/8 a'3/8g'3/8f'3/8 e'3/8d'3/8c'3/8 | 
(9:8:9b3/8a3/8g3/8 f3/8e3/8d3/8 c3/8a3/8c3/8 | (9:8:9d3/8f3/8a3/8 d'3/8a3/8f3/8 d3/8A3/8F3/8 |$ 
D z z |[Q:1/4=120] (9:8:9D3/8F3/8A3/8 d3/8f3/8a3/8 d'3/8a3/8f3/8 | f'2 d' | 
(9:8:9D3/8F3/8A3/8 d3/8f3/8a3/8 d'3/8a3/8f3/8 | f'2 d' |$ 
(9:8:9g'3/8a'3/8b'3/8 a'3/8g'3/8f'3/8 e'3/8d'3/8c'3/8 | 
(9:8:9b3/8a3/8g3/8 f3/8e3/8d3/8 c3/8a3/8c3/8 | (9:8:9d3/8f3/8a3/8 d'3/8a3/8f3/8 d3/8A3/8F3/8 | 
D z z |$ (9:8:9A,3/8C3/8E3/8 A3/8c3/8e3/8 a3/8e3/8c3/8 | A [Aceg] [Aceg] | 
(9:8:9D3/8F3/8A3/8 d3/8f3/8a3/8 d'3/8a3/8f3/8 | d [dfa] [dfa] |$ 
(9:8:9b3/8d3/8g3/8 b3/8d'3/8g'3/8 b'3/8g'3/8d'3/8 | 
(9:8:9d''3/8b'3/8g'3/8 d'3/8b3/8g3/8 d3/8g3/8b3/8 | 
(9:8:9a3/8b3/8c'3/8 d'3/8e'3/8f'3/8 g'3/8e'3/8c'3/8 |$ (3d'/a/f/ (3d/A/F/ .D | 
(9:8:9A,3/8C3/8E3/8 A3/8c3/8e3/8 a3/8e3/8c3/8 | A [Aceg] [Aceg] | 
(9:8:9D3/8F3/8A3/8 d3/8f3/8a3/8 d'3/8a3/8f3/8 |$ d [dfa] [dfa] | 
(9:8:9b3/8d3/8g3/8 b3/8d'3/8g'3/8 b'3/8g'3/8d'3/8 | 
(9:8:9d''3/8b'3/8g'3/8 d'3/8b3/8g3/8 d3/8g3/8b3/8 | 
(9:8:9a3/8b3/8c'3/8 d'3/8e'3/8f'3/8 g'3/8e'3/8c'3/8 |$ (3d'/a/f/ (3d/A/F/ .D |] 
V:2
D, .[F,A,] .[F,A,] | D, .[F,A,] .[F,A,] | D, .[F,A,] .[F,A,] |$ D, .[F,A,] .[F,A,] | 
A,, .[C,E,G,] .[C,E,G,] | A,, .[C,E,G,] .[C,E,G,] | D, .[F,A,] .[F,A,] |$ D, .[F,A,] .[F,A,] | 
D, .[F,A,] .[F,A,] | D, .[F,A,] .[F,A,] | D, .[F,A,] .[F,A,] | D, .[F,A,] .[F,A,] |$ 
A,, .[C,E,G,] .[C,E,G,] | A,, .[C,E,G,] .[C,E,G,] | D, .[F,A,] .[F,A,] | D, .[F,A,] .[F,A,] |$ 
(9:8:9A,,3/8C,3/8E,3/8 A,3/8[K:treble]C3/8E3/8 A3/8E3/8C3/8 |[K:bass] A,3 | 
(9:8:9D,3/8F,3/8A,3/8 D3/8[K:treble]F3/8A3/8 d3/8A3/8F3/8 | D3 |$[K:bass] G, .[B,D] .[B,D] | 
G, .[B,D][K:treble] .[B,D] | A, .[DF] .[A,EG] |$ .[DF][K:bass] .[D,,D,] z | 
(9:8:9A,,3/8C,3/8E,3/8 A,3/8C3/8[K:treble]E3/8 A3/8E3/8C3/8 | A,3 | 
[K:bass] (9:8:9D,3/8F,3/8A,3/8[K:treble] D3/8F3/8A3/8 d3/8A3/8F3/8 |$ D3 | 
[K:bass] G, .[B,D] .[B,D] | G, .[B,D][K:treble] .[B,D] | A, .[DF] .[A,EG] |$ 
.[DF][K:bass] .[D,,D,] z |] 
```
**Generated by EasyABC** 
![image](https://user-images.githubusercontent.com/15992876/59487547-ac246c80-8eaf-11e9-9742-7a66a264cdcd.png)
**Generated by abcjs** 
![image](https://user-images.githubusercontent.com/15992876/59487600-cd855880-8eaf-11e9-9899-f4926242e2e5.png)

We can find the different. Is that the breakline problem #25?

**Comment by zhaokewei** [comment]
https://github.com/paulrosen/abcjs/blob/master/docs/abc-notation.md
