### ISSUE TITLE
Transposing problem: the key is not taken into account

### ISSUE THREAD

**Issue by goplayerjuggler** [paulrosen/abcjs#231]
In the configurator, when setting transpose to -8 and entering the below ABC code, a C natural should be rendered. At present, a C flat is rendered.

X:1
K:C dor
_A

A second example, going from C major to G major.  Transpose: 7. It should render an F natural. At the moment, it renders an F flat.

X:2
K:C
_B

**Comment by paulrosen** [comment]
Ok, I'll look at that.

**Comment by paulrosen** [comment]
This was already fixed - unfortunately the version number of the configurator is a bit behind. I will update that soon.

Let me know if you see any problems in version 5.7.0.
