### ISSUE TITLE
Rendering problem for P (part) before a bar line

### ISSUE THREAD

**Issue by goplayerjuggler** [paulrosen/abcjs#232]
When there are two staves and a P (part) occurs before a bar line or a repeat line (vertical line(s) spanning the two staves) then the top stave is not aligned with the bottom one.

I put a simple repo below.
There is no problem in the [configurator](https://configurator.abcjs.net/interactive), but it is there in the [editor](https://abcjs.net/abcjs-editor.html)

X:1
M:3/4
%%staves {RH LH} 
V: RH clef=treble
V: LH clef=bass 
K:C
[P:A] %problem here 
[V: RH]
|: c2  | c4c2  | c4c2  | c4 :|
[V: LH]
|: C2 | C4C2 | C4C2 | C4 :|
[V: RH] %problem here too
|: d2 [P:B] | d4d2  | d4d2  | d4 :|
[V: LH]
|: D2 | D4D2 | D4D2 | D4 :|
[V: RH] %workaround; no problem
|: [P:C] e2 | e4e2  | e4e2  | e4 :|
[V: LH]
|: E2 | E4E2 | E4E2 | E4 :|

**Comment by paulrosen** [comment]
Ok, I'll look at this.

**Comment by paulrosen** [comment]
Will be fixed in 5.7.1

**Comment by goplayerjuggler** [comment]
Thanks. It also happened for with a Q in a similar setup:

var abc = `X:5
T:t
C:c
R:Valse assymétrique
M:(3+2)/8
Q: 1/4=100 
L:1/8
%%staves {RH LH} 
V: RH clef=treble
V: LH clef=bass 
K:C dor
%P:A
[V: RH]
|: c
[V: LH]
|: G,`

**Comment by paulrosen** [comment]
Thanks. I'm planning another release very soon, so will be fixed in 5.8.0.
