### ISSUE TITLE
Special Symbols do not render in text string

### ISSUE THREAD

**Issue by nikoootine** [paulrosen/abcjs#234]
Given this sample abc:
X: 1
T: Sample
M: 4/4
L: 1/8
R: reel
K: Emin
|:D2|"\u266f"EB{c}BA B2 EB

Reference: http://abcnotation.com/wiki/abc:standard:v2.1#text_strings

The unicode "\u266f" is being rendered as is rather than the sharp symbol. Text strings should be able to render unicode as indicated by the document unless I'm missing something. It would be great if there's a support for unicode rendering as I need to display these symbols:

Repeated-Figure 2:
https://www.fileformat.info/info/unicode/char/1d10e/index.htm

Repeated-Figure 3:
https://www.fileformat.info/info/unicode/char/1d10f/index.htm

**Comment by paulrosen** [comment]
Unicode can be used directly, so you can just use `|:D2|"♯"EB{c}BA B2 EB`. Also, it looks like you are using them in chord symbols. The octothorpe is converted to the sharp symbol automatically. For instance, `"F#m"` will use the unicode symbol for sharp.

**Comment by paulrosen** [comment]
Is there a reason you need to use the "\u266f" syntax?

**Comment by nikoootine** [comment]
Thanks. The above was just a random example. Like I said, my goal is to be able to display these symbols in the chord symbols:
Repeated-Figure 2:
https://www.fileformat.info/info/unicode/char/1d10e/index.htm
Repeated-Figure 3:
https://www.fileformat.info/info/unicode/char/1d10f/index.htm

Pasting them directly does not work.

**Comment by nikoootine** [comment]
Closing for now because I just figured that this is just a font issue
