### ISSUE TITLE
Empty lines in W: fields are not rebdered

### ISSUE THREAD

**Issue by norppa** [paulrosen/abcjs#235]
When using W: fields to write block lyrics, empty lines get ignored. This bunches all the verses into one block, making songs with multiple verses very difficult to read. The lyrics work properly in version 5.6.1, but not anymore in 5.6.2.

**Comment by paulrosen** [comment]
Ok, I'll look at this.

**Comment by paulrosen** [comment]
Will be fixed in v5.7.0
