### ISSUE TITLE
Js errors when animating MIDI after renderABC without Editor

### ISSUE THREAD

**Issue by jymen** [paulrosen/abcjs#236]
Hi 

I have a View.js project that do not request ABC Editor but needs animation between MIDI player and the parsed SVG.
I Followed the Editor based example HelloWorldView.js as a starting point but got some problems using following code :

`
Hi 

I have a View.js project that do not request ABC Editor but needs animation between MIDI player and the parsed SVG.
I Followed the Editor based example HelloWorldView.js as a starting point but got some problems using following code :

```javascript 
mounted: function() {
    this.options.scale = globalOptions.abcZoom
    this.options.responsive =  'resize' // initially fit screen
    this.show()
  },
  name: 'AbcScore',
  props: {
    tune: String,
    options: Object,
    instrument: Number,
  },

  methods: {
    show: function() {
      debugger
      // get a rendered instance to  be passed to rendeMidi
      let rendered = abcjs.renderAbc('paper', this.tune, this.options)
      abcjs.renderMidi(
        'midi-player',
        this.tune,
        { // parser params
          program: 1,
          generateDownload: true,
        },
        { // midi params
          listener: this.listener,
          animate: { listener: this.animate , target: rendered , qpm: 120 },
        } ,
      );
    },
// listener + animate code are the same as Helloworld example
``` 
The first js Error  I got when running the view is 
vue.esm.js:1897 TypeError: parent.abcjsTune.setTiming is not a function 
(see attached chrome debugging screenShot)

This error has no impact on displayed Score + Player

Next when I start the player the listener entered correctly 
(although I do not understand the usefulness of the this.progress = progress instruction

but before entéring the animate fonction a second javascript error is poping then in findElements function the elements parameter being undefined ...

Is there something I did wrong there ?

abcjs Version I use is the standard npm 5.6.9 
<img width="1384" alt="Screenshot 2019-07-01 at 20 01 25" src="https://user-images.githubusercontent.com/644653/60457084-6ac7e700-9c3b-11e9-9f8c-f391f23c53f9.png">
<img width="1389" alt="Screenshot 2019-07-01 at 19 51 57" src="https://user-images.githubusercontent.com/644653/60457173-ac589200-9c3b-11e9-960b-c6e0641ac9db.png">

**Comment by jymen** [comment]
Hi , 
Sorry my bad .... this was a problem on my side : I did not pay attention to the fact that logically abcjs.renderAbc is returning an array of tunes as a result and so pass rendered[0] and not rendered 
After fixing this everything has been working like a charm 

Thanks again for the great work

**Comment by paulrosen** [comment]
Thanks for getting back to me! I had this on my short list to look at.
