### ISSUE TITLE
setbarnb pseudocomment

### ISSUE THREAD

**Issue by jonathanlb** [paulrosen/abcjs#237]
Could the `%%setbarnb <integer>` pseudo comment be implemented? 

I'm using abcjs in my practice notes.  I have snippets of a quartet I'm prepping and would like to align the measure numbers of the piece with those appearing in my notes.

I've looked through `addDirective()` in `src/parse/abc_parse_directive.js` and `parse()` in `src/parse/abc_parse.js` and am happy to take a stab at it/create a pull request.

**Comment by paulrosen** [comment]
That would be useful to implement. If you'd like to contribute, that's fine. I can also do it before too long.

**Comment by jonathanlb** [comment]
Thanks, Paul.  I have a draft at https://github.com/jonathanlb/abcjs .  The draft doesn't go through the [release steps](https://github.com/paulrosen/abcjs/blob/master/docs/contributing.md), yet.

I'll figure out how to use the linter.  @paulrosen do you have a pointer to running the broader tests?

**Comment by paulrosen** [comment]
Don't worry about the release steps.

For the "lint" tests - that is a little complicated to set up. Some day I'll clean that up and publish it. The easiest thing for this kind of one-off is for you to give me one or more ABC strings that demonstrate any edge cases for the feature and I'll take it from there.

**Comment by paulrosen** [comment]
Just took a quick look at it - it could be simpler. You don't need to set the multi-line var. (Most directives DO, since they are global, but this one has an immediate, one-time effect, so it can just be set directly.)

**Comment by jonathanlb** [comment]
OK.  I will eschew addMultilineVar() and remove setBarNumber() -- I was leveraging the parameter checking in the former and cleaning up the key with the latter.
