### ISSUE TITLE
Support rendering in non-browser environments

### ISSUE THREAD

**Issue by StephanHoyer** [paulrosen/abcjs#239]
First off, great lib.

I tried to use it in node, but it seems it's not possible because the lib relies on browser API in order to work.

Are there any plans to make this also render in node?

**Comment by StephanHoyer** [comment]
It works using [domino](https://github.com/fgnass/domino).
```
    const domino = require('domino')
    const window = domino.createWindow(
      '<div class="music"></div>',
      'http://example.com'
    )
    const musicEl = window.document.querySelector('.music')
    global.Element = window.Element
    global.CharacterData = window.CharacterData
    global.DocumentType = window.DocumentType
    global.window = window
    global.document = window.document
    const ABCJS = require('abcjs')
    ABCJS.renderAbc(musicEl, tile.config.notation)
    console.log(musicEl.outerHTML)
```

**Comment by paulrosen** [comment]
That's great that you got it to work!

How does the text placement look? That is the key problem: I need to know how much room text will take up and that is so dependent on browser variables, including CSS on the page at the time. I was looking to separate the layout from actually writing the SVG, but I couldn't get around that problem.

**Comment by StephanHoyer** [comment]
I just switched to [abc2svg](https://www.npmjs.com/package/abc2svg), which works great in node and the browser.

Thanks for the inspiration though.
