### ISSUE TITLE
wrong listener offset when score starts with comments

### ISSUE THREAD

**Issue by jymen** [paulrosen/abcjs#242]
Hi , 

This can be reproduced with configurator / interactive :
using following score : 
% 
%   test 
%
%% vocalfont Bookman-Light 12
X:1
%
% comment
%% test 
K:G
|| A
when togling 'User click listener'
Selecting the A note in score generates a wrong abcElem.startChart %% instead of expected A
Removing the 3 comment lines on top make the problem go away

**Comment by jymen** [comment]
Using the abc O'Carolan tune collection test file
[TuneCollectionTest.txt](https://github.com/paulrosen/abcjs/files/3439229/TuneCollectionTest.txt)

 do not provide the right notes selection offsets in source starting with tunes 0 first note
I Attached this file also here

**Comment by paulrosen** [comment]
Will be fixed in 5.8.0
