### ISSUE TITLE
Midi with animated cursor on notation - Wordpress plugin

### ISSUE THREAD

**Issue by amorset** [paulrosen/abcjs#245]
Hi Paul,

The ABC-Notation Wordpress plugin is great and very useful and I am using it for an educational website but I want to add functionality to it.
The notation and midi display together ok using the shortcodes. 
However I would like to enable that when the midi file plays an animated cursor tracks the music above.
I have tried to incorporate the code below from configurator in various ways but it doesn't work.
I have also tried various other snippets and looked at advice you have given in other posts but it isn't clear to me what to do.
Could please indicate how I would get the animation to work in Wordpress?
Thank you,
Brian

`abcjs.renderMidi(
    "midi-id",
    abcString,
    {
        animate: { listener: function(abcjsElement, currentEvent, context) {}, target: tunes[0], qpm: 120 },
    });

abcjs.midi.startPlaying(document.querySelector(".abcjs-inline-midi"));
abcjs.midi.stopPlaying();
abcjs.midi.restartPlaying();
abcjs.midi.setLoop(document.querySelector(".abcjs-inline-midi"), true);
abcjs.midi.setRandomProgress(0.33);`

**Comment by paulrosen** [comment]
That should definitely be easy to switch on in WordPress. I'll work on it. There's probably a way to get it work as is, but I need to update the WordPress plugin soon anyway, so I'll put that in the instructions.

The first problem I can think of is styling - there are lots of possibilities for what the cursor should look like.

This will be in 5.8.1

**Comment by amorset** [comment]
Good thanks 👍 - If we can see a cursor I can look after the styling I think : ) - it's the abcjs part I can't figure out!

**Comment by amorset** [comment]
Just wondering Paul, in the meantime, would you be able to give me a general outline or some pointers as to the best approach to take myself as I would really like to have the feature working for the project (which actually is primarily for my daughter who lives abroad). Thanks

**Comment by paulrosen** [comment]
I took a glance to see what would be required - it would require changing `abc-notation.php`. You need to save the return value of `ABCJS.renderAbc` and pass that into `ABCJS.renderMidi` as part of the animation. 

I think I would leave that code as it is, though, and create a new entry point that does both the visual and animation parts. I'd also like to leave a hook so that users can do their own javascript in response to an "event".

I'm planning on getting to this within the week.

I was also getting ready to put the new audio controls in, which I think will work better and be much less code, but I haven't decided on what I want the api to look like yet, so that probably won't be ready by next week.

**Comment by amorset** [comment]
Ok, thanks Paul - look forward to seeing it when you are finished.

**Comment by paulrosen** [comment]
The plugin is ready - try updating and using the new `abcjs-audio` shortcode.

**Comment by amorset** [comment]
That's really great Paul - you're a wizard. I would simply never have been able to do it. Thanks a lot!

**Comment by amorset** [comment]
Just one issue which I notice regarding syncing the midi and the cursor. On most of the devices I have tested abcjs-audio the cursor appears on the notation a note behind the midi audio output. On one phone they do seem to be in sync. Does it depend on the speed of the graphics processor?
Is there a setting or something to do to modify it or have you experienced this yourself?

**Comment by paulrosen** [comment]
I'll look at it. It syncs up on my fast computer. I have a newer version of the audio that takes fewer resources. I think I might be replacing it in the WP plugin in the next version.

**Comment by amorset** [comment]
Just a quick question Paul. 
%%vocalspace stylesheet directive doesn't seem to work. 
I am trying to use a tin whistle fingering font with abcjs-lyric. 
It works but is overlapping the staff above it. 
I am unable to create space between the lyric font and the staff.
Is there any way you know of to do this?

**Comment by amorset** [comment]
Hi again Paul, just wondering did you make any progress in syncing the cursor with the midi audio in the abc-notation plugin?
It is actually the cursor that lags the audio so I think it might not be an issue of resources required by the audio. Maybe instead a rendering delay with the cursor?
I am using it on tinwhistle.ie

**Comment by paulrosen** [comment]
I'll have a new version of the wordpress plugin by the end of the year that I hope will address this. There are a number of bugs fixed that aren't yet released.

**Comment by paulrosen** [comment]
closed for lack of activity - I think the issues were addressed.
