### ISSUE TITLE
unminified version of abcjs

### ISSUE THREAD

**Issue by ChorHizzle** [paulrosen/abcjs#246]
Would it be possible to include an unminified version of abcjs_midi_*.*.*-min.js in the bin/ directory?

**Comment by paulrosen** [comment]
That's a good idea - I've been doing my in-app debugging using the node installation, which has the source code and it is chopped up in smaller files, but it would be convenient to do debugging on simple websites, too, by just changing the name of the script.

I'll try to get this in the next version.

**Comment by paulrosen** [comment]
Will be fixed in 5.8.2
