### ISSUE TITLE
Increase space between lyric and staff

### ISSUE THREAD

**Issue by amorset** [paulrosen/abcjs#247]
Just a quick question Paul. (Moved this from previous thread to here as an issue of its own)
%%vocalspace stylesheet directive doesn't seem to work.
I am trying to use a tin whistle fingering font with abcjs-lyric.
It works but is overlapping the staff above it.
I am unable to increase the space between the lyric font and the staff.
Is there any way you know of to do this?

**Comment by paulrosen** [comment]
I see that %%vocalspace isn't hooked up properly, so I'll implement that - it shouldn't be hard. BUT, the font should have had enough space. Can I see the font you were using? Maybe there is another bug.

**Comment by amorset** [comment]
I'm using a font called Tin Whistling Fingering Font
https://github.com/OMerkel/tin_whistle/tree/master/res/font

It could work in the chord space above the music but it is more conventional to have the fingering below the staff.
The attached file shows the current output overlapping the bottom of the staff above.
![overlapping_font](https://user-images.githubusercontent.com/554508/64080964-367fae00-ccf2-11e9-9367-f04a91d316cf.jpg)

**Comment by amorset** [comment]
I have found a workaround for this issue - see image below.
I edited the font in FontForge and used the transform function to move the font glphs down on the x-axis.
![font-edit](https://user-images.githubusercontent.com/554508/64281623-6bd30880-cf4b-11e9-9549-2bc6b238ff48.jpg)

**Comment by amorset** [comment]
I'm using the above font on http://www.tinwhistle.ie
