### ISSUE TITLE
event info  in onEvent  does not contains appoggiaturas

### ISSUE THREAD

**Issue by jepcolombia** [paulrosen/abcjs#248]
In the following example there is an appoggiatura : {/E} ,  that also sounds in the playback  and appears in the render but is not included in the info returned by event in the onEvent function ( full-synth example -CursorControl function onEvent function). Only appears the main note.

X:1
T:Title
C:Composer
L:1/8
M:4/4
K:C
V:1 treble nm="Piano" snm="Pno."
V:1
|[Q:1/4=126.5451692][ce]2 z2{/E} GE [Cc]2 |
|]

**Comment by jepcolombia** [comment]
Hi Paul, 
is there any other way que get that note (appoggiatura)? Iam trying to show the accordion button for each note while playing. 
Appreciate your help.
Thanks a lot for your app!!

**Comment by paulrosen** [comment]
Did you figure this out or get a work around? I was getting ready to do another sweep on these issues.

**Comment by jepcolombia** [comment]
Hi Paul ,
Thanks for your replay. I thought I did a not clear or obvios question but
I’m still trying to figure it out how to split the event to have one for
the grace note a one for the main. Is it possible ?

Thanks a lot for your help!

**Comment by paulrosen** [comment]
I'm swamped with back-to-school right now, but was planning on catching up this weekend.

**Comment by paulrosen** [comment]
The way the internal structure is now, the entire "grace note + main note" is just one "event".  The information about the grace note is present, but it isn't easily usable.

The very least I could do is provide a version of the `midiPitches` element for grace notes. But that won't give you a separate callback for each moment that a grace note is played; it would still just be one callback event.

I will try to come up with something for this.

**Comment by jepcolombia** [comment]
hi Paul,
thanks for your answer. What iam intended to do is animation of a virtual keyboard for a Colombian music that use too many grace notes (Vallenato music). Any idea or tip on how to do it , i will appreciate a lot,
Best regards

**Comment by paulrosen** [comment]
The next version will have an entry in the callback that lists the grace notes. It isn't a separate event like you are hoping. You could start your own timer when you get that event and animate them each in turn.

I might be able to figure out something more convenient for you but it won't be in the next day or so.

**Comment by jepcolombia** [comment]
Thanks Paul, as allways looking forward to your next release, each time coming more better and complete. My  best wishes for you!!

**Comment by paulrosen** [comment]
Let me know if the info I'm giving you now is usable for your purpose - it's not exactly what you asked for, but it might do.

Please feel free to reopen this issue if it doesn't help.

**Comment by jepcolombia** [comment]
Yes Paul, It is ok to close it. Thank you!!
