### ISSUE TITLE
Make it possible to render SVGs of a fixed height

### ISSUE THREAD

**Issue by p-himik** [paulrosen/abcjs#249]
I use ABC to render a set of SVGs that contain usually a few measures that fit in one line. UI allows switching between the images with tabs so that all SVGs are positioned at the same point visually.
The issue with the current sizing approaches of abcjs is that it's impossible to make sure that SVGs stay the same height. It means that UI elements jump around when a user switches between different tabs with SVGs.

Right now, it seems that to fix it I have to:
1. Specify `{responsive: "resize"}`
2. Specify `height: 100px` for the parent of the SVG (or any other preferable height)
3. Specify `height: 100%` for the SVG
4. Remove `padding-bottom` from the parent.

The main issue is that I have to use `!important` for the 4th item in my custom CSS since abcjs adds the property directly to the element itself.
What do you think?

**Comment by paulrosen** [comment]
I think I would probably do something similar. You might be able to use `overflow: hidden` instead of step 4. I'm not sure you need the first step since you have a fixed size you want it to be. You might want to add `%%stretchlast` parameter

**Comment by p-himik** [comment]
The issue with 1 is that if I don't have `responsive`, the notation can overflow the outer block with fixed height. It's especially visible if I have playback control within the same block.

Regarding 4 - but `overflow: hidden` is already there. ABCJS has set it to the immediate parent container of SVG.

Thanks for the hint about `%%stretchlast`! Although it can look interesting when the notation contains some text underneath - there can be an empty space at the end. It seems that the width is computed first and then reduced to preserve aspect ratio when the height of the resulting notation is too big.

**Comment by paulrosen** [comment]
Reopen this if it is still an issue.
