### ISSUE TITLE
Horizontal Scrolling or Panorama view of score.

### ISSUE THREAD

**Issue by GitterHubber** [paulrosen/abcjs#251]
Hi,

First of all many thanks for giving us abcjs.

Is it possible for abcjs to render the score in a single line, left to right, that way the view scrolls left to right instead of the current top down.

This feature seems to be present in Musescore called continuous view, in Finale its called Panorama view, if I'm not mistaken..

Is there a configuration setting already, or if not could you let me know which files to look at to get this done?

**Comment by paulrosen** [comment]
There's not a particular feature for this, but there is a way to do it -
In your ABC string, set `%%staffwidth <some-large-number>`. Then don't put any new lines in the music or use the `wrap` parameter in the `renderAbc` call.
