### ISSUE TITLE
Engraver is undefined when using oneSvgPerLine rendering with TimingCallBacks

### ISSUE THREAD

**Issue by amauryt** [paulrosen/abcjs#254]
Hi Paul, first of all, thank you for this amazing ABC notation library.

I need to implement an animated pagination for lines of music, but I think that I've found a bug when trying to pass an _abcjs_ output object rendered with the `oneSvgPerLine` option to the constructor of `TimingCallbacks`. Or perhaps I'm using a non-supported combination, as I can display each line as a separate _SVG_ without any problem, and I can use `TimingCallbacks` with a rendered output where `oneSvgPerLine` is _false_.

This is the error message I get when creating a new `TimingCallbacks` with `oneSvgPerLine` set to _true_, which is displayed for each line of music:

```
abc_tune.js:1306 Uncaught (in promise) TypeError: Cannot read property 'staffgroups' of undefined
    at Object.Tune.makeVoicesArray (abc_tune.js:1306)
    at Object.Tune.setupEvents (abc_tune.js:1349)
    at Object.Tune.setTiming (abc_tune.js:1472)
    at TimingCallbacks.self.replaceTarget (abc_timing_callbacks.js:23)
    at new TimingCallbacks (abc_timing_callbacks.js:33)
```

If such a combination is not supported, could you give me any hint to implement a different strategy to animate different lines of music?

Thanks in advance.

**Comment by paulrosen** [comment]
This will be fixed in in 5.8.2.
