### ISSUE TITLE
Playing just one note

### ISSUE THREAD

**Issue by avetma** [paulrosen/abcjs#256]
Is there a way to play just one note from console? I have included abcjs_midi_5.6.7-min.js file on the page, and I tried something like `MIDI.noteOn(0,50,127,0);` but it doesn't work.

Thank you!

**Comment by paulrosen** [comment]
It's coming! I was just working on this - if you look at the latest version and see the example `full-synth.html` it plays one note when the user clicks on a note. I'm trying to make that code more intuitive now.

Another thing you can do is make an abc string with just that note in it and call `ABCJS.renderMidi()` on it.

**Comment by avetma** [comment]
Thank you for a quick response!
It's weird, because `MIDI.noteOn` works fine if I played something earlier on the same page through standard abcjs graphic controls. But doesn't work (returns undefined) before that...
