### ISSUE TITLE
something is missing running last full-synth.html example

### ISSUE THREAD

**Issue by jepcolombia** [paulrosen/abcjs#257]
the sample use library abcjs_basic_5.8.1.js changing to abcjs_basic_5.8.1-min.js get the following error
Uncaught TypeError: ABCJS.synth.SynthController is not a constructor
    at full-synth.html:121

**Comment by paulrosen** [comment]
I'm sorry - I haven't packaged up the latest version yet for release. I wanted to create the libraries once at release time. I hope to have the release sometime soon - hopefully in a day or two.

In the meantime, if you want to run the example now, you could check out the latest version and do `npm run build:basic`.

**Comment by jepcolombia** [comment]
Thanks Paul for the answer.

**Comment by jepcolombia** [comment]
Hi Paul, doing npm run build:basic 
and the following appears :
              
C:\Users\jep\Documents\MUSICA\abcjs-master\abcjs-master>npm run build:basic

> abcjs@5.8.1 build:basic C:\Users\jep\Documents\MUSICA\abcjs-master\abcjs-master
> npm run webpack -- --env.mode development --env.type basic

npm WARN invalid config loglevel="notice"

> abcjs@5.8.1 webpack C:\Users\jep\Documents\MUSICA\abcjs-master\abcjs-master
> webpack "--env.mode" "development" "--env.type" "basic"

'webpack' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abcjs@5.8.1 webpack: `webpack "--env.mode" "development" "--env.type" "basic"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the abcjs@5.8.1 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jep\AppData\Roaming\npm-cache\_logs\2019-10-11T16_15_44_865Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abcjs@5.8.1 build:basic: `npm run webpack -- --env.mode development --env.type basic`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the abcjs@5.8.1 build:basic script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jep\AppData\Roaming\npm-cache\_logs\2019-10-11T16_15_45_061Z-debug.log

C:\Users\jep\Documents\MUSICA\abcjs-master\abcjs-master>

**Comment by paulrosen** [comment]
Did you do `npm install` first? You just have to run that when something changes in `package.json`, but you do have to run it once.

**Comment by jepcolombia** [comment]
You are right Paul! Now its working. Thank you!!
