### ISSUE TITLE
Broken links on home page

### ISSUE THREAD

**Issue by impressivewebs** [paulrosen/abcjs#258]
Great little library, thanks for this!

The [home page](https://www.abcjs.net) points to three URLs:

https://www.abcjs.net/dist/abcjs-basic.html  
https://www.abcjs.net/dist/abcjs-editor.html  
https://www.abcjs.net/dist/abcjs-plugin.html  

But the correct URLs should not include the "dist" folder, so these are broken.

**Comment by paulrosen** [comment]
Thanks so much for the report! Fixed.
