### ISSUE TITLE
currentTime (milliseconds) in full-synth.html

### ISSUE THREAD

**Issue by joshstovall** [paulrosen/abcjs#265]
I am trying to get the millisecond data, so I can see the current beat.

I can get note/time info from 
```
self.onEvent = function(ev) {
	  console.log(ev)
}
```
however, this only works when a new note is played. 

I found the configurator example, that uses
`
listenerCallback(abcjsElement, currentEvent, context) {}
`
but can't seem to get this to work in the new full-synth example
Is it possible to implement this into the full-synth?

**Comment by paulrosen** [comment]
I see that, and a couple other options for TimingCallbacks that I haven't supported in the new synth method. That will be in version 5.9.2, available soon.

**Comment by paulrosen** [comment]
Ok, it will be in version 5.10.0, coming soon. You can see the calling code in the newly checked in code in full-synth.html. It requires building the library to use (until the release).
