### ISSUE TITLE
API for key

### ISSUE THREAD

**Issue by hwellmann** [paulrosen/abcjs#268]
I would like to get hold of the key of a tune, without parsing the header myself. 

Is there any official API for that? 

Using `tune.lines[0].staff[0].key` seems like getting dirty with library internals.

**Comment by paulrosen** [comment]
I have lots of functions for exposing timing and meter info, but none for keys. However, that is easy to do and seems reasonable. This will just be the *initial* key and will ignore any key changes.

There are two different things that can be returned: the actual key name, and/or the accidentals. In the case of custom key signatures, only the second thing is meaningful. I'll return both.

**Comment by hwellmann** [comment]
Just noticed you added getKeySignature() in 5.10.0, tried it in my app, and it works fine. Thanks a lot!
