### ISSUE TITLE
abc_plugin-midi qpm: overwrites Q: from abc

### ISSUE THREAD

**Issue by hoejoe** [paulrosen/abcjs#269]
I think this setting should set the tempo to a default value if no Q: is specified in the abc data set.
"window.ABCJS.plugin.render_options = {qpm: 100,};"

from abcjs/docs/api.md:
**params (for midi)** | **Default** | **Description**
qpm | 180 | The tempo, if not specified in abcString.

Unfortunately, this value is always taken, even if Q: is set correctly.
If I omit the setting completely, the default value of (I think) 180 is very high, so I would like to set another default value.

**Comment by paulrosen** [comment]
This probably needs to be a separate option, to not break existing pages. And the documentation needs to be corrected.

I'm moving to a new way to do audio, so I would rather add this new option there.

I don't think I have time to squeeze this into the imminent release, but I will add it soon.

**Comment by paulrosen** [comment]
I thought about it some more - that is definitely a good feature. I will hope to have it in the 5.10.3 release, hopefully soon. I'll create an option `defaultQpm` that will only be used if there isn't a tempo in the header of the abc string.

**Comment by paulrosen** [comment]
This will be in version 5.10.4, released very soon.
