### ISSUE TITLE
Triplet's number 3 displayed too far away from the beam

### ISSUE THREAD

**Issue by ChorHizzle** [paulrosen/abcjs#273]
For an example, see the final measure of this (Note that the issue is worse in measure 4 than in measure 1):
```
X: 1
T: Unchanging Love (Transition 1)
C: 
M: 4/4
K: C
Q: 70
L: 1/8
V:0 clef=treble
 [K:C]  z2/1 (3:2:3C1/1F1/1G1/1 _A2/1 _B1/1A1/1&  "C"x4/1  "Fm"x4/1 |  G2/1- G1/1A1/1 _B3/2A1/2- A1/1G1/1&  "Em"x4/1  "A7"x4/1 |  F1/2E1/2F1/2C'1/2- C'2/1 G1/2^F1/2G1/2D'1/2- D'1/1C'1/2D'1/2&  "Dm"x4/1  "Em"x4/1 |  (3:2:3_E'1/1D'1/1C'1/1 (3:2:3C'1/1_B1/1_A1/1 G2/1- G2/1&  "Fm"x4/1  "G"x4/1  |]
V:1 clef=bass
 [K:C]  E4/1 _A2/1 C2/1|  G3/1[B,1/1G,1/1] [E4/1^C4/1]|  F3/1D1/1 [E4/1B,4/1]|  [F4/1C4/1] [D4/1B,4/1] |]

```

**Comment by paulrosen** [comment]
Can you post a picture? I tried your example and it looks ok to me:

![triplet-issue](https://user-images.githubusercontent.com/69818/69480833-fa338980-0dd8-11ea-8aba-8d3d15b451df.png)

If your example looks different, can you post the options you used to call `renderAbc`? If it looks the same, would you let me know what you were expecting it to look like?

**Comment by ChorHizzle** [comment]
I was using an older version. It looks good now. Thank you!
