### ISSUE TITLE
Display on a keyboard

### ISSUE THREAD

**Issue by josephernest** [paulrosen/abcjs#28]
Do you know if a tool / library exist that does this:

    input : chord in abc language. ex : [C E G]

    output : the chord displayed on a keyboard (the key to use highlighted)

![screenshot](https://deepwellbridge.files.wordpress.com/2011/02/free-piano-chords-11.jpg)

It would be helpful to help a friend who doesn't know music notation, and would like to learn chords ;)

**Comment by paulrosen** [comment]
I don't. The parser in abcjs is separable, so that could be used to handle
the input, but someone would have to write the keyboard part.


On Wed, Jan 21, 2015 at 7:43 AM, josephernest <notifications@github.com>
wrote:

> Do you know if a tool / library exist that does this:
>
> input : chord in abc language. ex : [C E G]
>
> output : the chord displayed on a keyboard (the key to use highlighted)
>
> It would be helpful to help a friend who doesn't know music notation, and
> would like to learn chords ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulrosen/abcjs/issues/28>.
>



-- 
Paul Rosen
Performant Software Solutions, LLC

**Comment by grimmdude** [comment]
I wrote this simple svg keyboard a while back that could be used to implement this.  If I'm feeling sporty this weekend maybe I'll try to work on that.

https://github.com/grimmdude/Raphael-Keyboard

**Comment by josephernest** [comment]
Waw, would be great indeed!

(For example in order to show to music learners how chord progressions work, etc.)
