### ISSUE TITLE
Whether to support xml to display staffs？

### ISSUE THREAD

**Issue by ifredom** [paulrosen/abcjs#283]
Whether to support xml to display staffs？

**Comment by paulrosen** [comment]
I'm sorry. I don't understand your question. Can you provide an example of what you mean?

**Comment by ifredom** [comment]
> I'm sorry. I don't understand your question. Can you provide an example of what you mean?

Thanks for your reply, I use Google Translate. I mean: Is there a way to render musicXml?

**Comment by paulrosen** [comment]
ABCJS does not support musicxml.

**Comment by ifredom** [comment]
> ABCJS不支持musicxml。

**Comment by ifredom** [comment]
> ABCJS does not support musicxml.

tks
