### ISSUE TITLE
Koron and Sori

### ISSUE THREAD

**Issue by Ashkanph** [paulrosen/abcjs#284]
Hi

I wanted to add two Iranian traditional music symbols to the abcjs. ( [Koron](https://en.wikipedia.org/wiki/Koron_(music)) and [Sori](https://en.wikipedia.org/wiki/Sori_(music)) ).

Can you help me from where I should start? I looked the code, but it is somehow complicated to me. It would be nice if you add them to the abcjs and the editor and midi plugins, or guide me how to do it.

Thanks in advance

**Comment by paulrosen** [comment]
Very interesting - I didn't know about these. It looks like they are used the same as the quarter-tone symbols. Those are already supported:
```
X: 1
K: C
_/B ^/c | 
```
![quarter-tone-demo](https://user-images.githubusercontent.com/69818/71369363-853ea580-2578-11ea-9ac0-6d784ad0eabd.png)

Am I reading that correctly?

So, there are two ways to approach this that I can think of:

1) You can change the symbols for the quarter tones to the ones you want to use by changing abc_glyphs.js.
2) You can add a new syntax for specifying those symbols and recognize that in the parser. You would then add the glyphs instead of changing them.

The first way is easier and might get you what you need at the cost of not having the standard quarter sharp and quarter flat symbols. You'd have to merge your changes back in every time abcjs updates, but that file doesn't change much so it should be easy.

The items that need to change are 'accidentals.halfsharp' and 'accidentals.halfflat'. Those are SVG paths. I've been thinking of making that format more intuitive, but sorry, I haven't gotten around to it yet.

If you give me an SVG of those two symbols I'll create the entries you need.

**Comment by Ashkanph** [comment]
Thank you for your response :)

You are right, they must be same. Quarter-sharp must be Sori and Quarter-flat must be koron.

![03_QT_Symbols-500x171](https://user-images.githubusercontent.com/22937754/71399539-2f7e0200-2639-11ea-8e89-c1224fb2e8d7.png)

The first approach sounds nice to me; I created [a fork of your repository](https://github.com/Ashkanph/abcjs) and will do the changes there. But even adding the svgs looks like a challenge to me :D These are the svgs:

https://upload.wikimedia.org/wikipedia/commons/3/31/Koron_sign.svg

https://upload.wikimedia.org/wikipedia/commons/b/bb/Sori_sign.svg

**Comment by Ashkanph** [comment]
@paulrosen, I can't convert those SVGs to the format you have used in the `abc_glyphs.js`:

```javascript
{d:[['M',2.43,-10.05],['c',0.21,-0.12,0.54,-0.03,0.66,0.24],['c',0.06,0.12,0.06,0.21,0.06,2.01],['c',0.00,1.05,0.00,1.89,0.03,1.89],['l',0.72,-0.48],['c',0.69,-0.48,0.69,-0.51,0.87,-0.51],['c',0.15,0.00,0.18,0.03,0.27,0.09],['c',0.21,0.15,0.21,0.18,0.21,1.41],['c',0.00,1.11,-0.03,1.14,-0.09,1.23],['c',-0.03,0.03,-0.48,0.39,-1.02,0.75],['l',-0.99,0.66],['l',0.00,2.37],['c',0.00,1.32,0.00,2.37,0.03,2.37],['l',0.72,-0.48],['c',0.69,-0.48,0.69,-0.51,0.87,-0.51],['c',0.15,0.00,0.18,0.03,0.27,0.09],['c',0.21,0.15,0.21,0.18,0.21,1.41],['c',0.00,1.11,-0.03,1.14,-0.09,1.23],['c',-0.03,0.03,-0.48,0.39,-1.02,0.75],['l',-0.99,0.66],['l',0.00,2.25],['c',0.00,1.95,0.00,2.28,-0.06,2.37],['c',-0.06,0.12,-0.12,0.21,-0.24,0.27],['c',-0.27,0.12,-0.54,0.03,-0.69,-0.24],['c',-0.06,-0.12,-0.06,-0.21,-0.06,-2.01],['c',0.00,-1.05,0.00,-1.89,-0.03,-1.89],['l',-0.72,0.48],['c',-0.69,0.48,-0.69,0.48,-0.87,0.48],['c',-0.15,0.00,-0.18,0.00,-0.27,-0.06],['c',-0.21,-0.15,-0.21,-0.18,-0.21,-1.41],['c',0.00,-1.11,0.03,-1.14,0.09,-1.23],['c',0.03,-0.03,0.48,-0.39,1.02,-0.75],['l',0.99,-0.66],['l',0.00,-2.37],['c',0.00,-1.32,0.00,-2.37,-0.03,-2.37],['l',-0.72,0.48],['c',-0.69,0.48,-0.69,0.48,-0.87,0.48],['c',-0.15,0.00,-0.18,0.00,-0.27,-0.06],['c',-0.21,-0.15,-0.21,-0.18,-0.21,-1.41],['c',0.00,-1.11,0.03,-1.14,0.09,-1.23],['c',0.03,-0.03,0.48,-0.39,1.02,-0.75],['l',0.99,-0.66],['l',0.00,-2.25],['c',0.00,-2.13,0.00,-2.28,0.06,-2.40],['c',0.06,-0.12,0.12,-0.18,0.27,-0.24],['z']],w:5.25,h:20.174},
```

I tried [SVG to RaphaelJS convertor](http://readysetraphael.com/) and I tried `font_generator/font_editor.html` but was'nt successful.

**Comment by paulrosen** [comment]
Try inserting this around line 106 of `abc_glyphs.js`:
```
	glyphs['accidentals.halfflat'] = { d: [
			['M',0,-4],
			['l', 0, 20],
			['l', 1.5, 0],
			['l', 0, -12],
			['l', 8.5, -4],
			['l', -8.5, -4],
			['l', 0, 1.5],
			['l', 6, 2.5],
			['l', -6, 2.5],
			['l', 0, -5],
			['z']],w:10,h:20
	};

	glyphs['accidentals.halfsharp'] = { d: [
			['M',0,-8],
			// left vertical line
			['m',3,0.82],
			['l',0, 19.18],
			['l', 1.70, 0],
			['l', 0, -19.18],
			['z'],

			// right vertical line
			['m',3.06,-0.82],
			['l',0, 19.18],
			['l', 1.7, 0],
			['l', 0, -19.18],
			['z'],

			// top diagonal line
			['m', -6.47,4.2],
			['l', 3, 1.29],
			['l',0, 1.39],
			['l',-3,-1.29],
			['l',0,-1.39],
			['z'],
			['m', 4,1.2],
			['l', 3, 1.29],
			['l',0, 1.39],
			['l',-3,-1.29],
			['l',0,-1.39],
			['z'],
			['m', 4,1.2],
			['l', 3, 1.29],
			['l',0, 1.39],
			['l',-3,-1.29],
			['l',0,-1.39],
			['z'],

			// bottom diagonal line
			['m', 3,2],
			['l', -3, 1.29],
			['l',0, 1.39],
			['l',3,-1.29],
			['l',0,-1.39],
			['z'],
			['m', -3,1.52],
			['l', -3, 1.29],
			['l',0, 1.39],
			['l',3,-1.29],
			['l',0,-1.39],
			['z'],
			['m', -5,2.5],
			['l', -3, 1.29],
			['l',0, 1.39],
			['l',3,-1.29],
			['l',0,-1.39],
			['z']],w:15,h:20
	};
```
That's just a rough sketch - I'm sure it can be drawn better. Let me know if the proportion could be made better. I didn't see any examples of it's use, so if you could post a picture of these symbols used as accidentals in real music I might be able to tweak it.

**Comment by Ashkanph** [comment]
Thank you, yes, it works, but at least the sori needs to be fixed:
![6](https://user-images.githubusercontent.com/22937754/71451279-6d893c00-2787-11ea-8f51-0481a218cc7c.png)

These are some examples of using them in the notes. I just remember they can come in the "key" too; What should I do about the keys (like the below examples)?

![3](https://user-images.githubusercontent.com/22937754/71451316-fc965400-2787-11ea-8937-d3d83a913c6b.png)

![4](https://user-images.githubusercontent.com/22937754/71451321-0cae3380-2788-11ea-8ae2-ec53e1a15e82.png)
![5](https://user-images.githubusercontent.com/22937754/71451322-0fa92400-2788-11ea-9173-b941fe4ade4d.png)


![1](https://user-images.githubusercontent.com/22937754/71451328-2780a800-2788-11ea-9758-2e7f49208f6a.jpg)

![2](https://user-images.githubusercontent.com/22937754/71451329-30717980-2788-11ea-971f-8b78c9d388d4.jpg)

**Comment by paulrosen** [comment]
I did another pass at it. I also noticed a bug in getting quarter tones in the key signature that I fixed but is not in the release yet. Merge the latest into your fork.
```
	glyphs['accidentals.halfflat'] = { d: [
			['M',0,-4],
			['l', 0, 20],
			['l', 1.5, 0],
			['l', 0, -12],
			['l', 8.5, -4],
			['l', -8.5, -4],
			['l', 0, 1.5],
			['l', 6, 2.5],
			['l', -6, 2.5],
			['l', 0, -6.5],
			['z']],w:10,h:20
	};

	glyphs['accidentals.halfsharp'] = { d: [
			['M',0,-9],
			// left vertical line
			['m',3,0.82],
			['l',0, 19.18],
			['l', 1.70, 0],
			['l', 0, -19.18],
			['z'],

			// right vertical line
			['m',3.06,-0.82],
			['l',0, 19.18],
			['l', 1.7, 0],
			['l', 0, -19.18],
			['z'],

			// top diagonal line
			['m', -6.06,3.2],
			['l', 3, 1.29],
			['l',0, 1.39],
			['l',-3,-1.29],
			['l',0,-1.39],
			['z'],
			['m', 4.7,1.95],
			['l', 1.25, .6],
			['l',0, 1.39],
			['l',-1.25,-.6],
			['l',0,-1.39],
			['z'],
			['m', 3,1.3],
			['l', 4.5, 2.5],
			['l', -2.25,0],
			['l',-2.2,-1.1],
			['l',0,-1.39],
			['z'],

			// bottom diagonal line
			['m', 0,5],
			['l', 4.5, -2.5],
			['l', -2.25,0],
			['l',-2.2,1.1],
			['l',0,1.39],
			['z'],
			['m', -3,1.5],
			['l', 1.25, -.6],
			['l',0, -1.39],
			['l',-1.25,.6],
			['l',0,1.39],
			['z'],
			['m', -4.2,1.7],
			['l', 3, -1.29],
			['l',0, -1.39],
			['l',-3,1.29],
			['l',0,1.39],
			['z']],w:15,h:20
	};
```

**Comment by paulrosen** [comment]
I'm adding an entry point that will allow you to modify individual glyphs with an example of using it to add the Koron and Sori characters. I'll have that released in the next day or so.

**Comment by Ashkanph** [comment]
Thank you very much. The new glyphs were exactly what i wanted.

I think by adding an entry point for it, there wont be any need to my fork :) , thanks again

**Comment by paulrosen** [comment]
Check out the new version 5.12.0. In particular look at the `change_glyphs.html` example.

**Comment by Huji** [comment]
This is awesome! Thanks @paulrosen
