### ISSUE TITLE
Ties that should go over a note with a different pitch end on it instead

### ISSUE THREAD

**Issue by p-himik** [paulrosen/abcjs#285]
Example sequence: `A- B A`.
It's rendered as
![image](https://user-images.githubusercontent.com/4410314/71379819-7afec480-25d5-11ea-9fb9-95809c8d9631.png)

But the tie should go over `B` and end on the second `A`.

**Comment by paulrosen** [comment]
I think that construct is not strictly legal. I think it should be written like this: `(A B A)`.

I'm trying to interpret this section of the standard:

https://abcnotation.com/wiki/abc:standard:v2.2#ties_and_slurs

It is clear that the intention is for the two notes on either side of the tie should be the same but it doesn't address this exact situation.

But reading the word "successive" in the following: "Ties connect two successive notes of the same pitch" implies that there can't be a separation.

I'm not sure how to interpret what you are suggesting either if I were to see it written. It would look so much like a slur that I would play it as a slur.

**Comment by p-himik** [comment]
The sentence before the one you quoted: "It should be noted that although the tie - and slur () produce similar symbols in staff notation they have completely different meanings to player programs and should not be interchanged."
So it seems like `(A B A)` is also not a good thing here if I want a real tie.

[2] has some examples of the behavior I describe. But of course, this is not a source of truth.

An interesting and somewhat relevant example from the ABC mailing list [1]:
`K:Ab D- | K:A C` "would be considered a tie, because D-flat and C-sharp are different notes, but the same pitch (assuming equal temperament)."

I've asked the author of the ABC standard about it - maybe we'll get an answer soon.


[1] https://www.mail-archive.com/abcusers@argyll.wisemagic.com/msg04028.html
[2] https://www.ucolick.org/~sla/abcmusic/piano/piano.html

**Comment by paulrosen** [comment]
Closed for inactivity. If you get more info let me know.
