### ISSUE TITLE
Basic Drum notation 

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#286]
Hi
I see in @rigobauer  #122  that something was done and is possible. I see an example in the #122 that is working.
But I was not able to find documentation in order to understand it.

Where can I found documentation about displaying drum notation with abcjs?
Thank you

**Comment by paulrosen** [comment]
This is a combination of a couple of features: 

1) The `U:` is defined here: https://abcnotation.com/wiki/abc:standard:v2.1#redefinable_symbols

2) The `!style=x!` is defined here: https://paulrosen.github.io/abcjs/overview/abc-notation.html#additions-to-the-standard

3) The `K:perc` is defined here: https://abcnotation.com/wiki/abc:standard:v2.1#clefs_and_transposition

4) `[ng2F2]` is a number of features: the brackets means that it is a "chord", that is, the notes in between appear vertically. `ng2` is using the macro defined in the U: line to modify the `g2` note with the "x" style.

I don't know if that is getting to your question. Are there other features of drum notation you have a question about?

I should probably add an elaborate drum example. If you have a drum pattern you'd like to see, attach a picture here.

**Comment by osvi64** [comment]
Thank you Paul. Precious as usual.
I understood the example. Attached you can find the main symbols for drum notation. I should be able to generate all the symbols, minus the line before the last. 
I mean the line with open Hi Hat, Closed Hi Hat, Ghost notes. Is there a way also for them?

![reading-drum-notation](https://user-images.githubusercontent.com/29627488/71846957-0bf09800-30cc-11ea-8aa8-6a161a6cf65d.jpg)

**Comment by paulrosen** [comment]
```
X: 1
M: 4/4
L: 1/4
U:n=!style=x!
K:perc
V:ALL stem=up
[P:Open Hi-Hat]!open!ng !open!ng !open!ng !open!ng |\
[P:Closed Hi-Hat]!+!ng !+!ng !+!ng !+!ng |\
[P:Ghost Notes]"<("">)"B "<("">)"B "<("">)"B "<("">)"B |
```

**Comment by osvi64** [comment]
Great. Thank you so much.

Last thing if you can. If I play it with the midi controller, the sound associated to the notes is not the rigth one. Is there a way to remap in some way, associating a differente note/sound? In my app I'm stil using midi.js.

Thank you

**Comment by paulrosen** [comment]
Yeah - that's on my list. I haven't gotten around to implementing that yet. I'll move that up on the priorities. (And it won't matter whether you are using midi.js or the new audio, constructing the sound is done the same for both.)

**Comment by osvi64** [comment]
Hi Paul, is there a way to avoid printing the sharp symbol?
See at the example below: In case of open HiHat I need to print the x for the ^g note, without the sharp symbol. I need to put ^g instead of g because I need to make the Synth produce a different note.
Is there any way to obtain it?

Thank you

![image](https://user-images.githubusercontent.com/29627488/75325662-80001e80-5879-11ea-8d8f-8e2b6151ebc1.png)

**Comment by osvi64** [comment]
Opened in a specific issue

**Comment by paulrosen** [comment]
The sharps are no longer printed and the sounds are now correct if you use `%%percmap`

**Comment by sejinniemma** [comment]
We are currently using a website down below to convert musicXML to abc.js to create sheet music.
This time, we want to convert drums to abc.js and use it.
If you know of a website that can convert drums to abc.js like the one below, or if you know any other way, please let us know. Thank you.

https://wim.vree.org/js/xml2abc-js.html

**Comment by MalabarFront** [comment]
> Is there a way to have ghost notes on the snare together with other notes like this?
> <img alt="Image" width="650" height="200" src="https://private-user-images.githubusercontent.com/7091110/462898878-e0e37db0-f233-4ea4-a669-c8c6ac1dcdf3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg0NzM4MDEsIm5iZiI6MTc1ODQ3MzUwMSwicGF0aCI6Ii83MDkxMTEwLzQ2Mjg5ODg3OC1lMGUzN2RiMC1mMjMzLTRlYTQtYTY2OS1jOGM2YWMxZGNkZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjFUMTY1MTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWVkOWRlODY3MmI2NTM5NTIwYmRhMzc2NWFlMjg5MWEzODM1YmY0MDc3NzJkYWFhYjE1M2Q1NjU2Y2UxMDI4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mf9HjfRDEhf_EqcwS3QvFT9wEyTnn-otiTXwd__4kbw">
> 
> From my understanding, this is not valid abc.
> 
> ```
> |[g"<("">)"c] z z z|
> ```
> 
> The annotation should come before `[]` but then the parenthesis don't apply to the snare anymore. Did I miss anything ?

What was the resolution to this? I'm facing the same problem, where as soon as I turn a snare into a ghost, it gets shifted on note along instead of appearing in a chord.

Eg. 

Normal snare on beat 2 with a hi-hat. Works fine.

```
X:1
M:C
L:1/8
V:1 perc stem=up
%%percmap D  pedal-hi-hat x
%%percmap F  acoustic-bass-drum
%%percmap G  low-floor-tom
%%percmap A  high-floor-tom
%%percmap B  low-tom
%%percmap c  acoustic-snare
%%percmap ^c side-stick x
%%percmap d  low-mid-tom
%%percmap e  hi-mid-tom
%%percmap f  high-tom
%%percmap ^f ride-cymbal-1 x
%%percmap ^a diamond x
%%percmap g  closed-hi-hat x
%%percmap ^g open-hi-hat x
%%percmap a  crash-cymbal-1  x
K:C perc
[gF]g [gc]g gg gg |
```

Ghost snare on beat 2 with a hi-hat. Broken. Inserts an extra note.

```
X:1
M:C
L:1/8
V:1 perc stem=up
%%percmap D  pedal-hi-hat x
%%percmap F  acoustic-bass-drum
%%percmap G  low-floor-tom
%%percmap A  high-floor-tom
%%percmap B  low-tom
%%percmap c  acoustic-snare
%%percmap ^c side-stick x
%%percmap d  low-mid-tom
%%percmap e  hi-mid-tom
%%percmap f  high-tom
%%percmap ^f ride-cymbal-1 x
%%percmap ^a diamond x
%%percmap g  closed-hi-hat x
%%percmap ^g open-hi-hat x
%%percmap a  crash-cymbal-1  x
K:C perc
[gF]g [g"<("">)"c]g gg gg |
```

**Comment by paulrosen** [comment]
That looks like a bug. There is a work around (a little ugly but it looks like it does the trick).

```
[gF]g "@-9,-15(""@13,-15)"[gc]g gg gg |
```

**Comment by MalabarFront** [comment]
> [gF]g "@-9,-15(""@13,-15)"[gc]g gg gg |

Fantastic, thanks for the reply. Want me to raise a separate issue for this?
