### ISSUE TITLE
Dotted slurs seem to not work

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#289]
Code:
```
CD.(EAGB)DADFDAD
```
Result:
![image](https://user-images.githubusercontent.com/15198808/71782267-4df4dd80-2fe9-11ea-9d71-ccb4b2b87b52.png)

**Comment by rualark** [comment]
Actually, reading ABC notation standard, I do not understand how this could be implemented - how to distinguish staccato from dotted slur.

**Comment by paulrosen** [comment]
I think the dotted slur is when the dot is immediately before the open paren.

This is not yet supported, but I'll get to it soon.

(Keep them coming! If you are missing a feature you need to use, let me know.)

**Comment by rualark** [comment]
> I think the dotted slur is when the dot is immediately before the open paren.
> 
> This is not yet supported, but I'll get to it soon.
> 
> (Keep them coming! If you are missing a feature you need to use, let me know.)

Exactly! I should have realized that slur starting with staccato is never used.

**Comment by Godless-** [comment]
> Exactly! I should have realized that slur starting with staccato is never used.

Well, actually it is very usable in choir music - slur meaning that more than one note spans over a syllable and still indicated to be performed staccato. Looking forward to this feature (dotted slur)! That's a perfectly sound notation (pun intended).

**Comment by rualark** [comment]
> > Exactly! I should have realized that slur starting with staccato is never used.
> 
> Well, actually it is very usable in choir music - slur meaning that more than one note spans over a syllable and still indicated to be performed staccato. Looking forward to this feature (dotted slur)! That's a perfectly sound notation (pun intended).

It seems that abcjs currently resolves ".(" as `staccato + slur start`, which is a problem for analysis software, where slur can start from any note. I do not know how to start slur from dotted note currently. Please support resolving ".(" as `dotted note + slur start`

**Comment by paulrosen** [comment]
Fixed in beta.15
