### ISSUE TITLE
Switch out the Quicktime plugin for a pure javascript solution

### ISSUE THREAD

**Issue by bjarkihall** [paulrosen/abcjs#29]
I like your project but I was wondering if it isn't possible to switch out the Quicktime plugin dependency for a pure javascript solution, now that Quicktime is a bit out-dated (and not a necessity).
Best regards,
Bjarki

**Comment by paulrosen** [comment]
Yes, that would be great. Unfortunately I haven't found a completely
seamless alternative yet.


On Tue, Mar 17, 2015 at 2:05 AM, Bjarki Hall <notifications@github.com>
wrote:

> I like your project but I was wondering if it isn't possible to switch out
> the Quicktime plugin dependency for a pure javascript solution, now that
> Quicktime is a bit out-dated (and not a necessity).
> Best regards,
> Bjarki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulrosen/abcjs/issues/29>.
>



-- 
Paul Rosen
Performant Software Solutions, LLC

**Comment by Tirno** [comment]
The timbre-midi branch contains the closest we have come to switching out quicktime - and is probably ready for the prime time

**Comment by paulrosen** [comment]
Version 2.3 will have the quicktime removed and just a link to download. In the next version, I'll have an integrated MIDI version.
