### ISSUE TITLE
Ignoring notes in midi

### ISSUE THREAD

**Issue by Ashkanph** [paulrosen/abcjs#292]
Hi again :)

For me the midi of this note is'nt correct: 
```
X:1
T:Har waya
M:2/4
L:1/8
K:C
z ^G/2G/2 GG | ^G3/2-^A/2 G/2^F/2F | ^G^A B/2-A/2A/2-G/2 | ^G3/2-^A/2 G/2^F/2F :|
```
It must be like [this](https://gofile.io/?c=p7oSl1), But some notes are getting ignored in the abc midi file. I tested it with the `editor-midi.html` in the `examples` folder.

Have I missed something?

**Comment by paulrosen** [comment]
You definitely uncovered a bug!

There is an error in your slurs, which the visual renderer is able to figure out, but the audio is not.

You are using the hyphen to draw the slurs, but that is supposed to be for a tie. Parentheses are for slurs. There is a subtle difference between them: with ties it changes the length of the note. With slurs it just takes the space out between notes.

Anyway, I'll definitely make the audio more robust, but you should change the line to:
```
z ^G/2G/2 GG | (^G3/2^A/2) G/2^F/2F | ^G^A (B/2A/2)(A/2G/2) | (^G3/2^A/2) G/2^F/2F :|
```

**Comment by Ashkanph** [comment]
I wasn't aware of the difference between hyphen and parentheses in abc notation. Thank you very much :)
