### ISSUE TITLE
How to decrease space between staves?

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#293]
I tried using `%%sysstaffsep`, but it results in more space between tenor and bass than between soprano and alto (meaning space between beams):
![image](https://user-images.githubusercontent.com/15198808/71851723-351f2180-30e8-11ea-8a78-c0665c915d42.png)

**Comment by rualark** [comment]
Another example of spacing that could be more compact:
![image](https://user-images.githubusercontent.com/15198808/72688839-4de1fb00-3b1c-11ea-94a8-15b6c23ef45d.png)

**Comment by paulrosen** [comment]
Actually, there was a bug in calculating when nothing extends below the staff (like with bass clefs that don't contain low notes) I fixed that and the spacing will hopefully be better now.

**Comment by paulrosen** [comment]
Fixed in beta.15, I think. Let me know if it looks ok.
