### ISSUE TITLE
Make part name clickable and selectable from API

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#295]
Is it possible to make part name clickable? Currently cursor changes to "select text" when hovering mouse over part name.

Can I then highlight a selected part name after redrawing abc?

**Comment by paulrosen** [comment]
That could be done. Are there any other elements you want clickable?

**Comment by rualark** [comment]
Thanks! I do not see more important clickable elements for now, because I have not finished designing music analysis ui, but it seems to me that all text strings should be separately clickable, probably except measure numbers. I hope to be more specific when I start to draw music analysis shapes.

**Comment by paulrosen** [comment]
This will be fixed in the next version.

**Comment by rualark** [comment]
Probably not in commit 9aa7929adc69b3e90ee69f2b2f25c8b8cb8f694a
Or I have not figure out how to disable selecting text yet.

**Comment by paulrosen** [comment]
You can still select text: I wanted that because people do want to do that. It's just that it also pings the callback when it is clicked so that the visual editor can react.

I guess I can add an option to disable selecting text. I am personally pretty annoyed when I go to websites and I can't select any text I see.

**Comment by rualark** [comment]
> You can still select text: I wanted that because people do want to do that. It's just that it also pings the callback when it is clicked so that the visual editor can react.
> 
> I guess I can add an option to disable selecting text. I am personally pretty annoyed when I go to websites and I can't select any text I see.

Notation editors usually do not allow to select text, because you can click-edit text and select it from there. This is why selecting text is not needed in visual editor. 

But if you need a more simplified interface where text selection is possible without clicking, this interface should either not interfere with dragging (by checking if dragging is above text or not) - or text selection should have option to be disabled.

**Comment by paulrosen** [comment]
Yeah, maybe selecting text and dragging are mutually exclusive.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.13
