### ISSUE TITLE
Display failing due to < characters

### ISSUE THREAD

**Issue by jimc-hjones** [paulrosen/abcjs#298]
I expect there's an easy fix for this, but I can't spot it.
I knocked up a display page using abcjs, and for the first time I've been presented with a tune that contains < characters.
My page is very simplistic and just embeds the abc in a web page with php
https://www.devboats.co.uk/tunesbook/EwellSessions/tunedisplay.php?abc/Will%20Atkinson%27s%20Schottische.abc
What seems to be going on is that the  < are being read as html and messing up the interpretation, so presumably I should wrap the abc in something, but what? Apologies if this is well documented somewhere I haven't spotted.

**Comment by paulrosen** [comment]
Replace all `<` with `&lt;` and all `>` with `&gt;`. (You don't have any, but if you had `&` replace that with `&amp;`) Also, be sure there aren't extra spaces at the beginning of the line - to recognize a header, the colon has to be the second character.

So, in your example:
```
X: 3
T: Will Atkinson's Schottische
R: barndance
M: 4/4
L: 1/8
K: Gmaj
|: G&gt;A |"G"B2 B2 B&lt;d-d2 |"C"c&gt;B c&gt;d e4 |"D" d&gt;g f&gt;e d&gt;c B&gt;A |"G" G&gt;A (3 BAG D2 G&gt;A |
"G"B2 B2 B&lt;d-d2 |"C" c&gt;B c&gt;d e4 |"D" d&gt;g f&gt;e d&gt;c B&gt;A |"G"G2 B2 G2 :|
|: d2 |"D"c&lt;A F2 F2 e2 |"G" d&lt;B G2 G2 g2 |"D"f2 A&gt;B "C"c2 e2 | "G"d&gt;B G&gt;A B2 d2|
"D"c&lt;A F2 F2 e2 |"G" d&lt;B G2 G2 g2 | "D"f2 A&gt;B "C"c&gt;d e&gt;f |"G" g2 g2 g2 :|
|: G&gt;A |"G"B2 B2 B2 A&gt;G |"D" F&gt;E F&gt;G A2 A&gt;B|"C" c2 c2 c2 "/B"B&gt;"/A"A |"G" G&gt;F G&gt;A B2 G&gt;A|
"G" B2 B2 B2 A&gt;G | "D"F&gt;E F&gt;G A2 A&gt;B |"C"c2 c2 c2 "/B"B&gt;"/A"A |"G"G2 B2 G2:|
```

**Comment by jimc-hjones** [comment]
OK thanks. I was hoping to avoid converting to the html entities because of the way my page works reading a library of standard abc files, but I expect I can do the conversion on the fly in code.  Thanks again for your time.
