### ISSUE TITLE
How to distinguish, clef of which voice was clicked without parsing classes string passed to clickListener?

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#299]
Example:
```
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Soprano"
V: V1 clef=treble name="Bass"
[V: V0]c4d4e4f4|
[V: V1]D4C4B,4A,4|
```

**Comment by paulrosen** [comment]
Parsing the classes is the intended way to do it - does that cause a problem? You would look for `abcjs-v.` and the wildcard character is the voice number.

**Comment by rualark** [comment]
Ok, thanks. This is an option, although I would try to avoid string parsing if possible, because this makes code less readable and is potentially less robust.

**Comment by paulrosen** [comment]
What I do is take the class string and do `split(" ")`. Then I do a `.map()` and convert it to the structure that is useful for my needs.

**Comment by rualark** [comment]
Thanks.
