### ISSUE TITLE
Bad key on some parts in multivoices tunes with key changes

### ISSUE THREAD

**Issue by njouve** [paulrosen/abcjs#30]
In the following tune  the second voice does not have an initial key declared ( and it doesn't have to have this) it is shown and played in the key of the end of the previous part.
The second part/voice  should be started in G the same as the first part but it starts in D

X:1
T:Upplandsschottis
O:Sweden
M:4/4
L:1/8
Z:From Klaus Rõhling - Zeilitzheim 2013
Z:2nd part by Ben Thackeray
K:G
V:1
"G"G,2B,D G2G2|"Am"G<F A<F "D7"D4|D2FA c2c2|"G"c<B d<B G4|
"G"G2 Bd "G7"g2g2|"C"e2ce g2g2|"G"d2B<d "D7"c<A F<A|"G"G<F "D7"G<A "G"G4:||
K:D
|:"D"d2A<d "A7"c2A<c|"D"d<A d<e f2 a<f|"G"g2e<g "D"f2 d<f|"Em"e<d c<B "A7"A4|
"D"d2 A<d "A7"c2 A<c|"D"d<A d<e "D7"f2 a<f|"Em"g2 e<c "A7"A<c e<c|"D"d<c "G"d<e "D"d4:|]
V:2
D2GB d2d2|B<A c<A F4|F2Ac e2e2|e<d g<d B4|
B2 dg d2d2|G2EG c2 c2|b2 g<b a<d c<d|B2c2d4:||
K:D
|:f2d2g4|f<d f<g a4|b2g<b a2f<a|e<f g<^g a2=g2|
f2d2g4|f<d f<g a4|G2c2e2g2|f2g2f4:|]

**Comment by paulrosen** [comment]
Yes, I see that. Thanks for the bug report. At least this one has an easy
workaround: just add [K:G] to the start of the second part. I'll fix this
for the upcoming release. Look for it soon.

On Mon, Apr 13, 2015 at 4:49 PM, njouve <notifications@github.com> wrote:

> In the following tune the second voice does not have an initial key
> declared ( and it doesn't have to have this) it is shown and played in the
> key of the end of the previous part.
> The second part/voice should be started in G the same as the first part
> but it starts in D
>
> X:1
> T:Upplandsschottis
> O:Sweden
> M:4/4
> L:1/8
> Z:From Klaus Rõhling - Zeilitzheim 2013
> Z:2nd part by Ben Thackeray
> K:G
> V:1
> "G"G,2B,D G2G2|"Am"G<F A<F "D7"D4|D2FA c2c2|"G"c<B d<B G4|
> "G"G2 Bd "G7"g2g2|"C"e2ce g2g2|"G"d2B<d "D7"c<A F<A|"G"G<F "D7"G<A "G"G4:||
> K:D
> |:"D"d2A<d "A7"c2A<c|"D"d<A d<e f2 a<f|"G"g2e<g "D"f2 d<f|"Em"e<d c<B
> "A7"A4|
> "D"d2 A<d "A7"c2 A<c|"D"d<A d<e "D7"f2 a<f|"Em"g2 e<c "A7"A<c e<c|"D"d<c
> "G"d<e "D"d4:|]
> V:2
> D2GB d2d2|B<A c<A F4|F2Ac e2e2|e<d g<d B4|
> B2 dg d2d2|G2EG c2 c2|b2 g<b a<d c<d|B2c2d4:||
> K:D
> |:f2d2g4|f<d f<g a4|b2g<b a2f<a|e<f g<^g a2=g2|
> f2d2g4|f<d f<g a4|G2c2e2g2|f2g2f4:|]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulrosen/abcjs/issues/30>.
>



-- 
Paul Rosen
Performant Software Solutions, LLC

**Comment by njouve** [comment]
Thanks Paul, nothing really important in fact. Your work is still much appreciated by TradMusician users. I've just released a new version by the way.

**Comment by paulrosen** [comment]
I'm closing some old issues due to inactivity. I have this feature on my list to do when I have time.
