### ISSUE TITLE
How to change font and font size for bar numbers, text, chords and other text?

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#302]

**Comment by paulrosen** [comment]
When calling `renderAbc`, pass the following parameter:
```
{ 
  format: { 
    titlefont: "Verdana 16 italic bold",
    gchordfont: "Verdana 16 italic bold",
    composerfont: "Verdana 16 italic bold",
    footerfont: "Verdana 16 italic bold",
    headerfont: "Verdana 16 italic bold",
    historyfont: "Verdana 16 italic bold",
    infofont: "Verdana 16 italic bold",
    measurefont: "Verdana 16 italic bold",
    partsfont: "Verdana 16 italic bold",
    repeatfont: "Verdana 16 italic bold",
    subtitlefont: "Verdana 16 italic bold",
    tempofont: "Verdana 16 italic bold",
    textfont: "Verdana 16 italic bold",
    voicefont: "Verdana 16 italic bold",
    tripletfont: "Verdana 16 italic bold",
    vocalfont: "Verdana 16 italic bold",
    wordsfont: "Verdana 16 italic bold",
    annotationfont: "Verdana 16 italic bold",
  }
}
```

**Comment by rualark** [comment]
How can I change font of lower ("_Lyric") and upper text ("^Text")?

**Comment by paulrosen** [comment]
If the reason you are using the lower format is for lyrics, you should use `w:` instead. Then you can use `vocalfont` for that. Otherwise, there isn't a way to target them separately.

**Comment by rualark** [comment]
> If the reason you are using the lower format is for lyrics, you should use `w:` instead. Then you can use `vocalfont` for that. Otherwise, there isn't a way to target them separately.

Thanks a lot for your suggestion! But lyrics are very limited:
- Lyric is not printed under the pause
- Lyric cannot contain space
- Lyric cannot contain dash

Yet, lyrics are powerful tool!

:bulb: Can we overcome all of these lyrics limitations by allowing lyrics in double quotes and printing lyrics under the pause?

:bulb: Can you also allow to specify separate fonts for upper, lower, left and right text?
