### ISSUE TITLE
Audio examples pages return code 404

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#303]
https://paulrosen.github.io/abcjs/examples/basic-synth.html
https://paulrosen.github.io/abcjs/examples/full-synth.html

![image](https://user-images.githubusercontent.com/15198808/72211878-e73d5b80-34e3-11ea-9ef3-1bba4108fc46.png)

**Comment by paulrosen** [comment]
Ok, I'll fix that in the next release. In the meantime, find the files in the repo in the folder `examples`
