### ISSUE TITLE
Increase clickable area around notes

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#305]
People find it difficult to click abcjs notes on mobile phones and tablets, because clickable area is very small. Increasing it would help very much. For example, area between two notes can be divided proportionally:

![image](https://user-images.githubusercontent.com/15198808/72212889-a1d65980-34f6-11ea-8f04-f0bc99fc55e4.png)

**Comment by paulrosen** [comment]
That's an interesting idea - I already have a rectangle that is a little larger than the note. I guess there's no harm in having a click anywhere on the music snap to the nearest element.

In fact, now that I think about it - I could do that without the extra rectangles and it might speed up rendering.

**Comment by rualark** [comment]
This seems a good idea. But I would limit the distance of this snapping and make it changeable with parameters. Actually, there is one more thing: best way to calculate this distance is to calculate distance from click point to the contour of the shape, which is a current clickable area for example. Calculating distance to center of an object can yield problematic results when clicking between large and small objects. Also, clicking inside rectangles should not allow to snap outside the rectangle.

Will this approach be compatible with clickable text?

**Comment by paulrosen** [comment]
That's a good question - I don't want to prevent users from selecting text but I'm not sure how to do both. I might need a switch where you set `{ wantsSelect: true }` or something.

Another thing to think about is compound objects: for instance `"Gm"v[DB]`. Currently that is one selection, and I think that makes sense because that is one musical "event". But how would the user specify one of the notes, or just the chord, or the decoration?

**Comment by rualark** [comment]
Ideally, every note and text should be selected separately like in a notation software like Sibelius - this way visual editing has more chances to be developed.

**Comment by paulrosen** [comment]
See the latest code in the repo for a possible fix.

**Comment by rualark** [comment]
Thank you! This seems to work very good. Do you think adding a parameter to control maximum distance of snap would be useful?

**Comment by paulrosen** [comment]
Yes. I wonder if it should be a parameter or just a max distance.

Also it seems like it would be different across lines. Perhaps it should never select something in a different line. What do you think?

**Comment by rualark** [comment]
Exactly! Selecting across lines is bad. Actually, when choosing a closest object, it should be chosen between objects in the same line only.
I would prefer a configurable parameter.

**Comment by paulrosen** [comment]
I added a max distance for clicking - I arbitrarily set it at 12 pixels, but that can be changed. I hope that it doesn't need to be a parameter but it can be just set to a reasonable value. Let me know if the latest code works better for you.

**Comment by rualark** [comment]
Thanks, I will check it out on next iteration.
