### ISSUE TITLE
What is the best way to get midi from abc notation for output to midi file when using abcjs and not abcjs-midi?

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#308]

**Comment by paulrosen** [comment]
That is something I didn't port over to the new audio yet. I'll put that on my list.

**Comment by rualark** [comment]
Until then, can abcjs-midi be imported as a module just to not interfere with global scope and to convert to midi?

**Comment by paulrosen** [comment]
I would just import and use the midi version. That is a superset of the basic version. 

The fix is coming soon, though!
