### ISSUE TITLE
Playback for visual music editor

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#309]
Could you please help me choose a straightforward and robust interface for playback with the following requirements? I see that SynthController does that, but I will use my own visualization - should I still use SynthController or there is a more straightforward way?

- Initialize - `.init()`, then `.prime()` :ok:
- Play - `.start()` :ok:
- Pause and resume - `.pause()`, `.resume()` :ok:
- Change bpm - `millisecondsPerMeasure` :ok:
- Play note on click or input - `.playEvent` :ok:
- Start playback from arbitrary beat - is it "percent" of time or of beats in `.seek()`? Could you please specify this in docs?
- Receive "playback ended" event - how can I do it without SynthController `audioParams.onEnded`?
- Display vertical line moving with playback, like in `full-synth` example - I see that it can be done with `CursorControl`. Is there a simple way to just receive `onEvent` without `SynthController` or `CursorControl` so that I can draw cursor?

:warning: renderMidi gives significantly better sound than CreateSynth: sound of basic-midi.html is significantly better than sound of basic-synth.html and full-synth.html (I can create an audio recording to compare if needed).
Why is that? Are there problems with renderMidi that forced moving to synth? Can renderMidi be used or is it deprecated? What is the difference between abcjs and abcjs-midi? Can aforementioned requirements be met using renderMidi?

**Comment by paulrosen** [comment]
TimingCallbacks is the basis for all that timing - when you start that, it sends callbacks for a lot of useful events - new notes, beats, subdivisions of beats, approaching the end of the line, and the end of the piece. It doesn't have any UI associated with it, so you can just hook into those callbacks and run whatever UI you want. SynthController calls TimingCallbacks so it is basically the same effect. I am trying to onion this so that you can have as much or as little functionality as is convenient.

seek takes percentage of the entire tune.

If you are watching the beats callback, you'll get one last callback at the end of the piece.

You can write your own class that takes the same entry points as CursorControl and pass that in. That was the intention. What I'd do is copy the CursorControl class to your own code and modify it as you want.

**Comment by paulrosen** [comment]
Oh - about renderMidi - there were lots of performance problems with that. It would work passably on my fast computer, but just not keep up on a lot of phones. About the sound quality, I think I know what is going on and I plan to make another pass on this code to improve it. I think the sound quality only suffers when you are playing more than one note at a time - have you noticed anything else with it? It's also a little quieter, which I'll also improve.

**Comment by rualark** [comment]
Currently renderMidi sounds much better than synth, the difference is huge. Here is my analysis of this problem.

Same music played in Chrome by renderMidi (from basic-midi.html example) and synth (from basic-synth.html example): [listen](https://audiomack.com/embed/playlist/rualark/abcjs-test)

Synth seems to have gaps in audio, phasing and no stable reverb - compared to renderMidi. Let's look at it closer.

Loudness is generally the same, although renderMidi is a little louder (renderMidi on the left):
![image](https://user-images.githubusercontent.com/15198808/72380108-c6644880-3725-11ea-9564-fcbed9da385c.png)

When you zoom in, you can see that there are abrupt gaps between notes played by synth, which probably kills music quality:
![image](https://user-images.githubusercontent.com/15198808/72379448-7fc21e80-3724-11ea-957e-18d4da407f5f.png)

renderMidi does not have this problem:
![image](https://user-images.githubusercontent.com/15198808/72380437-733ec580-3726-11ea-9c7a-e2f66d7fdfa3.png)

If you zoom spectrum in more, you can see that even inside the note synth spectrum has severe artifacts, which probably cause this phasing sound:
![image](https://user-images.githubusercontent.com/15198808/72380732-1394ea00-3727-11ea-9cf1-0b486641eb45.png)

renderMidi does not have this problem:
![image](https://user-images.githubusercontent.com/15198808/72380782-2efff500-3727-11ea-9eee-014d1328eb53.png)

**Comment by paulrosen** [comment]
That does! I have an idea of what needs to change, but I need to figure out how to do it. This is a high priority issue for me.

**Comment by rualark** [comment]
Could you look at this issue please? I got it today from user. It seems that user input some notes (clicked note_ci) and then clicked play. All call stack with code is shown.
https://sentry.io/share/issue/a2f5715aa8424e23969fd7b3e27d992e

**Comment by paulrosen** [comment]
Can you figure out what their abc string was? Or at least the instrument they were using? There is a "missing note". If I can reproduce it I can guard against it.

**Comment by rualark** [comment]
I am not sure if breadcrumbs are shown at the page that I shared above. Here are they:


<details>
  <summary>Breadcrumbs</summary>

```
console
No previous state stored in this browser
logger	console
extra	{"arguments":["No previous state stored in this browser"]}
10:58:51
console
analyse CA3 __Z12doubleValuesPfi 1,2,3,4
logger	console
extra	{"arguments":["analyse","CA3","__Z12doubleValuesPfi",[1,2,3,4]]}
10:58:54
console
[object Object]
logger	console
extra	{"arguments":[{"type":"RESULT","modName":"CA3","data":"[2,4,6,8]","funcName":"__Z12doubleValuesPfi"}]}
10:59:33
console
Click [object Object] 0 abcjs-staff-extra abcjs-time-signature abcjs-l0 abcjs-m0 abcjs-v1 abcjs-note_selected [object Object] undefined
logger	console
extra	{"arguments":["Click",{"type":"specified","value":"[\"[Object]\"]","abselem":"{\"abcelem\":\"[Object]\",\"bottom\":2.065290322580645,\"children\":\"[Array]\",\"duration\":0,\"durationClass\":0,\"elemset\":\"[Array]\",\"extra\":\"[Array]\",\"extraw\":0,\"heads\":\"[Array]\",\"invisible\":false,\"minspacing\":10,\"right\":\"[Array]\",\"specialY\":\"[Object]\",\"top\":9.934709677419354,\"tuneNumber\":0,\"type\":\"staff-extra time-signature\",\"w\":11.795,\"x\":88.05924999999999}"},0,"abcjs-staff-extra abcjs-time-signature abcjs-l0 abcjs-m0 abcjs-v1 abcjs-note_selected",{"line":0,"voice":1,"measure":0},"[undefined]"]}
10:59:33
console
analyse CA3 __Z12doubleValuesPfi 1,2,3,4
logger	console
extra	{"arguments":["analyse","CA3","__Z12doubleValuesPfi",[1,2,3,4]]}
10:59:33
ui.click
body.modal-open > div#abc > svg
10:59:36
ui.click
div.modal-content > div.modal-header > button.close[type="button"]
10:59:36
console
[object Object]
logger	console
extra	{"arguments":[{"type":"RESULT","modName":"CA3","data":"[2,4,6,8]","funcName":"__Z12doubleValuesPfi"}]}
10:59:37
ui.click
body
10:59:38
console
Click [object Object] 0 abcjs-rest abcjs-d1 abcjs-l0 abcjs-m1 abcjs-v1 abcjs-n0 abcjs-note_selected [object Object] 0
logger	console
extra	{"arguments":["Click",{"el_type":"note","startChar":188,"endChar":191,"rest":"{\"type\":\"whole\"}","minpitch":7,"duration":1,"maxpitch":7,"averagepitch":7,"abselem":"{\"abcelem\":\"[Object]\",\"bottom\":6.396129032258065,\"children\":\"[Array]\",\"duration\":1,\"durationClass\":1,\"elemset\":\"[Array]\",\"extra\":\"[Array]\",\"extraw\":0,\"heads\":\"[Array]\",\"invisible\":false,\"minspacing\":1,\"right\":\"[Array]\",\"specialY\":\"[Object]\",\"top\":7.603870967741935,\"tuneNumber\":0,\"type\":\"rest\",\"w\":11.25,\"x\":205.846625}"},0,"abcjs-rest abcjs-d1 abcjs-l0 abcjs-m1 abcjs-v1 abcjs-n0 abcjs-note_selected",{"line":0,"voice":1,"measure":1},0]}
10:59:38
console
analyse CA3 __Z12doubleValuesPfi 1,2,3,4
logger	console
extra	{"arguments":["analyse","CA3","__Z12doubleValuesPfi",[1,2,3,4]]}
10:59:38
ui.click
body > div#abc > svg
10:59:39
ui.click
body
10:59:40
console
[object Object]
logger	console
extra	{"arguments":[{"type":"RESULT","modName":"CA3","data":"[2,4,6,8]","funcName":"__Z12doubleValuesPfi"}]}
10:59:40
console
analyse CA3 __Z12doubleValuesPfi 1,2,3,4
logger	console
extra	{"arguments":["analyse","CA3","__Z12doubleValuesPfi",[1,2,3,4]]}
10:59:40
ui.click
img#note_ci
10:59:42
console
[object Object]
logger	console
extra	{"arguments":[{"type":"RESULT","modName":"CA3","data":"[2,4,6,8]","funcName":"__Z12doubleValuesPfi"}]}
10:59:43
ui.click
body > div#toolbar
10:59:43
console
analyse CA3 __Z12doubleValuesPfi 1,2,3,4
logger	console
extra	{"arguments":["analyse","CA3","__Z12doubleValuesPfi",[1,2,3,4]]}
10:59:43
ui.click
a#undo.btn.btn-outline-white.p-1[title="Undo<br>(shortcut Ctrl+Z)"] > img#undoi
10:59:44
console
Click [object Object] 0 abcjs-rest abcjs-d1 abcjs-l0 abcjs-m0 abcjs-v1 abcjs-n0 abcjs-note_selected [object Object] undefined
logger	console
extra	{"arguments":["Click",{"el_type":"note","startChar":183,"endChar":186,"rest":"{\"type\":\"whole\"}","minpitch":7,"duration":1,"maxpitch":7,"averagepitch":7,"abselem":"{\"abcelem\":\"[Object]\",\"bottom\":6.396129032258065,\"children\":\"[Array]\",\"duration\":1,\"durationClass\":1,\"elemset\":\"[Array]\",\"extra\":\"[Array]\",\"extraw\":0,\"heads\":\"[Array]\",\"invisible\":false,\"minspacing\":1,\"right\":\"[Array]\",\"specialY\":\"[Object]\",\"top\":7.603870967741935,\"tuneNumber\":0,\"type\":\"rest\",\"w\":11.25,\"x\":125.370875}"},0,"abcjs-rest abcjs-d1 abcjs-l0 abcjs-m0 abcjs-v1 abcjs-n0 abcjs-note_selected",{"line":0,"voice":1,"measure":0},"[undefined]"]}
10:59:44
console
analyse CA3 __Z12doubleValuesPfi 1,2,3,4
logger	console
extra	{"arguments":["analyse","CA3","__Z12doubleValuesPfi",[1,2,3,4]]}
10:59:44
ui.click
body > div#abc > svg
10:59:45
console
[object Object]
logger	console
extra	{"arguments":[{"type":"RESULT","modName":"CA3","data":"[2,4,6,8]","funcName":"__Z12doubleValuesPfi"}]}
10:59:45
console
analyse CA3 __Z12doubleValuesPfi 1,2,3,4
logger	console
extra	{"arguments":["analyse","CA3","__Z12doubleValuesPfi",[1,2,3,4]]}
10:59:45
ui.click
img#note_ci
10:59:48
console
[object Object]
logger	console
extra	{"arguments":[{"type":"RESULT","modName":"CA3","data":"[2,4,6,8]","funcName":"__Z12doubleValuesPfi"}]}
10:59:49
console
[object Object]
logger	console
extra	{"arguments":[{"type":"RESULT","modName":"CA3","data":"[2,4,6,8]","funcName":"__Z12doubleValuesPfi"}]}
10:59:52
ui.click
img#playi
10:59:53
ui.click
img#playi
10:59:54
exception
TypeError: soundsCache[note.instrument][noteName].getChannelData is not a function
```

</details>

**Comment by rualark** [comment]
Analysis of current abcjs synth:
Played with abcjs synth:
![image](https://user-images.githubusercontent.com/15198808/82764612-c6353180-9e18-11ea-8f95-0f284532aeb7.png)
![image](https://user-images.githubusercontent.com/15198808/82764683-45c30080-9e19-11ea-9302-0dd4fb9382b0.png)

Played with NI Gentleman:
![image](https://user-images.githubusercontent.com/15198808/82764654-0d232700-9e19-11ea-9902-2910313f7cd0.png)
![image](https://user-images.githubusercontent.com/15198808/82764669-29bf5f00-9e19-11ea-9652-8b3ac7a213a6.png)

Sound here: https://audiomack.com/rualark/playlist/abcjs-sound-comparison

**Comment by moonwave99** [comment]
I am facing the same issue - basically:

- `renderMidi` sounds way cleaner than synth;
- there is no way to retrieve the played pitches through the midi API, so for visualisation purposes I cannot use it.

[Chrome v83.0.4103.97 on OS X - abcjs v6-beta10]

What is the current status of this? Is there anything I can do in order to help you?

[thank you so much for working on this wonderful library btw!]

**Comment by paulrosen** [comment]
I think there are two problems, but when those are solved we'll see if there is more.

First, I'd like to improve the soundfont, at least for piano - that seems to be the one that can naturally sound good with midi. I'm investigating that now. If you can find a sound font where the individual notes can be split into a separate files I will incorporate that.

Second, I have an idea of something I can do when creating the sound buffers to improve it. I will do an experiment this weekend to see if that helps.

**Comment by rualark** [comment]
What is the problem with buffers?

**Comment by paulrosen** [comment]
I am doing a very simple addition to get two notes into a buffer if they are in the same voice. I am going to experiment with not doing any of my own calculations and create as many channels as needed to keep all the notes separate.

**Comment by rualark** [comment]
Playback is very much improved as of today
