### ISSUE TITLE
Annotations drawn over note beams

### ISSUE THREAD

**Issue by dvdrndlph** [paulrosen/abcjs#31]
Thanks for developing this incredibly useful library.

In the following ABC, annotations in the bass line are obscured by the beams.

X:1
T:Onnotations
L:1/16
M:2/4
K:C
V:1 treble
V:2 bass
V:1
z +4+CDE F2G"_4"F, | +5+G2c2 B2c2 | dGAB cABG | d2g2 f2g2 | eagf egfa | %5
V:2
z8 | z "_1"C,"_3"D,E, F,"_3"D,"_5"E,C, | +5+G,2G,,2 z4 | z G,A,B, CA,B,G, | C2B,2 C2D2 | %5

It seems that ABCJS is good at missing the note heads with annotations, but not always the stems and beams.

**Comment by paulrosen** [comment]
I guess you are referring to the second measure in the second line? I'm not
seeing it overlap. I'm not sure what is different between our setup. I
assume you are using the latest version of abcjs? Is there a public URL
where you can show me that problem?

On Fri, Apr 24, 2015 at 9:32 AM, David Randolph <notifications@github.com>
wrote:

> Thanks for developing this incredibly useful library.
>
> In the following ABC, annotations in the bass line are obscured by the
> beams.
>
> X:1
> T:Onnotations
> L:1/16
> M:2/4
> K:C
> V:1 treble
> V:2 bass
> V:1
> z +4+CDE F2G"_4"F, | +5+G2c2 B2c2 | dGAB cABG | d2g2 f2g2 | eagf egfa | %5
> V:2
> z8 | z "_1"C,"_3"D,E, F,"_3"D,"_5"E,C, | +5+G,2G,,2 z4 | z G,A,B, CA,B,G,
> | C2B,2 C2D2 | %5
>
> It seems that ABCJS is good at missing the note heads with annotations,
> but not always the stems and beams.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulrosen/abcjs/issues/31>.
>



-- 
Paul Rosen
Performant Software Solutions, LLC

**Comment by dvdrndlph** [comment]
Yes, the second measure in the bass clef line shows the problem. I see it if I paste this abc into http://abcjs.net/abcjs-editor.html. The annotations print right over the beams.

**Comment by dvdrndlph** [comment]
The demo editor is using abcjs_editor_1.10-min.js. It could be that this problem is fixed in the latest version. I will confirm.

**Comment by dvdrndlph** [comment]
With version 2.0, the original ABC renders fine.

However, this ABC shows the problem:

X:1
T:Onnotations
L:1/16
M:2/4
K:C
V:1 treble
V:2 bass
V:1
z +4+CDE F2G"_4"F, | +5+G2"^3"c2 B2c2 | dGAB cABG | d2g2 f2g2 | eagf egfa | %5
V:2
z8 | z "_1"C,"_3"D,E, F,"_3"D,"_5"E,C, | "^5"G,2+3+G,,2 z4 | z G,A,B, CA,B,G, | C2B,2 C2D2 | %5

**Comment by paulrosen** [comment]
The beta version that I posted takes care of this problem, too. It will be in version 2.1.

**Comment by dvdrndlph** [comment]
You are the man. Thanks.
