### ISSUE TITLE
In bass-8 clef, "8" should be printed below clef, but not below staves

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#311]
When printed below staves, it is visually not associated with clef and looks like some text.

Abcjs:

![image](https://user-images.githubusercontent.com/15198808/72671065-f5e0c100-3a55-11ea-8db3-f335ca660812.png)

Examples from common notation software:

![image](https://user-images.githubusercontent.com/15198808/72671056-e06b9700-3a55-11ea-840d-0c5f6a3dbfd0.png)

**Comment by paulrosen** [comment]
Will be fixed in next version.
