### ISSUE TITLE
Double flat and noteheads images need a slight improvement

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#312]
Please make double flat symbol closer to a conventional (currently first flat is smaller than the second). Also, there is a white gap in a notehead at high scale.
![image](https://user-images.githubusercontent.com/15198808/72671196-c632b880-3a57-11ea-9eca-2866117ef5eb.png)

Conventional:

![image](https://user-images.githubusercontent.com/15198808/72671210-ea8e9500-3a57-11ea-9904-6be0dd17127f.png)

This is low priority.

**Comment by paulrosen** [comment]
beta.16 contains a better double flat. 

Would you supply some ABC that shows the gap? I don't see the problem. It is possible it was fixed since this was created or it is dependent on something else on the line.

**Comment by rualark** [comment]
I do not see gap in current version
