### ISSUE TITLE
Should we allow user to download abcjs render as PNG?

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#313]
I found some ways to do that using canvg here: https://stackoverflow.com/questions/3975499/convert-svg-to-image-jpeg-png-etc-in-the-browser

Do you think there is a better way?

By the way, why do you use `svg` and not `canvas`?

**Comment by paulrosen** [comment]
I use SVG for the ability to select and move individual elements. You can target stuff with css, for instance. It's pretty flexible.

I guess the reason you want to do this is so users can save and print out the final results? What I've been doing is just taking advantage of the "print preview". Users can "print to PDF".

But to your question - I haven't looked at that so I don't have an opinion.

**Comment by rualark** [comment]
Thanks. I use PDF too. I have already implemented several options for export:
MusicXML, MIDI, PDF, ABC, SVG.

**Comment by yasz** [comment]
> 谢谢。我也用PDF。我已经实现了几个导出选项： MusicXML、MIDI、PDF、ABC、SVG。

can u share this features to this topic ?
