### ISSUE TITLE
How can I just get the data:audio/midi link from renderMidi without creating a div and without requiring user to click a generated link in it

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#314]
There is no convenient place for this div in a visual notation editor design. I use bootstrap and not plain links.

P.S. I actually managed to do that by hiding div, modifying filename and then clicking on an anchor element found by path (not by id, because it does not have one). But it is not a very straightforward solution:

```
<div style='display: none' id="midi-download"></div>
<script>
  let el = $('.abcjs-download-midi > a');
  el.attr('download', filename + '.mid');
  el[0].click();
</script>
```

**Comment by paulrosen** [comment]
This is a similar solution as issue #315 and I'll take care of it at the same time.

**Comment by paulrosen** [comment]
There is a new entry point: `var midi = ABCJS.synth.getMidiFile(abcString, options)`. The options are the same as those passed in to renderAbc and other places. In addition, if you pass `{generateLink: true}` then the return value will be an `<a>` that can be placed on the page. Otherwise the return value is the string that should be sent to the server. (It is encoded.)

**Comment by rualark** [comment]
Hi! This is a good solution if a developer can show a clickable <a> tag to a user and ask user to click it. Programmatically clicking a link does not seem to work in all browsers. There is a cross-browser library, which seems stable in my testings: https://github.com/eligrey/FileSaver.js/

I use it to allow user to download MusicXML, ABC, SVG files and I would probably use it for MIDI files too. I am not completely sure how to pass MIDI filee to it though. Here is how I pass MusicXML:

```
saveAs(new Blob([xml], {type: "text/xml"}), name2filename(nd.name, nd.filename) + '.xml');
```

Here I found an example of passing a MIDI file:

```
var file = new Midi.File();
var track = new Midi.Track();
file.addTrack(track);
track.addNote(0, 'c4', 64);
track.addNote(0, 'd4', 64);
track.addNote(0, 'e4', 64);
track.addNote(0, 'f4', 64);
track.addNote(0, 'g4', 64);
track.addNote(0, 'a4', 64);
track.addNote(0, 'b4', 64);
track.addNote(0, 'c5', 64);
var bytes = file.toBytes()
var blob = new Blob([bytes], {type:'audio/midi'})
saveAs(blob,"music.midi")
```

https://blog.logrocket.com/binary-data-in-the-browser-untangling-an-encoding-mess-with-javascript-typed-arrays-119673c0f1fe/

I think that we can pass MIDI file there if you can return unencoded MIDI file. I also need unencoded file to send it to server. Could you please allow this, for example, by accepting midiOutputFormat: 'binary', 'urlencoded'

**Comment by paulrosen** [comment]
Ok, will add that.

**Comment by rualark** [comment]
Thanks. Actually, I see that current issue is about urlencoded midi link and it is also great!
And this issue is about binary MIDI: https://github.com/paulrosen/abcjs/issues/315
