### ISSUE TITLE
How can I get midi file content from abcjs so that I can send it to server with ajax or XMLHttpRequest?

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#315]

**Comment by paulrosen** [comment]
I'll get you an easy entry point for this when I make the midi available with the new synth. I want to finish the drag-and-drop changes first.

**Comment by paulrosen** [comment]
I changed the option to `midiOutputType` and that can equal `link`, `encoded`, or `binary`. The binary version returns a Uint8Array.

**Comment by rualark** [comment]
Thanks! Why is list returned? What does the index mean?

**Comment by paulrosen** [comment]
I'm not sure what you mean - can you post an example?

**Comment by rualark** [comment]
I mean that to get midi data I have to take first element of the list:
`ABCJS.synth.getMidiFile(abc, {midiOutputType: 'encoded'})[0]`

**Comment by paulrosen** [comment]
I see what you're asking - ABC allows multiple tunes in the same string. So for example:
```
X:1
K:C
cdef|

X:2
K:D
defg|
```
Produces two different tunes.

**Comment by rualark** [comment]
Thanks a lot. I need tempo and dynamics control for further improvement of MIDI output:
https://github.com/paulrosen/abcjs/issues/317
