### ISSUE TITLE
Gradual tempo and dynamics change

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#317]
What is the best way to gradually change tempo and dynamics of playback without adding tempo and dynamics marks to every note?

**Comment by paulrosen** [comment]
There isn't a way currently. There is, however, a back door: if you use the option `{ sequenceCallback: callbackFunction }` you will get the midi sequence just before it is created and you can modify it however you want.

Dynamics and other modifications to the sound is not very far along, unfortunately. It's on my list for someday. A number of those things are probably not hard to do, so I should probably take a pass at them.

**Comment by rualark** [comment]
What do you mean by "is not very far along" ?

**Comment by paulrosen** [comment]
I mean that I pay attention to the pitch and the rhythms, but I've just started trying to think about dynamics and decorations and "swing".

**Comment by rualark** [comment]
For expressive MIDI playback two things are most important:
1. Change velocity of individual notes
2. Add tempo events. If it is difficult to implement changing tempo at arbitrary tick, it is ok to change tempo at least on note starts, although this makes tempo generation logic more difficult.

Could you tell if you are interested in implementing these two things and what approximate time it could take? I was just thinking if this could be done within 1-3 months?

There are many more important techniques to achieve realistic sound, including CC and articulations, but they can already be done in Artinfuser Studio automatically, if MIDI file is sent there: https://artinfuser.com/studio/docs.php?d=re_algorithms

So, I am planning to set dynamics and tempo and then send result to Artinfuser Studio.

**Comment by paulrosen** [comment]
I'm not sure if there is something to be done here - you can set the velocity with the `%%beat` command and you can also use the standard ff, pp, etc and crescendos.

Please reopen if there is still something to do.
