### ISSUE TITLE
Bar numbers collide with clef symbol

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#318]
Bar numbers are too close to clef symbol:
![image](https://user-images.githubusercontent.com/15198808/72748555-9f47c400-3bc8-11ea-84f8-43800e577706.png)

**Comment by paulrosen** [comment]
You are definitely exercising the limits! I haven't seen anyone get up to 3 digit measure numbers before.

Do you think the number should be pushed left or the clef be pushed right? I think the number should be moved.

**Comment by rualark** [comment]
I think, clef should never be moved. This is how it looks in Sibelius:
![image](https://user-images.githubusercontent.com/15198808/72751895-d79fd000-3bd1-11ea-87fc-1e04069244d7.png)
Pushing the number up seems best way if this does not lead to other collisions with what is about the number.

**Comment by rualark** [comment]
Fixed
![image](https://user-images.githubusercontent.com/15198808/73410998-ed6d6d80-4314-11ea-860d-a894ceb2f03b.png)
