### ISSUE TITLE
Parsing classes in click event listener

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#319]
Did you change how classes are passed to event listener? Seems that now they are passed in separate array elements.
Or is this some mode, that I do not intercept?
P.S. I still think that class parsing is a not a good idea to get voice number.

**Comment by paulrosen** [comment]
I probably did that accidentally. I'm definitely not ready to release the master branch yet - I haven't had a chance to polish it up.

And - I'm in the area, I'll provide that info in the callback so you don't have to parse.

**Comment by paulrosen** [comment]
I changed the classes back to being a string for backwards compatibility.
I added a new parameter that contains an object with `{ line: 99, voice: 99, measure: 99 }`. Those are the things in the classes that aren't expressed in the first parameter.

**Comment by rualark** [comment]
> I changed the classes back to being a string for backwards compatibility.
> I added a new parameter that contains an object with `{ line: 99, voice: 99, measure: 99 }`. Those are the things in the classes that aren't expressed in the first parameter.

This works!
