### ISSUE TITLE
Clicking a part name now results in 'cannot read property elemset of null'

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#321]
I'm not sure, but it seems that it started to happen after implementing dragging:

```
Uncaught TypeError: Cannot read property 'elemset' of null
    at EngraverController../src/write/abc_engraver_controller.js.EngraverController.notifySelect (abcjs_basic_5.12.0.js:18238)
    at EngraverController.mouseUp (abcjs_basic_5.12.0.js:18126)
./src/write/abc_engraver_controller.js.EngraverController.notifySelect @ abcjs_basic_5.12.0.js:18238
mouseUp @ abcjs_basic_5.12.0.js:18126
```

```
%%barnumbers 1
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Piano"
V: V1 clef=bass name="Piano"
[V: V0]z4G4e4c4|B4A4G4F4|G8c8-|c4B2A2B8|A8d8-|d4c2B2c4A4|B4g4f4e4|d8A8|G8c8-|c4B2A2B8|c16|z16|
[V: V1]C,16|D,16|E,16|G,16|F,16|A,16|G,16|F,16|E,16|D,16|C,16|z16|
```

![image](https://user-images.githubusercontent.com/15198808/73216391-f9b3c800-4166-11ea-83b3-7ea53bd7344c.png)

**Comment by paulrosen** [comment]
Ok, that happens when the part name is the first thing - shouldn't be hard to fix.

**Comment by rualark** [comment]
Ok. Now when part is clicked there is no error, but voice number is not sent in object.

**Comment by paulrosen** [comment]
That is fixed in master.

Are there any other selection or dragging issues that you have that I've forgotten about? I think there was a jittering sometimes when dragging but other than some clean up, it's close to implemented.

**Comment by rualark** [comment]
Thanks! Yes, currently open issue is jittering.
