### ISSUE TITLE
staccato

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#323]
It appears  to me that the midi rendering does not respect staccato. Staccato notes are played legato. Any idea of a workaround?

**Comment by paulrosen** [comment]
Coming soon! Making the audio more expressive is on my very short list.

**Comment by ThorsenRune** [comment]
Thanks, I think that it could be accomplished in the midi translation as interpreting a staccato note as a half + half a rest!?

**Comment by ThorsenRune** [comment]
Working in version 6
