### ISSUE TITLE
npm dependency issues

### ISSUE THREAD

**Issue by Ksinia** [paulrosen/abcjs#324]
Hello @paulrosen, thank you for the awesome library!

recent abcjs releases available [in npm](https://www.npmjs.com/package/abcjs) have several issues that would be nice to be addressed.

* [5.10.3](https://www.npmjs.com/package/abcjs/v/5.10.3) is fine and has only `midi` as a dependency.
* [5.11.0](https://www.npmjs.com/package/abcjs/v/5.11.0) has `abcjs@5.10.3` as a dependency, which is some kind of misconfiguration and should be fixed.
* [5.12.0](https://www.npmjs.com/package/abcjs/v/5.12.0) has `abcjs@5.11.0` as a dependency, which is some kind of misconfiguration and should be fixed as well. Also, it's available on npm but not in this code [releases](https://github.com/paulrosen/abcjs/releases) which creates a situation of the release on unknown commit without a changelog, and which is available only to npm users.

If something requires clarification, please let me know!

**Comment by paulrosen** [comment]
Thanks for pointing that out - I'll fix that in the next version. Hopefully that won't take too long to get finished.

You can see the changes for 5.12.0 in RELEASE.md

**Comment by Ksinia** [comment]
Thank you! I was looking at https://github.com/paulrosen/abcjs/releases this whole time and it didn't have information about 5.12.0.

**Comment by Ksinia** [comment]
I don't see this error in current master branch, resolving.
