### ISSUE TITLE
midi-instrument-patches usage

### ISSUE THREAD

**Issue by Ksinia** [paulrosen/abcjs#325]
Hello!

Is it possible to use [midi-instrument-patches](https://www.jsdelivr.com/package/npm/midi-instrument-patches) ([github link](https://github.com/yvesgurcan/midi-instrument-patches))? In my opinion, it's piano sound is better than everything available in [this library standard way of loading sounds](https://paulrosen.github.io/midi-js-soundfonts/).

[Here](https://melodic-dictation.netlify.com/melody) is the demo of the current sound of this music pack, I have a version with midi-instrument-patches and abcjs Synth player side-by-side but it's not deployed. If that's necessary, I can build a demo of it somewhere on JSFiddle.

**Comment by paulrosen** [comment]
I would definitely be interested in exploring that, but unfortunately that project doesn't have a readme file. Do you know if there is documentation for it?

**Comment by Ksinia** [comment]
I've created an issue about it, I hope together with the author of the repo we'll be able to figure out how to make this sound available to abcjs users as well.

**Comment by yvesgurcan** [comment]
Hi @paulrosen and @Ksinia! Thank you for your interest in the MIDI patches. Currently, they are used with a library called `web-midi-player` (https://github.com/yvesgurcan/web-midi-player). Essentially, these files are loaded by a script that uses a version of `libtimidity` converted to JavaScript thanks to Web Assembly. Would that approach be compatible with `abcjs`?

**Comment by paulrosen** [comment]
Well, I don't think it would be easy to import the patch files directly, unless they are a standard music file format. However, I got the latest ABCJS to work with web-midi-player! 

Unfortunately, that version is not quite ready for release, but if you want to play with it, you can clone this project and type `npm run build:basic`. When I finish debugging, this will be in the next release.

I took the javascript example in the web-midi-player repo and added this:
```
        <script src="./src/abcjs_basic_5.12.0.js"></script>
        <script>
            function playAbcjs() {
                var abc = "X:1\nL:1/4\nK:C\ncdef|cdef|";
                var visualObj = ABCJS.renderAbc("paper", abc);
                var midi = ABCJS.synth.getMidiFile(abc, {midiOutputType: "binary"});
                var status = midiPlayer.play({ arrayBuffer: midi[0] });
                console.log("midiPlayer status: ", status);
            }
        </script>
```
Add added these two elements:
```
<div id="paper"></div>
<button onclick="playAbcjs()">Play ABCJS</button>
```
I haven't tested it anywhere but my mac in Chrome, though, so YMMV.

**Comment by yvesgurcan** [comment]
This is great! I'm so glad you were able to use the `arrayBuffer` input to play the object generated by your library.

I'm not quite sure about the file format of the pat files but I'm happy to look into it. What would be the expected standard?

Also, out of curiosity, is there a plan to enable ABCjs to generate music sheets out of MIDI files? I would love to highlight such a feature :)

**Comment by paulrosen** [comment]
As long as I can understand the format it might be ok - WAV files are directly loadable, but large. It looks like MP3 is translated by all browsers that are likely to be able to support everything. I haven't had to look into other formats. For instance, if there were a javascript way to turn the pat files into wav buffers that would work.

BUT: I'm not sure that is the problem. I have an idea of how to make the abcjs sound much better with the existing sound fonts. I just need a little free time to explore it.

**Comment by paulrosen** [comment]
And, generating sheet music from midi is more complicated than you would think. I would love to have that but it would be a large effort and a lot of understanding of music theory. For instance if I saw note 61, should I call it C# or Db? How do I determine what key signature to use? How do I determine the time signature if the volume of the notes are all the same? If the midi were created by a human at a keyboard, the timing won't be perfect so there needs to be a way to not notate 1/16th notes, for instance.

**Comment by yvesgurcan** [comment]
I don't know if there's a way to turn the `.pat` files into WAVE buffers. I know that these files are specific to Timidity and that Timidity itself generates WAVE buffers out of `.mid` files thanks to these `.pat` files, which is different. Hope it helps!

**Comment by Ksinia** [comment]
> I took the javascript example in the web-midi-player repo and added this:

To clarify, I am already using abcjs for the notes render and web-midi-player for playing the sounds in a way you pointed out. It's not a problem at all to connect the output of abcjs with web-midi-player.

I would be happier by using just a single tool for everything (abcjs) but I am not satisfied with the sound quality, and with web-midi-player, I'm restricted with the fact that it [doesn't work under Safari](https://github.com/yvesgurcan/web-midi-player/issues/135#issuecomment-579267297): now I see that [abcjs works but only on two clicks](https://github.com/paulrosen/abcjs/issues/328) and doesn't work on mobile Safari at all for me, for reasons I haven't yet identified.

**Comment by paulrosen** [comment]
I'm currently working on the sound quality and the Safari 13 issues.

**Comment by paulrosen** [comment]
If you are able to run the latest code (newer than the released version) you will hear a much better output. I'm still working to improve it more, but it already is getting there.

**Comment by Ksinia** [comment]
Github master version is broken for me in Safari: I see mp3 files loading on first click (same as before), but the sound never plays on no matter how many clicks. In Chrome it plays but with bad quality.

[The code I use for play](https://github.com/Ksinia/melodic-dictation-client/blob/c02f8210e1bc9d881109abe5b88e6e29ed38a8a3/src/components/MelodyListContainer.js#L11-L27) (without `soundFontUrl` property when I was testing GitHub master version).

**Comment by paulrosen** [comment]
I'll mock up a simple app with that code and see what I get.

**Comment by Ksinia** [comment]
Resolving in favor of #328, as a solution from [this comment](https://github.com/paulrosen/abcjs/issues/325#issuecomment-580671066) works well for me.
