### ISSUE TITLE
Two voices on the same staff

### ISSUE THREAD

**Issue by Garchbold** [paulrosen/abcjs#329]
I am trying to make a voice module that supports SATB, but I am having trouble getting it to render on two staves.

Here is an example of the notation I am trying to render:
X:1
L:1/4
M:3/4
K:Eb
%%staves {S A T B}
V:S treble up
c ^B c || 
V:A treble down
E ^D E || 
V:T bass up
E, F, E, || 
V:B bass down
A,, A,, A,, || 

This is what I am getting:
<img width="265" alt="Screen Shot 2020-02-05 at 1 31 49 PM" src="https://user-images.githubusercontent.com/15057944/73885117-13ff3d00-481c-11ea-897b-adb686d49e4f.png">

I was wondering if there was a way to render it as such:
<img width="360" alt="Screen Shot 2020-02-05 at 1 33 04 PM" src="https://user-images.githubusercontent.com/15057944/73885145-24171c80-481c-11ea-9a58-6a978f4e6eb2.png">

where the stem direction signifies which voice rather than needing a new staff for each voices

**Comment by paulrosen** [comment]
Change this line:
```
%%staves {(S A) (T B)}
```
(Notice the parentheses.)

**Comment by Garchbold** [comment]
Amazing, exactly what I needed! Thanks for the prompt response Paul. Love this library btw!
