### ISSUE TITLE
Please allow to disable frame selecting clicked note

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#330]
If we do not show frame selection, are we losing some important visualization? To my knowledge so far, it seems to be only additional information, which can be beneficial only in specific scenarios.

Selecting note with frame and color at the same time looks a little bit cluttered, or is this needed?

On mobile it hides part of note and has uncontrolled color:
![image](https://user-images.githubusercontent.com/15198808/74093530-185d7b80-4ae4-11ea-8874-6909be259e4e.png)

**Comment by paulrosen** [comment]
If you want, you can use `outline: none` in css to hide that. 

Having some indication of what is focused is essential for accessibility - if the user only uses the keyboard then they wouldn't know where they are. You can do lots of different styling options to make it look better, or you can use different styling if you detected a mouse click versus a keyboard event.

**Comment by rualark** [comment]
Where do I put it in CSS? I tried adding to div:
```
<div style='outline: none' id='abc'>
```

**Comment by paulrosen** [comment]
This is just off the top of my head, but something like this:
```
<style>
path:focus, text:focus, g:focus {
  outline: none;
}
</style>
```
BUT - don't do that exactly. You are messing up your keyboard only users. There's a lot of resources about a11y and focus styles if you google for it.

**Comment by rualark** [comment]
Let me explain in more details. I think that highlighting selected note is very important. It is already done with fill-highlighting. But there is also frame highlighting, when a frame is drawn around the note. This frame is not needed - highlighting note seems enough. When user uses keyboard, highlighting with fill highliting is used, which is enough: why do we also need to draw a frame? I worked in several notation editors and not a single editor uses frame highlighting, all fill-highlight the note. Fill highlighting looks ok. Frame highlighting hides part of note, looks cluttered and over-detailed.
