### ISSUE TITLE
Demo editor renders notes too close to each other

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#331]
![image](https://user-images.githubusercontent.com/15198808/74093625-adad3f80-4ae5-11ea-9db9-746b3d7c07dc.png)

```
%%barnumbers 1
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Piano"
V: V1 clef=bass name="Piano"
[V: V0]z4G4e4c4|B4A4G4F4|G8c8-|c4B2A2B8|A8d8-|d4c2B2c4A4|B4g4f4e4|d8A8|G8c8-|c4B2A2B8|c16|z16|
[V: V1]C,16|D,16|E,16|G,16|F,16|A,16|G,16|F,16|E,16|D,16|C,16|z16|
```

**Comment by paulrosen** [comment]
If you have more notes than will fit on a line, you can add `%%staffwidth 1000` or something to make the line longer. It will always try to lay the music out as best it can.

**Comment by rualark** [comment]
Ok. I just thought that notes should never get that close to each other on demo editorpage.
