### ISSUE TITLE
Three-line part name is needed for analysis

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#332]
Additional information has to be shown in part name for analysis. Can we support newline in part name with `\n` or newline itself?

![image](https://user-images.githubusercontent.com/15198808/74093657-f8c75280-4ae5-11ea-901c-00343d6d9e44.png)

Without that it will take too much space on mobile:
![image](https://user-images.githubusercontent.com/15198808/74107172-835b9080-4b7e-11ea-95f2-1facb52e84f4.png)

**Comment by paulrosen** [comment]
That's a good idea. I think it should accept the "\n" to do a new line. I'll put it on the bug list.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.13

**Comment by rualark** [comment]
Thanks a lot! It works. Can we align it a little bit better?
https://i.imgur.com/BaaRlsG.png

**Comment by paulrosen** [comment]
For space between lines, I'm deferring to the font. That is what it reports. But it could be settable.

**Comment by rualark** [comment]
How to set it?
