### ISSUE TITLE
Can we center note text exactly at the center of note head?

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#333]
![image](https://user-images.githubusercontent.com/15198808/74094025-9cffc800-4aeb-11ea-985e-f58a8f3bd3d3.png)

```
%%barnumbers 1
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Sop."
V: V1 clef=treble name="Alt."
V: V2 clef=treble-8 name="Ten."
V: V3 clef=bass name="Bas."
[V: V0]C16|D16|^"???"E16|C16|z16|
[V: V1]z16|z16|z16|z16|z16|
[V: V2]z16|z16|z16|z16|z16|
[V: V3]z16|z16|z16|z16|z16|
```

Should be:
![image](https://user-images.githubusercontent.com/15198808/74094043-e223fa00-4aeb-11ea-9857-8915ee26339c.png)

**Comment by paulrosen** [comment]
This item is pretty old and I think some of this has changed - if you do the chord notation `"Cm7"C` then it should be centered. If you do the annotation notation `"^Cm7"C` it should be left justified and the length of the annotation doesn't affect the x-coordinate.

I do see that the chord notation is not quite centered and I'll look into that.

**Comment by rualark** [comment]
It looks like this issue can be moved into ⬇️ low priority queue: most important problems were fixed.
