### ISSUE TITLE
Questions on Scrolling music during animation

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#337]
Hi Paul

Please can you give me some suggestions on the best way to realize the following during a music animation:
I would like to have a fixed area (frame) on the page containing just one or two lines of score (let's say 2 measures per line) , while the music to be played is longer (let's say 20 measures); my goal is  making the measures will scroll inside the frame horizontally or vertically, following tha animation cursor.
Is it possible? I saw some parameters like ViewportHorizontal /Scrollhorizontal in Visual configurator but I was not able to produce what I need.
Also I saw the lineEndCallback that should be useful for me ("it can be used to scroll the page at the right time") but I don't know if and how can I move and center the score svg within the frame .

Please can you give some suggestions on the direction I should take and how I can reach my goal ?

Thank you so much in advance for any help you can provide
Osvaldo

**Comment by paulrosen** [comment]
I do that exact thing by using the lineEndCallback. If you already are using the timingCallbacks object it is pretty easy to get that callback. The object that is passed in contains `top` and `bottom`. Find the element that is the immediate parent of the SVG. Set the `margin-top` of that to put the music where you want. I also use `transition: margin-top .3s ease 0s;` on that element to make the music scroll smoothly.

**Comment by osvi64** [comment]
Hi Paul
Thank you for your answer but I need additional support as I'm at beginner level in Web programming.
I created the Endline callback function and it works; if I understood correctly I should put a NEGATIVE value (calculating it based on the top / bottom values of the info object) in the margin-top property of the element paper that contains the results of the renderAbc function call. I did it manually through dev tools on Chrome and it works but  ....  I have problems in doing it via js inside the Endline callback function. Please can you provide me an example including the transition animation, so I can use it inside the Callback function?

Also I have a problem in fixing the height of the paper element: if I put more lines in the abc string they are all displayed as the paper element grows in height, while I would like to display only two lines. I tried with css height property but without success at the moment

Thank you again 
Osvaldo

**Comment by paulrosen** [comment]
You might need `overflow: hidden` too. I can't tell without debugging what you have. If you go into your dev tools and set the following properties on the div that is the direct parent of the SVG, you should see a scroll:
```
    overflow: hidden;
    margin-top: -70px;
    height: 300px;
```
Then it is just a math problem to scroll the right amount. 

Also, when you get the event that the music has stopped, remove margin-top to go back to the top.

**Comment by osvi64** [comment]
Hi Paul
I was able to do something working, but I realize that is too much difficult for me to calculate the right shifting with responsive layout, as the callback event pass the original dimensions and not the resized ones.

So i'm now investigating in another direction: just one long line and scrolling horizontally. Scrolling is  working but I have an issue with rendered score: if I remove the newline on the abc string or if I don't use the WRAP parameter, I obtain a very compressed score (notes closed to each other).
I don't understand why. I went the the configurator page and I removed the newline in the abc string example; result: the notes are rendered with normal spacing. But in my page they are rendered "compressed".
What am I doing wrong?
Below you can find the screen shot of the 2 situation. The first is the score rendered compressed, the second is with wrap params. (the same I have if I put manually \n in the abc string)

Thank you Osvaldo

![image](https://user-images.githubusercontent.com/29627488/74368380-d37f6080-4dd3-11ea-9f2f-c9df5bf99aaa.png)


![image](https://user-images.githubusercontent.com/29627488/74368299-aa5ed000-4dd3-11ea-933b-106fd1d11a0f.png)

Thank you

**Comment by paulrosen** [comment]
You need to add the { staffwidth: 2000 } parameter. By default the staff width is 700 and if the minumum size of the music is larger than that then it takes out all space between notes and extends it. You'll have to play with the number you set the staff width to figure out what works. What you might do is see what the width of the SVG is for a typical piece and double it.

**Comment by chrisspen** [comment]
> I do that exact thing by using the lineEndCallback. If you already are using the timingCallbacks object it is pretty easy to get that callback. The object that is passed in contains `top` and `bottom`. Find the element that is the immediate parent of the SVG. Set the `margin-top` of that to put the music where you want. I also use `transition: margin-top .3s ease 0s;` on that element to make the music scroll smoothly.

Is there more to it? I'm trying to scroll the display leftwards, and it's not quite working.

I've successfully setup the animation listener and I'm retrieving "left" attribute from event, and then I'm setting the svg element's marginLeft to the negative of that value. That causes the display to scroll left, but not enough. Eventually, after 4 or 5 measures, the current note being played is off the screen. If the event's "left" attribute isn't it's left offset relative to its position inside the svg element, then what is it?

**Comment by paulrosen** [comment]
I would have to debug to see. That should have worked. Do you have any css transforms on the SVG that might affect it?

**Comment by chrisspen** [comment]
The problem was I had scale set. Multiplying the offset by the scale fixed the issue.

**Comment by paulrosen** [comment]
Thanks for the report - it sounds like that's a bug. If you don't mind, would you post a sample ABC string and the exact command you are using to call `renderAbc`?

**Comment by chrisspen** [comment]
No, that's just it, I'm saying it's not a bug. I was trying to shift the sheet music based on which note was currently playing, but I incorrectly assumed the offset inside the svg element was the same outside the svg element. I had to translate that from local to global coordinates by multiplying it by the scale.
