### ISSUE TITLE
Prevent text from being highlighted when note is clicked

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#338]
One of approaches to show mistakes in music is to use colored text (red or yellow) above and below staff: colored text above text can show melodic mistakes, while colored text below staff can show harmonic mistakes. Both these texts should never change their color when being clicked so that user always sees the color of mistake. User should be able to click text above, note or text below - in all three cases only note should be highlighted. Currently all three are highlighted when any of three is clicked. How can it be implemented?

![image](https://user-images.githubusercontent.com/15198808/74190412-6220a000-4c63-11ea-91d0-012608292eb4.png)

**Comment by paulrosen** [comment]
You could target that in css with:
```
.abcjs-annotation.abcjs-note_selected {
  fill: #000000;
}
```
How are you setting the error colors to begin with? Are you adding an extra class after the SVG is drawn? That's what I'd do.

**Comment by rualark** [comment]
Well, I actually did not understand how to highlight text yet: https://github.com/paulrosen/abcjs/issues/290#issuecomment-583852823

**Comment by paulrosen** [comment]
I think this is answered. Please reopen if not.
