### ISSUE TITLE
How to prevent gaps between notes with long text

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#339]
Is there a way to span text along multiple notes (when they do not have their own text)? Currently long text creates gaps between notes (VII4/3):

![image](https://user-images.githubusercontent.com/15198808/74191152-600b1100-4c64-11ea-90d4-84460f54901c.png)

```
%%barnumbers 1
M:4/4
K:F
L:1/16
V: V0 clef=treble name="SOPRANO [Sop.] (c.f.)"
V: V1 clef=treble name="ALTO"
V: V2 clef=treble-8 name="TENOR [Ten.] (sp. 3)"
V: V3 clef=bass name="BASS"
[V: V0]f16|d16|"^!"c16|A16|B16|d16|c16|A16|G16|F16|
[V: V1]z16|z16|z16|z16|z16|z16|z16|z16|z16|z16|
[V: V2]"_I"z4F4G4A4|"^?""_VII4/3"B4c4d4e4|"_V"c4"^?"g4a4"^?"g4|"_I"f4e4d4c4|"_II"B4"^?"A4G4A4|"_II"B4"^?"G4g4f4|"_V"e4d4e4c4|"_VI"d4f4g4f4|"_V"e4d4c4e4|"_I"f16|
[V: V3]z16|z16|z16|z16|z16|z16|z16|z16|z16|z16|
```

**Comment by paulrosen** [comment]
Yes, that is on my list. It's complicated to do in a generic way because I then have to see if the next note would intersect it.

**Comment by rualark** [comment]
There is another complication: long text should not intersect with next text.

**Comment by chrisfargen** [comment]
In your music, the measure `"^?" "_VII4/3" B4c4d4e4` looks like this:
![2020-06-13-125637_157x156_scrot](https://user-images.githubusercontent.com/2993720/84574701-3418ad00-ad76-11ea-9860-ad4d103f4ee2.png)

You can change this to `"^?" "_VII4/3" x16 & B4c4d4e4` to yield this:
![2020-06-13-130143_110x162_scrot](https://user-images.githubusercontent.com/2993720/84574773-cb7e0000-ad76-11ea-82bb-894718bc357a.png)

This solution uses voice overlay feature `&` with invisible rest symbol `x`. Set `x` duration to one full measure (`x16` when `L:1/16`, `x8` when `L:1/8`, etc.). Place your annotations to the left of `x16`. The text annotations can then apply to the invisible rest. Even though the `x` rest is invisible, the entire width of that measure is reserved for whatever text you apply to it.

Note: you can also use spacing symbol `y`, but this may cause audio playback to malfunction.

**Comment by paulrosen** [comment]
The next version will improve the spacing of this. The code in the main branch currently doesn't change the spacing for annotations, but I am still working on making sure there are no collisions.

**Comment by rualark** [comment]
> x16 &

Thanks, this is an interesting solution. Improvement of spacing in abcjs would be the best, because this way algorithm does not need to think about the length of text when generating abc notation. But also I am interested in understanding abcjs notation better.

It seems that this solution works only for whole-measure text. I tried to change to x8, but it was a mess, or am I doing something wrong?

**Comment by paulrosen** [comment]
The overlay creates a separate voice and different voices need to have the same number of beats in a measure to be lined up correctly. You should be able to use two x8.

But in any case, let me know if the new version looks better to you and keep you from having to do this hack.

**Comment by rualark** [comment]
Ok, lets look at the new version:

```
%%barnumbers 1
M:4/4
K:Bb
L:1/16
V: V0 clef=treble name="Alt."
V: V1 clef=bass name="Bas."
[V: V0]z4D4E4F4|G8C8-|C2D1A1D4B,4C4|"^Bb"D2"^A (major)"^C1"^F"F1"^Bb"D2"^Gm"G2"^Dm"F4"^Bb"F4|F4G2F2E4c4|B4D4E4F4|G8D4=E4|^F4G4=E4^F4|G16|
[V: V1]G,,16|E,16|"_Long text"D,2D,1A,,1B,,4z8|_B,,2A,,2B,,4D,4B,,4|C,16|D,16|B,,16|A,,16|G,,16|
```

6.0.0 beta.9 looks like this:
![image](https://user-images.githubusercontent.com/15198808/85211043-06230200-b34e-11ea-804e-110c19198dad.png)

6.0.0 beta.10 and beta.12 look like this:
![image](https://user-images.githubusercontent.com/15198808/85211064-2eaafc00-b34e-11ea-86e8-1d84197c5d70.png)

It seems that we need to calculate text box boundaries and detect overlaps with other text and objects.

**Comment by paulrosen** [comment]
Agreed. It isn't trivial, though. I'm working on it. Hopefully next week.

**Comment by rualark** [comment]
Is this spacing considered to be ok? It seems that staffs could be a little closer?
![image](https://user-images.githubusercontent.com/15198808/87256047-577b6880-c498-11ea-87aa-3b233e28ac8e.png)

```
%%barnumbers 1
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Part 1\n[Sop.]\n(sp. 1)"
V: V1 clef=bass name="Part 2\n[Bas.]\n(c.f.)"
[V: V0]c16|B16|G16|e16|c16|d16|G16|B16|c16|
[V: V1]"_I"C,16|"_VII6"D,16|"_III"E,16|"_III6"G,16|"_VI"A,16|"_II6"F,16|"_III"E,16|"_VII6"D,16|"_I"C,16|

```

**Comment by paulrosen** [comment]
It does seem like there is extra spacing there. I'll soon have a "debug" mode that puts lines in that explains why things are where they are.

**Comment by rualark** [comment]
I see that there are much less overlaps in 6.0.0.15, but still there are:
![image](https://user-images.githubusercontent.com/15198808/91233628-4e89e200-e73a-11ea-90cf-cba0d5bf1a75.png)


```
%%barnumbers 1
Q:1/4=140
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Piano\n[Sop.]\n(sp. 5)"
V: V1 clef=bass name="Piano\n[Bas.]\n(c.f.)"
[V: V0]z4^^G4e4c4|B4A4=G4F4|G8c8-|c4"^!"B12-|"^?"B12"^?"z4|"^?"e4A2"^?"G2B4A4|"^!""^asdflkjqwer lqejr wqoieur qwoieru qowiuer"F4f4"^!""^asdflkjqwero"a4"^qwersdkfj hsakdfjh qwkr"D4|"^!""^wqoeriu qweroiu"A,8"^!"g8|"^!"B,8"^?"f8|"^?"G4"^!"f2"^!"G2"^!""^asdfoiuqwer qwer"c8|"^?"c'16|z16|
[V: V1]"^?"C,16|D,16|E,16|G,16|"^!"F,16|"^!"A,16|"^!"G,16|"^!"F,16|"^!"E,16|"^!"D,16|C,16|z16|

```

Probably, these overlaps will be rare, as they require a lot of text, but they are possible.

**Comment by paulrosen** [comment]
I only defined two lanes for the annotations but it looks like you need more. I'll work on it more.

**Comment by rualark** [comment]
Thanks a lot!

I also noticed that "overlap detection" does not work for text that is below staff like "_text". Could you please add this? Example:

```
%%barnumbers 1
Q:1/4=140
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Sop."
[V: V0]"_?"c4B4d4e4|"^?""_?""^⛔"E4A4"^✅"B4e4|"_?"G4A4d4e4|"_VII"B4A4G4F4|"_VI6/4""^✅"E4A4B4A4|"_II"a4g4f4d4|"_I"c4B4A4"_asdfaasdf"G4|"_VI6/4""^✅"E4A4B4c4|"_II6/4"A4B4c4d4|"_III6/4"B4e4d4e4|"^?""_VI6/4""^⚠️"E4A4B4c4|"_?"A4B4d4e4|"^?""_VI6/4""^✅"E4A4B4"^✅"c4|"_VI4/3"A4G4"^✅"E4A4|"_III6""^✅"B4e4G4B4|"_VI4/2""^✅"A4"^?""^⚠️"G4"_II"D8|"_I"C16|
```

**Comment by paulrosen** [comment]
fixed in beta.16

**Comment by rualark** [comment]
Currently looks like this (text overlaps with each other, lyrics overlap with notes):
![image](https://user-images.githubusercontent.com/15198808/92693998-0af4c200-f34f-11ea-92f3-7a94dae2482e.png)

**Comment by rualark** [comment]
I think, current approach to text is good. But lyrics should work in a different way:
1. First lyrics (first "_text" for this note) should always be on one line, no matter what. Second lyrics (second "_text") should always be on one line too. And so on.
2. Lyrics should span multiple notes until it starts to overlap with next lyric of the same lane. When overlap is detected, lyrics should not be moved to another lane. Instead, notes should be moved forward and gap between notes should be increased.

**Comment by rualark** [comment]
Text above looks better now, although it is cut on the right.
![image](https://user-images.githubusercontent.com/15198808/92695236-da158c80-f350-11ea-8e17-92baa04eee8d.png)

**Comment by rualark** [comment]
Also, text rows now collide:
![image](https://user-images.githubusercontent.com/15198808/93031966-636ddd00-f637-11ea-9f78-3d0e26c04442.png)
```
%%barnumbers 1
Q:1/4=140
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Sop.\n(sp. 5)"
V: V1 clef=bass name="Bas.\n(sp. 5)"
[V: V0]"^🚩""^C - I"G8"^🚩"e8|"^⚠️"c8G8|"^⚠️""^Dm"F8"^F"A8|"^⚠️""^G - V"G16|"^Am"C8"^ø"D8|"^⚠️""^Em"E8G8|"^🚩""^F"F8"^⚠️"A,8|"^🚩""^G"B,16|"^🚩"G8"^🚩"e8|"^⚠️"c8G8|"^⚠️"F8A8|"^🚩"G16|"^🚩""^Am"C8"^ø""^⚠️"B,8|"^⚠️"C8"^⚠️"G,8|"^Dm  G"D16|"^⚠️""^C"C16|
[V: V1]"_I"C,16|"^⚠️""_I6"E,16|"_II"D,8F,8|"_V"G,16|"^⚠️""_VI"A,16|"_III"G,8E,8|"^⚠️""_II"D,8F,8|"^🚩""_V"G,8"^🚩"G,,8|"^⚠️""_I"C,16|"_I6"E,8G,8|"^⚠️""_IV"A,8F,8|"^⚠️""_V6"G,8B,,8|"^⚠️""_I"C,8"^ø"D,8|"_I6"E,16|"_II6"F,8"_V"G,8|"_I"C,16|

```

**Comment by rualark** [comment]
I suppose that this issue should move to low priority ⬇️ because most important parts of it have been fixed (except cutting text on the right).

**Comment by paulrosen** [comment]
I think most of these issues were handled - any remaining should be made an issue by itself.
