### ISSUE TITLE
Voice overlay

### ISSUE THREAD

**Issue by dvdrndlph** [paulrosen/abcjs#34]
This is really a feature request. Section 7.4 in 2.1 ABC standard, which allows additional voices to be added to a measure on the fly, would really come in handy for what I am trying to do. But this "volatile" feature does not appear to be implementers in ABCJS. That is, the last measure in the following ABC code does not have three voices in it:

``` X:1
T:Zocharti Loch
C:Louis Lewandowski (1821-1894)
M:C
Q:1/4=76
K:Gm
(B2c2 d2g2)  | f6e2         | (d2c2 d2)e2 | d4 c2z2 &\
                                                              A8  &\
                                                              F2 E2 D2 CB, |
```

Thanks for all of your great work.

**Comment by paulrosen** [comment]
I haven't implemented this yet, sorry. I don't know when I'll get to it, but it won't be right away. I've got a few features ahead of it.

**Comment by paulrosen** [comment]
In 3.2.0, one level of overlay is supported: that is, you can get two voices in the same measure.
