### ISSUE TITLE
lineEndCallback  callback in full-synth example not called

### ISSUE THREAD

**Issue by jepcolombia** [paulrosen/abcjs#341]
Iam adding this lines to use ABCJS.TimingCallbacks in full-synth example but leCallback()  is not called(nothing in console.log). Am I missing something else?

var visualObj = ABCJS.renderAbc("paper", abc[currentTune], abcOptions)[0];
			var objtimeCall = new ABCJS.TimingCallbacks(visualObj, {	
									lineEndAnticipation: 500,
			                                                 lineEndCallback: leCallback}); 
function leCallback(){
	 console.log("endline");
	window.scrollBy(0,50);
}

**Comment by paulrosen** [comment]
Did you call objtimeCall.start() somewhere?

**Comment by jepcolombia** [comment]
Oops shame on me!
Many thanks Paul!!
