### ISSUE TITLE
Bug with drum intro when pickup length is very close to 1

### ISSUE THREAD

**Issue by rimi-itk** [paulrosen/abcjs#342]
I'm playing around with some very weird rhythms (e.g. quintuplets and sextuplets) and have found an issue with adding a drum tracks when the computed pickup length is very close to 1.

In the example https://codepen.io/mikkelricky/pen/poJJXgy the pickup length is computed as `0.9999999999999998` and this messes up midi generation of the drum intro (for 1 bar) and the actual melody never plays.

**Comment by paulrosen** [comment]
Is fixed in the 6.0.0 beta
