### ISSUE TITLE
How to move from a given abcElem to the next and previous

### ISSUE THREAD

**Issue by jepcolombia** [paulrosen/abcjs#344]
Hi Paul,
testing  on your examples Iam trying to use abcElem passsed to  the clicklistener function and be able to navigate from that point  forward and backward with arrow keys calling again the clicklistener function with next o previous abcElem. Do you have an idea of the best way to do that?
Thanks in advance for your hep

**Comment by jepcolombia** [comment]
I found a way using abcElem (starChar and classes) and digging into visualObj  for the voice that matches abcElem and  keep traversing  visualObj finding next abcjs-note type abcjsElem. But if there is a better way, I will appreciate that.

**Comment by paulrosen** [comment]
That's an interesting question. I need to think about that for a minute. I think it will be possible in the next version (currently in beta) by adding an API call. I'm creating a new array of elements that should make that straight forward.

**Comment by jepcolombia** [comment]
Great news!! thanks Paul.
