### ISSUE TITLE
Question on showCursor param

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#348]
Hi Paul
In old abcjs.startAnimation function there was the possibility to set the showCursor param.

In the new abcjs.TimingCallbacks documentation I didn't find it or something similar. 
Is the functionality still available? If not, is there an easy way to implement it?

Thank You in advance
Osvaldo

**Comment by osvi64** [comment]
I found how to do it in the full-synth example. 
Thank you
Osvaldo

**Comment by TylerNoblett** [comment]
hi @osvi64! How did you get the cursor to show up with the timing callbacks? I'm also trying to figure it out, but haven't yet landed on a solution

**Comment by paulrosen** [comment]
When you create timingCallbacks there is an option for getting a callback on every "event". If you look at what is returned in that callback you should be able to figure out which note needs to be highlighted. In the full-synth.html example you can see the CursorControl class which has an example of how to change the DOM to show the cursor.
