### ISSUE TITLE
Ability to highlight (or style in general) entire bars

### ISSUE THREAD

**Issue by mattsoftware** [paulrosen/abcjs#350]
At the moment I am getting the event callbacks to notify me when a note is being reached, with the note element which I can then style accordingly. I am also getting the end of line callback which I can then manage scrolling of the music on the page. What I would love to do is to get callbacks on reaching the end of each bar, with entries for the bar currently ending, and the next bar about to start.

I would then like to take these and style them appropriately (I could possibly dull out all the music except the current bar and the next bar, for example).

From what I can tell with my limited use of the library so far is this cant be done as each note and bar symbol are essentially svg paths in an overall scheme. It might be a breaking change (or perhaps an option that can be provided?) but maybe all the notes belonging to the same bar could be in its own <g> subgraph so we can group them appropriately. Maybe in the 'endOfBar' callback we could get an array of notes for the current and next bar? 

Sorry if this is already implemented, if it is can I get a hint on how to get this information.

Let me know if any of this is unclear. I am new to abcjs and have only limited experience in reading music in general.

**Comment by paulrosen** [comment]
When you call `renderAbc()` the third param are various options. A useful one is `{ add_classes: true }` which will give you the precision you need, I think.

There is a beat callback and that has a flag about whether it is the first beat in a measure. So when you initialize `TimingCallbacks` pass in `beatCallback`.

**Comment by mattsoftware** [comment]
Ok. Looks like with the add_classes i can get each bar by looking for the elements with abcjs-m0 (first bar) abcjs-m1 (second bar) etc (jotting down for others to find and future reference for myself). I had tried previously but could not see any difference (potentially I added that flag to the wrong options, not sure)

Thanks for your feedback. I will attempt to work with that and see how far I get.

**Comment by mattsoftware** [comment]
I am going to add to this as I just figured out my previous comment was incorrect. The individual note can be found with a combination of classes...

* abcjs-l[0-9]+ (the line number of the note, 0 indexed)
* abcjs-m[0-9]+ (the measure/bar of the note in the line, 0 indexed)
* abcjs-n[0-9]+ (the nth note in the measure, 0 indexed)

**Comment by paulrosen** [comment]
Plus
* abcjs-v[0-9]+ (the voice number)
