### ISSUE TITLE
Build issue with Create react app

### ISSUE THREAD

**Issue by borisrorsvort** [paulrosen/abcjs#353]
Hi, I just updated create react app and abcjs. I’m getting compilation errors for the midi file:

```bash
node_modules/midi/js/adaptors-AudioAPI.js: 
Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
```

abcjs version: 6.0.0-beta.7
cra version: 3.4.0

**Comment by paulrosen** [comment]
I assume this happened with a completely new project? I'll create one from scratch and see what I get. If you have steps to reproduce it might save me some time.

**Comment by paulrosen** [comment]
And when are you getting the errors? Is that when you have the line:
```
import abcjs from "abcjs/midi";
```

If so, can you try taking the "midi" part off and seeing if it works? If so you can still use audio, the midi version is some old code.

**Comment by paulrosen** [comment]
Closed for inactivity. If this is still a problem, please reopen.
