### ISSUE TITLE
Starting animation does not seem to follow multiple endings correctly

### ISSUE THREAD

**Issue by mattsoftware** [paulrosen/abcjs#355]
Possibly due to https://github.com/paulrosen/abcjs/issues/74 when I have multiple endings to a repeat part, the flow does not seem to correspond with the abc notation (note also I may have notation incorrect).

Tried:
```
X:1
T:Repeat multiple times
K:C
|:: C D E F ::|
```
Expected the bar to play three times (as per http://abcnotation.com/wiki/abc:standard:v2.1#repeat_bar_symbols)

However the bar only played twice

I also tried this...
```
X:1
T:Repeat multiple times
K:C
|: C D E F |1 G A B C :|2 D E F G :|3 A B C D |]
```
Expected the order to be played (lets call them A, B, C, D)... A B A C A D
However the actual order played was... A B A C C D

I fully expect I might have notation incorrect for the above, i tried multiple places with the repeat with different results, but the notation I mention above feels like the most correct for me, unless someone can weight in and correct me :)

Thanks

**Comment by paulrosen** [comment]
The second example is definitely a bug and I'll look into it. It should play as you expect. It probably won't take very long to get a fix out.

The first example is odd, though. I don't think that is legal notation. I do see it in the abc standard, but have you ever actually seen music printed like that? It isn't in the standard notation guides that I've seen.

**Comment by mattsoftware** [comment]
Haha, I am a newbie for all this, so no I have never seen it in music, but I havn't seen a lot of music either ( played guitar for years, starting off by chords and ear, later by tabs mainly).

I was basically looking for a way to practice my drums, putting in the beats i want to practice, and repeating them say 16 times. Instead of copy and paste 16 times, or even putting the score into a loop, i was trying to figure out how to repeat a bar 16 times before moving on. The only syntax it looks like I can use is the |:::::: ... ::::::| which seems silly, but looks like standard syntax ¯\_(ツ)_/¯ or to do something like |:[1-16] .... :]| which might print out wierd but also probably more standard.

**Comment by mattsoftware** [comment]
Also, just to link the two issues, #225 would also be fantastic to be implemented as I have seen this notation for drums to indicate the repeating beat without the need to be watching every bar closely.

As soon as I get my little project finished I intend to dive deeper into abcjs to work out how to contribute, if this task or #225 needs looking at further down the track I think I will be interested as a way to get into the codebase a little.

**Comment by paulrosen** [comment]
That would be great! There are lots of unfinished things like this that could use attention.

**Comment by paulrosen** [comment]
closed for inactivity
