### ISSUE TITLE
Avoid to print sharp symbol for drum notation

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#356]
Hi Paul, is there a way to avoid printing the sharp symbol?
See at the example below: In case of open HiHat I need to print the x for the ^g note, without the sharp symbol. I need to put ^g instead of g because I need to make the Synth produce a different note.
Is there any way to obtain it? Is there any way to identify sharp symbols in the rendered score SVG?

Thank you

![image](https://user-images.githubusercontent.com/29627488/75325662-80001e80-5879-11ea-8d8f-8e2b6151ebc1.png)

**Comment by paulrosen** [comment]
I think so, but I'm not sure at the moment. I will study it this weekend and get back to you. I think the drum notation is mostly done, but there may be bugs.
