### ISSUE TITLE
midiPitches from event in eventCallback always empty

### ISSUE THREAD

**Issue by unkleho** [paulrosen/abcjs#359]
Hi all,

Been playing around with this library and enjoying it a lot.

Had a go with the new TimingCallbacks class and got it mostly working. I'm not sure if I'm doing it right, but I can't get midiPitches to show up in eventCallback. It is always an empty array.

The interactive docs also show an empty array for midiPitches:
https://paulrosen.github.io/abcjs/animation/timing-callbacks.html#example

I've got a CodeSandbox illustrating this issue:
https://codesandbox.io/s/loving-nobel-lvjld

Any help would be great.

Many thanks

**Comment by paulrosen** [comment]
Thanks for the report. I'll look into this soon. Try upgrading to version 6.0.0-beta.8 and see if that helps.

**Comment by unkleho** [comment]
Hey no worries. Unfortunately midiPitches still outputs [].
I've updated https://codesandbox.io/s/loving-nobel-lvjld to use 6.0.0-beta.8

**Comment by paulrosen** [comment]
Will be fixed in 6.0.0-beta.10

**Comment by unkleho** [comment]
Looking forward to it! Thanks
