### ISSUE TITLE
Getting the error: MIDI is not defined after upgrade

### ISSUE THREAD

**Issue by stephaneeybert** [paulrosen/abcjs#360]
I was using the dependency just fine, when I upgraded my Angular project, and got the error: MIDI is not defined

See the [SO](https://stackoverflow.com/q/60723149/958373) question.

I could not pinpoint what exactly happened.

**Comment by paulrosen** [comment]
I will duplicate and see. In the meantime, try the 6.0.0-beta.8 version and see if that helps.

**Comment by paulrosen** [comment]
Try the following to include the package:
```
import abcjs from 'abcjs';
```
Notice that the "/midi" is removed. You can still do audio using the synth interface.

**Comment by stephaneeybert** [comment]
I just installed the dependency again with the command:
```
npm install abcjs
```
This installed the dependency:
```
"abcjs": "^5.12.0",
```
And then tried the following source code:
```
import abcjs from 'abcjs';
import abcjsMidi from 'abcjs/midi';
const sheetAbc = abcjs.renderAbc(name, '', { add_classes: true });
```
And there was no syntax error, and no runtime error when serving the application.

**Comment by paulrosen** [comment]
Well, that's good, I guess. It would be nice it know what happened.

There are two slightly different things about the midi package - it is the only one that abcjs pulls in (and it only pulls it in when using the `abcjs/midi` version) and it isn't in npm, but it is pulled directly from github.

Maybe node_modules just had to be rebuilt? I have run into that sometimes.

Feel free to reopen if it happens again.
