### ISSUE TITLE
midi playback behaves unexpectedly for measures with 2 different chords of half-note duration

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#366]
Screenshot of example attached.

Thanks for your work!

![thing2](https://user-images.githubusercontent.com/2993720/78946467-cb206a80-7a90-11ea-8502-2013c3a04f51.jpg)

```T: Example #2
M: 4/4
L: 1/4
R: 
K: Amin
Q: 100
%
%%text Playback sounds weird:
%
"Am" C C B, A, | "F7" B,2 "E7" "_(↑); expected: E7/E; actual: E7/B" c, B, |
%
%%text Workaround:
%
"Am" C C B, A, | "F7" B,2 "E7/E" "_(↑)" c, B, |

**Comment by paulrosen** [comment]
Yes, that's a bug. If the chord changes mid-measure it shouldn't play the 5 in that beat. It will be fixed in the next version.

**Comment by chrisfargen** [comment]
> Yes, that's a bug. If the chord changes mid-measure it shouldn't play the 5 in that beat. It will be fixed in the next version.

@paulrosen -- great work on 6.0.0-beta.10. I'm having lots of fun testing out new functionality.

Just noticed this issue may have fallen through the cracks.
