### ISSUE TITLE
Support for midi download without midi player

### ISSUE THREAD

**Issue by sjktje** [paulrosen/abcjs#37]
It'd be great if the 'midi player' in ABCJS.renderMidi() could be disabled, so one could do something 

In html:
```html
<button id='midi-button'>Download MIDI</button>
```
And, in javascript:
```javascript
$('#midi-button').click(ABCJS.renderMidi(...))
```
Is this already supported? Am I missing something? Many thanks for a great library!

**Comment by paulrosen** [comment]
The next version (version 2.3) will remove the QuickTime link. It just has the link as you describe. It is already checked in, but I haven't finished testing to make the release, yet.
