### ISSUE TITLE
abcjs-midi not found on npm

### ISSUE THREAD

**Issue by lets00** [paulrosen/abcjs#370]
Hi,

I can't find this module in npm. 
I want to use the renderMidi() method but I don't found in abcjs module.

**Comment by paulrosen** [comment]
Sorry for the delay in responding. 

That module isn't in npm, but you can reference it like this:
```
    "midi": "https://github.com/paulrosen/MIDI.js.git#abcjs"
```
When the beta is released this issue will be resolved.
