### ISSUE TITLE
Complex Rendering & Playback

### ISSUE THREAD

**Issue by JonathanILevi** [paulrosen/abcjs#371]
For a project of mine, I have been putting off doing proper playback because I have an complex desired result.

I have four-part music.  I have code which creates the ABC data from an internal data format with certain user-preferences applied.  Including showing only some of the parts, or showing a part twice (like Tenor on Treble and Bass clef), and transposition.  There are separate settings for rendering and for playback.  e.g. The user can render all four part sheet music but playback only the melody.

What I am needing is to have playback animation on the rendered music despite the rendering and playback using different ABC data.  I am also looking to have seeking (for playback) done by clicking on the staff.

This does not fit the simple pattern of the examples.  How possible is this?

**Comment by paulrosen** [comment]
You can use the playback animation callbacks to know *when* to do something. Then you could figure out what notes the callback was specifying and target them in your display if you set the `{ add_classes: true }` parameter when drawing.

Also, if you look at the object returned from `renderAbc` after calling the animation, there is an array `noteTimings` which you can probably use.

Or, the animation that happens is the same as is done when calling `timing_callbacks` so  you could start that at the same time as the audio and not use the audio's callback.
