### ISSUE TITLE
need to press button 3 times to start playback

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#373]
Hi!
I'm building this Prima Vista site for my music students, and when uploaded here:
http://www.musikboden.se/avista.html
it will take me 3 clicks on play button  (Spela upp) to start the playback, it works on the first click if it's not online.
v.6.0.0 beta 8

I should say that when pressing the "Spela upp" button, this 3 clicks fenomenen is happening, but if pressing directly on Play on the Synthcontrol will start the playback at once.

The "Spela upp" button is the same button as "Play/Pause" in the "full synth" example

![Skärmavbild 2020-04-16 kl  22 37 56](https://user-images.githubusercontent.com/18282700/79504355-14ddf780-8033-11ea-8afb-5a67af218cf7.png)

**Comment by musikboden** [comment]
This phenomenon happens only with Safari v.13.1 web browser
Firefox v. 64.0 and Chrome v. 81.0.4.... works fine

**Comment by paulrosen** [comment]
This is a problem with the audioContext being suspended. I'll look at the code and see what changed in Safari 13.

**Comment by paulrosen** [comment]
This will be fixed in version 6.0.0-beta.10

**Comment by musikboden** [comment]
Thank you Paul, it starts right away now! :)
