### ISSUE TITLE
Not an issue, rather a question

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#378]
I have searched for a abcjs forum but found only the closed forum here:
http://abcnotation.com/forums/
Is there a place to ask questions, technical issues etc?

**Comment by paulrosen** [comment]
For abcjs or for abc notation in general? If it is an abcjs question you can ask it here.

For abc notation issues, your best bet is to read the standard doc: https://abcnotation.com/wiki/abc:standard:v2.2 There are plans to create a google groups for abc but I'm not sure if that is active yet.

You can also ask me occasionally. I might not get around to it immediately, though!

**Comment by musikboden** [comment]
It's mostly concerning how to write commands etc, the abc notation is well documented I think.
So now when I have you here, thank for a fantastic project and all work you commit to it, it's just great!! :)
My question is if you have an example of how to implement "soundFontUrl" inside the "full synth" example, I just can't find how or where I should write it in the code?
Let's say I have a sound font I would like to use when not connected to WIFI, I have it in a folder called "soundfonts" at the same level as the the main "full synth .html" file, how would go on with this?

**Comment by paulrosen** [comment]
This is a snippet from another project that uses it:
```
	const midiBuffer = new abcjs.synth.CreateSynth();
	return midiBuffer.init({
		visualObj: visualObj,
		soundFontUrl: soundFontUrl,
		onEnded: function () {
			finishedCallback();
		}
	}).then(function () {
```
It needs to be an available URL. When you are using localhost, you will still need to serve it somehow so the address will be something like `localhost:3001`. But that is a good way of running offline.

**Comment by musikboden** [comment]
Thank you Paul, I will figure it out!
Cheers!
