### ISSUE TITLE
Change playback volume

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#379]
Hi, I'd like to control the volume of the midiplayer. How can it be done?
Would the code containing 'var volume = (sound.volume / 96) * 3.0;' be the right place to change that?

**Comment by paulrosen** [comment]
Yes, that changes it globally. 

There are two ways to change it without changing anything in abcjs:
1) The regular marks `!pppp!` through `!ffff!` in the music changes it.
2) You can pass in `sequenceCallback` as an option in `CreateSynth().init()` like this: 
```
function callback(seq) {
  // Change seq 
  return seq;
}

var synth = new abcjs.SynthControl();
synth.init({ options: callback });
```
Study that structure and you can change anything in there, including the volume.

**Comment by ThorsenRune** [comment]
Thanks Paul,great.  Ill have a look into it when  I got time. 
Could you please give a hint on Add glissando symbol https://github.com/paulrosen/abcjs/issues/374?

**Comment by ThorsenRune** [comment]
Well, the callback is used during rendering not durign playback. It would be useful to be able to alter the volume during playback. Unfortunately I don't understand the playback mechanism yet.  Maybe its not even possible?

**Comment by paulrosen** [comment]
That's not possible with the way the playback mechanism is set up - it creates the entire music in advance. That was the only way I could solve some of the performance problems. 

And the scope of this project is not real-time performance. It is concentrating on specifying the tune in advance and then processing it.

Sorry.
