### ISSUE TITLE
Last line is not justified

### ISSUE THREAD

**Issue by ElvenSpellmaker** [paulrosen/abcjs#38]
Use a piece of music with a shorter last line than the rest of the lines.

The expected output is that the last line is justified to match the width of all the other lines. Instead the line is aligned to the left and squished.

This applies to all versions that I have tried (including the latest 2.1).

Example: http://theocarinanetwork.com/single/?p=8369853&t=7338254
![abcjs_justify_bug2](https://cloud.githubusercontent.com/assets/5989422/7833712/cffd0ea6-0460-11e5-811a-1d8e4cd9d1c4.png)

(Issue 149 on Googlecode)

**Comment by Tirno** [comment]
This is mostly by design. Maybe we did keep track of the number of measures in the previous line and justify the last line if it has that number of measures



—

**Comment by paulrosen** [comment]
There is a directive for this:

%%stretchlast .7

You can experiment with different numbers, but that decides how short the line is before it won't get stretched.

**Comment by paulrosen** [comment]
So, I think this is as designed. I agree that the default should be to align the last line, but that's not how the abc standard was written.
