### ISSUE TITLE
unexpected chord playback with eighth note triplets when two chords are specified within measure

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#381]
In particular, the issue seems to occur in the presence of an eighth note triplet in the second beat of a measure in 4/4 time.

![thing20](https://user-images.githubusercontent.com/2993720/80429499-4029d780-88ba-11ea-9954-a948cb3fb7c6.jpg)

```
M: 4/4
L: 1/8
Q: 80
%%text plays as expected:
"C" (3 C2 C2 C2 "G/G" (3 C2 C2 C2 |
%%text playback unexpected:
"C" (3 CCC (3 CCC "G/G" (3 CCC (3 CCC |
%%text plays as expected:
"C" (3 CCC (3 CCC (3 CCC (3 CCC |
%%text playback unexpected:
"C" (3 CCC (3 CCC "C" (3 CCC (3 CCC |
```

**Comment by paulrosen** [comment]
I can reproduce this and it will be fixed in the next beta.
