### ISSUE TITLE
Alteration is ignored in case of a legato from one bar to another  in midi

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#382]
Consider the fragment
X: 1
T: Assolo
K: Bb
Q:1/4 =80
 Ad-d2 d2d=B-| B4 z4|
Midi will play the last B as B flat, not natural as it should
 
![image](https://user-images.githubusercontent.com/6916927/80770387-784a4800-8b50-11ea-83cb-23f19f77af50.png)

midi will play the last note incorrectly as a Bb not B

**Comment by paulrosen** [comment]
I can reproduce this. It will be fixed in the next beta version
