### ISSUE TITLE
setting soundFontUrl in Editor

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#384]
how is setting soundFontUrl supposed to work when using Editor?
It seems to revert back to default when using cursorControl.

**Comment by paulrosen** [comment]
There was a bug in setting it. It will be fixed in 6.0.0-beta.10. You should be able to set it with:
```
new ABCJS.Editor("abc", {
  soundFontUrl: "https://etc"
  // etc...
});
```
