### ISSUE TITLE
Adding Figured Bass To Staff

### ISSUE THREAD

**Issue by Garchbold** [paulrosen/abcjs#385]
I am trying to write a Roman Numeral analysis below the bass line (see image below)
![image](https://user-images.githubusercontent.com/15057944/80988916-09d3e700-8de9-11ea-9402-8533f53c7c1d.png)

I tried using the "s:" line, but noticed two issues:
1. I can't get the buildup to work
2. I can't place the key under the clef
![image](https://user-images.githubusercontent.com/15057944/80989120-57e8ea80-8de9-11ea-914d-157557971c5d.png)

I was wondering if you had any insights on how to make this work? Thanks!

**Comment by paulrosen** [comment]
In the short run there isn't a way to get exactly what you want, but you can put the items in `w:` to get them in the right place, then post-process the svg to get them to look like you want.

For instance:
```
V:S
Bc^A|
w:V I II
```
then after rendering the music with `{add_classes: true}`, search for the annotations with `querySelector` and replace the SVG.

Sorry there's not a less-hacky way to do it at the moment.

For putting the key in, you can use the "_G:" format.
