### ISSUE TITLE
Adjoining notes cover each other up in SATB

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#386]
This:
![image](https://user-images.githubusercontent.com/1113368/81020182-df584d00-8e2d-11ea-9d0a-dfadb076f2d2.png)
should look like this:
![image](https://user-images.githubusercontent.com/1113368/81020239-fac35800-8e2d-11ea-8d58-23d7ffa7227e.png)

Example:
%%abc-charset utf-8
X:1
L:1/8
M:4/4
%%score (S A)
V:S clef=treble middle=B stem=up
V:A clef=treble middle=B stem=down
[V:S]G2 ||
[V:A]F2 ||

**Comment by paulrosen** [comment]
Definitely a bug. I'll get to it soon.

**Comment by nbruley** [comment]
Great news. I was just about ready to go through all 837 scores and manually fix them with CSS like this, but since it sounds like you're interested in fixing it before long, I'll wait :)
div.Speranza  svg .abcjs-v0.abcjs-l0.abcjs-m0.abcjs-n2 {transform: translate(-4px,0);}
div.Speranza svg .abcjs-v1.abcjs-l0.abcjs-m0.abcjs-n2 {transform: translate(4px,0);}

**Comment by nbruley** [comment]
Wow, you get a lot of requests so I'm not surprised this isn't fixed and I'm not expecting it to be, but still rooting for this change :)  Maybe it was more difficult than expected?

**Comment by paulrosen** [comment]
It requires a little be of refactoring. It shouldn't have been difficult. I have that refactoring high on the list because there are a few bugs that are related.

**Comment by nbruley** [comment]
Paul, Do you have an update on this issue? Is a fix still in the works? You mentioned "soon" above but that was over a year ago... Not complaining about your free work, just wondering.

**Comment by paulrosen** [comment]
I'm sorry about my pace - this last year has been something! I need to feel like I have time to finish the refactoring if I start it. I know it is annoying to be waiting. 

I'd accept pull requests or guide someone and it would happen faster.

**Comment by nbruley** [comment]
FYI, unfortunately I'm finding that the workaround is not as easy as just moving notes sometimes... better than nothing though. You also run into issues with accidentals overlapping adjoining notes because they move with the note, etc.
![image](https://user-images.githubusercontent.com/1113368/136487198-58bbc246-122a-48de-ab1d-54eb432fa54f.png)

**Comment by paulrosen** [comment]
Can you post some representative ABC strings so I can see all the cases you are running into?

**Comment by paulrosen** [comment]
Not yet - I will see if I can have an update for you soon, but, for instance, you put an ABC string on this first message in the thread but not on the second one. I can recreate that, but I'm guessing maybe you've run into other types of cases that would be interesting to work on at the same time. In any case - the two you posted are enough to get me started.

**Comment by nbruley** [comment]
6. Same pitch, different duration and voice
![image](https://user-images.githubusercontent.com/1113368/136629477-ce6ce063-0060-497f-bbea-dd8f62157db1.png)

**Comment by paulrosen** [comment]
I guess I should have built the minimized versions for you - they are built now.

**Comment by nbruley** [comment]
I found it now, thank you so much for working on this! It should save me a ton of time and make the music much more presentable.

I do see some more tweaks that can be done. It appears that overlapping notes of the same note should be imposed on each other (and note the note placement in bass clef also):
![image](https://user-images.githubusercontent.com/1113368/137539533-b97e793f-da2b-4a7b-a75b-c18b6d066c26.png)
instead of like this:
![image](https://user-images.githubusercontent.com/1113368/137539607-f7838cec-5f58-495b-ac1a-21d781987a85.png)

Here's an example ABC that might help debugging:

%%abc-charset utf-8

X:1
T:Constancy
T:8.7.8.7 D
C:Anonymous
L:1/8
Q:1/4=80
M:3/4
K:G
%%score (S A) (T B)
V:S clef=treble middle=B stem=up
V:A clef=treble middle=B stem=down
V:T clef=bass,, stem=up
V:B clef=bass,, stem=down
[V:S]D D | G2>F2 E G| D2 G2|| 
B B |A2>A2 G A |B4||
D D| G2>F2 E G| D2 G2 ||
B B| A2>A2 B A| G4 ||
d d| d2>B2 e d| d2 B2|| 
c c| c2>A2 d c| B4 ||
D D | G2>F2 E G| D2 G2|| 
B B |A2>A2 B A | G4|]
[V:A]D C | B,2>D2 C C| B,2 B,2|| 
D D |D2>D2 D C | B,4||
D D | (D2C) D C C | B,2 B,2 ||
G F | E2>G2 F F | G4 ||
F G| A2>G2 F G| ^G2 G2|| 
A =G| F2>F2 D E| G4 ||
D C | B,2>D2 C C| B,2 B,2|| 
D D |C2>C2 D C |B,4|]
[V:T]B, A, | G,2>G,2 G, G,| G,2 D,2||
G, G,| F,2>F,2 E, F,| G,4||
B, A,| G,2>A,2 G, A,| F,2 G,2||
E, F,| G,2>C2 D C| B,4 ||
D D| D2>D2 C D| B,2 E2||
E C| D2>C2 D D| D4 ||
D, D,| G,2>G,2 G, G,| (G,A,) (B,F,)|| 
E, F,| G,2>E2 D C| B,4 |]
[V:B]G,, G,, | G,,2>B,,2 C, E,| G,2 G,,2||
G,, B,,| D,2>D,2 D, D,| G,,4||
G, F,| E,2>D,2 C, A,,| B,,2 E,2||
E, D,| C,2>E,2 D, D,| G,4 ||
D, E,| F,2>G,2 A, B,| E,2 E,2||
A, A,| D,2>D2 B, A,| G,4 ||
D, D,| G,2>B,,2 C, E,| G,2 G,2|| 
G, F,| E,2>G,2 G, F,| G,,4 |]

**Comment by nbruley** [comment]
I am ecstatic that beta 35 fixes this!  

I still see the following where I think the bottom note should adjust right, but this is very minor:
![image](https://user-images.githubusercontent.com/1113368/139617508-474deb41-44db-4703-b28c-7eb0e7351a29.png)

I didn't do a thorough review but I don't see anything else jumping out at me.

THANK YOU so much, this saves me a ton of time and I no longer feel hesitant about publishing the scores.
