### ISSUE TITLE
Simple stable way to get coordinates of elements

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#390]
It seems that having coordinates in abselem will be convenient.
Yet, any recommended way to get x1,x2,y1,y2 of notes and other elements can be ok.

**Comment by paulrosen** [comment]
If you get an SVG element (various methods: using `document.querySelector(".abcjs-v0")`, the callback from the user clicking or dragging, the callback from TimingCallbacks), then you can use the built in SVG function:
```
var dim = elem.getBBox();
// dim contains x, y, width, height
```
For instance, from the clickListener which passes in an abcelem:
```
abcelem.abselem.elemset[0].getBBox()
```

**Comment by paulrosen** [comment]
Did this work?

**Comment by rualark** [comment]
Thanks for your reply! I am planning to continue working with coordinates after we get wrappable glissando to work.
