### ISSUE TITLE
Issue with V: transpose and %%score

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#393]
I'm making jazz guitar lead sheets, and I'm having trouble lowering lead guitar one octave while keeping chord playback within a sensible octave range.

Using `%%score chords lead`, playback works as expected (plays the C one octave below middle C):
```
%%score chords lead
V:chords name="Chords"
V:lead name="Lead" transpose=-12
[V: chords]
"C"x8 | "G7"x8 |
[V: lead]
C8- | C8 |
```

Using `%%score (chords lead)`, transposition is lost in playback (plays middle C):
```
%%score (chords lead)
V:chords name="Chords"
V:lead name="Lead" transpose=-12
[V: chords]
"C"x8 | "G7"x8 |
[V: lead]
C8- | C8 |
```

Any suggestions appreciated. Thanks.

**Comment by ThorsenRune** [comment]
Well I would expect that. If you write V:chords name="Chords" transpose=-12 then you are good for your lead

**Comment by chrisfargen** [comment]
> Well I would expect that. If you write V:chords name="Chords" transpose=-12 then you are good for your lead

Thanks for replying. That doesn't solve my issue. Yes, setting "transpose=-12" on V:chords does lower V:lead by an octave, but my goal is to lower V:lead by an octave _without_ lowering the octave of the accompaniment.

Upon further consideration, this issue may be related to [#391](https://github.com/paulrosen/abcjs/issues/391). Compressing the range of the accompaniment may be the best solution.

**Comment by paulrosen** [comment]
Yeah, I think fixing #391 is right.
