### ISSUE TITLE
Possible issue: Accidentals on tied notes do no carry over across measures on midi playback

### ISSUE THREAD

**Issue by santh** [paulrosen/abcjs#395]
Sharped or flatted notes tied to note in the next measure do not play correctly unless note is sharped or flatted as well. I thought the modern convention was to maintain the accidental across bars if the notes are tied.

**Comment by ThorsenRune** [comment]
I think it is recognized as a bug here:  https://github.com/paulrosen/abcjs/issues/382

**Comment by paulrosen** [comment]
Will be fixed in 6.0.0-beta.10
