### ISSUE TITLE
Please allow to control gap between exported MIDI notes

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#397]
Gap between exported MIDI notes can change in abcjs later due to playback sound optimization. On the other hand, true legato algorithms depend on this gap significantly. Please add parameter to switch gap behavior to MuseScore standard:

- Non-slurred notes should always have 25 pulses gap
- Slurred notes should always have 1 puse gap

**Comment by alexdemartos** [comment]
Hi,

how do you control the separation between consecutive notes in ABC notation or in abcjs?

**Comment by rualark** [comment]
Hi. Do you mean gap in exported MIDI file?

**Comment by alexdemartos** [comment]
Well, I actually mean for audio playback/synthesis. Not sure if it's the same

**Comment by rualark** [comment]
I do not control it. I use default MIDI exporting from abcjs.
