### ISSUE TITLE
Dynamic scrolling by specifying note?

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#398]
I suppose this is more of a feature request, but is there any way to force a tune to be displayed on a single line, and then specify a note index to scroll to?

I'm trying to make a widget to highlight a point in a specific tune by jumping to it, like a carousel.

I found that simply stripping out newlines from my ABC forces abcjs to render everything on a single line.  However, I can't find any way to scroll to specific notes. I can set the left margin to scroll, but I have no reliable way to correlate margin offset with note position, since note spacing isn't guaranteed to be consistent.

**Comment by paulrosen** [comment]
When you draw the music with renderAbc, use the option `{ add_classes: true }`. You can find the note you want by looking at the classes. There is a class for the measure number, and also a class for the note position in that measure. That is, to find the 3rd note in the 2nd measure, you can do something like `document.querySelector(".abcjs-m1.abcjs-n2")` (note that the indexes are zero-based.

**Comment by paulrosen** [comment]
Fixed for inactivity. Please reopen if you have more questions about this.

**Comment by chrisspen** [comment]
I'm finding not all notes have the correct class set. For example, a single quarter note at the beginning of a measure has these classes:

    abcjs-note abcjs-d0-25 abcjs-p6 abcjs-l0 abcjs-m7 abcjs-v0 abcjs-n0 

None of these classes correspond to the format you describe.

However, about half the notes do have a correct class set, and with that, I can look them up and use `document.querySelector(note_class).getBoundingClientRect().x` to find their absolute position on screen.

Why do some notes have have the type of class you describe?
