### ISSUE TITLE
ABCJS.renderMidi not defined

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#399]
The documentation refers to an ABCJS.renderMidi method, but this is not present in the most recent https://raw.github.com/paulrosen/abcjs/master/bin/abcjs_basic_5.9.1-min.js

Where is this method published?

**Comment by paulrosen** [comment]
That is a deprecated method. It is available if you use the abcjs_midi version of the library. Also, the version you specified is not the latest version. You can find that version of the midi here: https://github.com/paulrosen/abcjs/blob/master/bin/abcjs_midi_6.0.0-beta.9-min.js. 

However, I'd encourage you to look at the method of audio that is demonstrated in https://github.com/paulrosen/abcjs/blob/master/examples/full-synth.html.
