### ISSUE TITLE
Pause method?

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#400]
Is there a way to programmatically pause the midi playback without resetting the current position?

There's a `ABCJS.midi.startPlaying()` and `ABCJS.midi.stopPlaying()` but no `ABCJS.midi.pausePlaying()`, and unfortunately `stopPlaying()` not only stops playback but resets the display back to the first note.

**Comment by paulrosen** [comment]
In `full-synth.html` you'll see an example of a audio control that is created like this:
```
synthControl = new ABCJS.synth.SynthController()
```
that has a pause command.
