### ISSUE TITLE
Mark individual notes in a chord without marking entire chord or breaking the chord up (!mark!)

### ISSUE THREAD

**Issue by jpgm317** [paulrosen/abcjs#402]
It would be nice if we could !mark! an individual note in a chord to draw attention to particular notes in a chord. However, if one tries to do this in abc notation, the chord splits up in the rendering.  
For example:
!mark! [CEG] marks the entire chord green, which is good, but what if you wanted to emphasize the G in the triad [CEG]?
[CE !mark!G] will render as broken notes (no longer a chord)

**Comment by musikboden** [comment]
That is strange, [CE!mark!] will render as a chord for me, but all notes will be marked.
I'm using beta8 tested in the "Editor-Synth" example
But I agree, it would be useful to mark only one of the notes in a chord!

Btw, is there a way to change the colour of the marked notes?

**Comment by chrisfargen** [comment]
> Btw, is there a way to change the colour of the marked notes?

Yes. To get this slightly darker `!mark!` color:

![2020-05-20-114439_166x143_scrot](https://user-images.githubusercontent.com/2993720/82467370-97713100-9a8f-11ea-843e-737951e6a172.png)

1. In the `abcjsParams` definition, set property `add_classes` to `true`.
```
<script type="text/javascript">
...
abcjsParams: {
	...
	add_classes: true
	...
}
...
</script>
```

2. Style using CSS.
```
<style>
.mark {
	fill: yellowgreen;
}
</style>
```

**Comment by musikboden** [comment]
> > Btw, is there a way to change the colour of the marked notes?
> 
> Yes. To get this slightly darker `!mark!` color:
> 
> ![2020-05-20-114439_166x143_scrot](https://user-images.githubusercontent.com/2993720/82467370-97713100-9a8f-11ea-843e-737951e6a172.png)
> 
> 1. In the `abcjsParams` definition, set property `add_classes` to `true`.
> 
> ```
> <script type="text/javascript">
> ...
> abcjsParams: {
> 	...
> 	add_classes: true
> 	...
> }
> ...
> </script>
> ```
> 
> 1. Style using CSS.
> 
> ```
> <style>
> .mark {
> 	fill: yellowgreen;
> }
> </style>
> ```

Great, thank you! :)

**Comment by samuelbradshaw** [comment]
In addition to adjusting the fill (color), you can also add a stroke (border) to increase the thickness.

fill
stroke
stroke-dasharray
stroke-dashoffset
stroke-linecap
stroke-width

**Comment by paulrosen** [comment]
Allowing the notes of a chord to be drawn separately so they can be styled differently is definitely high on my list. I won't be able to get to it in this upcoming release, though.

You can hack around it though - right after drawing you can find the chord with `svg.querySelector(".abcjs-m2.abcjs-n3")` or whatever. Then you can determine the position in the svg that it was placed. Then you can append your own cursor at that place.

If you look at the https://github.com/paulrosen/abcjs/blob/master/examples/full-synth.html example, you'll see the example of creating a vertical line as a cursor. You could do a similar thing, but not use a line, but use your own shape.

**Comment by jpgm317** [comment]
Thanks, Paul!  Great project!  I'll take a look at your suggestions.  One other related question as this has to do with identifying separate notes/pitches:  How do the pitch classes work (abcjs-p0)?  They're obviously not MIDI numbers - which would also be good as classes to distinguish notes.  

That way I could identify them using svg.querySelector(`.abcjs-p0`), etc., but I'm not sure what pitch I'm referring to.  1st pitch in key?  Or does this also work with octave class that I somehow recall reading about somewhere, but can't seem to find.  

Thanks again!

**Comment by paulrosen** [comment]
The pitch numbers are visual. They aren't really pitches - they are physical places on the staff. Zero is the line below the staff (middle C on treble clef. One is the space above it. Minus one is the space below it.

That's a good idea to have a class based on the midi numbers. I don't think I've figured out that information at the time I assign classes. Maybe I can do a second pass and add the midi numbers, though.

**Comment by musikboden** [comment]
> stroke-linecap



> In addition to adjusting the fill (color), you can also use CSS to add a stroke (border) to increase the thickness. Here are some of the CSS properties you can use (there might be others I'm missing):
> 
> fill
> stroke
> stroke-dasharray
> stroke-dashoffset
> stroke-linecap
> stroke-width

Thank you! I've managed to get those working.
I looked at Wim Vrees examples and he is using a transparent rectangle with different colours for each voice, I managed to set different colours for each separate voice but I'm not able to draw a rectangle as in this example: https://wim.vree.org/js3/xmlplay.html?test/tabgitbasdrum_rt.abc
Would it be possible you think?

**Comment by jpgm317** [comment]
> The pitch numbers are visual. They aren't really pitches - they are physical places on the staff. Zero is the line below the staff (middle C on treble clef. One is the space above it. Minus one is the space below it.
> 
> That's a good idea to have a class based on the midi numbers. I don't think I've figured out that information at the time I assign classes. Maybe I can do a second pass and add the midi numbers, though.

Gotcha.  Unfortunately, the pitch class won't work very well with sharps and flats for what I had in mind.  Midi number classes would add a tons of potential functionality.  I've added midi numbers to SVG notes  with setAttribute, and it works; however, the problem is that once the ABC string is rewritten (as strings are immutable) the SVG I've added the class to disappears.  So, a midiNum class is the way to go.

**Comment by paulrosen** [comment]
The individual notes are now selectable.
