### ISSUE TITLE
score for 4 hands

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#403]
What am I doing wrong?
I can't get  grand staff brackets for both pianos

X:1
T:Vi har en gammal faster
T:från "Stora pianoraketen"
C:Trad. Arr: M.Strömblad, H.Råberg Schrello, I.Kullberg
%%score { 1  2 }  { 3  4 }
Q:1/4=100
L:1/8
M:4/4
I:linebreak $
K:D
V:1 treble
V:2 treble
V:3 bass 
V:4 bass
V:1 
[K:clef=treble+8][K:transpose=12]
A | FF FF F F2 F | FF EF G2 z G | 
w: Vi | har en gam-mal fas-ter, som | he-ter Ing-e-borg, vi |
EE EE A A2 B | AG FE D2 A2 |
w: bru-kar hen-ne här-ma, hon | går på sta-dens torg. Så |
F2 FF F F2 F | FF EF G2 z G | 
w: här svaj-ar hat-ten och | hat-ten svaj-ar så! Och |
E2 EE A A2 B | AG FE D2 z |]
w: så svaj-ar hat-ten och | hat-ten svaj-ar så! |
V:2
A | FF FF F F2 F | FF EF G2 z G | 
EE EE A A2 z | A4 D2 A2 |
F2 FF F F2 F | FF EF G2 z G | 
E2 EE A A2 z | A4 D2 z |]
V:3
z | z [!2!F,!4!A,] z [F,A,] z [F,A,] z [F,A,] | z [F,A,] z [F,A,] z [!3!G,!4!A,] z [G,A,] |
z [G,A,] z [G,A,] z [G,A,] z [G,A,] | z [G,A,] z [G,A,] z [F,A,] z2 |
z [F,A,] z [F,A,] z [F,A,] z [F,A,] | z [F,A,] z [F,A,] z [G,A,] z [G,A,] |
z [G,A,] z [G,A,] z [G,A,] z [G,A,] | z [G,A,] z [G,A,] z [F,A,] z |]
V:4
z | D,2 C,2 B,,2 A,,2 | D,2 A,,2 E,2 A,,2 |
D,2 C,2 B,,2 A,,2 | B,,2 C,2 D,2 A,,2 |
D,2 C,2 B,,2 A,,2 | D,2 A,,2 E,2 A,,2 |
D,2 C,2 B,,2 A,,2 | B,,2 C,2 D,2 D,, |]

**Comment by paulrosen** [comment]
That's a bug. It will be fixed in the next version.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.13

**Comment by musikboden** [comment]
Thank you Paul!

**Comment by musikboden** [comment]
Hi again,
there seems to be some bugs in this, this tune uses 2 voices in player 1 and 3 voices in player 2, the %%score { 1 | 2 } { ( 3 5 ) | } seems to break the bracket functions as well as misplacing the names.

`X:1
T:The brown duet book
T:Her Dear Round Little Face
C:Russian folk-tune
%%score { 1 | 2 } { ( 3 5 ) | 4 }
L:1/8
Q:1/4=80
M:4/4
I:linebreak $
K:G
V:1 clef=treble nm="Primo"
V:2 clef=treble 
V:3 clef=bass nm="Secundo"
V:4 clef=bass 
V:5 clef=bass 
V:1
!<(!"^Andante con moto"!p! !3!B2 B2 d2 !4!cB |!<)!!>(! AB AG !3!F2 D2 |!>)!!mp! (.!3!B2 .B2 .d2)!<(! (!4!cB | A2 .B.c .B2 .A2) | %4
!<)!!<(!!mf! z8!<)!!<(! | z8 |!<)!!p! (.E2!>(! .G2 .F2)"^ritard." (.B2 | E4 e2)!>)! z2 |] %8
V:2
 z8 | z8 | z8 | z8 | %4
 !3!G2 G2 B2 AG | !4!F!1!G FE ^D2 B,2 | z8 | z8 |] %8
V:3
!p! z2!<(! !5!!2![GD]2 z2 [GD]2 |!<)! z2!>(! !5!!1![EA,]2 z2 !2!C2 |!>)!!p! z2!<(! !5!!2![GD]2 z2 [GD]2 | z2 !4!!1![FC]2 z2 !4!!1![FB,]2 | %4
!<)!!mf! z2!<(! !4!!1![EB,]2 z2!<)!!>(! [EB,]2 | z2 !5!!2![CF,]2 z2 !2!!1![F,^D,]2 |!>)!!p! !5!!1![B,E,]4!>(! !4!A,4!>)! |!>(!!pp! z2 ([CA,]2 [B,G,]2)!>)! z2 |] %8
V:4
 !5!G,,4 B,,4 | C,4 !1!D,2 !2!F,2 | !1!G,4 B,,4 | D,4 !2!^D,4 | %4
 !1!E,4 G,,4 | !3!A,,4 !2!B,,2 A,,2 | !1!G,,2 !2!E,,2 !5!B,,,4 | !2!E,,6 z2 |] %8
V:5
 x8 | x8 | x8 | x8 | %4
 x8 | x8 | x4 !1!E,2 !2!^D,2 | !1!E,6 z2 |] %8
`

![Skärmavbild 2020-07-12 kl  11 42 09](https://user-images.githubusercontent.com/18282700/87243322-58c77980-c435-11ea-9184-855c5a50401d.png)
