### ISSUE TITLE
Setting soundFontUrl changed?

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#404]
Hi!
Thank you for a great beta 10 fix and update!!
However I now have an issue with setting the soundFontUrl, it worked great in the "full synth" example with beta 8
I used this line to set it:
var soundFontUrl = "https://musikboden.se/soundfonts/FluidR3_GM/"
however now in beta 10, it will not work any longer, it sets the default soundfont.
Is there something I could fix easily?
Cheers /Ulrik

**Comment by paulrosen** [comment]
Does this work? (this is a modification to the full synth example)
```
const midiBuffer = new abcjs.synth.CreateSynth();
	return midiBuffer.init({
		visualObj: visualObj,
		soundFontUrl: "https://musikboden.se/soundfonts/FluidR3_GM/"
	}).then(function () {
```

**Comment by musikboden** [comment]
> Does this work? (this is a modification to the full synth example)
> 
> ```
> const midiBuffer = new abcjs.synth.CreateSynth();
> 	return midiBuffer.init({
> 		visualObj: visualObj,
> 		soundFontUrl: "https://musikboden.se/soundfonts/FluidR3_GM/"
> 	}).then(function () {
> ```

Yes if I change your code " abcjs" to uppercase it sounded but it's still the default soundfont

**Comment by musikboden** [comment]
I made a "console.log(midiBuffer)" and this shows:
![Skärmavbild 2020-05-26 kl  07 27 28](https://user-images.githubusercontent.com/18282700/82863527-ac801100-9f22-11ea-8d4d-694d388a6ebf.png)

**Comment by musikboden** [comment]
I modified the "abcjs_basic_6.0.0-beta.10-min.js" for now

**Comment by paulrosen** [comment]
Ok, I'll figure out what happened and fix it for next release.

**Comment by paulrosen** [comment]
I'm sorry that the documentation hasn't kept up - I've improved it just now. I didn't give you the right structure for setting the soundfont. I hopefully made it a little clearer in full-synth.html now. The relevant piece is:
```
midiBuffer.init({
	//audioContext: new AudioContext(),
	visualObj: visualObj,
	// sequence: [],
	// millisecondsPerMeasure: 1000,
	// debugCallback: function(message) { console.log(message) },
	options: {
		// soundFontUrl: "https://paulrosen.github.io/midi-js-soundfonts/FluidR3_GM/" ,
		// sequenceCallback: function(noteMapTracks, callbackContext) { return noteMapTracks; },
		// callbackContext: this,
		// onEnded: function(callbackContext),
		// pan: [ -0.5, 0.5 ]
	}
}).then(function (response) {
```
Notice that there is another layer of indirection.

**Comment by musikboden** [comment]
Great, thank you!
