### ISSUE TITLE
Grand staff name misplaced

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#407]
If using Grand staff, the instrument name is misplaced, it should be placed between the 2 staves

X: 1
T: Test
L: 1/8
R: reel
%%score { A | B } { C | D }
V:A clef=treble+8 transpose=12 nm=Primo
V:B clef=treble
V:C clef=bass  nm=Secundo
V:D clef=bass-8 transpose=-12
K: Emin
V:A
CDEFG4
V:B
CDEFG4
V:C
C,D,E,F,G,4
V:D
C,D,E,F,G,4

![Skärmavbild 2020-05-26 kl  10 12 44](https://user-images.githubusercontent.com/18282700/82876680-7601c080-9f39-11ea-8f5d-021157b3b4b2.png)

**Comment by paulrosen** [comment]
Ok, I'll fix in the next version.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.13

**Comment by musikboden** [comment]
Great, thanks!
