### ISSUE TITLE
Render each line in a tune to a different div?

### ISSUE THREAD

**Issue by dvdrndlph** [paulrosen/abcjs#41]
Dear Paul:

I am writing an editor for pianists to enter fingering annotations. They enter (mostly) digits in an input field, and my code updates the abc string with appropriate annotations and re-renders. To keep the input fields next to the rendered notes, I am currently preprocessing each line in an input tune into separate abc tunes and rendering them individually, with some strained logic to keep the header information correct. I attach a picture of what my interface currently looks like.

![screen shot 2015-05-28 at 11 45 23 pm](https://cloud.githubusercontent.com/assets/4852894/7876597/0cfaa492-0594-11e5-8ebf-7b53e3eca765.png)

As you can see, the tie continuation marks are not rendered using this approach, and in general my approach seems rather brittle. What I really need is to display each individual line as it appears in the context of the whole tune. Is there a way to do this in abcjs?

Thanks,
Dave

**Comment by dvdrndlph** [comment]
Another thing that is making my code overly complex is using the abc text as the means to update what gets rendered. My code would be much simpler if I had a methods I could call to update your internal representation of the abc string, in a manner similar to how I am currently highlighting the rendered note. I tried to hack it like this, but, not too surprisingly, it didn't do what I wanted:
```
function highlight_abcjs_note(tune_object, staff_number, line_number, caret_location) {
    var staff = tune_object.lines[0].staff[staff_number];
    var voice = staff.voices[0]; // FIXME: Only one voice per staff supported.
    var note_number = get_note_number_at_caret(staff_number, line_number, caret_location);
    console.log("Note number at caret: " + note_number);
    var note_count = 0;
    for (var i = 0; i < voice.length; i++) {
        var elem = voice[i];
        if (elem.el_type !== 'note' || elem.rest) {
            continue;
        }
        if (elem.gracenotes) {
            note_count += elem.gracenotes.length;
        }
        note_count += elem.pitches.length;
        if (note_count > note_number) {
            var opts = {};
            opts.position = 'above';
            opts.type = 'text';
            var annotation = ABCJS.write.RelativeElement("5", 0, 15.25, undefined, opts);
            elem.abselem.addChild(annotation);
            elem.abselem.highlight();
            break;
        }
    }
}
```
Also, the api.md documentation does not seem to put any of this on a very firm footing:
```
tuneObject contains a structure which is a machine-friendly version of the abc string that it was created from. It is the class ABCJS.data.Tune and is basically some meta-information and an array of each line in the tune. The format of that data is subject to change.
```
Ideally (in my mind at least), abcjs would provide a stable API we could use to identify, highlight, and modify elements without our needing to refer to the original abc string. This API could of course grow over time.

Anyway, thanks again for the great work on this library.

Cheers,
Dave

**Comment by boxplayer** [comment]
Hi Lads

I implemented a simple Note Editor (including Fingering): Go to etunebook.ch, load my tunebook, choose a tune, then choose abc, then choose Note Editor. I did not invest much time in this (labels are currently in bad shape), but it still seems to work (fingering dropdown is the second from left).

Martin

Von meinem iPhone gesendet

**Comment by dvdrndlph** [comment]
Dear Martin:

Are you updating the model directly to make the note changes? Can you provide a code snippet to show how you are doing this?

Thanks,
Dave

**Comment by paulrosen** [comment]
This is also somewhat of a hack, but you could increase the space between
staves with %%staffsep and put your input boxes on top of the svg.

Your idea of directly modifying the structure is a good one, but I need to
reserve the right to change the format of it to add features. I think there
may be some big changes coming in the next couple of versions, too.


On Fri, May 29, 2015 at 11:16 AM, David Randolph <notifications@github.com>
wrote:

> Dear Martin:
>
> Are you updating the model directly to make the note changes? Can you
> provide a code snippet to show how you are doing this?
>
> Thanks,
> Dave
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulrosen/abcjs/issues/41#issuecomment-106842923>.
>



-- 
Paul Rosen
Performant Software Solutions, LLC

**Comment by dvdrndlph** [comment]
I understand that the underlying data structure could change. I was hoping for some sort of encapsulation to insulate us from the changes. Right now, the only way I can access the elements is to navigate your structure.

Yes, I need to stop splitting up the ABC and do something else to keep the input fields and the rendered notes together on the screen. Your "hack" might be the simplest approach. Or I was thinking of putting all of the input fields in one scroll box and the rendered score in another. Then I just need to figure out how to keep the highlighted note in the middle of the scroll box.

Actually, it  would be nice if your editor (and Martin's) would do this. Selecting a note in one representation does highlight it in the other, but the user often has to manually scroll to see this. It would be nice if both highlighted elements were made visible on the screen automatically.

Thanks,
Dave

**Comment by boxplayer** [comment]
yes. the model gets updated (tune.pure). then the dots are refreshed (whole tune).

sources involved in the note editor:

views: 
https://github.com/boxplayer/eTuneBook/blob/master/app/views/tune.html <https://github.com/boxplayer/eTuneBook/blob/master/app/views/tune.html>
https://github.com/boxplayer/eTuneBook/blob/master/app/views/tuneabc.html <https://github.com/boxplayer/eTuneBook/blob/master/app/views/tuneabc.html>
controller: 
https://github.com/boxplayer/eTuneBook/blob/master/app/scripts/controllers/tuneabcCtrl.js <https://github.com/boxplayer/eTuneBook/blob/master/app/scripts/controllers/tuneabcCtrl.js>
directives: 
https://github.com/boxplayer/eTuneBook/blob/master/app/scripts/directives/tbkAbcElementSelect.js <https://github.com/boxplayer/eTuneBook/blob/master/app/scripts/directives/tbkAbcElementSelect.js>
https://github.com/boxplayer/eTuneBook/blob/master/app/scripts/directives/tbkAbcElementChange.js <https://github.com/boxplayer/eTuneBook/blob/master/app/scripts/directives/tbkAbcElementChange.js>

you need to know angularjs in order to understand these sources, 

hope this helps
Martin

**Comment by paulrosen** [comment]
There is now an options for rendering each line in a different div.
