### ISSUE TITLE
MIDI pitches info for multi-staff arrangements

### ISSUE THREAD

**Issue by luke-slnsw** [paulrosen/abcjs#410]
Hi there,

We were very excited that since v6.0.0-beta.10, midiPitches information now shows up in the eventCallback!

However when using it on a multi-staff arrangement it isn't possible to tell which staff each MIDI note is from (which is necessary if we are to have different staves played by different sounds).

In this example:

<img width="526" alt="Screen Shot 2020-05-27 at 11 01 20" src="https://user-images.githubusercontent.com/18181247/82964917-0a3b5880-a00a-11ea-9a93-3b958bdb101f.png">

we have 3 staves - the top one is voice or flute, the next two are treble and bass clef for piano. This is the info we get from the callback:

<img width="513" alt="Screen Shot 2020-05-27 at 11 02 05" src="https://user-images.githubusercontent.com/18181247/82964964-2dfe9e80-a00a-11ea-9f18-b936f7424f4d.png">

Is this something that is encapsulated somewhere else in the event callback object? Or have we omitted something in our ABC notation? Or is it a bug?

Currently the notation is like this (some lines removed for clarity):

X:1
M:4/4
K:A
L:1/4
%%score 1 2 | 3
V:1 name="VOICE"
|A G/ B/ E F|G2 z2|
... more lines ...
V:2 clef=treble name="PIANO-"
|[A,/E/A/] z/ [D/E/G/] z/ [C/E/A/] z/ [C/F/c/] z/|z [^DG^B] z [=DG=B]|
... more lines ...
V:3 clef=bass name="FORTE"
|[C,,/C,/] z/ [B,,,/B,,/] z/ [A,,,/A,,/] z/ [A,,/A,/] z/|[G,,G,] z [E,,E,] z|
... more lines ...

many thanks.
:L

**Comment by paulrosen** [comment]
I think this information is available to me when creating that event. I will add that.

**Comment by luke-slnsw** [comment]
That is excellent news Paul, thank you very much.

**Comment by luke-slnsw** [comment]
Hi again Paul,

I was checking some of the new beta versions and noticed that in beta.14, the midiPitches seem to have disappeared from the eventCallback.

Is that just temporary? Or has it moved elsewhere?

We (at the State Library of NSW, in Australia) are launching an experiment soon (more about that in another issue I'm about to add) that uses ABCjs and have coded around the lack of midiPitches data for now - but it would be great to have that info (tied to the staff number) sometime in the future...

thanks again
:L

**Comment by paulrosen** [comment]
fixed by calling setupAudio() after renderAbc()
