### ISSUE TITLE
If %%partsfont font size is below 14 and box is specified, the box overlaps text

### ISSUE THREAD

**Issue by santh** [paulrosen/abcjs#411]
%%partsfont Arial 10 box

![Screen Shot 2020-05-26 at 6 55 27 PM](https://user-images.githubusercontent.com/3333015/82968663-b5083400-9f82-11ea-83b3-9bc13d1fcad5.png)

%%partsfont Arial 14 box
![Screen Shot 2020-05-26 at 7 08 09 PM](https://user-images.githubusercontent.com/3333015/82969396-6a87b700-9f84-11ea-9845-b0a0897ff7f4.png)

**Comment by paulrosen** [comment]
Thanks for the bug report. I'll fix that in the next version.

**Comment by santh** [comment]
Thanks, Paul!

Scott



www.santhony.com
santh@comcast.net
650-738-2101

**Comment by chrisfargen** [comment]
Related: `%%gchordfont box` has a similar overlap issue, regardless of font size.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.13

**Comment by santh** [comment]
Thanks for the fixes, Paul.

I have a couple of new questions:

1. The box around parts looks much better but I would like to add a bit of left and right padding. Is there a way to do that, maybe with CSS?
2. Can %%text have a box parameter implemented?
3. Is there a way to get rid of the “%” in the abcjs-tempo-wrapper label and just use the number as the absolute BPM, not a percentage of the Q: value? 

Scott



www.santhony.com
santh@comcast.net
650-738-2101
