### ISSUE TITLE
Problem with abcjs-pN class with chords

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#412]
If you use the abjs-p3 class in order to color differently the F note (for example) and the F note belong to one chord, the style color property applies to all the notes of the chord rather than only to the F note

**Comment by paulrosen** [comment]
Yes, this is a bug. I do want to get to this soon, but I'm also afraid of breaking existing code - if someone is looking into the SVG they currently see a chord as a single path and they might be expecting that.

I will either just change that outright or add an option to allow either functionality.

I do have the question about the stem - which note should that go with? I'd be tempted to have the stem highlight with the bottom note when the stem is up and the top note when the stem is down.

**Comment by jpgm317** [comment]
In issue post 402, I suggested adding a MIDI note number class (for instance, abcjs-MIDINum60 for middle C) in place of the pitch class (which currently is based on xPos of the note, and currently isn't practical for accidentals) or change the pitch class value to the MIDI Num (although this would probably break some code).  The MIDI number would be more precise than the current pitch class for this purpose.

Would it simplify things if the stem were the original color (black)?  At least for my purposes, only the note heads need to be colored, not the entire stem, but perhaps osvi64 thinks has different requirements.

**Comment by paulrosen** [comment]
The parts of the chord are now separately selectable.
