### ISSUE TITLE
Feature request: support for voice stem=auto

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#414]
The music below contains two voices combined on one staff. In this context, the stems are being forced down by default. Setting `stem=up` helps for the music below, but isn't always a good fit. For this scenario, it would be nice to have a `stem=auto` option.

```
%%printtempo 0
T: La mer
M: 4/4
L: 1/8
K: Fmaj
Q: 100
%
%%score (chords lead)
%
V:chords
V:lead
%
[V: chords]
"G-" x2 "/" x2 "C7" x2 "C#°7" x2 | "D-7" x4 "Bb" x4 | "G-7" x8 | "C7" x8 |]
%
[V: lead]
d2 d2 (3 c2 A2 G2 | F4 D2 F2 | G8 | C4 z4 |]
```

**Comment by paulrosen** [comment]
I agree `stem-auto` should be supported. There is a work around in your case, though, which is to put the lead first. You just need to change this one line:
```
%%score (lead chords)
```

**Comment by chrisfargen** [comment]
Thank you! That fixes the printout. The downside of this solution, for my case, is that the audio playback will not include the chord accompaniment.

**Comment by paulrosen** [comment]
That's true. I'll see what I can do. As long as there is only one chord voice it shouldn't matter which one it is.

**Comment by chrisfargen** [comment]
> The downside of this solution, for my case, is that the audio playback will not include the chord accompaniment.

Just noticed this is no longer an issue in beta.14. Thanks for the fix, Paul!
