### ISSUE TITLE
Question: is there a way to increase distance between chord symbols and staff?

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#416]
![asdbwreds](https://user-images.githubusercontent.com/2993720/83340974-468de380-a2ac-11ea-9b80-dca8cf3c4401.jpg)

By way of CSS or ABC options?

**Comment by paulrosen** [comment]
How are you setting the gchordfont? If you do it in CSS then the layout might not pick up on the size. If you use
```
%%gchordfont Times 30
```
then it should have left enough space.

If you are using the gchordfont directive, would you paste the ABC string you used for the above?

**Comment by chrisfargen** [comment]
In the sample image, I was setting font size in the JS:
```
...
abcjsParams: {
	format: {
		gchordfont: "16"
	}
...
```

But even without specifying gchordfont, I have the overlap issue with this musical phrase. Not sure if there's an ABC-native way to increase space between chord symbols and staff, but it would be nice if there were.

ABC:

```

X: 
T: Swing guitars
C: Django
M: 4/4
L: 1/8
K: Cmaj
%
%%score (chords lead)
%
V: chords
P: A
"C"x4 "C7"x4 | "F"x4 "F-"x4 | "D-7"x4 "G7"x4 | "C"x4 "C7"x4 ||
%
V: lead
P: A
cegc' z a3 | gf z e z d3 | (3 gag ^fg _e' d'2 c'- | c'4 z =e2 c ||
```

**Comment by paulrosen** [comment]
That's a bug - it isn't using the font size to determine the vertical placement. I'll probably be able to get that fixed in the next version.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.13

**Comment by chrisfargen** [comment]
Thanks for working on this issue, Paul.

I just tested this using the example tune above, and here's what I got:

![ok](https://user-images.githubusercontent.com/2993720/86952997-cddb3c00-c121-11ea-8e41-2a7c30d73d7e.png)

I'm running beta.13 minified.

**Comment by paulrosen** [comment]
It looks like I'm not taking the height of the flat into consideration. And it looks like it could use a little more padding anyway. Although - some people like everything as compact as possible so I'm not sure about that.

**Comment by paulrosen** [comment]
fixed in beta.16
