### ISSUE TITLE
Triplet

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#417]
How do I write this triplet?
I can't find the right way to do it.
![Skärmavbild 2020-05-31 kl  15 55 10](https://user-images.githubusercontent.com/18282700/83354126-5f070800-a357-11ea-927d-a23e8c86ad0b.png)

And another question, is it possible to set a swing/shuffle playback feeling to eight notes?

**Comment by chrisfargen** [comment]
> How do I write this triplet?
> I can't find the right way to do it.
> ![Skärmavbild 2020-05-31 kl 15 55 10](https://user-images.githubusercontent.com/18282700/83354126-5f070800-a357-11ea-927d-a23e8c86ad0b.png)
> 
> And another question, is it possible to set a swing/shuffle playback feeling to eight notes?

`(3::2 A2 A`

Source: [ABC notation doc](http://abcnotation.com/wiki/abc:standard:v2.2#duplets_triplets_quadruplets_etc)

Swing feel not yet supported.

**Comment by musikboden** [comment]
Thank you Chris!
