### ISSUE TITLE
Decrease gap between fingering text?

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#420]
Is there a way to decrease the gap between the "fingering" text?
When I write fingerings for chords it is to much gap in my opinion.

![Skärmavbild 2020-06-01 kl  21 08 22](https://user-images.githubusercontent.com/18282700/83445022-8db2da80-a44c-11ea-9fd2-50c1d9d66341.png)

**Comment by musikboden** [comment]
Ok, I see.
Yes let me know what you find regarding layout.

**Comment by paulrosen** [comment]
closed for inactivity

**Comment by salmonito** [comment]
Still an issue in 2023, any solution for this (version 6.2.2)?
