### ISSUE TITLE
Accordion soundfont

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#421]
I'm building a lesson library for my accordion and pianostudents here:
http://www.musikboden.se/avista.html
it is also made for Avista reading (random lines) with settings for note values, meter etc.
I use the FluidR3_GM sound fonts but I have switched the Grand piano to the MusyngKite Grand because it sounds better.
The problem, in my opinion, is that almost every sound from the FluidR3 sounds as if there is a phase problem, and the accordion is not usuable.
So I look for a decent accordion soundfont to use, and that I can incorporate in the FluidR3...
Do you have any tips where to look, or how to do it myself?
I have sampled my own accordion but I don't understand how to build the soundfont used for this abcjs project.

Or is there another way to go, I mean to use some other sound source?

**Comment by paulrosen** [comment]
I'm also searching for a better soundfont! So let me know if you make any progress on that.

If you've got samples of every note on your accordion you can clone my soundfonts project and replace these files: https://github.com/paulrosen/midi-js-soundfonts/tree/gh-pages/FluidR3_GM/accordion-mp3

You should listen to the existing files to see how long to play each note, I guess.

I'm currently looking for a better piano soundfont to start with.

**Comment by musikboden** [comment]
Yes I will let you know if I find anything.
Great, I'll look in to that, I'll let you know how it's going, or if I need help :)

**Comment by ThorsenRune** [comment]
Great info this about the MP3. So you just record a bit of MP3 for each note and replace it?
Im looking for a clarinet sound.

**Comment by paulrosen** [comment]
Yes, the simple answer is just record each note as an mp3. The longer answer is that putting sounds together and have it sound natural is tricky. There is a lot of room for improvement in the current sounds so perhaps it's hard to make it sound worse, but I would definitely study the current soundfont to get the volume, attack, length, and end for notes.

**Comment by musikboden** [comment]
> I'm also searching for a better soundfont! So let me know if you make any progress on that.
> 
> If you've got samples of every note on your accordion you can clone my soundfonts project and replace these files: https://github.com/paulrosen/midi-js-soundfonts/tree/gh-pages/FluidR3_GM/accordion-mp3
> 
> You should listen to the existing files to see how long to play each note, I guess.
> 
> I'm currently looking for a better piano soundfont to start with.

@Paul I found this site with piano sound fonts

**Comment by paulrosen** [comment]
@musikboden did you forget the link?

**Comment by musikboden** [comment]
Sorry, herr it is:
https://sites.google.com/site/soundfonts4u/
