### ISSUE TITLE
How to draw "/" per beat for chords-only score

### ISSUE THREAD

**Issue by santh** [paulrosen/abcjs#422]
Is there a way to get slashes (1 per beat) for chord-only rhythm instruments like guitar and banjo like below? I thought I saw a note about doing that, but I can't find it.

![Screen Shot 2020-06-01 at 5 16 34 PM](https://user-images.githubusercontent.com/3333015/83466367-c1313d00-a42b-11ea-9bee-6ce0a2662d91.png)

**Comment by chrisfargen** [comment]
![ardfgdfs7](https://user-images.githubusercontent.com/2993720/83468493-e84b3700-a44a-11ea-9b69-6e2fa49f9a8f.jpg)

Kinda messy, but here's how I do it:

```
%%gchordfont Times New Roman 16
%%annotationfont Times New Roman italic bold 20
"F7" "@0,-17/"x2 "@0,-17/"x2 "@0,-17/"x2 "@0,-17/"x2 | \
"Bb" "@0,-17/"x2 "@0,-17/"x2 "@0,-17/"x2 "@0,-17/"x2 |
```

**Comment by santh** [comment]
I wonder if it would be possible to add just "/" or "s" for "slash" to the parser code as a type of "rest" symbol? It is not used anywhere else, at least by itself.

**Comment by paulrosen** [comment]
Here's an example:
```
X:1
T:alternate heads
M:C
L:1/8
U:n=!style=normal!
K:C treble style=rhythm
 "Am" BBBB B2 B>B | "Dm" B2 B/B/B "C" B4 |\
 "Am" B2 nGnB B2 nGnA | "Dm" nDB/B/ nDB/B/ "C" nCB/B/ nCB/B/ |B8| B0 B0 B0 B0 |]
```
"style" can be "normal" "rhythm" "x" or "harmonic"

That example puts occasional regular notes in using the "n" macro.

Unfortunately that won't sound correctly. That's a future project.

**Comment by paulrosen** [comment]
![alternate-heads](https://user-images.githubusercontent.com/69818/83546534-d1e6bf00-a4ce-11ea-8161-fadd38d389f9.png)

**Comment by santh** [comment]
Thanks, this is what I remembered seeing.

**Comment by MisterY** [comment]
I like how Chris' solution looks! With redefinable symbols, it should not be such a drag to use.

So I tried `U: l = "@0,-13/"` but that results in:

> Music Line:1:1: Unknown macro: "@0,-13/": lx2 kc
