### ISSUE TITLE
svg.js calls 'debugger' in version 5.12.0

### ISSUE THREAD

**Issue by OrangeTux** [paulrosen/abcjs#426]
First of all, thanks for this great project! 

I'm working on a project to automatically transcribe Midi input from a electronic piano. My code generated an invalid ABC notation. When I try to render that I hit the debugger.

It turned out that in 5.12.0 the debugger is called in [src/write/svg.js:127](https://github.com/paulrosen/abcjs/blob/41871d3c2e46a484c63d5b8eb481401aadc7ea1d/src/write/svg.js#L127).

This is the invalid ABC notation that caused it:

```
 X:1
  T:1/4=76
  L:1/4
  K:C
  V:1
  M:4/4
  |[C1][z2.5D1]
  V:2
  K:C clef=bass
  M:4/4
  |z4
```

I guess `[z2.5D]` causes it. 

I understand that my ABC notation is wrong, but I think the debugger should not be called your library.

**Comment by paulrosen** [comment]
Thanks for the report. In the 6.0.0-beta.10 version it no longer has the `debugger` statement. I already caught that I had forgotten to remove the debugging code. 

In the current version there is still an error that is printed to the console so I'll catch that case before it gets that far.

**Comment by paulrosen** [comment]
Rests can not appear inside of chords, so `[z]` is not legal. (the `2.5` isn't legal either.)

I fixed it so that it won't crash when it sees that. It will be in 6.0.0-beta.11

**Comment by OrangeTux** [comment]
Thanks!
