### ISSUE TITLE
Accidentals should not display if flat or sharp is in key signature

### ISSUE THREAD

**Issue by santh** [paulrosen/abcjs#430]
Not sure how to express this except by example:

In the key of F "_B" should not display the flat accidental on staff. I assume there is the same issue for "#" in sharp keys but not tested.

![Screen Shot 2020-06-09 at 9 50 59 PM](https://user-images.githubusercontent.com/3333015/84228619-6091a800-aa9c-11ea-8354-ae1d5cffa4a9.png)

**Comment by paulrosen** [comment]
The ABC standard doesn't work that way - it doesn't make any assumptions about things like that, the same way a word processor allows you to misspell. If you are in the key of F you shouldn't use the underscore on all the B notes. The ABC string should reflect exactly what you want it to look like. 

It will still sound correctly in the audio.
