### ISSUE TITLE
Audio player CSS not generating

### ISSUE THREAD

**Issue by TylerNoblett** [paulrosen/abcjs#432]
Hi! First off, thanks so much for creating this library - it's so helpful!

I've run into an issue wherein the CSS for the audio player isn't showing up. I'm using webpack, and can confirm that the css from font awesome and abc-midi is imported because when I add something like this to either file the css renders a black background, showing me that it's not a configuration issue with webpack.
```
body {
  color: white;
  background-color: black;
}
```
However, the audio controls are just empty squares, and I'm not sure why. I'm using the latest version of chrome 83.something, and installed font awesome and abc per the instruction on abcjs.net. Everything else renders fine (as shown in the picture)
```
npm install --save-dev abcjs
npm install --save-dev font-awesome
```
Here's my file
```
import * as ABCJS from 'abcjs/midi';
import 'font-awesome/css/font-awesome.min.css';
import 'abcjs/abcjs-midi.css';

const abc = `X:1\nT:New Beatles Song\nM: 4/4\nL: 1/4\nQ: 171\nK: G\n"G"A/2"Em"A/2"G7"c/2"A"d"G"z/2"Em"A|"D7"d/2"G"c/2B"C"d/2"D"b/2"G"c|d/2"Em"f/2"G"d"D"AB/2"G"a/2|\nw: you *  can *  *  play the *  *  game After a ride The *  *  *  band\n`;
var abcOptions = { add_classes: true, responsive: "resize" };
var audioParams = { chordsOff: false };

// if (ABCJS.synth.supportsAudio()) {
	var synthControl = new ABCJS.synth.SynthController();
	synthControl.load("#audio", 
        undefined, 
        {
            displayLoop: true, 
            displayRestart: true, 
            displayPlay: true, 
            displayProgress: true, 
            displayWarp: true
        }
    );

	var visualObj = ABCJS.renderAbc("paper", 
        abc, abcOptions);
	var createSynth = new ABCJS.synth.CreateSynth();
	createSynth.init({ visualObj: visualObj[0] }).then(function () {
		synthControl.setTune(visualObj[0], false, audioParams).then(function () {
			console.log("Audio successfully loaded.")
		}).catch(function (error) {
			console.warn("Audio problem:", error);
		});
	}).catch(function (error) {
		console.warn("Audio problem:", error);
	});
```
<img width="883" alt="Screen Shot 2020-06-10 at 8 55 01 AM" src="https://user-images.githubusercontent.com/22867407/84270156-42f22c00-aaf8-11ea-9866-3000e1f81428.png">

I'm hoping that this is just basic user error of some sort - do you have any thoughts off of the top of your head?

Another thing to note is that I copied and pasted the css I needed into my src directory and tried to reference it from that folder instead of the node module, but that didn't change anything either.

**Comment by paulrosen** [comment]
Sorry for the confusion - there are two ways to generate sound because I'm in the process of moving to the new way but will remain backwards compatible. The new way has different CSS and doesn't require fontawesome. Try including the following instead:
```
import 'abcjs/abcjs-audio.css';
```

**Comment by TylerNoblett** [comment]
ah awesome! I'll give that a try. Thanks for your quick reply!

**Comment by TylerNoblett** [comment]
I'll close this ticket after I'm able to test the new CSS

**Comment by TylerNoblett** [comment]
It works!
