### ISSUE TITLE
Feature request: option to toggle jazz styling of chord symbols

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#434]
_Update: Found the functionality I'm looking for in abc2svg. [Here's a screenshot](https://user-images.githubusercontent.com/2993720/91208706-9d069480-e6d8-11ea-884a-4e3c50e53e6c.png) of jazz chords rendered using an automatic chord styling tool in abc2svg. [(Source for the extension.)](https://gist.github.com/chrisfargen/4324c6cf6fed2c8f9a6eae1680e53169)_

_Here's a [slightly messy] solution that works for individual tunes in abc2svg:_

![2020-07-23-112719_1484x523_scrot](https://user-images.githubusercontent.com/2993720/88305522-9ea6fc00-ccd7-11ea-98e8-8472aaf8133d.png)

```
%%beginsvg
<style>
.sup {
        baseline-shift: super;
        font-size:0.66em
}
</style>
%%endsvg

%%staffsep 80px
%%setfont-1 * * class=sup
%%gchordfont sans-serifBold 18
X: 1
T: Cooley's
M: 4/4
L: 1/8
R: reel
K: Emin
|:D2||\
"E$1–7"EBBA "D$17"B2 EB|"G$1∆7"~B2 AB "C$1∆7"dBAG|\
"F#$1ø7"FDAD "F#$1m7b5"BDAD|"B7$1b9"FDAD "Ab$19"dAFD|
"G"EBBA "Ab$1o7"B2 EB|"A$1min7"B2 AB "D$17sus4"defg|\
"G$1maj7$0/B"afe^c "Bb$1o7"dBAF|"A$1+7"DE"Eb$19"FD "E$1m6" E2:|
```

----

_Original post:_

![asdmea](https://user-images.githubusercontent.com/2993720/84302105-d4769380-ab22-11ea-9b6a-d71975a67f09.jpg)

It would be nice to incorporate some basic chord symbol styling. Not sure how easy this would be to implement.

I got the result above by manually tweaking the SVG using Chrome DevTools. Here's my procedure:

For each gchord of format `[note][accidental][type][/bass]`:
1. Leave `[note][accidental]` as it is.
2. Remove `[type]` from original `<tspan>` element and append new `<tspan>` element with content `[type]`:
```
<tspan dy="-0.5em" style="font-size:0.6em">[type]</tspan>
```
3. Remove `[/bass]` from original `<tspan>` element and append new `<tspan>` element with content `[/bass]`.

    a. If there is a `[type]` specified before it, move element down so that we're back to baseline:

    `<tspan dy="0.5em" style="font-size:0.6em">[/bass]</tspan>`

    b. If there is no `[type]` specified before it, we're already at baseline:

    `<tspan style="font-size:0.7em">[/bass]</tspan>`

For further consistency, I also did the following:
1. Replace degree symbol `°` with lowercase letter `o` (for diminished chords).
2. Replace hyphen `-` with en dash `–` (for minor chords).

Here's the ABC I used for testing:

```
%%gchordfont 16
X: 1
T: Cooley's
M: 4/4
L: 1/8
R: reel
K: Emin
|:D2||"E-7"EBBA "D7"B2 EB|"G∆7"~B2 AB "C∆7"dBAG|"F#ø7"FDAD "F#m7b5"BDAD|"B7b9"FDAD "Ab9"dAFD|
"G"EBBA "Ab°7"B2 EB|"Amin7"B2 AB "D7sus4"defg|"Gmaj7/B"afe^c "Bb°7"dBAF|"A+7"DE"Eb9"FD "Em6" E2:|
```

**Comment by paulrosen** [comment]
That does look better - and it would solve some spacing issues because the chords would be a little shorter. I guess this should be an option so everyone's music doesn't suddenly look different.

**Comment by chrisfargen** [comment]
> I guess this should be an option so everyone's music doesn't suddenly look different.

Maybe option could be something like `%%stylegchord`?

**Comment by paulrosen** [comment]
Will be added in beta 36
