### ISSUE TITLE
Text annotation overlaps guitar chords

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#438]
I've seen text intersection issues discussed elsewhere (e.g., #339), but I haven't seen this particular issue documented yet.

ABC code:
```
X:
M:4/4
K:
"C∆7" "^annotation" c8 |
```

ABCjs:
![2020-06-16-121331_401x227_scrot](https://user-images.githubusercontent.com/2993720/84799835-d8932d00-afca-11ea-9b48-c352a448ed75.png)

abcm2ps:
![2020-06-16-121107_383x263_scrot](https://user-images.githubusercontent.com/2993720/84799871-e8ab0c80-afca-11ea-9227-35a0cd90bc20.png)

**Comment by paulrosen** [comment]
Thanks! I am about to work on collisions and this is another good example for testing.

**Comment by paulrosen** [comment]
Fixed in beta.15
