### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#442]
In abcjs_basic_6.0.0-beta.11-min.js, I get the "cannot read..." error when using a hyphen (tie) in this line:
"[Chorus]" A>d | c4-c A B>c | d6||
In abcjs_basic_6.0.0-beta.11.js, the error does not occur.

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.12. sorry about that!
