### ISSUE TITLE
Staccato lost in beta12

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#443]
Tried this in editor-synth:
X: 1
T: Cooley's
Q:1/4=70
M: 4/4
L: 1/4
R: reel
K: Emin
CDEF
.C.D.E.F

the staccato doesn't make any difference, it worked nicely in beta 10

**Comment by paulrosen** [comment]
I'm sorry - I was in the middle of revamping that. It's in an in between state. I will put the original staccato part back in for the next beta - I hope they come fairly quickly for a while.

**Comment by musikboden** [comment]
> I'm sorry - I was in the middle of revamping that. It's in an in between state. I will put the original staccato part back in for the next beta - I hope they come fairly quickly for a while.

Ahh, I see, no hurry. Thanks!
