### ISSUE TITLE
Examples are not being servered on GitHub pages

### ISSUE THREAD

**Issue by SteveALee** [paulrosen/abcjs#444]
The examples on https://paulrosen.github.io/abcjs/audio/synthesized-sound.html#examples are 404. I suspect all exampels are similarly broken.

The reason is the examples are not in the Docs folder so are not served at `https://paulrosen.github.io/abcjs`

Solutions include copying the examples to Docs - but then you have to keep the 2 copies in sync. Or serve from github via something like [githack](https://raw.githack.com/): eg

https://raw.githack.com/paulrosen/abcjs/master/examples/basic-synth.html (dev uncached URL)

**Comment by paulrosen** [comment]
Copying them over as part of the build step sounds like the right solution. Thanks.

**Comment by SteveALee** [comment]
Definitely if you have one :)
