### ISSUE TITLE
FYI How I'm using ABCJS

### ISSUE THREAD

**Issue by SteveALee** [paulrosen/abcjs#445]
I thought you might like to see how I'm using abcjs. Thanks so much for a great package!!

musicpracticetools is an experiment in an interactive music journal come tool for remote lessons and practice. See:

- https://musicpracticetools.net/tunes/crossfire/
- https://musicpracticetools.net/tunes/about/

I'm now adding playing so I can check my transcriptions are good.

**Comment by paulrosen** [comment]
Cool! That is a great, fun way to learn bass lines! You could also add a cursor but you'd have to sync it to the music.

**Comment by SteveALee** [comment]
I'm digging into the full synth example right now. It seems to have all I could want, and more.

**Comment by SteveALee** [comment]
Highliting now works. Really happy.
Found a few issues with docs and code

**Comment by paulrosen** [comment]
I think this is taken care of.
