### ISSUE TITLE
Docs for createSynth options seems incorrect

### ISSUE THREAD

**Issue by SteveALee** [paulrosen/abcjs#447]
The docs for Create Synth show many options as properties (i think as it nevers says  POJO is passed) but the full synth example and the [code]('/css/) show an `options` property for some settings

**Comment by SteveALee** [comment]
Also it says `audioContext` is required but it is not if you use a Controller with the synth as that create one for you if required..

**Comment by SteveALee** [comment]
PS is prime() required? is not called in the synth sample. is it another thing the controller does for you?

**Comment by paulrosen** [comment]
I'm in the middle of modifying the docs. That page has been updated but is not deployed to gitpages yet. Look here for slightly newer info: https://github.com/paulrosen/abcjs/blob/master/docs/audio/synthesized-sound.md

I will be doing a documentation push as soon as I have a free moment.

AudioContext is not required to be passed in, but is recommended if you have a complicated app. There is a limit to the number of them that can be created so it's better to reuse the same one. That can affect you even if you aren't using the audio context but it just happens to not be garbage collected yet.

Yes, prime() is called by the controller so you don't have to call it if you are using the technique in full-synth.

The example and the newer documentation do show the `options` parameter.

**Comment by paulrosen** [comment]
The docs have a bit more info in them now. I'm going to continue to improve them, too. If you see other inconsistencies please let me know.
