### ISSUE TITLE
Minimalize Staff Width

### ISSUE THREAD

**Issue by mjkaufer** [paulrosen/abcjs#45]
Hi,

I think we should add support to have the staff width minimize itself, so that only the sheet music is part of the rendered svg, such that no extraneous whitespace is included. The image attached is what I'm trying to avoid.

![screen shot 2015-07-06 at 3 26 06 pm](https://cloud.githubusercontent.com/assets/1483405/8531176/87361124-23f3-11e5-93f7-c2166cf04213.png)

**Comment by hbarudin** [comment]
Bump. FWIW, fiddling with [this width parameter](https://github.com/paulrosen/abcjs/blob/0e44f4c0359b3aa62d3c05cdfc2ffc54fd928099/api/abc_tunebook.js#L152) seems to have no effect.

**Comment by paulrosen** [comment]
There is now support for `{ responsive: "resize"}`, where you can put the SVG in any bounding `div` and control the size. Is that what you want or is there another use case? If there is, please reopen.
