### ISSUE TITLE
Unpredictable audio playback when changing MIDI programs inline

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#451]
Example:

```
Q: 1/4=120
[I: MIDI=program 32]
CDEF GABc |
%
[I: MIDI=program 0]
CDEF GABc |
CDEF GABc |
```

This should result in one bar of acoustic bass followed by two bars of piano. The resulting audio playback contains almost no piano, except for the last two notes.

Same issue occurs when you reverse the order from piano to acoustic bass:

```
Q: 1/4=120
CDEF GABc |
%
[I: MIDI=program 32]
CDEF GABc |
CDEF GABc |
```

**Comment by SteveALee** [comment]
Yeah on https://musicpracticetools.net/tunes/brown-eyed-girl/ half the loaded sounds are correctly electric bass and the others are piano (0)

```
X: 1
K: G cleff=bass transpose=-8
M: 4/4
Q: 1/4=145
L: 1/8
C: Van Morrison
T: Brown Eyed Girl
R: Pop
[I: MIDI=program 33]
EF|:"G"G2z3GB2|"C"c2zce2g2|"G"g2z3c^c2|"D"d2zEzFzF:|
```

Might be related to #452 as a lot of notes are loaded compared to those used.

**Comment by paulrosen** [comment]
I can't reproduce this on the master branch - It's possible it was fixed, it's possible that there is something different about your setup. Are you using the standard soundfont?

**Comment by chrisfargen** [comment]
I'm using an unedited copy of "examples/editor-midi.html" from abcjs 6.0.0-beta.12 with Chrome 83 on Ubuntu 16.04.

Here's a recording from Chrome: [2020-06-20-14:32:01.mp3.zip](https://github.com/paulrosen/abcjs/files/4808386/2020-06-20-14.32.01.mp3.zip)

Similar results in Firefox 77. Here is the console output from Firefox:

![2020-06-20-143903_1339x462_scrot](https://user-images.githubusercontent.com/2993720/85209268-7b69e500-b304-11ea-9b3c-a7d02ee80cea.png)

**Comment by paulrosen** [comment]
Oh - try editor-synth.html example instead.

**Comment by chrisfargen** [comment]
That did it! Works in editor-synth.html just fine. Huh...
