### ISSUE TITLE
Audio clicking with synth

### ISSUE THREAD

**Issue by SteveALee** [paulrosen/abcjs#453]
I'm getting annoying clicking.when vaous music plays wit bass notes played

see : https://musicpracticetools.net/tunes/brown-eyed-girl/

It's at the end of the notes so I wonder if better zerocrossing is need on truncated samples?

here's the abc source and I found it to be same with both soundfonts though it using https://paulrosen.github.io/midi-js-soundfonts/MusyngKite/acoustic_grand_piano-mp3/

[Update: fixed the following source as discussed below]

```
X: 1
K: Eb clef=bass transpose=-32
M: 4/4
Q: 1/4=115
L: 1/8
C: Stevie Ray Vaughan
T: Crossfire
R: Rock
[I: MIDI=program 33]
P: A
|:EE_GB_dd zB|_dd zBdBez:|
P: B
|:_GGGGGG zG|AAAA z4|_GGGGGG zG|AAAA z3(eB):|
P: C
|EE_GB_dd z_g'|g'e'_d'bd'e'_g'=g'|
```

**Comment by paulrosen** [comment]
I hear it on your site but not on mine. I'm not sure what is going on offhand. And you say you also tried FluidR3 and that does the same?

**Comment by paulrosen** [comment]
BTW, I'm expecting "clef" with only one F. It falls back to the right thing, though.

And why are you escaping the underscores? It causes a parsing error, but I also recover correctly from that.

**Comment by SteveALee** [comment]
yes same with other font.

Note I have visualTranspose of -24 which i found also effects the pitch. Thats to make entering the tunes easier. I quite forgot that. The extra -8 is as bass is always transposed..  pretty sure that is correct. and you might not be playing the same low pitches = eg B1.wav & B2.wav

>And why are you escaping the underscores?

hmm - that's strange. Will check. I see no errors though

**Comment by SteveALee** [comment]
> And why are you escaping the underscores?

Turns out to be a code formater running on save! Will disable. Was lucky to get away with that!

**Comment by SteveALee** [comment]
so I guess you need

`K: Eb cleff=bass transpose=-32` ?

to get the same notes in whatever you are using?

**Comment by SteveALee** [comment]
@paulrosen Now I'm confused.

on https://musicpracticetools.net/tunes/brown-eyed-girl/

The bottom E1 on the dots is playing an Ab1! how can that be?

**Comment by paulrosen** [comment]
Oh, another thing I was going to mention but forgot: `transpose=-8` is 8 half-steps. You want `transpose=-12`.

**Comment by SteveALee** [comment]
I just figured that! Lol what a plonker! 8va confused me I guess.

Thanks so much.

**Comment by SteveALee** [comment]
And whats worse is I suggested you use  -32 rather than -36! :)

**Comment by SteveALee** [comment]
I updated the abc source in the bug report above. 

Still getting the clicking despite trying both sound fonts and different voices. Some patches are better than others

**Comment by paulrosen** [comment]
I want to get to the bottom of this but I have to recreate it. Is this project open source or can you create an example with source code?

**Comment by SteveALee** [comment]
Thanks Paul. It's not open source simple as I'm deciding if (and how) I'd like to monitise it. Ideally would be open source with an appropriate buisiness model.

It's on GitHub so I could easily add you as a contrinutor for now if you are happy that way. It's trivial to install and run locally.

**Comment by SteveALee** [comment]
@paulrosen I've made the repository public (MIT Licence)

There's an [issue for you](https://github.com/music-practice-tools/music-practice-tools/issues) which I hope will help you get going

**Comment by paulrosen** [comment]
There have been lots of changes in the the audio since version 5.12. When I upgraded to the 6.0 beta the clicking went away.

**Comment by SteveALee** [comment]
Do you have an ETA for 6.0? Are there many breaking changes?

**Comment by paulrosen** [comment]
The release notes are here: https://github.com/paulrosen/abcjs/blob/master/RELEASE.md

There are some small breaking changes - nothing that would affect what you are doing. The method of selection is different and the format of the data that is returned in the callbacks is a little different.

**Comment by SteveALee** [comment]
Thank you. Any idea why it would use a different voice?

**Comment by SteveALee** [comment]
So the API changed with the soundfont now being specified in a [new sub options object](https://github.com/paulrosen/abcjs/blob/v6.0.0-beta.12/src/synth/create-synth.js#L54-L55) :)

Is working perfectly now with NO CLICKS!!! \0/ Seems louder too.

Thanks
