### ISSUE TITLE
9/4 meter tempo issue

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#454]
This tempo is wacky unless I change the meter to something other than 9/4 time. (version 6.10 beta)

%%abc-charset utf-8

X:1
T:Came He to Bethlehem's Manger
T:8.7.8.7 D w/ Refrain
C:arr. by P. J. Mansfield
L:1/4
M:9/4
Q:1/4=200
K:G
[B3D3]-[BD][FD][GD][AD][GD][D]|[F3D3][E3C3]-[E3C3]||

**Comment by paulrosen** [comment]
ok - this will be fixed in the next beta version.

**Comment by musikboden** [comment]
> This tempo is wacky unless I change the meter to something other than 9/4 time. (version 6.10 beta)
> 
> %%abc-charset utf-8
> 
> X:1
> T:Came He to Bethlehem's Manger
> T:8.7.8.7 D w/ Refrain
> C:arr. by P. J. Mansfield
> L:1/4
> M:12/4
> Q:1/4=200
> K:G
> [B3D3]-[BD][FD][GD][AD][GD][D]|[F3D3][E3C3]-[E3C3]||

Using 12/4 will be wacky as well
