### ISSUE TITLE
Implement !beambr1!

### ISSUE THREAD

**Issue by 8633brown** [paulrosen/abcjs#455]
Using `y` as a rest uses too much space, 

Not sure if this is meant to be this way or not, but I think it makes sense for the `y` rest to not add extra space as the music is unaffected in how it's read or played. Where as the `x` rest does actually add a rest in the music.

```
L: 1/16
cccc
```
![image](https://user-images.githubusercontent.com/31827535/85248869-6037cc00-b40f-11ea-931e-98450d00dabd.png)

```
L1/16
ccy2cc
```
![image](https://user-images.githubusercontent.com/31827535/85248830-48604800-b40f-11ea-9155-5c9d5c079fa5.png)

**Comment by paulrosen** [comment]
That comes from https://abcnotation.com/wiki/abc:standard:v2.2?s[]=%2Aspacer%2A#typesetting_extra_space

**Comment by 8633brown** [comment]
Ahh thank you. So is there no way to actually just remove the top beam without adding the extra space space?

**Comment by paulrosen** [comment]
I think there is a way to specify it in ABC, but I didn't see it on a quick look. You found an interesting effect - when the y has a value of quarter note or larger it counts as a beam break. That might be a bug.

**Comment by 8633brown** [comment]
Yeah I think you're right and I'm somewhat abusing the bug.
Maybe if i put into more context what I'm doing it'll give you more of an idea of what I'm looking for.
I'm looking to write a 16th note triplet followed by two 16th notes. ie 
```
L: 1/16
(3 dcdcc
```
![image](https://user-images.githubusercontent.com/31827535/85356107-612e3380-b4cb-11ea-8759-83c96c821a6a.png)

However from the last note of the triplet to the 4th note it should only have an 8th note bar.
I'm not sure if this is specific to the music were writing or not (mostly looking at pipeband snare drumming swiss notation)
Currently I'm using the bug to write it like 
```
L: 1/16
(3 dcdy2cc
```
![image](https://user-images.githubusercontent.com/31827535/85356147-7a36e480-b4cb-11ea-91b1-d7a61c50bb92.png)

As far as I can tell musically both ways are valid but writing it with the 8th note beam helps distinguish the off beat.
However to my understanding changing the time signature changes where the 8th note beam should appear.
It's also the same issue the other way around. i.e.
```
L: 1/16
dc(3 dcd
```
![image](https://user-images.githubusercontent.com/31827535/85357804-6a210400-b4cf-11ea-8d9e-b402ba45e8b2.png)

should be rendered (without the space and the `y`)
```
L: 1/16
dcy2(3 dcd
```
![image](https://user-images.githubusercontent.com/31827535/85357851-84f37880-b4cf-11ea-897e-e9c8438795d5.png)

So i guess my issue is tied to triplet rendering rather than spacing.

**Comment by paulrosen** [comment]
In that particular case, I think triplets should do that anyway. I'd call that a bug in rendering triplets. That seems to affect only the 16th note triplets or shorter. For 8th note triplets there should probably always be a complete beam break.

I'll fix this.

**Comment by paulrosen** [comment]
I looked at other examples and I think the standard is not to break the beam but to add a bracket in this case so I did that. If you want to break the beam you can always add a space like this:
```
dc (3dcd
```
This will be in the next version.

**Comment by 8633brown** [comment]
So just to clarify, master now renders a bracket above triplets if the triplet is joined to other notes.
The issue with adding a space before `dc (3dcd` or after `(3dcd dc` this completely removes the connecting beam which is not what i'm trying to do.
In my case I only want to remove the top part of the beam and leave the bottom beam.

Looking into this more I don't think this is a triplet issue, It's actually more general than that and includes any beam.
for example the rendering of (16 32nd notes)
```
M: 4/4
L:1/32
cccccccccccccccc
```

currently looks like
![image](https://user-images.githubusercontent.com/31827535/86059975-0fccf980-ba21-11ea-919f-1a8d55647d47.png)

```
M: 4/4
L:1/32
cccccccc cccccccc
```
Adding a space is perfect for seperating beats. but to show the off-beat is a little more difficult.

[abc 2.2](http://abcnotation.com/wiki/abc:standard:v2.2#Proposed-minor-additions) has a propposed minor addition for length modifiers on `y` spacers but there is no implementation described.

```
M: 4/4
L:1/32
ccccy4cccc ccccy4cccc
```
![image](https://user-images.githubusercontent.com/31827535/86064189-b74e2a00-ba29-11ea-8869-acd099b1e136.png)

I think most music editors would calculate where the primary beam should be kept, in most situations, from the time signature, but I think that is out of scope for the standard. So i think the `y` spacer with a note length is the next best option. 
So I think ultimately I'm back to the original issue of the `y` spacer being too large, and the current implementation is correct  for `y` and `x` but perhaps `z` is wrong in that it should always completely remove the beam as visible rests shouldn't be beamed?

**Comment by chrisfargen** [comment]
![out](https://user-images.githubusercontent.com/2993720/87585137-98e46180-c6ac-11ea-9a5a-cd3e96976566.png)

FYI, here's the example from abcm2ps file `sample4.abc`.

```
X:
K:C
C///D///E///F///G///F///E///D///\
C///D///E///F///G///F///E///D/// \
"^beam break"C///D///E///F///!beambr2!G///F///E///D///\
!beambr1!C///D///E///F///!beambr2!G///F///E///D///||
```

In abc2svg, `!beambr1!` and `!beambr2!` are implemented. But `!beambr3!` throws `error Unknown decoration 'beambr3'`.

**Comment by paulrosen** [comment]
fixed in beta.15
