### ISSUE TITLE
OneSvgPerLine access from editor

### ISSUE THREAD

**Issue by 8633brown** [paulrosen/abcjs#457]
Printing a single svg can be quite awkward on most web browsers.
One of the main issues I'm coming up against is line breaks in the middle of a rendered staff.

Splitting each line into a seperate svg, I find, makes it far easier. But the editor doesnt have access to the relevant parameter for rendering.
Would it be worth giving the editor a small refactor to make use of the abc_tunebook_svg render function.

**Comment by paulrosen** [comment]
Good idea. I don't think that will be hard.

**Comment by 8633brown** [comment]
I can look I to this a little more if you have some preferences in how this is done? I think it would be a good idea if the editor made use of the API's produced from abcjs instead of directly making another if that makes sense?

**Comment by paulrosen** [comment]
I just checked in something that might help. That code is some of the oldest code in the project and it has barely changed. The editor's parameters should now match renderAbc.

**Comment by paulrosen** [comment]
fixed in beta.13
