### ISSUE TITLE
Synth options qpm and defaultQpm have no effect

### ISSUE THREAD

**Issue by 8633brown** [paulrosen/abcjs#461]
The options hash is being passed in to the midi sequencer okay as far as i can tell 
https://github.com/paulrosen/abcjs/blob/e91c4394d8897e5d16aa79ed465f447652e6697f/src/midi/abc_midi_sequencer.js#L108-L121
But it doesnt seem to have any effect on the music played.
I believe it's using the default value set here
https://github.com/paulrosen/abcjs/blob/e91c4394d8897e5d16aa79ed465f447652e6697f/src/data/abc_tune.js#L1375-L1392

**Comment by paulrosen** [comment]
Thanks for the report.

I plan to fix all the tempo-related issues this weekend. There's some refactoring to do.

**Comment by dantam** [comment]
Is this still a problem? "Q:" appears to work fine on [demo page](https://www.abcjs.net/abcjs-editor.html), but not on a [react wrapper](https://fuhton.com/react-abc/example/#/editor)

**Comment by paulrosen** [comment]
You are using the old midi system that is deprecated and has a number of bugs. See the example `/examples/full-synth.html` in this repo for how to use the new system.
