### ISSUE TITLE
Any plans for a Bower package?

### ISSUE THREAD

**Issue by hbarudin** [paulrosen/abcjs#47]
Hello -

Quick question: I've just discovered the joy of Bower, and I'm currently working on a project that uses ABCJS. Any thought of releasing ABCJS as a Bower package? This would allow developers using ABCJS to keep their versions up to date more easily. I would also be willing to help if that would aid in the process! Seems pretty easy: http://bower.io/docs/creating-packages/

In any case, thanks for this great code and all your hard work!

**Comment by paulrosen** [comment]
I haven't used Bower, but I'm open to supporting it if you help. I guess I just need to add bower.json and do a couple of commands to register it?

**Comment by hbarudin** [comment]
Delayed response, sorry. Yes, looks like you'd need to add a `bower.json` file ([here's some specs on that](https://github.com/bower/spec/blob/master/json.md)) as well as go through the registration process (a couple of commands, like you said). One good thing about this is you could use Bower to maintain your dependency on Raphael and JQuery. They do suggest some maintenance things, like using semver Git tag (which it looks like you're already doing, or close to). As I said back in Oct, I'm happy to do this and submit a pull request if you'd like, just give me the go-ahead and I'll go for it.

**Comment by paulrosen** [comment]
Hi, thanks for the offer! I sent you some details to your email address. I'm not sure if you got it.

**Comment by hbarudin** [comment]
Hello! Yes I got your email, I just haven't had a chance to sit and write a thought out response yet. Soon, though, I swear!

**Comment by paulrosen** [comment]
I've created an npm version. I'd love to get your feedback about whether that works for you. You can now install it with "npm install abcjs --save".

**Comment by paulrosen** [comment]
Let me know if there is more work needed for Bower, or whether the npm package support is sufficient.
