### ISSUE TITLE
Feature request: functions for play/pause/stop/repeat

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#470]
This may already be available, I just haven't found it. I would like the ability to play/pause/stop/repeat playback based on click events elsewhere on the page without being limited to using the provided player. This would allow use of my own existing player as well as stopping playback when a user switches songs, etc.

**Comment by paulrosen** [comment]
See the basic-synth.html demo.

Use this object:
```
midiBuffer = new ABCJS.synth.CreateSynth();
```
instead of the `SynthControl`.

That has start(), pause(), resume(), seek(percent), and stop() properties.
