### ISSUE TITLE
Feature Request: Chord symbol playback should take chord symbol placement into account

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#472]
```
K: Gmin
P: Devil in the Straw Stack
|: "Gm" GFDF GFDF | GF D2 "F" C4 | "Gm" GFDF G2 d2- | "Dm" dcAc dcAc |
"Gm" GFDF GFDF | GF D2 "F" C4 | "Gm" GFDF G2 d2- | "Dm" dc A2 "Gm" G4 :|
```

In the tune above, the second measure contains a chord symbol specified on the third beat. There is no chord symbol specified on the first beat. abcjs audio playback currently interprets this as four beats of "F". However, the typical interpretation of this would be two beats of "Gm" followed by two beats of "F".

There is a workaround that involves explicitly specifying "Gm" on the first beat of such measures. However, most existing ABC tunes do not include this "courtesy" chord symbol, thus requiring the user to take the extra step of adding extra chord symbols to achieve proper playback for each tune. Also, mid-measure chord changes are common in many of the styles of music for which ABC notation is widely used in the community.

Irish trad:

```
K: Edor
P: Drowsy Maggie
|: "Em" E2 BE dEBE | E2 BE "D" AFDF | "Em" E2 BE dEBE | "C" BABc "D" dAFD |
"Em" E2 BE dEBE | E2 BE "D" AFDF | "Em" E2 BE dEBE | "C" BABc "D" dAFD :|
```

Bluegrass:

```
K: Amix
P: The Red Haired Boy
|: AF || "A" E2A2 ABcd | efec "D" d2cd | "A" e2A2 ABcA | "G" BAEF G2 GF |
"A" E2A2 ABcd | efec "D" d2cd | "A" e2 a2 "E" afed | "A" c2A2A2 :|
```

1920's Jazz:

```
K: Fmaj
P: Honeysuckle Rose
"G-7" .e2 (3:2:3 ded "C7" G2 z2 | "G-7" .e2 (3ded "C7" Ge z d | \
"G-7" .e2 (3ded "C7" G2 z2 | "G-7" .e2 (3ded "C7" Gd z d |
"F" z d z d ._d2 .d2 | c2 Ac "C7" z2 dd | \
"F" z d2 d ._d2 .d2 | c2 Ac "Abdim7" z c d^d ||
```

Just my two cents! I think it would be a well-received change to the playback functionality, which is where abcjs really excels over alternatives such as abc2svg.

**Comment by chrisfargen** [comment]
Incidentally, this is in the neighborhood of #366.

**Comment by paulrosen** [comment]
That's a bug - it used to work like you describe. It will be fixed in the next beta.

**Comment by chrisfargen** [comment]
Thanks Paul!
