### ISSUE TITLE
CursorControl onLineEnd(data) event not working on the last line

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#476]
Hi Paul

I noticed that starting from beta.8 release the onLineEnd() event seems to work differently from the previous release on the last line.
The data object seems to be corrupted or incomplete.
Below you can find a console.log message; ( 		console.log(" ON LINEEND" + JSON.stringify(data));   )

the song has 4 measures on 2 lines. As you can see at measure number 4 the event is fired but the object is incomplete.

ON LINEEND {"measureNumber":2,"milliseconds":4486,"top":258.590625,"bottom":386.028125}
 ON LINEEND{"measureNumber":4,"milliseconds":8972,"bottom":null}
 ON LINEEND{"measureNumber":2,"milliseconds":4486,"top":258.590625,"bottom":386.028125}
  ON LINEEND{"measureNumber":4,"milliseconds":8972,"bottom":null}

Thank You
Osvaldo

**Comment by paulrosen** [comment]
I didn't go back to the previous release but I thought that is how it always worked - if `top` is not defined that means the tune is over. 

What values would make sense for `top` and `bottom` at this point? I'm open to suggestions.

**Comment by osvi64** [comment]
Hi Paul
You are right, I didn't analyze my issue correctly. The difference from beta 7 (and previous) to 8 (and following) is that the onLineEnd() event is no more fired at the beginning of the song

Below the same song log with release 7

 ON LINEEND{"milliseconds":0,"top":60.135625000000005,"bottom":212.760625}
 ON LINEEND{"milliseconds":6372,"top":250.840625,"bottom":372.465625}
ON LINEEND{"milliseconds":9558,"bottom":null}
 ON LINEEND{"milliseconds":0,"top":60.135625000000005,"bottom":212.760625}

As you can see the event is fired also at millisecond 0 while in release 8 and following not.

Generally speaking, is probably correct that the event is not fired at the beginning as it is called onlinend. 
My issue is; I have the loop button on , so the music is restarting automatically. With previous versions, as the event is fired also at the beginning, the score is scrolling back to the top. (I have some scrolling instructions on the event).

I solved now testing if info.top is not defined and assuming that it means that the end of the song is reached.
Is it the correct solution or do you think that returning to the top has a better one?
If I'm doing well, you can close the issue. Sorry for opening the issue without completely understanding the point.

Thank you so much for your work
Osvaldo

**Comment by paulrosen** [comment]
You're right, it should be called at the beginning if it has looped there. It wouldn't be called at the beginning the first time, though. If it is looping it shouldn't emit the end event.
