### ISSUE TITLE
[P:] is buggy

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#481]
Something has changed the "in abc-string" [P:] function 
The [P:] function in this song worked fine before beta 13, but now I found that the [P:] in the first line resulted in this error:
`Uncaught TypeError: Cannot read property '0' of undefined
    at abcjs_basic_6.0.0-beta.13-min.js:3
    at e.exports.appendElement (abcjs_basic_6.0.0-beta.13-min.js:3)
    at e.exports.letter_to_inline_header (abcjs_basic_6.0.0-beta.13-min.js:3)
    at abcjs_basic_6.0.0-beta.13-min.js:3
    at r (abcjs_basic_6.0.0-beta.13-min.js:3)
    at abcjs_basic_6.0.0-beta.13-min.js:3
    at Object.each (abcjs_basic_6.0.0-beta.13-min.js:3)
    at e.exports.parse (abcjs_basic_6.0.0-beta.13-min.js:3)
    at Object.s.renderEngine (abcjs_basic_6.0.0-beta.13-min.js:3)
    at Object.e.exports [as renderAbc] (abcjs_basic_6.0.0-beta.13-min.js:3)`

I have 3 [P:] in this song but only the first one causes the error, if I remove the first it works as it should.
This is the song:

X:1
T:Tetris
C:från dataspelet "Tetris"
%%printtempo 0
Q:1/4=80
L:1/8
M:4/4
I:linebreak $
K:Am 
[P:A-läge]"E7"!5!e2 !2!B!3!c !4!d2 !3!c!2!B | "Am"!1!A2 !1!A!3!c !5!e2 !4!d!3!c | "E7"!2!B3 !3!c !4!d2 !5!e2 | "Am"!3!c2 !1!A2 !1!A4 ||
|:[P:D-läge]"Dm"z !1!d2 !3!f "G"!5!a2 !4!g!3!f | "C"!2!e3 "^sträck o;dra ihop"!1!c [P:A-läge]!5!e2 !4!d!3!c | "E7"!2!B2 !2!B!3!c !4!d2 !5!e2 | "Am"!3!c2 !1!A2 !1!A4 :|

**Comment by paulrosen** [comment]
Sorry! Will fix this weekend.

**Comment by musikboden** [comment]
In this test, the [P:] will break the beaming and also create gaps in the notation ( second beat second bar)

![Skärmavbild 2020-07-17 kl  08 22 40](https://user-images.githubusercontent.com/18282700/87755131-b2012580-c806-11ea-8669-4a6f4bfc7945.png)

**Comment by paulrosen** [comment]
The extra gap is caused by the length of the chord. If you remove the chord then there is no extra gap.

I've never seen a part start in the middle of a measure before. What does that even mean?

**Comment by paulrosen** [comment]
In the first example I'm not seeing the crash. Can you post the code you are using that causes it?

**Comment by musikboden** [comment]
> In the first example I'm not seeing the crash. Can you post the code you are using that causes it?

It is this code:

X:1
T:Tetris
C:från dataspelet "Tetris"
%%printtempo 0
Q:1/4=80
L:1/8
M:4/4
I:linebreak $
K:Am
[P:A-läge]"E7"!5!e2 !2!B!3!c !4!d2 !3!c!2!B | "Am"!1!A2 !1!A!3!c !5!e2 !4!d!3!c | "E7"!2!B3 !3!c !4!d2 !5!e2 | "Am"!3!c2 !1!A2 !1!A4 ||
|:[P:D-läge]"Dm"z !1!d2 !3!f "G"!5!a2 !4!g!3!f | "C"!2!e3 "^sträck o;dra ihop"!1!c [P:A-läge]!5!e2 !4!d!3!c | "E7"!2!B2 !2!B!3!c !4!d2 !5!e2 | "Am"!3!c2 !1!A2 !1!A4 :|

**Comment by paulrosen** [comment]
I meant the JavaScript - I tried that tune and it worked for me in the editor, so I figure it is something odd with the way it was called. I'll try in some different environments and see if I can get it to fail.

**Comment by paulrosen** [comment]
I tried again and couldn't cause the crash.

**Comment by musikboden** [comment]
> I tried again and couldn't cause the crash.

I guess I've messed up the code my code on this one, I'm sorry forget this.
