### ISSUE TITLE
chord placement on the first line of music, beta 13

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#482]
Since beta 13, the chord names are closer to the staff and collidate with the fingering, and this only occurs
at the first line of music as I can see
![Skärmavbild 2020-07-14 kl  23 07 08](https://user-images.githubusercontent.com/18282700/87476822-52005880-c627-11ea-95ed-b9af78d10986.png)

**Comment by paulrosen** [comment]
Will look at this weekend.

Can you post your ABC string?

**Comment by musikboden** [comment]
> Will look at this weekend.
> 
> Can you post your ABC string?

Here it is:

X:1
T:Tetris
C:från dataspelet "Tetris"
%%printtempo 0
Q:1/4=80
L:1/8
M:4/4
I:linebreak $
K:Am 
"E7"!5!e2 !2!B!3!c !4!d2 !3!c!2!B | "Am"!1!A2 !1!A!3!c !5!e2 !4!d!3!c | "E7"!2!B3 !3!c !4!d2 !5!e2 | "Am"!3!c2 !1!A2 !1!A4 ||
|:[P:D-läge]"Dm"z !1!d2 !3!f "G"!5!a2 !4!g!3!f | "C"!2!e3 "^sträck o;dra ihop"!1!c [P:A-läge]!5!e2 !4!d!3!c | "E7"!2!B2 !2!B!3!c !4!d2 !5!e2 | "Am"!3!c2 !1!A2 !1!A4 :|

**Comment by musikboden** [comment]
I made a test with the "editor-synth.html" and the gchords line is at the same height from the staff, regardless the fingering positions and the music pitch.
So it doesn't seem to be a problem with the **first** line of music, it has to do with the note pitch.
The fingering positions follow the note placements but the chords doesn't

X:1
T:Test
M:4/4
K:C
"C"!1!C!2!D"C/B"!3!E!1!F "Am"!2!G!3!A"C/G"!4!B!1!c | "Dm/F"!2!d!3!e"Ebmaj7"!1!f!2!g "Dm"!3!a"Db7"!4!b "C"!5!c'2 |

![Skärmavbild 2020-07-17 kl  08 08 59](https://user-images.githubusercontent.com/18282700/87754256-c93f1380-c804-11ea-9b24-4faa2e55fc58.png)

If it would be possible to adjust the chord position in the ABC line, I have not found any gchord-spacing option.

**Comment by paulrosen** [comment]
I see - the fingering doesn't add to the height of the note. If it did then the chord row would be pushed up. Thanks for the report.

**Comment by musikboden** [comment]
It works fine now, thanks!
