### ISSUE TITLE
Time signature not repeated across parts

### ISSUE THREAD

**Issue by SteveALee** [paulrosen/abcjs#483]
I don't know if this is correct behaviour or not but it seems inconsistent .

In a multi part ('P') tune the key signature declared in the header is repeated at the start of each part but the time signature is not..eg

![image](https://user-images.githubusercontent.com/618922/87521392-3c694e00-c67c-11ea-8929-1aa84e0c6c37.png)

**Comment by paulrosen** [comment]
From what I can see it is just one voice so I don't think the time signature should be repeated.

**Comment by paulrosen** [comment]
I guess this is not a problem. If you still think there is an issue, please reopen.
