### ISSUE TITLE
Multiple repeats not handled correctly

### ISSUE THREAD

**Issue by SteveALee** [paulrosen/abcjs#484]
The spec says "By extension, `|::` and `::|` mean the start and end of a section that is to be repeated three times, and so on."

but `|:: ... ::|` is converted to `|: .... :|:`

**Comment by paulrosen** [comment]
Yeah, the multiple repeats are not supported. That's not standard notation.

**Comment by SteveALee** [comment]
> That's not standard notation.

but it is in the standard! :)
