### ISSUE TITLE
Different classes for every note

### ISSUE THREAD

**Issue by rockgobo** [paulrosen/abcjs#49]
I am trying to write a little extension that mark every note with a different Color according to my rainbow bells that have a specific color for different notes (8 bells for one octave going from C to C). Is there a nice way to add the tone pitch of a note as a CSS Class so that i can use Colors for different note.

I also plan the same mechanism when my boomwhrackers have been shipped as they also use Colors for different pitches.

**Comment by rockgobo** [comment]
Ok, I figured out where the notes are drawn and changed the file draw/abc_absolute_element.js a little bit. In the line where the type is pushed in the endGroup i added pitch_{x} to the type. I think that is not the most elegant Version but it works for me. Now i get a css-class to the note elements and can change the color using this class.


![vollbildaufzeichnung 24 11 2015 144004 bmp](https://cloud.githubusercontent.com/assets/3286890/11368310/66f89a28-92b9-11e5-912b-5b52689f4279.jpg)

**Comment by paulrosen** [comment]
Have you tried `{ add_classes: true }` when initializing?

That is:

`tuneObjectArray = ABCJS.renderAbc(output, tunebookString, parserParams, { add_classes: true }, renderParams)`

**Comment by rockgobo** [comment]
yes I do that but that only adds the class "note" to every not, i also needed the pitch (hope that is the correct english term) ... like pitch_0 for a C note.

**Comment by jocoolie** [comment]
It'd be great if this were an initialization setting, with the option to
toggle relative pitch (do-re-mi, think shapenote singing) and absolute
pitch (a-b-c). How should octave displacement be handled?

Looks to me like rests are coming out as C though.

**Comment by rockgobo** [comment]
I realy like this project! It would be interessting to know how I can add another style to the system. Something like big round circles instead of exact nodes. 

Or maybe somthing like this:
![11140-4](https://cloud.githubusercontent.com/assets/3286890/11421356/7a6f3a54-9434-11e5-84d0-6c661f2bc00e.jpg)

**Comment by paulrosen** [comment]
As far as a different style for each pitch, that wouldn't be too hard to add in the same place that the other classes are added. I don't think I would get around to it soon -- I'm working on some midi features at the moment, but I'd accept a pull request if it were generic enough. I'd suggest a class for the pitch (perhaps p0, p1) and a class for the octave (perhaps o3, o4).

As far as another style, if it is just a matter of the size of the notes, you can use the %%scale directive. Otherwise, you need to draw the style yourself and add it to the glyphs. Look at how the alternate noteheads https://github.com/paulrosen/abcjs/blob/master/abc-notation.md are handled for an example.

**Comment by paulrosen** [comment]
Version 3.3.2 has a number of new classes that should allow you to narrow down each individual note.

**Comment by Seanmcdon** [comment]
not sure if this helps, and I can't really remember what I did, but I use the colors red and blue for left/right hand handchimes. If this interests anyone send me a message.


<img width="656" alt="Screen Shot 2020-04-28 at 10 01 26 AM" src="https://user-images.githubusercontent.com/8369966/80496495-47db9180-8937-11ea-8072-b582ecf2b3d3.png">

**Comment by jpgm317** [comment]
It would be nice if we could !mark! an individual note in a chord, to draw attention to particular notes in a chord.  However, if one tries to do this in abc notation by marking the G notehead in a C Major chord [CE !mark!G] , the chord is rendered as broken notes (no longer a chord), even though the abcNotation is enclosed in brackets.

**Comment by proxy-m** [comment]
Smth like this https://github.com/proxy-m/abcjs-colored/blob/abcjs-colored/examples/editor.html

`abcjsParams: {add_classes: true}`

```
	<style>
		.abcjs-p-28, .abcjs-p-21, .abcjs-p-14, .abcjs-p-7, .abcjs-p0, .abcjs-p7,  .abcjs-p14, .abcjs-p21, .abcjs-p28 {
			fill: red; /*C*/
		}
		.abcjs-p-27, .abcjs-p-20, .abcjs-p-13, .abcjs-p-6, .abcjs-p1, .abcjs-p8,  .abcjs-p15, .abcjs-p22, .abcjs-p29 {
			fill: sandybrown; /*D*/
		}
		.abcjs-p-26, .abcjs-p-19, .abcjs-p-12, .abcjs-p-5, .abcjs-p2, .abcjs-p9,  .abcjs-p16, .abcjs-p23, .abcjs-p30 {
			fill: gold; /*E*/
		}
		.abcjs-p-25, .abcjs-p-18, .abcjs-p-11, .abcjs-p-4, .abcjs-p3, .abcjs-p10, .abcjs-p17, .abcjs-p24, .abcjs-p31 {
			fill: green; /*F*/
		}
		.abcjs-p-24, .abcjs-p-17, .abcjs-p-10, .abcjs-p-3, .abcjs-p4, .abcjs-p11, .abcjs-p18, .abcjs-p25, .abcjs-p32 {
			fill: lightskyblue; /*G*/
		}
		.abcjs-p-23, .abcjs-p-16, .abcjs-p-9,  .abcjs-p-2, .abcjs-p5, .abcjs-p12, .abcjs-p19, .abcjs-p26, .abcjs-p33 {
			fill: blue; /*A*/
		}
		.abcjs-p-22, .abcjs-p-15, .abcjs-p-8,  .abcjs-p-1, .abcjs-p6, .abcjs-p13, .abcjs-p20, .abcjs-p27, .abcjs-p34 {
			fill: purple; /*B*/
		}
	</style>
```
