### ISSUE TITLE
responsive not working

### ISSUE THREAD

**Issue by mxbastian** [paulrosen/abcjs#496]
hi guys,

ich need your help. I use abcjs in following way: https://gracile-software.de/projects/ZDF_Mark/random.php
Click on a song to enter the player. How can i do paper area resize for mobile view? It is in a extra div and i add:

function initEditor() {
  new ABCJS.Editor("abc", { paper_id: "paper",
  synth: {
  el: "#audio",
  options: { displayLoop: true, displayRestart: true, displayPlay: true, displayProgress: true, displayWarp: true }
  },
 generate_warnings: true,
 warnings_id:"warnings",
 abcjsParams: {
 generateDownload: true,
 **resposive: "resize",**
 clickListener: selectionCallback
}
});
}
window.addEventListener("load", initEditor, false);

But it is'n working. What i do wrong?

Thx a lot and kind regards from Berlin, Germany!

**Comment by paulrosen** [comment]
I don't know if that is a typo here or in your code, but you are missing an "n": "responsive". 

If that doesn't work then it probably is an interaction with other css or the structure of your html. I would need to see more code to tell.

**Comment by mxbastian** [comment]
Jesus, it works. A bit embarrassing now *facepalm*. But thx for your quick response.

Now for something completely different: Is there a way to add different instruments to the Player?

Best regards

**Comment by paulrosen** [comment]
Add this to your ABC string:
```
%%MIDI program 40
```
Where the number is one off from the MIDI standard. So the "40" above is actually MIDI instrument "41". (That is to be compatible with other ABC programs.)
