### ISSUE TITLE
Line breaks in multi-staff scores

### ISSUE THREAD

**Issue by avnerdorman** [paulrosen/abcjs#497]
I am having trouble with line-breaks in multi-staff scores. Here's an example - the left hand is splitting in the correct spots (as it does in "Easy ABC" but the right hand is all over the place in my site using abcjs. Any idea why this would happen? 

X:1
T:Trio Sonata in D Minor
T:Theme
C:Antonio Vivaldi
%%score { 1 | 2 }
L:1/8
Q:1/4=108
M:3/4
I:linebreak $
K:F
V:1 treble 
V:2 bass 
V:1
[dF]6 | [^cE]6 | [dF]6 | [eG]6 | [fA]6 | [eG]6 | [dF]6 | [^cE]6 | [dF]6 | [^cE]6 | [dF]6 | [eG]6 | 
[fA]6 | [eG]6 | [dF]2 [^cE]4 | [dD]6 |] 
V:2
D,2 D,3 D, | A,,2 A,,3 A,, | D,2 D,3 D, | C,2 C,3 C, | F,2 F,3 F, | C,2 ^C,3 C, | D,2 B,,3 G,, | 
A,,2 A,G,F,E, | D,2 D,3 D, | A,,2 A,,3 A,, | D,2 D,3 D, | C,2 C,3 C, | F,2 F,3 F, | C,2 ^C,3 C, | 
D,G, A,2 A,,2 | D,6 |]

**Comment by paulrosen** [comment]
Line breaks are determined by the physical line break in the abc code. The "linebreak" parameter is not supported yet in abcjs.

**Comment by avnerdorman** [comment]
Thank you! I didn't realize that!

**Comment by avnerdorman** [comment]
Do you know of a tool that would add line breaks to abc files? Say every 4 or 6 bars? I am importing xml files into EasyABC - and doing this manually is taking a lot of time...

Thanks!

**Comment by paulrosen** [comment]
When calling `renderAbc` you can add the wrap parameter. Something like this: `{ staffwidth: 700, wrap: { minSpacing: 1.8,maxSpacing: 2.8,preferredMeasuresPerLine: 4} }`. You need to tell it the desired width of the staff then the spacing parameters will help with not cramming the notes too close. It will attempt preferredMeasuresPerLine unless that would make the spacing weird.

**Comment by avnerdorman** [comment]
Great and thanks!! You just saved me many hours of work! 👍
