### ISSUE TITLE
Tempo question

### ISSUE THREAD

**Issue by avnerdorman** [paulrosen/abcjs#499]
In the same example I posted before, the tempo playback through the synth seems to be off by a factor of 3. When I keep it the way it is below, the quarter note is 324 I believe. When I write q=54 it's a good tempo (as if dotted half is 54). I think this has something to do with "L:1/8" - never had this issue with other scores. 

My question is, how do I override the tempo in the synth? I see that there's an option for that, but I can't quite decipher the syntax. 
Thanks!

X:1
T:Trio Sonata in D Minor
T:Theme
C:Antonio Vivaldi
%%score { 1 | 2 }
L:1/8
M:3/4
Q:1/4=108
K:F
V:1 treble 
V:2 bass 
V:1
[dF]6          | [^cE]6          |  [dF]6          | [eG]6        |  [fA]6        | [eG]6         | [dF]6          | [^cE]6 | [dF]6 | [^cE]6 | [dF]6 | [eG]6 |
[fA]6          | [eG]6           |  [dF]2 [^cE]4   | [dD]6        |]
V:2
D,2   D,3 D,   | A,,2   A,,3 A,, |  D,2   D,3 D,   | C,2   C,3 C, |  F,2   F,3 F, | C,2   ^C,3 C, | D,2   B,,3 G,, |
A,,2  A,G,F,E, | D,2    D,3 D,   |  A,,2  A,,3 A,, | D,2   D,3 D, |  C,2   C,3 C, | F,2   F,3 F,  | C,2   ^C,3 C,  |
D,G,  A,2 A,,2 | D,6             |]

**Comment by paulrosen** [comment]
This is a bug that I've recently fixed. I will have a new beta out soon with this in it. Look for 6.0.0-beta.14.

**Comment by avnerdorman** [comment]
Thank you!
