### ISSUE TITLE
Note heads overlapping

### ISSUE THREAD

**Issue by GiacomoCaruso** [paulrosen/abcjs#50]
Hello, I guess there is an issue when multiple voices are a second apart. The two note heads should not overlap. The note head of the second voice should be displayed a bit more to the right, so that doesn't overlap. Is there a way to overcome this problem?

ex. abcjs
<img width="19" alt="screen shot 2015-12-04 at 13 27 23" src="https://cloud.githubusercontent.com/assets/16151765/11590054/d2c7d9ea-9a8d-11e5-9bb1-139f8ba5ef7a.png">

ex. sibelius 7
<img width="32" alt="screen shot 2015-12-04 at 13 54 37" src="https://cloud.githubusercontent.com/assets/16151765/11590156/970c5e5c-9a8e-11e5-9bfe-f0c5d96adbe3.png">

**Comment by paulrosen** [comment]
Yes, that's a bug. I haven't looked into it yet, but I'm guessing it won't be easy to fix. I've put it on my list. Sorry about that.

**Comment by paulrosen** [comment]
I'm closing some old issues due to inactivity. I have this feature on my list to do when I have time.
