### ISSUE TITLE
abcjs_basic_6.0.0-beta.14-min.js:3 Uncaught TypeError: Cannot set property 'ABCJS' of undefined

### ISSUE THREAD

**Issue by jepcolombia** [paulrosen/abcjs#502]
Hi Paul,
doing an import of the module I get the following
abcjs_basic_6.0.0-beta.14-min.js:3 Uncaught TypeError: Cannot set property 'ABCJS' of undefined
    at abcjs_basic_6.0.0-beta.14-min.js:3
    at abcjs_basic_6.0.0-beta.14-min.js:3

**Comment by paulrosen** [comment]
What is your environment? What browser are you using? Are you loading the library in using a script tag in an html document?

**Comment by jepcolombia** [comment]
Iam using a .js module with first instrucction:        import "abcjs_basic_6.0.0-beta.14-min.js" 
or.        import abcjs from "abcjs_basic_6.0.0-beta.14-min.js"
or.        import * as abcjs from "abcjs_basic_6.0.0-beta.14-min.js"
and it fails (it works with previos versions)
Iam using crome

**Comment by jepcolombia** [comment]
Google Chrome Versión 84.0.4147.105 (Build oficial) (64 bits)

**Comment by jepcolombia** [comment]
using safari:

undefined is not an object (evaluating 'e.ABCJS=t()')

**Comment by paulrosen** [comment]
Are you using node_modules?

If so, you can add `"abcjs": "6.0.0-beta.14",` to the package.json file and run `npm install`. Then use the import statement `import abcjs from "abcjs";`.

If not, you can add the statement:
```
<script src="path/to/abcjs_basic_6.0.0-beta.14-min.js" type="text/javascript"></script>
```
to your html file directly.

**Comment by jepcolombia** [comment]
Oh I see the package.json is left in a very previous version 5.xx.xx and had to be updated manually , right?

**Comment by paulrosen** [comment]
To get the beta version you have to specify it directly. If you just `npm add abcjs` you'll get the last "official" version. Is that what you mean?

**Comment by jepcolombia** [comment]
oh Ok. got it
