### ISSUE TITLE
From  abcjs_basic_6.0.0-beta.10-min.js version  to beta.15 ,animation goes unsync (using this tune and full-synth example)

### ISSUE THREAD

**Issue by jepcolombia** [paulrosen/abcjs#507]
X:1
T:Title
C:Composer
L:1/8
M:4/4
K:F
V:1 treble nm="Piano" snm="Pno."
V:1
[Q:1/4=129.0476605][df][Bd][Bd][Bd] [df][Bd][Bd][Bd] |[Q:1/4=127][df][Bd][Bd][Bd] [df][Bd][Bd][Bd] |
[Q:1/4=131] [Af][Ac][Ac][Ac] [Af][Ac][Ac][Ac] |[Q:1/4=130] [Af][Ac][Ac][Ac] [Af][Ac][Af][Ac] |[Q:1/4=127][ce]2 z2{/E} GE [Cc]2 |
[Q:1/4=124.0058861] CEGB AcBG |[Q:1/4=123.1818487] F2 z2{/A} cG F2 |[Q:1/4=131] [df][Bd][Bd][Bd] [df][Bd][Bd][Bd] |
[Q:1/4=128.2966904] [df][Bd][Bd][Bd] [df][Bd][Bd][Bd] |[Q:1/4=131] [Af][Ac][Ac][Ac] [Af][Ac][Ac][Ac] | [Q:1/4=131][Af][Ac][Ac][Ac] [Af][Ac][Af][Ac] |[Q:1/4=128] [ce]2 z2{/E} GE [Cc]2 | 
[Q:1/4=130.0973779]CEGB AcBG |[Q:1/4=126.1148023]{/F} AF{/F} f2 z FAc |[Q:1/4=125.0124361][df] [df]2 [df] [df]2 [df][df]- |[Q:1/4=130] [df] [ce]2 [Bd] [Ac]2 [Bd][ce]- | 
[Q:1/4=127.4149784][ce] [CEc]2 z z CEG |[Q:1/4=127.0526951] [ce] [ce]2 [ce] [ce]2 [ce][ce]- |[Q:1/4=129.0322581] [ce] [Bd]2 [Ac] [GB]2 [Ac][dB]- |[Q:1/4=129] [dB] [Ac]2 z2 FAc |
[Q:1/4=129.241546] [df] [df]2 [df] [df]2 [df][df]- |[Q:1/4=129.0322581] [df] [ce]2 [Bd] [Ac]2 [Bd][ce]- | [Q:1/4=133] [ce]deg [ac']2 [gB]2 |  
[Q:1/4=133]z z2 z2 [Ac][Ac][Bd] | [Q:1/4=127][ce] [ce]2 [ce] [ce]2 [ce][ce]- |[Q:1/4=133] [ce] [Bd]2 [Ac] [GB]2 [Ac][Bd]- |  
[Q:1/4=128][Bd]cfa [Bd']2 [ac']2 |[Q:1/4=127] z z z z z CFA | [Q:1/4=128][Bd] [Bd]2 [Bd] [Bd]2 [Ac][ce]- | 
[Q:1/4=134][ce] [Bd]2 [Ac] [GB]2 [FA][EG]- |[Q:1/4=131] [EG]ceg c'Bge |[Q:1/4=129.1907598] c2 z2 z CEG |  
[Q:1/4=131][Ac] [Ac]2 [Ac] [Ac]2 [ce][eg]- |[Q:1/4=136] [eg] [ce]2 [Ac] [Ac]2 [GB]{/F}A |[Q:1/4=124.4219563]  F{/A} f3{/A} cA{/F}AF | 
[Q:1/4=127.4149107]z F2 [Bd]2 [Bd] [df]2- | [Q:1/4=130.0973779][df]{/A} c2 [ce]{/B} d2 [CEc]2- |[Q:1/4=133] [CEc] [CEc]2 [Ac]2 [Ac] [ce]2- |
[Q:1/4=130.0973779] [ce] [Bd]2 [Bd]{/A} c2 [FA]2- |[Q:1/4=131] [FA] F2 [Bd]2 [Bd] [df]2 |]

**Comment by jepcolombia** [comment]
using beta.14 the greater unsync
Thanks Paul for your project an help

**Comment by jepcolombia** [comment]
the different on my tune is measure times changing I think

**Comment by paulrosen** [comment]
Ok, thanks. That's a good test case. Another beta soon, I hope.

**Comment by paulrosen** [comment]
fixed in beta 16
