### ISSUE TITLE
[feature request] ottava support

### ISSUE THREAD

**Issue by grigoriliev** [paulrosen/abcjs#51]
Hi,
First, thank you for your great work!
I would like to request a support for the ottava keyword in abcjs.
Section 4.6.6 in the ABC standard v2.1:
"An important item of notation concerns passages written in a different octave, to save ledger lines. Such a passage is marked by a dashed line starting with something like "8va". "

**Comment by paulrosen** [comment]
That *is* a missing feature in ABC. 

It looks like what you are pointing to is just a proposal, though -- the syntax for input isn't specified exactly and the proposal is overly complicated.

I'd personally be in favor of `!8va(!`  to start and `!)8va!` to end for the octave higher. For the octave lower, the proposal suggested `!8vb(!` which seems a little odd to me, but I don't know anything better.

**Comment by grigoriliev** [comment]
The syntax you proposed looks ok to me.
To be honest, I'd appreciate the support of this feature, whatever the syntax is :)

**Comment by paulrosen** [comment]
I'm closing some old issues due to inactivity. I have this feature on my list to do when I have time.
