### ISSUE TITLE
Alteration has to be hidden after the tie

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#511]
Currently looks like this, which is wrong:
![image](https://user-images.githubusercontent.com/15198808/90981936-9824d200-e56c-11ea-831d-41f783f4234f.png)

```
CCC^C-|^C=CCC
```

Has too look like this (from Sibelius):
![image](https://user-images.githubusercontent.com/15198808/90981864-061cc980-e56c-11ea-850d-0b8b47026a8e.png)

**Comment by paulrosen** [comment]
I just tried `CCC^C-|C=CCC` and it played back correctly for me.

For placing items, ABC doesn't try to figure out musical rules very much - if you put a `^` in the ABC string, it will be printed on the page.

I do try to follow musical rules when playing back, though.

**Comment by paulrosen** [comment]
I think this is working - reopen if there is still a problem

**Comment by rualark** [comment]
Thanks, it works in current version.
