### ISSUE TITLE
Tempo element not aligned with tempo text

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#512]
Should look like this (Sibelius), except equals sign should not be that close to a note:
![image](https://user-images.githubusercontent.com/15198808/91232458-d6222180-e737-11ea-8067-ded5ac2fa0f4.png)

Looks in 6.0.0.15:
![image](https://user-images.githubusercontent.com/15198808/91232499-e1754d00-e737-11ea-9c69-830060e1c5b8.png)

Looked in 6.0.0.13:
![image](https://user-images.githubusercontent.com/15198808/91232517-e9cd8800-e737-11ea-9065-d4ad39d5b84b.png)

**Comment by paulrosen** [comment]
It looks like you want the baseline aligned. Ok.

**Comment by paulrosen** [comment]
fixed in beta.16

**Comment by rualark** [comment]
Same result so far:
![image](https://user-images.githubusercontent.com/15198808/92691930-14c8f600-f34c-11ea-8ba8-b12c163d2a55.png)

```
%%barnumbers 1
Q:1/4=255
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Sop."
V: V1 clef=treble name="Alt."
V: V2 clef=treble-8 name="Ten."
V: V3 clef=bass name="Bas."
[V: V0]"_I"c16|z16|z16|z16|
[V: V1]z16|z16|z16|z16|
[V: V2]z16|z16|z16|z16|
[V: V3]z16|z16|z16|z16|
```

**Comment by paulrosen** [comment]
What is your ABC string for this? I see it as
![tempo-alignment](https://user-images.githubusercontent.com/69818/92741259-6a050780-f34c-11ea-9982-aba7e19229ec.png)
