### ISSUE TITLE
6.0.0.15 release takes more empty space at the top

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#513]
Not a big issue but taking extra space is not needed:
![image](https://user-images.githubusercontent.com/15198808/91232790-7d06bd80-e738-11ea-92f2-7c90f09545c3.png)

**Comment by paulrosen** [comment]
There were cases where items were touching each other. So I just put a couple pixels between each "lane".

**Comment by rualark** [comment]
Will adding more empty text lanes to prevent overlaps increase this unused whitespace even more?

**Comment by paulrosen** [comment]
The extra text lanes are only added if needed so they only affect the lines that contain the dense text.

**Comment by paulrosen** [comment]
Closed for inactivity.
