### ISSUE TITLE
Learn the last note played with Timming Callbacks

### ISSUE THREAD

**Issue by db5050** [paulrosen/abcjs#516]
I use Timming Callbacks events. Animation and cursor is on.
How can I tell when the song is over and the last note is played? Is there a returning function?
Because when the song is finished beatCallback, lineEndCallback events are still running. So I need to be able to call the "Stop" function when the song ends.
If I know the last note is playing, including repeats, I can do extra processing.

**Comment by paulrosen** [comment]
There should be one more call to `beatCallback` at the end of the tune.

There have been bugs where some ABC strings are causing the timingCallbacks to not be at the right time. If you are seeing that, please post an ABC string where you see the problem.

**Comment by db5050** [comment]
Total Beat comes out too long. That's why it comes out of play mode too late. But I was able to solve this with Line Callback. I stop it when "null" value in Line Callback event.
