### ISSUE TITLE
Fix slur wrapping

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#517]
![image](https://user-images.githubusercontent.com/15198808/91643939-366ad900-ea40-11ea-9c56-0386351598fd.png)

```
T: New Exercise
M: C
L: 1/4
K: C
V:1 name="Alto\n[species 2]\n[Sop.]"
"^1"c2"^2→"G2|B2d2|B2.(A2|C4)|B2.(A2|C4)|B2.(A2|C4)|B2.(A2|C4)|B2.(A2|C4)|B2.(A2|C4)|B2.(A2|C4)|B2.(A2|C4)|B2.(A2|C4)|
V:2 clef=treble-8 name="Tenor\n[c.f.]\n[Alt.]"
"^4. Consecutive leaps - - -"c4|e4|d4|c4|d4|c4|d4|c4|d4|c4|d4|c4|d4|c4|d4|c4|d4|c4|d4|c4|
w:H
w:F
w:I
```

**Comment by paulrosen** [comment]
Can reproduce. Hopefully fixed this weekend.

**Comment by paulrosen** [comment]
Will be in beta.16

**Comment by rualark** [comment]
Thanks a lot! Now it is better:
![image](https://user-images.githubusercontent.com/15198808/92690155-2361de00-f349-11ea-83e0-999afc7b94de.png)

Slur should be dashed and a little wider, so that it looks like the beginning of the slur.

Example from lilypond:
![image](https://user-images.githubusercontent.com/15198808/92690290-64f28900-f349-11ea-9c2b-dc888e9df87d.png)

Example from Sibelius:
![image](https://user-images.githubusercontent.com/15198808/92690345-8489b180-f349-11ea-9151-dee26744a49d.png)

**Comment by paulrosen** [comment]
fixed in beta 24
