### ISSUE TITLE
Timing Callback - Select Start Note and Loop

### ISSUE THREAD

**Issue by db5050** [paulrosen/abcjs#518]
How can I make sure that the note I want is played continuously from the note I want to the note I want using the StartChar and EndChar data? Do I have such a possibility? Can I create a custom loop?

**Comment by paulrosen** [comment]
I've done similar in client code - I restrict it to measure boundaries to make the selection easier for the user. But the user is the one to select it based on clicking and dragging over the measures they want. I'll look at it and give you some pseudo code that will help.

**Comment by paulrosen** [comment]
I see what I did - I use the `beatCallback` from `timingCallbacks`. When the user selects, say measures 5 through 8 in 4/4 time, I keep variables saying start at beat 20 (5x4) and end at beat 32 (8x4). Then beatCallback looks sort of like this:
```
var startBeat = // set this to the user's selection
var endBeat = // set this to the user's selection
beatCallbackIntercept = function(beatNumber, totalBeats, totalTime) {
  if (beatNumber === endBeat)
    // seek in both the timingCallback and the synth to the starting place.
}
```

**Comment by paulrosen** [comment]
Use `setProgress()` in timingCallback and `seek` in CreateSynth.

**Comment by paulrosen** [comment]
For the other part of your question - to do the above if you have the character position instead of the element, I've added a convenience function `getElementFromChar()` that will be in beta 16.

**Comment by db5050** [comment]
Thank you. I will try.

**Comment by db5050** [comment]
> I see what I did - I use the `beatCallback` from `timingCallbacks`. When the user selects, say measures 5 through 8 in 4/4 time, I keep variables saying start at beat 20 (5x4) and end at beat 32 (8x4). Then beatCallback looks sort of like this:
> 
> ```
> var startBeat = // set this to the user's selection
> var endBeat = // set this to the user's selection
> beatCallbackIntercept = function(beatNumber, totalBeats, totalTime) {
>   if (beatNumber === endBeat)
>     // seek in both the timingCallback and the synth to the starting place.
> }
> ```
When I click on a note with ClickListener some parameters are returned. We cannot get the BeatNumber value of the clicked note. If we could, we could choose the area to be played by clicking the notes.
Is there such a possibility, but I don't know?

**Comment by paulrosen** [comment]
The callback from the clickListener contains two things that might be useful:

`currentTrackMilliseconds` that is the position in milliseconds, not beats so there would be some conversion.

`midiPitches.start` that is the position in whole notes from the beginning of the piece. So if that contains 2.5 for instance then you know it is 10 quarter notes from the beginning and can calculate that way.

**Comment by paulrosen** [comment]
Closed for lack of activity. If you want to follow up I'll reopen.
