### ISSUE TITLE
Node JS Support

### ISSUE THREAD

**Issue by AlexGustafsson** [paulrosen/abcjs#52]
#### What

Support for Node JS, preferably as a NPM package.
#### Why

This is a one of a kind Javascript package that would fill an empty void if the package were to support Node.

I am currently in need for a package that can render ABC notation and that can run in a Node environment.

**Comment by paulrosen** [comment]
I haven't used node.js, but I'll try to figure out how to make and test an NPM for the next release (hopefully not long!). 

In the meantime, can you just include this file in your program? https://github.com/paulrosen/abcjs/blob/master/bin/abcjs_editor_latest-min.js 

Are there any other changes that are required? This package assumes a browser environment to create an SVG in.

**Comment by muddydixon** [comment]
Hi paulrosen.

I hope abcjs to be managed by npm too.
Recently frontend js modules are managed by it, e.g. d3.js, jquery.

**Comment by DanielJRaine** [comment]
I'm not sure how else to add myself to the number of people who want npm support for this other than leaving another comment here.

**Comment by paulrosen** [comment]
Believe it or not, I'm getting around to looking into this now. Stay tuned!

**Comment by paulrosen** [comment]
I've created an npm version. I'd love to get your feedback about whether that works for you. You can now install it with "npm install abcjs --save".

**Comment by Ralex86** [comment]
Thx a lot Paul for the npm support ! I'll check if that works for me ! Stay tuned :)

**Comment by paulrosen** [comment]
This is now supported.

**Comment by muddydixon** [comment]
Cool! 🎉
