### ISSUE TITLE
Note Dot Head on Simultaneous notes

### ISSUE THREAD

**Issue by dannybullo** [paulrosen/abcjs#520]
Hi,

First of all THANK YOU for the fantastic library!

I need to color simultaneous and not simultaneous Notes.
1) I **CAN** Color not simultaneous notes by getting the DOM Element by doing **$(".abcjs-nX")**, where **X** is the note index.
That works, but I think it would be cleaner to have specific Classes for Specific Notes, and NOT depend on Note Index.
NOTE: The color applies to the **whole note.** It is not Possible to apply color to the **Head** Only.

2) Chords: Of course, the notes happens simultaneously. If I render **|[C2E2G2B2]|**, I get one **STEM** and **all Heads** corresponding to all notes in the Chord in just ONE _PATH_ Element in the **SVG**. That makes it impossible to Color **Different Note Heads** for simultaneous Notes

Is there any workaround? Any plan to add specific Classes for Notes, including the different parts of the note _(Stem, Head Flag)_

Thank you very much!

Danny Bullo

**Comment by jpgm317** [comment]
https://github.com/paulrosen/abcjs/issues/402

**Comment by paulrosen** [comment]
Separating the separate notes has been asked before and I agree it is useful. I'm about to do a small maintenance release, but maybe I can get it into a future release soon.

There are other classes on notes: the duration and the line/space that they appear. I don't know if that would help.

**Comment by dannybullo** [comment]
Thank you very much Paul! It is ok, will wait for the next release. I'm doing an educational app, so I use color for notes in scales, etc. I will incorporate "Chord Note colors" in the future when you have it ready.

For the record: In my opinion, it would also useful to have classes to find independent notes, regardless of position. For example get all "G" notes, or get "G2" notes. So maybe add a composite class that has note and/ or note AND octave.
Last: not sure if you can do this. but add Event Listener to note where the callback cat get info about the note - again, note and octave. That way I can make note sounds with a distinctive sound, or do some logic.

Thanks again!

Danny Bullo

**Comment by paulrosen** [comment]
Separate targets for chords is in beta 35
