### ISSUE TITLE
Rolled chord support

### ISSUE THREAD

**Issue by SlowBubble** [paulrosen/abcjs#524]
Is there a way for the abc notation and the abcjs editor to notate rolled chords?
The only info I found is an ancient thread about doing it with !r!:
https://www.mail-archive.com/abcusers@argyll.wisemagic.com/msg05924.html#:~:text=rolled%20chord

**Comment by chrisfargen** [comment]
@SlowBubble do you mean like this?

```
X:
K:
!arpeggio![CEGc]4
```

**Comment by SlowBubble** [comment]
That's exactly what I'm looking for. Thanks, Chris!
