### ISSUE TITLE
Horizontal centre the notes

### ISSUE THREAD

**Issue by dpaniukov** [paulrosen/abcjs#525]
Hello, is there any way to centre the notes horizontally? If I have just a few notes the title is at the centre but not the notes. 

![notes_not_centered](https://user-images.githubusercontent.com/16146198/93834634-89ecd300-fc4a-11ea-9b27-0c3a16c70cac.png)

**Comment by paulrosen** [comment]
You can use `%%staffwidth 400` to pick the number of pixels that the staff will take. You can experiment with that to get it centered. You can also use `%%stretchlast` to stretch the music out.
