### ISSUE TITLE
Feature request: call a function at the end of playback

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#527]
I think maybe there is a way to call a function at end of playback with Timing Callbacks, https://paulrosen.github.io/abcjs/animation/timing-callbacks.html#example, but I don't know how... Is there an easier way?

**Comment by paulrosen** [comment]
Use `beatCallback` from the timing callbacks: https://paulrosen.github.io/abcjs/animation/timing-callbacks.html#parameters

There's an example of calling it on that page.

**Comment by nbruley** [comment]
Would I have to know (or perhaps calculate somehow) the number of beats in the song in order to know when playback is stopped?

**Comment by nbruley** [comment]
So I see the info returned in the example gives the total number of beats when it first starts running, so there must be a way to return that info and call a function when beatNumber = totalBeats; I'll have to play with it I guess to understand better how this works.

**Comment by nbruley** [comment]
I tried this, but it doesn't work... am I on the right track?
```
var visualObj = ABCJS.renderAbc("*", TuneABC, abcOptions)[0]; //create object to play but don't display ("*")
midiBuffer = new ABCJS.synth.CreateSynth();	 // This does a bare minimum so this object could be created in advance, or whenever convenient.

/*  Ability to call a function when ending playback to repeat or change the play button. */
//https://paulrosen.github.io/abcjs/animation/timing-callbacks.html#creation
var timer = new ABCJS.TimingCallbacks(visualObj, {
	beatCallback: function() {
		console.log(beatNumber);
		if (beatNumber == totalBeats) { //tune has ended
			stopPlayback();
		}
	}
});
```
I also tried this for the standard player, with onEnded option but that doesn't appear to do anything...
```
var createSynth = new ABCJS.synth.CreateSynth(); //create the audio abc object for playback
createSynth.init({
		visualObj: visualObj[0],
		options: {
			// soundFontUrl: "https://paulrosen.github.io/midi-js-soundfonts/FluidR3_GM/" ,  (doesn't work?)
			// sequenceCallback: function(noteMapTracks, callbackContext) { return noteMapTracks; },
			// callbackContext: this,
			onEnded: function() {
				stopPlayback();
				console.log('here');
			}
			// pan: [ -0.5, 0.5 ]					
		}
	}).then(function () {
```

**Comment by paulrosen** [comment]
Change beatCallback line to:
```
beatCallback: function(beatNumber, totalBeats, totalTime) {
```

**Comment by nbruley** [comment]
I'm in v6.0.0-beta.24 but still not getting the log "reached end" with this code. Maybe I need another reference somewhere...

```
var timer = new ABCJS.TimingCallbacks(visualObj, {
	beatCallback: function(beatNumber, totalBeats, totalTime) {
		console.log(beatNumber);
		if (beatNumber == totalBeats) { //tune has ended
			console.log('reached end');
			stopPlayback();
		}
	}
});
if (ABCJS.synth.supportsAudio()) {
```

**Comment by nbruley** [comment]
My problem was I didn't call timer.start()
