### ISSUE TITLE
How to specify number of repeats of a section

### ISSUE THREAD

**Issue by SteveALee** [paulrosen/abcjs#529]
Is there away to say how many repeats for a section between `|:` and `:|`? Or is it always only a single repeat (2 play throughs)?

I was unable to find anyhting in the spec or code.

**Comment by paulrosen** [comment]
It's always a single repeat. You can set the number of times and ending is played, though:
```
ABcd efga |1,2,3 ABcd efga |4 ABcd efga |
```

**Comment by SteveALee** [comment]
Seems thats what I was missing. Thanks.
