### ISSUE TITLE
spurious "if (!window.ABCJS)"{window.ABCJS = {}}

### ISSUE THREAD

**Issue by neuhaus** [paulrosen/abcjs#53]
I noticed that throughout `abcjs_basic_2.3-min.js` there are more than 30 occurrences of the block

    if (!window.ABCJS) {
        window.ABCJS = {}
    }

at the top level. Can't we get rid of all but the first one?

**Comment by paulrosen** [comment]
I suppose. That is at the top of each file so that the files can be loaded in any order. I like that flexibility. I could write a post-processor that strips them from the minimized version, but it doesn't seem worth it.
