### ISSUE TITLE
Bar numbers

### ISSUE THREAD

**Issue by SteveALee** [paulrosen/abcjs#530]
For this example 12 bar blues I want the first bar on each line to be labeled but  `%%barnumber x` is no good (unless "x4 +1" would work :)

The syntax `% n`given in the abc spec for printing bar numbers doesn't seem to work.

```
% 1
| "G" g2d g2d g2d gdg | "F" f2c f2c f2f a_bc' | "C" c2c e2e f2f _g2g | "G" ggg ggg ggg A_B=B |
% 5
|: "C" c2c e2e g2g _bag | "F" F2F A2A c2c _ed_d | "C" c2c e2e g2g _bag |  "C" c2c e2e g2g _bag |
% 9
| "F" f3 fcf ^f3 fBf| "F" f2f _e2e d2d _d2d | "C" c2c e2e g2g _bag | "C" c2c e2e g2g ef_g  |
% 13
| "G" g2g B2B d2d fec| "F" f2f _e2e d2d _d2d| "C" c2c _B2B A2A _A2A | "G" Ggg ggg ggg fed :|
```

**Comment by paulrosen** [comment]
To do the first bar of each line:
```
%%measurenb 0
```

**Comment by SteveALee** [comment]
Brilliant thanks. Is that documented?

In my case Bar 1 was not annotated but that is not a problem at all.

![image](https://user-images.githubusercontent.com/618922/95470618-e8b78980-0978-11eb-8ee8-98ad0f1c09cf.png)
