### ISSUE TITLE
EventCallback-X Position-Rect Tag

### ISSUE THREAD

**Issue by db5050** [paulrosen/abcjs#531]
I am using TimeCallback. My problem is this. I open a console in my browser. Clicking on the note I see the html tags. Here the x value in the note's "rect" information is the correct value. However, the value of x in the information returned with EventCallback is different and incorrect. That's why the cursor display is often wrong. How can I fix this situation? Or let me ask like this. How can I get "rect" information with EventCallback?

**Comment by paulrosen** [comment]
I need to see an example. What is your ABC string?

**Comment by db5050** [comment]
Thanks. 
I found that the problem is with my own codes. Problem is solved...
