### ISSUE TITLE
synthControl.options

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#533]
Hi!
In my project I'm using the beta version 13, today I tried the beta version 18 and suddenly the "voicesOff" option did not work anymore.
Is it removed or only moved so that I can access it from somewhere else?

This is my code where I use it now:

`function start() {
			if (synthControl)
			synthControl.options = {
				chordsOff: !document.getElementById("Chords").checked, 
				voicesOff: voiceUnChecked,`

**Comment by musikboden** [comment]
When I use beta 18 I'll get this error:
`Uncaught (in promise) TypeError: Failed to set the 'value' property on 'AudioParam': The provided float value is non-finite.
    at e.exports (abcjs_basic_6.0.0-beta.18-min.js:3)
    at abcjs_basic_6.0.0-beta.18-min.js:3
    at new Promise (<anonymous>)
    at e.exports.e.prime (abcjs_basic_6.0.0-beta.18-min.js:3)
    at abcjs_basic_6.0.0-beta.18-min.js:3`

**Comment by paulrosen** [comment]
I can reproduce. It will be fixed soon.

**Comment by musikboden** [comment]
👍
