### ISSUE TITLE
synthControl.warp

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#534]
Hi!
How is it possible to control the synthControls warp function?
I want to control the tempo % from a different control element

/Ulrik

**Comment by paulrosen** [comment]
Good question! You can call most of the functionality of `SynthController` directly without the audio control, but not that one. You could fake it by calling `synthControl.onWarp(ev)` where ev is an input element (or any object that contains an integer in `ev.target.value`).

I think it is simple to expose a function `setWarp()` that does the same thing. It will be in the next beta.

**Comment by musikboden** [comment]
> I think it is simple to expose a function `setWarp()` that does the same thing. It will be in the next beta.
Beautiful, thanks Paul!
