### ISSUE TITLE
Odd chord playback with M: 12/8

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#535]
Example:

```
X: 1
T: Dan O'Keefe's no. 1
M: 12/8
R: slide
K: Ador
|:"Am" A2e e2d "G" BAB d2B | "Am" A2e e2d "G" B2A GAB |
```

For the purposes of playback, it would be nice if 12/8 was treated a bit more like 6/8.

This sounds closer to what I would expect of above:

```
X: 1
T: Dan O'Keefe's no. 1
M: 6/8
R: slide
K: Ador
|:"Am" A2e e2d | "G" BAB d2B | "Am" A2e e2d | "G" B2A GAB |
```

I could always change the time sig to 6/8 on a tune-by-tune basis, but I wonder if I may not be the only one who has run into this issue.

P.S., nice work on beta.18!

**Comment by paulrosen** [comment]
That's strange - both of those examples sound the same to me. Can you show me how you are calling it?

And what do you hear differently on the 12/8 version?

**Comment by chrisfargen** [comment]
Here's what I get using 'abcjs-6.0.0-beta.18/examples/editor-midi.html':

[2020-10-12-11:57:08.mp3.zip](https://github.com/paulrosen/abcjs/files/5366166/2020-10-12-11.57.08.mp3.zip)

The 'chick' for all chords appears to be a G chick, even for the Am.

**Comment by paulrosen** [comment]
Oh, will be fixed in next beta.
