### ISSUE TITLE
Mouse position in staff

### ISSUE THREAD

**Issue by avnerdorman** [paulrosen/abcjs#538]
One more question - does the listener return the mouse position in the staff or svg? I can calculate the position myself, but I think it would be easier (and probably better) to use what you already have in there for the dragging feature. Is this something that's easily accessible?

Thanks!

**Comment by paulrosen** [comment]
It returns the original mouse event and `clientX, clientY` is the position in the SVG that was clicked.

**Comment by avnerdorman** [comment]
Thanks!
