### ISSUE TITLE
set loop

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#539]
I want the user to set a portion of the music and loop it, I can set the loop start and end points using "abcElem.currentTrackMilliseconds" for clicked note.
Now I want to use these loop start and end points, to set the synth to play between these points, is it possible? If so, can you give a hint where to look?

/Ulrik

**Comment by paulrosen** [comment]
I did that in an app - what I do is monitor the beat callback from the timing callbacks. Then do a seek right then.

For instance:
```
var timingCallbacks = new abcjs.TimingCallbacks(... beatCallback: beatCallback ...);
var startRepeat = 8;
var endRepeat = 12;
function beatCallback(beatNumber, totalBeats, totalTime) {
  if (beatNumber >= endRepeat) {
    var percentDone = startRepeat/totalBeats;
    timingCallbacks.setProgress(percentDone);
    midiBuffer.seek(percentDone);
  }
}
```

**Comment by musikboden** [comment]
Hi Paul,
I'm lost and I wonder if you could help me out?
I am able to set the "setProgress" percentage, and I can visually see that the synth controller jumps to the right place to start, however it jumps right back to the beginning and starts to play from there.

If I understand right, I have to set the midiBuffer.seek(percentage), but I can't figure out where to set in my code.
The code is taken from the "fullSynth example"

If you have a small working example I would be very thankful.

This is my code inside "setTune() function", and here is where the midiBuffer is created, and as I understand it, also have to set the seek function, right?
`
function setTune(userAction) {
			var visualObj = ABCJS.renderAbc("paper", abc[currentTune], {
				visualTranspose : transposeValue + instrumentTranspose + klingandeFactor[klingandeArray.indexOf(document.getElementById("klingande").value)],
				add_classes: true}, abcOptions)[0];
			var midiBuffer = new ABCJS.synth.CreateSynth();
			midiBuffer.init({
				visualObj: visualObj,
				options: {
					soundFontUrl: soundfont,
				}
			})
			.then(function (response) {
				if (synthControl) {
					synthControl.setTune(visualObj, userAction).then(function (response) {
						tracks = midiBuffer.flattened.tracks.length;
						const drums = document.getElementById("drums");
						const chords = document.getElementById("chords");
						if (document.getElementById("paper").querySelectorAll(".abcjs-chord").length > 0) 
						{
							chords.style.visibility = "visible";
							document.getElementById("chordsLabel").innerText = "Komp";
							tracks = tracks - 1;
						}
						else
						{
							chords.style.visibility = "hidden";
							document.getElementById("chordsLabel").innerText = "";
						}
						if (abc[currentTune].includes("%%MIDI drum"))
						{
							drums.style.visibility = "visible";
							document.getElementById("drumsLabel").innerText = "Trummor";
							abc[currentTune].includes("%%MIDI drumon")? tracks = tracks - 1: "";
						}
						else
						{
							drums.style.visibility = "hidden";
							document.getElementById("drumsLabel").innerText = "";
						}
						if (tracks != document.getElementsByClassName("voices").length)
						{
							trackBtns();
						}
						console.log("Audio successfully loaded.")
					}).catch(function (error) {
						console.warn("Audio problem:", error);
					});
				}
			}).catch(function (error) {
				console.warn("Audio problem:", error);
			});
		}

		function next() {
			currentTune++;
			if (currentTune >= abc.length)
				currentTune = 0;
			setTune(true);
		}
`

**Comment by paulrosen** [comment]
I'll create an example. Hold on...

**Comment by musikboden** [comment]
@paulrosen Thank you, I really appreciate it 👍

**Comment by paulrosen** [comment]
Here's the example: https://github.com/paulrosen/abcjs/blob/dev/examples/play-on-repeat.html

It will hit the regular repo when I release the next beta.

**Comment by musikboden** [comment]
Thank you Paul, I will experiment with this! 👍

**Comment by paulrosen** [comment]
If this isn't resolved let me know.

**Comment by musikboden** [comment]
Thank you, the looping function is working great! 👍
