### ISSUE TITLE
Support for callback after render

### ISSUE THREAD

**Issue by libertychisasuro** [paulrosen/abcjs#54]
Is it possible to add a callback after the output has been rendered? This would help get around race conditions such that logic that is dependent on the output of ABC.render is executed via callback.

**Comment by paulrosen** [comment]
Do you mean when using the Editor? If you are using the Basic call, then it is finished rendering by the time the function returns.

For the editor, I'll put in an parameter that defines a callback function.

**Comment by libertychisasuro** [comment]
I am using Basic. I will try using the return. Thanks!
