### ISSUE TITLE
Feature request: support running in web worker w/ no SVG render

### ISSUE THREAD

**Issue by ezekielaquino** [paulrosen/abcjs#541]
I don't know if it's possible but It would be great to be able to only output the raw "definition" of the sheet music (`renderAbc('*', abcString)`) with its methods totally decoupled from the visual renderer (svg) so it can be run in a web worker thread

**Comment by paulrosen** [comment]
I looked into this. The biggest issue is that part of the definition requires how long text will be and as far as I can tell there's no way to know except for putting it in an SVG and calling getBBox. I wish I could figure out a way to get around that. If you have an idea let me know.

But the second issue is that the parsing is pretty fast as it is. When I did performance tests I saw that most of the time has to do with creating the SVG so I don't think you'll save much time that way. If you are seeing different results please post the ABC string you are using to test.

**Comment by paulrosen** [comment]
I'm closing this because there isn't anything to do unless the size of text in SVG is solved. Please reopen if you have more info.
