### ISSUE TITLE
What is this referring to?

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#545]
With the new beta 21 I get this error message when using synthControl.play(); (my project is based on the "fullSynth example"

Uncaught (in promise) TypeError: Cannot read property 'w' of undefined
    at abcjs_basic_6.0.0-beta.21-min.js:3
    at Object.setupEvents (abcjs_basic_6.0.0-beta.21-min.js:3)
    at Object.setTiming (abcjs_basic_6.0.0-beta.21-min.js:3)
    at e.exports.r.replaceTarget (abcjs_basic_6.0.0-beta.21-min.js:3)
    at new e.exports (abcjs_basic_6.0.0-beta.21-min.js:3)
    at abcjs_basic_6.0.0-beta.21-min.js:3

Can someone tell me what the "w" is referring to?
and what is it that is undefined?

**Comment by paulrosen** [comment]
Can you post the ABC string or part of it? I don't necessarily need it, but it might make it quicker to find the problem.

**Comment by paulrosen** [comment]
nvm. I found a simple case:
```
X:1
T:title
L:1/4
K:C
cdef|
T:subtitle
gabg|
```
The error occurs when there is a subtitle line (and probably a %%text and other interstitial things.)

Will be fixed this week.

**Comment by musikboden** [comment]
Thank you Paul! I'll get you a 🍺

**Comment by musikboden** [comment]
Is this issue the same as #551 ?

**Comment by paulrosen** [comment]
Yes, it is.

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.22

**Comment by musikboden** [comment]
Beautiful! Thank you.
