### ISSUE TITLE
request

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#546]
When changing tempos in the middle of a tune with more than 1 voice, we have to set the tempo for all voices separately for playback to work, and it looks terrible.
In this example the treble staff has 2 voices and the bass staff 1 voice

X: 1
T: Test
%%score { ( 1 3 ) | 2 }
Q:1/4=100
M: 4/4
L: 1/8
K: C
V:1 clef=treble
V:3 clef=treble
V:2 clef=bass
V:1
a2b2c'2b2 | a2b2c'2b2 |[Q:1/4=80] a2b2c'2b2 | a2b2c'2b2 |
[Q:1/4=120] a2b2c'2b2 | a2b2c'2b2 |[Q:1/4=100]a2b2c'2b2 | a2b2c'2b2 |
V:3
E8 | G8 |[Q:1/4=80] F8 | A8 |
[Q:1/4=120] E8 | G8 |[Q:1/4=100] F8 | A8 |
V:2
A,4 G,4 | F,4 E,4 |[Q:1/4=80] A,4 G,4 | F,4 E,4 |
[Q:1/4=120] A,4 G,4 | F,4 E,4 |[Q:1/4=100] A,4 G,4 | F,4 E,4 |

![Skärmavbild 2020-11-04 kl  11 04 41](https://user-images.githubusercontent.com/18282700/98097631-8c6b5b00-1e8d-11eb-9dcd-e4864378a4d2.png)

Notice:
The tempo change at bar 5 is outside the rendered area
to fix this you have to set a new barline on the second line of music for each voice, then it looks like this:
Not so good looking.

![Skärmavbild 2020-11-04 kl  11 08 00](https://user-images.githubusercontent.com/18282700/98097965-03085880-1e8e-11eb-9f23-c029a0aaca98.png)

1) Either make a tempo change global, so you set it in the first voice and it will influence all voices
2) or, make use of !invisible! to set all tempo changes to invisible except one?
3) Would it be possible to make the tempo change appear at the beginning of a bar if it's after a line break?
 so that you don't need to set an extra barline at the beginning of a new line?

**Comment by paulrosen** [comment]
That's interesting - I think the standard is vague about this point.

To me, it makes sense for the tempo to always affect all voices because what would it possibly mean to have two staves running at different tempos? Then you could use either of the lines for the tempo indicator depending on where you want it to show up.

**Comment by musikboden** [comment]
Hi Paul, I agree with you, I think it should be a global tempo indicator that will affect all voices, that is what I meant, as it is now, you have to set the tempo changes for all voices separately. 

I suggest, if it's possible to script, that making a tempo change in one voice ( maybe the first voice) will affect all other voices, what do you think?

**Comment by musikboden** [comment]
btw, it would be great to have to be able to make use of !invisible!, in case of ritardandos and accelerandos.

**Comment by paulrosen** [comment]
Yeah, it should work for any voice so the user has flexibility.

I'm not sure what you mean by the last comment about !invisible!. Can you show me a small sample and what you want it to look and sound like?

**Comment by musikboden** [comment]
> Yeah, it should work for any voice so the user has flexibility.
> 
> I'm not sure what you mean by the last comment about !invisible!. Can you show me a small sample and what you want it to look and sound like?

Oh, I found it in the abcplus project here, at page 42
http://abcplus.sourceforge.net/abcplus_en.pdf

**Comment by musikboden** [comment]
You're right, it says "make the next note or measure bar invisible", I'm sorry I was a bit hasty and didn't read all of it.
I was thinking it would be possible to hide next element, what ever the element was, like: ab2c !invisible![Q=112], to hide the tempo change, but I realise now, that wasn't the purpose of !invisible! 😢
and that answer you're second question regarding the ritardandos and accelerandos.

Thank you for the 
`.abcjs-tempo.abcjs-v1 {
  display: none;
}`
example, good to know, it makes it possible to not show the tempo changes on all other voices than one, but it will still be a mess in one voice, if making ritardandos or accelerandos.
Or is it possible to decide what tempo markings to hide/show?
Look at this:

X:1
T:Cooley's
M:4/4
Q:1/4=90
L:1/8
R:reel
K:Emin
|:D2|"^accelerando"EB{c} BAB2 [Q:1/4=100]EB|~B2 AB[Q:1/4=110] dBAG|FDAD [Q:1/4=120]BDAD|FDAD dAFD|
[Q:1/4=130]EBBA [Q:1/4=140]B2 EB|B2 AB [Q:1/4=150]defg|afe^c [Q:1/4=160]dBAF|DEFD E2:|

![Skärmavbild 2020-11-14 kl  12 29 58](https://user-images.githubusercontent.com/18282700/99146092-1f1dae00-2675-11eb-8475-8b99426d253c.png)

Here I would like to show the initial tempo and the last tempo marking, but hide all others, is it possible?

**Comment by musikboden** [comment]
Btw, in this example above, the playback bar will end before the music has ended, strange....

**Comment by paulrosen** [comment]
That's a different bug. It looks like the cursor also gets off. It looks like it is fine the first time, and then it goes at a different pace around the second or third measure on the repeat.

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.22

Now a tempo change in one voice affects all voices.

**Comment by musikboden** [comment]
That is great, thank you!
