### ISSUE TITLE
How to render individual symbols?

### ISSUE THREAD

**Issue by JakubKoralewski** [paulrosen/abcjs#548]
Hello, I'm using the 6.0.0-beta.21.

I'm building a small random notes generator, and I wanted to implement a way for the user to choose which notes they want to be used. I'd like to use abcjs for this since I'm already bundling it as a dependency, but I don't know if there's a way to individually render a note, pause, triple without the staff and the clef etc.?

Thanks.

I found the font_gen.html file but it shows how to display individual glyphs, but I'm looking for whole notes.

Will the simplest solution be to generate all the notes I want and then copy the generated svg code?

I'm guessing this is all I need
```abc
X: 1
M: 4/4
L: 1/8
K: C
| A12 A8 A4 A3 A2 A3/2 A/1 A5/8 A/2 A/3 A/4 A/6 A/8 |
(3A8A8A8 (3A4A4A4 (3A2A2A2 (3AAA (3A/2A/2A/2 (3A/4A/4A/4 (3A/8A/8A/8  |
(3A12A12A12 (3A3A3A3 (3A3/2A3/2A3/2 (3A5/8A5/8A5/8 (3A/3A/3A/3 (3A/6A/6A/6 |
z12 z8 z4 z3 z2 z3/2 z/1 z5/8 z/2 z/3 z/4 z/6 z/8
```
Would be nice to be able to render to a single element using a function in the API which could take a single expression.

So I've been slowly copying but I just realized I'm gonna have to take the SVG x,y, offset into account 🤦‍♂️ wish me luck

OK I can't do it lol

Last effort: render normally and hide the clef and staff 🤣 but then the centering... omg

**Comment by JakubKoralewski** [comment]
Ok so the current half-baked solution of mine is to render normally with add_classes, hide staff etc. then after render loop through the notes and get the minX, minY, the corresponding width and height, same for max values and set the viewBox on the svg correspondingly. Not perfect, but I guess it works.

**Comment by paulrosen** [comment]
I've done similar - there is some trial and error to get it positioned right. But part of the string I use is:
```
%%staffwidth 30
K:C clef=none % need to draw the stafflines, then hide them, since they are used for positioning.
V:all stem=up
(3BBB
```
Then hide the staff lines with
```
.abcjs-staff {
	opacity: 0;
}
```
The staffwidth will change the general spacing so that triplets aren't too wide.
