### ISSUE TITLE
Midi program, midi instrument

### ISSUE THREAD

**Issue by BaniMontoya** [paulrosen/abcjs#55]
Hello, im try to do like:   

```
window.onload = function() {
        abc_editor = new ABCJS.Editor("abc", { paper_id: "paper0", midi_id:"midi", warnings_id:"warnings",midi_options:{instrument:64}, add_classes: true , gui:true });
    }

```

im try to select a program instrument for midi generated, but im see that always generate program 2, im try to modify also on library to make test but i cant see, what generate midi is always on program2.
can i do samething on params?,

thanks

**Comment by paulrosen** [comment]
Use `{ program: 64 }` instead of `{ instrument: 64 }`

**Comment by SoftSofter** [comment]
Hello Paul Rosen, thanks for the abc.js work.
im try to do:
	window.onload = function() {
abc_editor = new ABCJS.Editor("abc", { paper_id: "paper0", midi_id:"midi", warnings_id:"warnings",midi_options:{program:22}, add_classes: true , gui:true });
}
also with program but dont have change on sound but if modify thos "var l=d.program||2" on abcjs_editor.js make difference.
Also, its posible make change direct on textarea like:
%%MIDI voice Tb instrument=59 or
M:C
L:1/8
Q:1/4=66
K:C
V:Rueckpos
%%MIDI voice instrument=53 bank=2
A3B    c2c2    |d2e2    de/f/P^c3/d/|d8    |z8           |
V:Organo
%%MIDI voice instrument=73 bank=2
z2E2-  E2AG    |F2E2    F2E2        |F6  F2|E2CD   E3F/G/|

**Comment by paulrosen** [comment]
In the newest version abcjs 3.3.0, try the following instead of the above:
```
M:C
L:1/8
Q:1/4=66
K:C
V:Rueckpos
%%MIDI program 53
A3B    c2c2    |d2e2    de/f/P^c3/d/|d8    |z8           |
V:Organo
%%MIDI program 73
z2E2-  E2AG    |F2E2    F2E2        |F6  F2|E2CD   E3F/G/|
```
