### ISSUE TITLE
gracenotes in sequenceCallback?

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#550]
Since Paul showed me how to apply swing to a tune, using the sequenceCallback, I'm also trying to modify the grace notes in a tune, but I can't find a way to do that in the sequenceCallback since the "tracks" doesn't give any information about what kind of note it is.
Is there a simple way to modify the grace notes before playback?

**Comment by paulrosen** [comment]
I think the solution will be to carry along another field through the process. That would be something like "type" and would be an enumeration of "normal", "grace", "decoration".

**Comment by musikboden** [comment]
👍

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.22

**Comment by musikboden** [comment]
Beautiful! 😀
