### ISSUE TITLE
playback broken?

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#551]
This tune will not play back using "editor-synth" example beta 21 with Chrome Version 86.0.4240.183 (Officiell version) (x86_64)

X:1
T:Swing med upptakt
M:4/4
L:1/8
Q:1/4=70
R:medium swing
K:C
C | DCDE FG2 A- |AcBd c2 A!>! c-|c8 |]

**Comment by nbruley** [comment]
What error are you getting? I'm getting a "cannot read property 'w' of undefined" error on this line in my implementation.
 var endX = next && el.top === next.top ? next.left : lines[el.line].staffGroup.w;

**Comment by musikboden** [comment]
This is the error I get:
Uncaught (in promise) TypeError: Cannot read property 'left' of undefined
    at skipTies (abcjs-basic.js:1673)
    at addEndPoints (abcjs-basic.js:1685)
    at Object.Tune.setupEvents (abcjs-basic.js:1654)
    at Object.Tune.setTiming (abcjs-basic.js:1748)
    at TimingCallbacks.self.replaceTarget (abcjs-basic.js:346)
    at new TimingCallbacks (abcjs-basic.js:356)
    at abcjs-basic.js:16044
skipTies @ abcjs-basic.js:1673
addEndPoints @ abcjs-basic.js:1685
Tune.setupEvents @ abcjs-basic.js:1654
Tune.setTiming @ abcjs-basic.js:1748
TimingCallbacks.self.replaceTarget @ abcjs-basic.js:346
TimingCallbacks @ abcjs-basic.js:356
(anonymous) @ abcjs-basic.js:16044
Promise.then (async)
doNext @ abcjs-basic.js:14743
(anonymous) @ abcjs-basic.js:14733
Promise.then (async)
acResumerMiddleWare @ abcjs-basic.js:14727
(anonymous) @ abcjs-basic.js:14766

running it in Chrome Version 86.0.4240.183

**Comment by paulrosen** [comment]
A fix is coming! I hope this weekend.

**Comment by musikboden** [comment]
👍

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.22

**Comment by musikboden** [comment]
Thank you!
