### ISSUE TITLE
question

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#552]
I'm working on a "swing" function using the sequenceCallback function, and it's working fine except for tunes with an pickup that starts on offbeat.
Even if the tune starts with a pickup, the first note, or pause, has the start value of 0, so...
Is there an easy way to "read" the tune if it's starting on an offbeat?

Cheers! /Ulrik

**Comment by paulrosen** [comment]
I don't know of a clean way, but I can think of a couple of tricks.

First, the normal volume of the first item in the measure (if you don't change it with `!f!` for instance) is 105. You can look for that.

Second, you can query the tune object for the length of the pickup: `visualObj[0].getPickupLength()`.

**Comment by musikboden** [comment]
> I don't know of a clean way, but I can think of a couple of tricks.
> 
> First, the normal volume of the first item in the measure (if you don't change it with `!f!` for instance) is 105. You can look for that.
> 
> Second, you can query the tune object for the length of the pickup: `visualObj[0].getPickupLength()`.

Ah, thank you, the second suggestion seems to be the best way to do it. 👍
