### ISSUE TITLE
When a tie is not followed by the same sound, then that sound is not played again.

### ISSUE THREAD

**Issue by ApplePedlar** [paulrosen/abcjs#553]
When I play it back, I can hear D but not C.

I tried [abcjs editor](https://www.abcjs.net/abcjs-editor.html).
![image](https://user-images.githubusercontent.com/2986661/99085223-493a8600-260b-11eb-8d67-8e5e3f5f6575.png)

**Comment by paulrosen** [comment]
That is technically not a legal construct. A tie is always to the same note. If you use a slur instead it should give you what you want:
```
(C|D)CDC DCDC|]
```

**Comment by ApplePedlar** [comment]
I was surprised when I played it back without realizing that I had written an unnecessary hyphen and certain sounds stopped coming out of the middle. It might be more helpful to make it a syntax error.

**Comment by paulrosen** [comment]
I went back and forth on that. I decided to be as permissive as possible. In this case I knew what the code meant. There is a currently a push to work more on the ABC standard so I hope some guidance will happen about cases like this.
