### ISSUE TITLE
class abcjs-dynamics bug?

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#556]
class abcjs-dynamics will affect crescendo & diminuendo lines but not dynamic symbols like, p, mf or f etc.
Is it supposed to be like that? In that case, is there also a class for p, mf, ff etc?

However the abcjs-decoration will affect both crescendo lines and p, mf, ff etc

**Comment by paulrosen** [comment]
Ok, will be in next version.

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.22

**Comment by musikboden** [comment]
Thank you Paul!
