### ISSUE TITLE
The playback speed of 6-tuplet is too fast.

### ISSUE THREAD

**Issue by ApplePedlar** [paulrosen/abcjs#557]
![image](https://user-images.githubusercontent.com/2986661/99794619-ca46cf80-2b6d-11eb-8fa5-233cc8cb09d5.png)
I used https://www.abcjs.net/abcjs-editor.html 

Two triplets and a 6-tuplet should sound the same, but the 6-tuplet is played twice as fast.

Thank you.

**Comment by paulrosen** [comment]
Thanks for the bug report. I'll fix.

**Comment by paulrosen** [comment]
Note: a work around is to explicitly set the ratio like this:
```
(3ccc (3ccc | (6:4ccc ccc|
```

**Comment by paulrosen** [comment]
I've been studying this. It looks like, while you are right that the standard definition of the 6-tuplet should imply 6:4, the ABC standard defines it at 6:2. So I think I can't change this. So you will have to notate it `(6:4`. Sorry.

**Comment by ApplePedlar** [comment]
Thank you for telling me how to work around it!
