### ISSUE TITLE
beatSubdivisions issue

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#558]
The function to set "beatSubdivisions" doesn't seem to work.
If I set the beatSubdivisions = 4, the "beatNumber" in cursorControl.onBeat  beat callback, will still only be called once per beat

**Comment by musikboden** [comment]
The thing is that I've coded a loop function based on "beatNumber" and the user sets the start and end points using clickListener and if it's a song with a pickup that starts on offbeat, it's impossible to set the loop start and end points on the beat.
The beatNumber starts counting at the first note present in the song and if it starts on offbeat it will not work.

**Comment by paulrosen** [comment]
I took the full-synth.html sample and added `console.log("beat", beatNumber)` as the first line in the `CursorControl:onBeat` function. I see it being called every half beat. Can you post the code that you are using to call it?

**Comment by musikboden** [comment]
Yes, you're right, it works in the full-synth example, but not in the play-on-repeat example, has it to do with the different structure and the use of timingCallbacks?
My code is from the beginning based on the full-synth example but since I implemented the loop function I had to go more into the play-on-repeat structure and skipped the synthController part.

**Comment by musikboden** [comment]
So is there a way to set onBeat function to report on every eight note even if the meter is 2/2 or 6/8

**Comment by musikboden** [comment]
Ok, I found I had to set "beatSubdivisions: cursorControl.beatSubdivisions," in timingCallback, all fine now :)
