### ISSUE TITLE
Tag titleleft does not work

### ISSUE THREAD

**Issue by dpaniukov** [paulrosen/abcjs#562]
Hello,

The tag `%%titleleft` does not align the title to the left. To reproduce, I put it on the editor and the title is still centred.

Any suggestions on how to get around this issue? 
Thank you

**Comment by paulrosen** [comment]
That is a bug - I'll have a fix soon.

**Comment by paulrosen** [comment]
Will be in version 6.0.0-beta.23

**Comment by dpaniukov** [comment]
Looking forward to it. Thank you!
