### ISSUE TITLE
beta 22 bug

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#564]
Running "Play-on-repeat" example results in error:
"Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at TimingCallbacks.self.setProgress (abcjs-basic.js:610)
    at play-on-repeat.html:86"

**Comment by paulrosen** [comment]
Thanks for the report. I'll have a patch ready quickly.

**Comment by paulrosen** [comment]
Will be fixed in 6.0.0-beta.23
