### ISSUE TITLE
full-synth example bug

### ISSUE THREAD

**Issue by mihammerl** [paulrosen/abcjs#566]
hi paul, awsome library! 🥇 

i think i found a bug in the abcjs-6.0.0-beta.22/examples/full-synth.html
if the audio is stopped and the position of the slider is changed, the cursor gets out of snyc

here is a video:
[abcjs_ Synth Demo — Mozilla Firefox 2020-11-27 17-58-59.zip](https://github.com/paulrosen/abcjs/files/5608968/abcjs_.Synth.Demo.Mozilla.Firefox.2020-11-27.17-58-59.zip)

Thank you!

**Comment by paulrosen** [comment]
Thanks for the report. I'll look at it.

**Comment by paulrosen** [comment]
Fixed in version 6.0.0-beta.25

**Comment by mihammerl** [comment]
hi paul!
thanks for fixing this :)
i actually found another bug in this context (abcjs-6.0.0-beta.26/examples/full-synth.html). 
scenario:

1. change position of the progress button (.abcjs-midi-progress-background)
2. note is highlighted correctly
3. start player
4. music is played from correct position, but the cursor (.abcjs-cursor) is one measure later

changing progress position after starting the player works fine!
can you please have a look on this? thanks!

**Comment by mihammerl** [comment]
@paulrosen 
i'm not shure if you received the message above... 
you can watch this please (and reopen the issue)? thanks!
