### ISSUE TITLE
preload Audio-files

### ISSUE THREAD

**Issue by mxbastian** [paulrosen/abcjs#568]
Hi guys,

i've a problem. There is a huge gap between start play synth audio and listen the music. This colidates with other functions i embeded in the whole structure. Is there a way to preload the soundfiles on page-onload, instead of load soundfiles on button play?

Test the issue here: https://gracile-software.de/projects/ZDF_Mark/random.php
Click on a Song to reach the Player.

Thx und best regards from Berlin.

**Comment by paulrosen** [comment]
I've pasted part of the synth example here to show you how to split it up.

Notice first that you can't do anything until the user interacts with the page, so you can't do this at page load, but you can do it after the user clicks something.

Then, although this is becoming less important as browsers improve, you should be sure that audio is supported.

Then notice the `midiBuffer.init` call. That's where the notes are loaded. If you know the tune you want then you can call that early. That's the really slow part. The notes are cached so even if you know the key, instruments, and octave you could pass in a scale or something.

Then notice the `midiBuffer.prime` call. That has a small delay, depending on the tune, but it can also be done early. What I do when setting multiple actions off at once is wait until that promise is resolved to start everything.

```
startAudioButton.addEventListener("click", function() {
	startAudioButton.setAttribute("style", "display:none;");
	explanationDiv.setAttribute("style", "opacity: 0;");
	if (ABCJS.synth.supportsAudio()) {
		stopAudioButton.setAttribute("style", "");

		// An audio context is needed - this can be passed in for two reasons:
		// 1) So that you can share this audio context with other elements on your page.
		// 2) So that you can create it during a user interaction so that the browser doesn't block the sound.
		// Setting this is optional - if you don't set an audioContext, then abcjs will create one.
		window.AudioContext = window.AudioContext ||
			window.webkitAudioContext ||
			navigator.mozAudioContext ||
			navigator.msAudioContext;
		var audioContext = new window.AudioContext();
		audioContext.resume().then(function () {
			// In theory the AC shouldn't start suspended because it is being initialized in a click handler, but iOS seems to anyway.

			// This does a bare minimum so this object could be created in advance, or whenever convenient.
			midiBuffer = new ABCJS.synth.CreateSynth();

			// midiBuffer.init preloads and caches all the notes needed. There may be significant network traffic here.
			return midiBuffer.init({
				visualObj: visualObj,
				audioContext: audioContext,
				millisecondsPerMeasure: visualObj.millisecondsPerMeasure()
			}).then(function (response) {
				// console.log(response); // this contains the list of notes that were loaded.
				// midiBuffer.prime actually builds the output buffer.
				return midiBuffer.prime();
			}).then(function () {
				// At this point, everything slow has happened. midiBuffer.start will return very quickly and will start playing very quickly without lag.
				midiBuffer.start();
				return Promise.resolve();
			}).catch(function (error) {
				if (error.status === "NotSupported") {
					stopAudioButton.setAttribute("style", "display:none;");
					var audioError = document.querySelector(".audio-error");
					audioError.setAttribute("style", "");
				} else
					console.warn("synth error", error);
			});
		});
	} else {
		var audioError = document.querySelector(".audio-error");
		audioError.setAttribute("style", "");
	}
});
```
