### ISSUE TITLE
Worth to notate regarding multitempos

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#569]
Testing in the "full-synth" example beta 24

If changing "Cooley's" to include multitempo like this:

var abc = [
			"T: Cooley's\n" +
			"M: 4/4\n" +
			"L: 1/8\n" +
			"Q:1/4=70\n" +
			"R: reel\n" +
			"K: Emin\n" +
			"|:{E}D2|EB{c}BA B2 EB|[Q:1/4=80]~B2 AB dBAG|[Q:1/4=90]FDAD BDAD|FDAD dAFD|\n" +
			"[Q:1/4=100]EBBA B2 EB|[Q:1/4=110]B2 AB defg|afe^c dBAF|DEFD E2:|\n" +
			"|:gf|eB B2 efge|eB B2 gedB|A2 FA DAFA|A2 FA defg|\n" +
			"eB B2 eBgB|eB B2 defg|afe^c dBAF|DEFD E2:|",
];

when the reprise start, abcjs will not consider the first tempo in the header "Q:1/4=70" and the animation will go out of sync with the playback sound.
Actually it looks like the animation is following the header tempo information but the sound playback is not.
The sound playback will be effected when it reach the first inline tempo information.

To make it work in this example, just move the header tempo to the inline music and it will sync properly, like this:

var abc = [
			"T: Cooley's\n" +
			"M: 4/4\n" +
			"L: 1/8\n" +
			"R: reel\n" +
			"K: Emin\n" +
			"|:[Q:1/4=70]{E}D2|EB{c}BA B2 EB|[Q:1/4=80]~B2 AB dBAG|[Q:1/4=90]FDAD BDAD|FDAD dAFD|\n" +
			"[Q:1/4=100]EBBA B2 EB|[Q:1/4=110]B2 AB defg|afe^c dBAF|DEFD E2:|\n" +
			"|:gf|eB B2 efge|eB B2 gedB|A2 FA DAFA|A2 FA defg|\n" +
			"eB B2 eBgB|eB B2 defg|afe^c dBAF|DEFD E2:|",
];

**Comment by paulrosen** [comment]
Ok, I can reproduce it.

**Comment by paulrosen** [comment]
Fixed in version 6.0.0-beta.25

**Comment by musikboden** [comment]
Great, thank you Paul! 👍
