### ISSUE TITLE
wrap bug with text

### ISSUE THREAD

**Issue by mihammerl** [paulrosen/abcjs#575]
hi paul :)

abcjs-6.0.0-beta.24\examples\wrap.html

adding %%text and redraw with Total width 500 fails: newLines[currentLine[j][k]].staff is undefined
    wrapLines file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/dist/abcjs-basic.js:11173
    parse file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/dist/abcjs-basic.js:4842
    getRevisedTune file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/dist/abcjs-basic.js:11722
    calcLineWraps file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/dist/abcjs-basic.js:11800
    doLineWrapping file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/dist/abcjs-basic.js:1145
    callback file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/dist/abcjs-basic.js:1131
    renderEngine file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/dist/abcjs-basic.js:707
    renderAbc file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/dist/abcjs-basic.js:1139
    redraw file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/examples/wrap.html:33
    changeParameters file:///C:/Users/mihammerl/Documents/dev/_sources/abcjs-master/abcjs-master/examples/wrap.html:56
abcjs-basic.js:11173:17

![image](https://user-images.githubusercontent.com/75008094/102089583-b87ae400-3e1c-11eb-9fea-239e1c45a8d2.png)

is there maybe a workaround? thanks!

**Comment by paulrosen** [comment]
Ok, I can reproduce. I don't think there is a work around but I can probably get this into next week's release.

**Comment by paulrosen** [comment]
I guess the workaround is to split these into two tunes and use the text as the title of the second one:
```
T: Cooley's
etc...

T:Test
etc...
```
with the blank line it will create two separate tunes that you would place with two `<div id="paper1">`.

Not ideal, I know.

**Comment by paulrosen** [comment]
Fixed in version 6.0.0-beta.25
