### ISSUE TITLE
Cannot read property 'millisecondsPerMeasure' of null

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#576]
In abcjs_basic v6.0.0-beta.24 I got this error briefly until I cleared my cache. Possibly connected with moving from git mp3 files to my own hosted ones. Don't know if it will appear again or not. You can close if you don't think it's an issue.

abcjs_basic.js:16193 Uncaught TypeError: Cannot read property 'millisecondsPerMeasure' of null
    at SynthController.self.go (abcjs_basic.js:16193)
    at SynthController.self.play (abcjs_basic.js:16248)
    at doNext (abcjs_basic.js:14896)
    at acResumerMiddleWare (abcjs_basic.js:14890)
    at HTMLButtonElement.<anonymous> (abcjs_basic.js:14919)

**Comment by nbruley** [comment]
This actually still happens. It appears that this is likely due to clicking play before all of the files are fully loaded. If I click play immediately on page load, I get the error. If I wait a few seconds for the player to receive the files to play, it plays fine. After the load of the page, everything loads very quickly and doesn't error regardless of whether I change the ABC. Maybe I need to do something on my side to now show the player until the initial load is complete.

**Comment by paulrosen** [comment]
This will be fixed in the next version. It's already fixed in dev.

**Comment by nbruley** [comment]
Thanks. I did change my code to wait to display the player until it has been fully loaded, so it's resolved on my side.

**Comment by paulrosen** [comment]
Fixed in version 6.0.0-beta.25
