### ISSUE TITLE
Wrong tempo playback

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#577]
When piece is played back, tempo is a little bit lower than specified tempo.
Simple to reproduce: play half or quarter notes at 120 bpm for a minute.

Example:
https://artinfuser.com/harmony-dev/editor.html?state=IgABEAwDckoEHuAUAMAC4CcCmAjANtiAJTxgllinnVWUU320N2NusctfM9N.vd-nXgJHChg0RLGTxU-XMWzlM1dPUKVGpWs26d2rXsP6jB4xfNWzN03ZMPLtx9ftO3rl8.deP3zz6BAcH-oX7hvpFBYVFKIAAQYODwAMoA9gAOAHQAJAAK-ACGAJYAdujFAG7YAAQZmGkAxtgAzi1pmDWNaaUt2JiVhRU9ALQAjADMAKz5RWUV1SP1Ta3tmCPdvf2Dw6Xj0wAe5McgAPoAW5UAWkA___

```
%%barnumbers 1
%%printtempo 0
Q:1/4=120
M:4/4
K:C
L:1/16
V: V0 clef=treble name="Sop."
[V: V0]B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4B4B4|B4B4z8|
```

Why this is important: tempo cannot be synchronized to exact external source.
Possible cause: maybe setTimeout is used instead of setInterval or something like this?

**Comment by paulrosen** [comment]
That's not happening for me. I wonder what is different on our systems. I played that back with a metronome on my phone and it doesn't drift. I also downloaded a wav file and looked at it in Audacity and the notes start right on the second.

**Comment by rualark** [comment]
For some reason I cannot reproduce it now...
I will reopen if I see that again.
