### ISSUE TITLE
Question about midi to ABC

### ISSUE THREAD

**Issue by osvi64** [paulrosen/abcjs#579]
Hi Paul

As it is possible to download the midifile of the ABCJS tune, it means that ABCJS is able to convert ABC to midi, I was wondering if it is possible in some way to do the opposite, i.e. to take a midi file (or a data structure with midi events) and transform it to abcjs tune.

Thank you

**Comment by paulrosen** [comment]
I don't have that functionality yet. Maybe someday. It is not completely trivial to do - there is a lot of information that the midi file doesn't contain that needs to be inferred from music theory. 

A simple example is - does midi note 61 refer to C# or Db?

There are also many timing issues - if the midi comes from someone playing a piano, for instance, then the notes won't be precisely on the beat so there is some intelligent rounding needed.
