### ISSUE TITLE
Can not get note name on click 

### ISSUE THREAD

**Issue by Aduffy** [paulrosen/abcjs#580]
I am trying to retrieve the note name on click but it does not see to be returned with the element 

See that there is a pitch I can grab and that there is a pitchToNote object as part of the synth 

```
	clickListener: (element) => {
		console.log(element);
		const pitch = element.pitches[0].pitch;
		const note = synth.pitchToNoteName[(pitch)];
		console.log(note);
	}
```
But.. if i click on my note that is a G3 the pitch returned is "-3" a value that is not in the pitchToNote object. (it contains 21 - 121) 

Is the 'pitch' being returned with my note on click un related to the pitch values in synth? 

Is there another way to get the note name (with octive) ?

Thanks.

**Comment by paulrosen** [comment]
If you aren't using audio then the pitch isn't calculated. After doing `tune = renderAbc` then call `tune[0].setUpAudio();` and you'll see more in the object. In particular see the `midiPitches` array.

**Comment by Aduffy** [comment]
Thanks Paul. Is there a way to get note name without using Audio?

**Comment by paulrosen** [comment]
You don't need to play the audio - just set it up. It doesn't take very long but I didn't want to add that for people who didn't need it.

**Comment by Aduffy** [comment]
Cool.. figured id give the playback a go, I have it displaying the play controls in my #audio div but when i hit play i gett error 

`Uncaught TypeError: can't access property "millisecondsPerMeasure", e.visualObj is null`

```javascript

	
	var el = document.getElementById("score");
	var visualObj = renderAbc(el, abcString, {
		add_classes: true,
		responsive: "resize",
		oneSvgPerLine: true,
		clickListener: ({ midiPitches, elements, ...rest }) => {	
			const note = synth.pitchToNoteName[midiPitches[0].pitch];
			console.log(note);
		}
	});
	console.log(visualObj);
	
	
	var synthControl = new ABCJS.synth.SynthController();
	
	synthControl.load("#audio", 
		{
			onEvent: ({ midiPitches, elements, ...rest }) => {
			  const note = synth.pitchToNoteName[midiPitches[0].pitch];
			  console.log(note);
			  const noteElement = elements[0].find(({ classList }) => classList.contains('abcjs-note'));
			  noteElements.forEach((x) => {
				x.classList.toggle('abcjs-note_playing', x === noteElement)
			  });
			}
		},
  		{
			displayLoop: true, 
			displayRestart: true, 
			displayPlay: true, 
			displayProgress: true, 
			displayWarp: true
		}
	);

	var createSynth = new ABCJS.synth.CreateSynth();
	createSynth.init({ visualObj: visualObj[0] }).then(function () {
		synthControl.setTune(visualObj[0], false, audioParams).then(function () {
			console.log("Audio successfully loaded.")
		}).catch(function (error) {
			console.warn("Audio problem:", error);
		});
	}).catch(function (error) {
		console.warn("Audio problem:", error);
	});

```

**Comment by paulrosen** [comment]
That's already fixed but I haven't released it yet - the problem is that it is still loading in the background. 

As a workaround, if you let the page sit until the network activity stops it should work.

**Comment by Aduffy** [comment]
I can see all the notes loading up for the playback 

![image](https://user-images.githubusercontent.com/265857/102703904-f23b5880-4229-11eb-9d74-331d4e04bbe2.png)

And nothing else to load but still get that error

**Comment by Aduffy** [comment]
OK i had missed the creating the audioParams object... odd it didnt give me an undefined error. 

added that and now have playback.. BUT. I hay my own local soundfont files for and acoustic steel string guitar 

```javascript
	const createSynth = new ABCJS.synth.CreateSynth();
	
	const audioParams = { 
		chordsOff: true, 
		soundFontUrl : '/assets/soundfonts/MusyngKite/acoustic_guitar_steel-mp3/',	
	 };
	createSynth.init({ visualObj: visualObj[0] }).then(function () {
		synthControl.setTune(visualObj[0], false, audioParams).then(function () {
			console.log("Audio successfully loaded.")
		}).catch(function (error) {
			console.warn("Audio problem:", error);
		});
	}).catch(function (error) {
		console.warn("Audio problem:", error);
	});
```
![image](https://user-images.githubusercontent.com/265857/102704159-92927c80-422c-11eb-9ac6-5e87501450a5.png)

 but it seems to be ignoring that path and playing the Grand Piano sounds from the defaults.

**Comment by paulrosen** [comment]
```
soundFontUrl: '/assets/soundfonts/MusyngKite'
```
Then in your ABC string put:
```
%%MIDI program 25
```

**Comment by Aduffy** [comment]
No love this is mt string 

```
X: 1
M: 4/4
L: 1/8
 K: G
 K: transpose=-12
 %%MIDI program 25
||A,B,^CD | E^F^GA | B^cde | ^f^gab | ^c'd'^c'b | a^g^fe | d^cBA | ^G^FED | ^CB,A, ||
```
and this is my audioParams

```javascript

	const audioParams = { 
		soundFontUrl: '/assets/soundfonts/MusyngKite',
		options: { program: 25 }
	};
	
```
Still loads notes from 
https://paulrosen.github.io/midi-js-soundfonts/abcjs/acoustic_grand_piano-mp3/

**Comment by paulrosen** [comment]
You can't have a leading space on the line. You can also combine the two K lines
```
K: G transpose=-12
```

**Comment by Aduffy** [comment]
OK fixed. But has no effect on Sound font.. 

![image](https://user-images.githubusercontent.com/265857/102725934-6da31580-42cf-11eb-9255-bd55796b0c43.png)

**Comment by paulrosen** [comment]
Sorry that the options are confusing. I'm working on clearer documentation right now. The sound font declaration goes here:
```
createSynth.init({ 
  visualObj: visualObj[0],
  options: {
    soundFontUrl: '/assets/soundfonts/MusyngKite'
  }
 }).then(function () {
```

**Comment by Aduffy** [comment]
Hi Paul moving the soundFontUrl into into the options did not help with this issue. files are still loading form Github, 

Please review my example page at https://music.duffield.me/abc2.html

```js
const audioParams = { 
	soundFontUrl: '/assets/soundfonts/MusyngKite',
	options: { 
		program: 25, 
		soundFontUrl: '/assets/soundfonts/MusyngKite'
	 }
};
```
Files still loading from GitHub...

**Comment by Aduffy** [comment]
I have resolved this now. I had the options in synthControl.setTune() instead of createSynth.init()
