### ISSUE TITLE
Class name for interval , note and octive 

### ISSUE THREAD

**Issue by Aduffy** [paulrosen/abcjs#581]
Is there a way to have each note include a class name for the interval based on the key? Also would be nice to have class for note and octave. 

I am hoping to use ABCjs in an app Im building to display scales. The rest of my app uses different colors to display intervals (on chord charts and fretboard) I am hoping that I can have the notes displayed with the same colors. 

<img width="908" alt="image" src="https://user-images.githubusercontent.com/265857/102578083-343f8f80-40ae-11eb-970d-59f02813a976.png">

**Comment by paulrosen** [comment]
If you use `renderAbc("paper", tune, { add_classes: true }` you will get a lot of info about the note.

It doesn't have the info you are asking for but you can look for the classes `abcjs-pXX` where XX is the vertical position of the note (With middle C = 0). So you can calculate it - for instance, in the key of G the tonic is -3 so the class `abcjs-p1` is  four positions higher (a D) so is the dominant.

**Comment by Aduffy** [comment]
That will work.
