### ISSUE TITLE
Timing bug in beta 24

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#583]
Since I changed to beta 24 all my loop points get out of sync so I looked at the "play-on-repeat" example, and if you set the start measure to 14 and end measure 16 you can clearly hear that the loop drift and it clips the first note and plays a short ms of the first note in measure 16.
This is happening only in beta 24, it looped perfect on earlier versions

**Comment by musikboden** [comment]
I also noticed, in this example, that the cursor is unsynced to the playback

**Comment by paulrosen** [comment]
This will be fixed in beta 25.

**Comment by musikboden** [comment]
👍

**Comment by paulrosen** [comment]
Fixed in version 6.0.0-beta.25

**Comment by musikboden** [comment]
Thank you Paul, it's much better now 👍 
But it's still some issues with looping and the "abcElem.currentTrackMilliseconds" not showing the exact value when comparing to "totalTime", see this:
#601
