### ISSUE TITLE
404 error for Soundfont URL in readme 

### ISSUE THREAD

**Issue by Aduffy** [paulrosen/abcjs#584]
The readme.md says

"In this beta the default soundfont was changed to https://paulrosen.github.io/midi-js-soundfonts/abcjs/  " 

but the domain returns a 404 error..

**Comment by paulrosen** [comment]
That is the base path - the actual sounds are in subfolders under that. For instance https://paulrosen.github.io/midi-js-soundfonts/abcjs/acoustic_grand_piano-mp3/F5.mp3
