### ISSUE TITLE
 spellcheck="false" for <textarea> on www.abcjs.net/abcjs-editor.html

### ISSUE THREAD

**Issue by dvergin** [paulrosen/abcjs#587]
For browsers that automatically do spellcheck in textarea boxes, it's a little distracting to see most of the abc code marked as mis-spelled. The simple addition of the spellcheck="false" attribute for that textarea element on that page (tested) would remedy the problem.

Cheers,
dvergin

**Comment by paulrosen** [comment]
Thanks! Fixed.
