### ISSUE TITLE
Transposition bug (?)

### ISSUE THREAD

**Issue by u38cg** [paulrosen/abcjs#588]
I use this bookmarklet (which uses abcjs) quite a lot for rendering random abc snippets:

https://github.com/m3g4p0p/abc-select-bookmarklet

I notice that if you take this abc:

X: 1
T: Auld Lang Syne – 2020 Edition
C: Jim Quail
M: 4/4
K: G minor
L: 1/8
D2| G3 G G2 B2| A3 ^G A2 (B A) | G3 G B2 d2 | e6 g2 |
d3 B B2 G2| A3 ^G A2 (B A) | G3 E E2 D2 | G6 e2 |
d3 B B2 G2 | A3 ^G A2 e2 | d3 B B2 d2 | e6 g2 |
d3 B B2 G2 | A3 ^G A2 (B A) | G3 E E2 D2 | G6 ||

Note that in bar 2, there is a semitone between A and ^G.  

If I transpose down a semitone in the bookmarklet to F# minor, the A becomes a G (sharp because of the key signature) and the F should now have a double sharp, but it has only kept a single sharp, so the distance between the two notes is now a whole tone.

**Comment by paulrosen** [comment]
The bookmarklet is using an older version of abcjs. That has already been fixed and I contacted the author about upgrading. You can see the current behavior in the example editor-transpose.html

**Comment by u38cg** [comment]
Ah, thanks Paul.  I'll send him a note as well, just in case he's missed it.
