### ISSUE TITLE
`onBeat` and `onEvent` desync after play-pause-reset-play

### ISSUE THREAD

**Issue by p-himik** [paulrosen/abcjs#594]
Currently we use both the Reset button and the current note highlighting.
And seems like with the new playback functionality, these things are somewhat broken if you use them together:
- Open `full-synth.html`
- Press Play
- Let it play for a few seconds
- Press Pause
- Press Reset (here the cursor line is not reset, but it's a minor issue)
- Press Play
then a wrong position will be highlighted as the current one.

And if you look at the line right under the controls that starts with "Beat", you'll notice that while the MIDI is playing the `onBeat` callback is not called for a few notes.

**Comment by Aduffy** [comment]
This also happens after adjusting the tempo, either via the built in BPM% control or val setWarp(). 
Issue can be viewed here. 
https://music.duffield.me/abc2.html

**Comment by paulrosen** [comment]
Thanks for the bug report. I'll look into it.

**Comment by paulrosen** [comment]
Fixed in version 6.0.0-beta.25
