### ISSUE TITLE
setTune millisecondsPerMeasure not working

### ISSUE THREAD

**Issue by alexdemartos** [paulrosen/abcjs#598]
Hi, first of all thanks for sharing this great library with the community and for all your effort.

I haven't been able to utilize the _millisecondsPerMeasure_ parameter on the _synthController.setTune_ call. No matter what value I set (500, 1000, etc), notes will always be 1/4s.

Am I doing something wrong?

```
this.synthController.setTune(this.abcjs[0], audioContext.state === 'running', {
        audioContext: audioContext,
        soundFontUrl: process.env.PUBLIC_URL + process.env.REACT_APP_SOUND_FONT_URL,
        program: this.props.instrumentId,
        millisecondsPerMeasure: (60 / this.state.tempo)*1000,
        visualObj: this.abcjs,
        ...
```

Thanks in advance.

**Comment by paulrosen** [comment]
Hi, thanks!

Sorry for the confusing way of setting parameters - I'm trying to simplify that now in a way that doesn't break existing programs.

The millisecondsPerMeasure parameter is overwritten when changing tunes - that makes it useless in this use case at the moment.

Right now you can change the tempo by calling the `this.synthController.setWarp(percent)` function. This will change the tempo from the value that is specified in the ABC string.

Look for a better way of calling this by beta 26.

**Comment by alexdemartos** [comment]
Thank you!
