### ISSUE TITLE
Errors and sync issues after setting BPM in Beta 25 

### ISSUE THREAD

**Issue by Aduffy** [paulrosen/abcjs#600]
Hi Paul Im sorry to report that I am still seeing issues with setting BMP and Sync in Beta 25.

**Issues with sync and tempo after setting Tempo / BPM with built in controls**
Steps to reproduce :

1. Press play - Play back is in sync with events (note changes color) BPM shows as 180.
2. Type in "50" in the % box next to where BPM is shown - changes to 45 BPM instead of 90...
3. Press play - Playback is not out of sync with events

https://music.duffield.me/abc3.html

**Comment by Aduffy** [comment]
Hey Paul, just wondering if you have had any time to look at this one..

**Comment by paulrosen** [comment]
I do have some fixes and will be doing another beta soon.

**Comment by paulrosen** [comment]
Fixed in beta.26

**Comment by Aduffy** [comment]
Changing tempo works as expected but events and audio are still completely out of sync. 

https://music.duffield.me/abc3.html
