### ISSUE TITLE
abcElem.currentTrackMilliseconds bug in beta 25?

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#601]
Comparing "abcElem.currentTrackMilliseconds" with "totalTime is not in sync in this tune.

X:1
T:In och utvänd get
C:Bulgarien
%%score { 1 | 2 }
%%printtempo 0
L:1/8
Q:1/4=140
M:11/8
I:linebreak $
K:C
V:1 treble nm="Piano"
V:2 bass 
V:1
%%MIDI gchordon
 "Am"A,B,CD EFD E2 E2 | GFED EFD E2 E2 | A,B,CD EFD E2 E2 | 
 "Dm"DDCB, "Em"CDB, "Am"A,2 A,2 | "Dm"DDCB, "Em"CDB, "Am"A,2 A,2 | "Dm"DDCB, "G"CDB, "C"CD E2 | 
 "Dm"DDCB, "Em"CDB, "Am"A,2 A,2 | "F"DDCB, "G"CDB, "Am"A,2 A,2 | %8
V:2
 A,,2 .[E,C,]2 E,,2 .[E,C,] A,,2 .[E,C,]2 | A,,2 .[E,C,]2 E,,2 .[E,C,] A,,2 .[E,C,]2 | A,,2 .[E,C,]2 E,,2 .[E,C,] A,,2 .[E,C,]2 | 
 D,,2 .[A,,F,,]2 E,,2 .[B,,G,,] A,,2 .[E,C,]2 | D,,2 .[A,,F,,]2 E,,2 .[B,,G,,] A,,2 .[E,C,]2 | D,,2 .[A,,F,,]2 G,,2 .[D,B,,] C,2 .[G,E,]2 | 
 D,,2 .[A,,F,,]2 E,,2 .[B,,G,,] A,,2 .[E,C,]2 | F,,2 .[C,A,,]2 G,,2 .[D,B,,] A,,2 .[E,C,]2 | %8

It's "totalTime" = 18857
It has 8 bars, so on first note in bar 5, it should be half the totalTime but it is:
3142.8571428571427

The meter is 11/8, maybe that is causing it?

**Comment by musikboden** [comment]
#583

**Comment by paulrosen** [comment]
Yeah it was because of the time signature of 11/8. This will be fixed in Beta 26. Coming soon, this will be a small release.

**Comment by musikboden** [comment]
👍

**Comment by paulrosen** [comment]
Fixed in beta.26

**Comment by musikboden** [comment]
Thank you Paul!
