### ISSUE TITLE
Question regarding accelerando

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#602]
If I have a tune with accelerando (multi tempo changes), will the "self.onBeat" follow the tempo changes?
And will the "abcElem.currentTrackMilliseconds" show actual time at logging?

**Comment by paulrosen** [comment]
It should. Let me know if it doesn't. The each tempo change will have to be explicitly set with the `Q:` command.

**Comment by musikboden** [comment]
Ok, I will! Thanks!
