### ISSUE TITLE
Defining selectTypes breaks input text focus&selection on note click

### ISSUE THREAD

**Issue by alexdemartos** [paulrosen/abcjs#603]
Hi,

I just found out that when I define the selectTypes parameter to any value in ['note', ...] or true, the abc text in the edit area does not get automatically selected and focused when clicking a note. It works properly if I remove the 'selectTypes' parameter. Is this a bug, or a known limitation?

Thank you.

```
new abcjs.Editor("ExEd-abc", { 
        canvas_id: "ExEd-paper", 
        warnings_id:"ExEd-warnings",
        abcjsParams: {
            responsive: 'resize',
            staffwidth: 500,
            add_classes: true,
            clickListener: this.handleNoteClick,
            dragging: false,
            selectTypes: ['note', 'clef', 'keySignature', 'voiceName', 'timeSignature', 'tempo'],
            format: {
              stretchlast: 0
            }
        }
});
```

**Comment by paulrosen** [comment]
That's a bug. Thanks for reporting! I'll get this fixed soon.

**Comment by paulrosen** [comment]
The correct text is being selected but the focus moves to the element clicked.

I think that is the correct behavior because that is the point of being able to select elements, but I could be convinced otherwise.

**Comment by alexdemartos** [comment]
Ok, thank you. I'll solve it by manually focusing the text element after the note click is triggered.

Thanks for your help!
