### ISSUE TITLE
Broken rhythm with >>> or <<< is incorrect

### ISSUE THREAD

**Issue by selfthinker** [paulrosen/abcjs#604]
All broken rhythm that is written with three greater than or lesser than signs is incorrectly interpreted. All broken rhythm with one or two such signs is fine.

The ABC spec says:
> `>>>` means that the first note is triple dotted and the length of the second divided by eight

But this code, for example,...
```
A>>>A A2>>>A2 A4>>>A4|A<<<A A2<<<A2 A4<<<A4|]
```
... leads to this output:
![triple-broken-rhythm-abcjs](https://user-images.githubusercontent.com/108893/104385298-e5f5a300-552a-11eb-85b4-1833b525ebf8.png)

This is the same example from $ABC_UI with a correct output:
![triple-broken-rhythm-abc-ui](https://user-images.githubusercontent.com/108893/104385297-e55d0c80-552a-11eb-80c4-39b0b96b97dc.png)

**Comment by paulrosen** [comment]
Thanks for the bug report. I'll look into it.

**Comment by paulrosen** [comment]
Fixed in beta.26
