### ISSUE TITLE
Publish midi to npm

### ISSUE THREAD

**Issue by mrdrogdrog** [paulrosen/abcjs#605]
HI,

We use abcjs in https://github.com/hedgedoc/react-client and the midi.js dependency is resolved via git.
Why is midi.js not published to npm?

I'm asking here, because the issue tracker of https://github.com/paulrosen/MIDI.js.git is deactivated.

Sincerely

Tilman from HedgeDoc

**Comment by mrdrogdrog** [comment]
Short explanation:
Our dependency-update-bot and our local yarn are fighting over the syntax of the [yarn.lock](https://github.com/hedgedoc/react-client/commit/ec41448867d3725f721bc5973d4d1dfd9001cff2). This is a bit annoying and could be solved with a npm package. :sweat_smile:

**Comment by paulrosen** [comment]
The reason it is not published is that it is a fork of MIDI.js with a couple hacks that I needed to make it work for my purposes.

It is only needed if you are using the old method of creating audio.

I think I can probably change the package to have it as a peer dependency. I'll experiment.

**Comment by mrdrogdrog** [comment]
That would be great :heart:

**Comment by paulrosen** [comment]
I think this is fixed in beta.26

**Comment by mrdrogdrog** [comment]
Thank you!
