### ISSUE TITLE
Something has changed in beta 25 & 26

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#606]
When loading a song in Safari, both desktop and iOS, from my site, I get this message "Didn't load note....." from the console, and it's coming from this line in beta 26
`function(n) {
                    if (n.renderedBuffer)
                        for (var i = 0; i < s.length; i++) {
                            var o = s[i] * r.tempoMultiplier;
                            c && (o -= c / 1e3),
                            o < 0 && (o = 0),
                            o = Math.floor(o * t),
                            a(e, n.renderedBuffer, o)
                        }
                    v()
                }, f.startRendering(), new Promise((function(e, t) {
                    v = e
                }))
            }
            console.log("Didn't load note: " + r.instrument + " " + p)`

However the notes are loaded (I think) but when hitting play, no sound is coming, the cursor is running as it should.
If I then activate the metronome, 

![Skärmavbild 2021-01-20 kl  19 48 56](https://user-images.githubusercontent.com/18282700/105221019-d2fd5700-5b58-11eb-8c3a-7d9eeb470d17.png)

it will update the code and when I hit play again, I'll get playback with sound.
I think this problem started with beta 25 but it could have been earlier...
If I use Chrome it works directly, no problems what so ever.

Paul could you please check if you can see what the problem is?

Here's the site:
http://musikboden.se/notbibliotek.html

**Comment by musikboden** [comment]
I tested all examples in beta 26 with Safari (Version 14.0.2 (14610.3.7.1.10))
This examples have problems with audio playback:
* basic-synth (no audio)
* editor-synth (no audio)
* printable (no audio)
* basic-transpose (no audio, but if I transpose it will play some random loaded notes)
* editor-transpose (even if I transpose it will not output any audio)
* full-synth (plays almost all notes but some notes will not play, if loaded again some other notes will not play)
* karaoke-synth (the first click fails, the second click works)
* modify-synth-input (the first click fails, the second click works)
* play-on-repeat (the first click fails, the second click works)
* synth-only (the first click fails, the second click works)

Is this a problem in Safari?

**Comment by musikboden** [comment]
I tested all examples above in Chrome (Version 88.0.4324.96 (Officiell version) (x86_64))
and they all started the playback as they should (with audio)
I noticed, in the "editor-transpose" example, that the different transpose methods sometime works, and sometime it's not working.

**Comment by paulrosen** [comment]
I can duplicate. Will fix in next beta.

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.27. If there is still a problem, comment here and I'll reopen.

**Comment by musikboden** [comment]
Thank you, now it works 🙏
