### ISSUE TITLE
Sync issues still present in Beta 27

### ISSUE THREAD

**Issue by Aduffy** [paulrosen/abcjs#607]
it seems the playback and events are still out of sync in  Beta 26. 

https://music.duffield.me/abc3.html

**Comment by paulrosen** [comment]
I can reproduce. Will be fixed in next beta.

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.27. If there is still a problem, comment here and I'll reopen.

**Comment by Aduffy** [comment]
Ya its MUCH better. Play, pause an restart all seem to work well, but if you let the tune play to the end and then play again its out of sync. :-( 

I updated my example page above with beta .27

**Comment by Aduffy** [comment]
I had hopped I could just add an synthControl.restart()  to the onFinish event as a work around,  it appears that a call to synthControl.restart() sets the notation back to the beginning but also fires the first (visual) event (my note is highlighted) but no audio is played... Then when I play again the visual events start at the second even and the audio at the first, so audio is exactly one note behind what is being shown .

**Comment by Aduffy** [comment]
Hey Paul did you see these comments? Please re open this ticket..

**Comment by Aduffy** [comment]
Hi Paul, have you had any luck finding the cause of this one?

**Comment by paulrosen** [comment]
Sorry - this has been a really busy couple of weeks. I have just a couple issues to look at before the next release and I hope to have it done this weekend.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.28
