### ISSUE TITLE
Audio not updated in "editor-synth"beta 26 example

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#609]
When trying out songs and abcjs functions in the "editor-synth" beta 26 example, the audio is not updated when changing notes.
The visual feedback is working great but not the audio playback
(tested on Chrome Version 88.0.4324.96 (Officiell version) (x86_64))

**Comment by paulrosen** [comment]
I can reproduce. It will be in the next beta, probably this weekend.

**Comment by paulrosen** [comment]
Fixed in 6.0.0-beta.27. If there is still a problem, comment here and I'll reopen.

**Comment by musikboden** [comment]
Thank you Paul, it seems to update as it should now. 👍
