### ISSUE TITLE
How to generate new glyphs?

### ISSUE THREAD

**Issue by remcohh** [paulrosen/abcjs#61]
Hello, not an issue but a question:
I want to add glyphs for  alternative note heads, I saw the font_gen example but I don't know how to generate the js structures as in the code, for example:

```
 'rests.whole':{d:[["M", 0.06, 0.03], ["l", 0.09, -0.06], ["l", 5.46, 0], ["l", 5.49, 0], ["l", 0.09, 0.06], ["l", 0.06, 0.09], ["l", 0, 2.19], ["l", 0, 2.19], ["l", -0.06, 0.09], ["l", -0.09, 0.06], ["l", -5.49, 0], ["l", -5.46, 0], ["l", -0.09, -0.06], ["l", -0.06, -0.09], ["l", 0, -2.19], ["l", 0, -2.19], ["z"]],w:11.25,h:4.68}
```

How does that work?

Thanks!

**Comment by paulrosen** [comment]
Good question! And one that I have to figure out each time I need to work with that. I'll document the procedure one of these days.

What you are seeing is the "path" that the font uses to draw the character. It always starts with "M" and always ends with "z". That font is registered in Raphael.

You can play around with the font in real time using font_editor.html, but I forget the format that you are supposed to put in there.

You can see the fonts that exist in abc_glyphs, and at the bottom you can see the extra ones that I added. You can add new ones there.

**Comment by devrimbozdag** [comment]
I couldn't add any new characters either. It is very difficult to do this with abcjs Font Editor. Even the format on the Font Generator page is very different. Isn't there an editor where I can create fonts for abcjs?

**Comment by paulrosen** [comment]
Unfortunately there isn't an editor - this part of abcjs was never maintained. However, this is just a regular SVG path so you can create it with your own editor. Just be sure to use all relative paths. You don't actually have to change the glyphs in abcjs, look at `examples/change_glyphs.html` for an example of substituting glyphs.

**Comment by db5050** [comment]
I've been dealing for days. I examined all the examples you said. I guess that's why I'm going to look for another script.
SVG Path Editor I have not tried is out. I wrote the codes by examining the sample page you provided. It didn't happen either. The format you use is not compatible with anything.
"{d: [['M', 0.06,0], ['l', 4.46,0.00], ['l', 5.49,0.00], ['l', 0.00,1.19], ['l', 0.00,1.29], ['l', - 0.06,0.09], ['l', - 5.06,5], ['l', - 5.06,0], ['z']], w: 12.81, h : 15.63} "

However, I liked ABCJS script very much.

**Comment by paulrosen** [comment]
The format is basically SVG: in the example above, the first element is `['M',0.06,0]`. That translates to `M0.06,0`, etc. The last two elements are the width and height the element takes up.
