### ISSUE TITLE
Responsive Height?

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#610]
Is there any way to make the renderAbc() resize horizontal only?

I trying to render music in a single line, which I can do by simply removing all newlines from the ABC.

However, so the notes are easy to read, I need to scale the height of the rendering so it takes up the full viewpoint. There doesn't seem to be any built-in method to do this automatically.

The ["responsive" option](https://paulrosen.github.io/abcjs/visual/render-abc-options.html#responsive) only scales the entire svg element up or down so the entire thing fits in the viewpoint. However, because my rendering is all on one line (and most of the line should flow out of the viewpoint) this scales the rendering down until the entire width is inside the viewport, making the notes too small to read.

I can somewhat accomplish this by manually specifying `scale`, but this is awkward to calculate for different viewpoint sizes.

**Comment by paulrosen** [comment]
Do I understand that you want one line of music and have it scroll horizontally? And have the scale be whatever fits vertically?

There isn't a built in way. I did one app where I "scaled to fit". I've pasted the code below. You can modify it to just scale vertically. This is probably similar to the "awkward" solution you are trying. I was thinking of incorporating something like this in abcjs but haven't yet. I think you just want to always take the "tooTall" path.

Call this right after you render the music and whenever the browser resizes. 
```
makeResponsiveInBothAxis() {
	const paper = document.querySelector(".paper-wrapper");
	const svg = document.querySelector("#paper svg");
	const rect = paper.getBoundingClientRect();
	const viewBox = svg.getAttribute('viewBox').split(' ');
	const musicWidth = Math.ceil(viewBox[2]);
	const musicHeight = Math.ceil(viewBox[3]);
	const musicRatio = musicWidth / musicHeight;
	const containerWidth = Math.ceil(window.innerWidth);
	const containerHeight = Math.ceil(window.innerHeight - rect.top - (this.useMidi() ? 53 : 0));
	const containerRatio = containerWidth / containerHeight;
	const tooTall = (containerRatio > musicRatio);
	if (tooTall) {
		const newWidth = Math.floor(containerWidth / containerRatio * musicRatio) - 2; // the 2 is just to give it a tiny margin.
		paper.setAttribute("style", "width:" + newWidth + "px");
	} else {
		paper.setAttribute("style", "width:" + "99%");
	}
	// For Safari 8
	let svgStyle = svg.getAttribute("style");
	svgStyle += "width:100%;height:100%;";
	svg.setAttribute("style", svgStyle);
},
```

**Comment by paulrosen** [comment]
I added a demo for the above code here: https://github.com/paulrosen/abcjs/blob/dev/examples/zoom-to-fit.html

It will make it to the main branch in the next release.

**Comment by chrisspen** [comment]
Thanks. But that code gives me the error:

    Uncaught TypeError: Cannot read property 'split' of null

for the line:

     const viewBox = svg.getAttribute('viewBox').split(' ');

**Comment by paulrosen** [comment]
What browser and device are you using? I tried a few different ones and it worked in them.

**Comment by chrisspen** [comment]
It get the error in Brave 1.3.118 and Chrome 85.0.4183.121.

If I inspect the svg element generated by our code, the viewBox attribute isn't present on the tag.

What are you trying to get? The total dimensions of the svg element? Couldn't you use the standard `el.getBoundingClientRect()`? That appears to return the correct results for me.

**Comment by chrisspen** [comment]
What strategy are you using to resize the svg element? Even if I try to manually set the width and height of the svg element or the containers, nothing seems to effect the rendered svg size. I've tried setting the containers and the svg element to large pixel values, and also large percentage values, and they have no effect.

The only thing that has any effect is setting the CSS `transform: scale(x,y)`, but that seems to scale it using the lower left corner as the axis, so it scales out of the screen, becoming unviewable.

**Comment by chrisspen** [comment]
Nevermind. I forgot the `responsive: "resize"` option when adapting your code.

Otherwise, I was able to get it to work. Although your code does the opposite of what I needed. It shrinks the entire element into view, whereas I needed to scale the height up until it matches the current page height. But that was easy to implement based on your code.

Thanks.
