### ISSUE TITLE
Percussion (Drumset) Playback

### ISSUE THREAD

**Issue by MisterY** [paulrosen/abcjs#612]
Hi!

Thanks for this awesome tool! I just found out about ABC and have been experimenting tonight so please note that I'm still pretty unaware of all the options available both in ABC notation and the js engine.

When using [the editor](https://www.abcjs.net/abcjs-editor.html), I'm setting `K: perc` to get the percussion clef and then I'm following (most-likely) [this](https://web.mit.edu/merolish/Public/drums.pdf) notation, which matches MuseScore's.

The editor MIDI playback then produces percussion sounds, i.e. whistle, timbale, and cowbell instead of bass drum, snare, and toms. My question is - is there a way to somehow specify that a drumset should be used, in order to get the actual drumset sounds (toms, cymbals - ride/crash, hi-hat, snare, bass)? 

Here's a simple example:

```
%abc-2.1
X: 1
T: Cooley's
M: 4/4
L: 1/8
Q:1/4=90
R: rock
K: perc
| F2 c2 FF c2 | AA ee LAA ^a2  |
| (3 F2 F2 F2 F2 c2 | F2 c2 F>F c2|
```

**Comment by MisterY** [comment]
In the meantime, I have found a sample for the drumset:

```
X:5
T:Drum Key
M:
L:1/4
%%MIDI channel 10
%%MIDI program 0
%%MIDI drummap F 36 %bass drum 1
%%MIDI drummap c 38 %acoustic snare
%%MIDI drummap ^D 44 %pedal hi-hat
%%MIDI drummap ^f 51 %ride cymbal 1
%%MIDI drummap ^g 42 %closed hi hat
%%MIDI drummap ^a 49 %crash cymbal 1
%%MIDI drummap ^b 52 %chinese cymbal
%%MIDI drummap e 50 %high tom
%%MIDI drummap d 48 %hi mid tom
%%MIDI drummap B 45 %low tom
%%MIDI drummap A 41 %low floor tom
K:C clef=perc
"^Bass"F|"^Snare"c|"^High tom"e|"^Mid tom"d|"^Low tom"B"^Floor tom"A|
"^China/Other Cymbal"^b|"Crash"^a|"^Hi-hat"^g|"Ride"_f|"Hi-hat Pedal"_D|]
```

However, the last 4 notes do not match the mapping. But all the others do, which is a bit weird.
I'm on Arch Linux and that might also have something to do with it.

**Comment by MisterY** [comment]
After some more troubleshooting, I noticed that the definitions for the hihat pedal and the ride cymbal are mismatched. Here is the corrected version:

```
X:5
T:Drum Key
M:
L:1/4
%%MIDI channel 10
%%MIDI program 0
%%MIDI drummap F 36 %bass drum 1
%%MIDI drummap c 38 %acoustic snare
%%MIDI drummap _D 44 %pedal hi-hat
%%MIDI drummap ^f 51 %ride cymbal 1
%%MIDI drummap ^g 42 %closed hi hat
%%MIDI drummap ^a 49 %crash cymbal 1
%%MIDI drummap ^b 52 %chinese cymbal
%%MIDI drummap e 50 %high tom
%%MIDI drummap d 48 %hi mid tom
%%MIDI drummap B 45 %low tom
%%MIDI drummap A 41 %low floor tom
K:C clef=perc
"^Bass"F|"^Snare"c|"^High tom"e|"^Mid tom"d|"^Low tom"B"^Floor tom"A|
"^China/Other Cymbal"^b|"Crash"^a|"^Hi-hat"^g|"Ride" ^f|"Hi-hat Pedal"_D|]
```

This leaves only the Crash cymbal. This tone triggers the chord together with the cymbal for this note and for all the remaining ones. If the Crash bar/note is commented-out, all the notes play on the correct instruments.
So, most likely this is an issue for another library (midi player)?

**Comment by paulrosen** [comment]
The chord issue is in your labeling. Change `"Crash"` to `"^Crash"`. Without the caret the quoted string is interpreted as a chord, which is C.

I wouldn't doubt that there are some bugs in the way the percussion notes are laid out, though. Let me know if something seems wrong.

Also, there is nothing wrong with using the editor you found, but that was designed to be as simple as possible so that it can be understood and copied. This site is a little more feature-rich: https://editor.drawthedots.com/

**Comment by MisterY** [comment]
Ouch! Thank you. I didn't get into the details of text. So, all the issues come from that example. This was given to me as an example on how to get the drumset sounds. Now at least I understand.

Thanks for the new link. Somehow I did not run into it although I've seen the Draw the Dots site.
In that editor, however, I get some unexpected results. So, back to the (hopefully) corrected sample:

```
X:5
T:Drum Key
M:
L:1/4
%%MIDI channel 10
%%MIDI program 0
%%MIDI drummap F 36 %bass drum 1
%%MIDI drummap c 38 %acoustic snare
%%MIDI drummap _D 44 %pedal hi-hat
%%MIDI drummap ^f 51 %ride cymbal 1
%%MIDI drummap ^g 42 %closed hi hat
%%MIDI drummap ^a 49 %crash cymbal 1
%%MIDI drummap ^b 52 %chinese cymbal
%%MIDI drummap e 50 %high tom
%%MIDI drummap d 48 %hi mid tom
%%MIDI drummap B 45 %low tom
%%MIDI drummap A 41 %low floor tom
K:C clef=perc
"^Bass"F|"^Snare"c|"^High tom"e|"^Mid tom"d|"^Low tom"B"^Floor tom"A|
"^China/Other Cymbal"^b|"^Crash"^a|"^Hi-hat"^g|"Ride" ^f|"Hi-hat Pedal"_D|]
```

Almost all the notes now have different sounds that what they're supposed to be. I.e. 
bass drum (F) = side stick
snare = hand clap

I've been using [this](https://www.cs.cmu.edu/~music/cmsip/readings/GMSpecs_PercMap.htm) reference and it works that way in the editor I used earlier.

Oh, I get it. All the notes are moved by 1:

```
39 Hand Clap

%%MIDI drummap c 38 %acoustic snare
```
and the acoustic snare gets the hand clap sound.

**Comment by MisterY** [comment]
If I define snare as
`%%MIDI drummap c 37 %acoustic snare`
then it plays correctly. So, off by 2, then?

**Comment by MisterY** [comment]
Bass Drum = 36
Side Stick = 37

With 
`%%MIDI drummap F 36 %bass drum 1`
note F plays the Side Stick (37) and not Bass Drum (36).

**Comment by MisterY** [comment]
Yep, confirmed. If I lower the values, all the sounds play correctly and they sound fantastic!
That could be a bug?

**Comment by paulrosen** [comment]
Yes. Thanks for this analysis. It is probably in the sound font. I'll look into it.

**Comment by MisterY** [comment]
I did suspect that at some point, after looking at how the library works. Thanks for looking into it. 

Off topic, now that I'm aware of this functionality, I'm willing to get back to the idea of creating a set list app (also PWA) for the gigs. Abcjs practically covers the rendering, syntax, and display of the sheets. 
I need a refresh on metronomes in js and that would be it. Just to add the UI and the list management. I love Vue and Quasar, so this is a match made in heaven. 
The question is, are you aware of an existing solution, so I don't reinvent the wheel but contribute instead? Is there some list of apps that utilise abcjs, like a showcase? 
This is something I would create for myself but there must be others needing the same solution. (well, perhaps not *right now*)

**Comment by paulrosen** [comment]
I might have something for you about the gig set list - I send you an email but I'm not sure I had your correct address.

**Comment by MisterY** [comment]
Back on the topic:
After finding out more on how this works I'm wondering if it would be useful to map the drumset sounds automatically, when the `K perc` is used.
There is a lot of different ways to write the drumset scores, i.e.

- https://drumnotes.com/docs/berklee.pdf
- https://web.mit.edu/merolish/Public/drums.pdf
- https://drummagazine.com/drum-notation-guide/
- https://musescore.org/en/handbook/3/drum-notation
- https://www.onlinedrummer.com/drum-key/

just to mention a few. There are differences in where they place the notes for hi-hat, ride, or what symbols they use for rim clicks vs rim shots, etc. Just looking at it, I'm confused as to which notation I've been using so far. So, to make it simple, I'd go ahead with the one in MuseScore for my sheets, because all my scores are already written that way.
While technically implementing one MIDI mapping for the perc notation would be simple, the big question is which notation to use. Of course, the entered instructions would override the predefined ones.

One option would also be not to do anything in this regard and leave it to the user. This has a side-effect of having plenty of header instructions even for the simplest of examples.

I'm not sure if the ABC standard says anything in this regard but it seems unfair to leave the instrument at Grand Piano if the user has decided to use the percussion notation. :) So, having *any* standard would be of help.

Any thoughts?

**Comment by paulrosen** [comment]
%%percmap is implemented. Hopefully that allows support for the above.

**Comment by mmoya** [comment]
The original course was archived and there is a new location for the [General MIDI Percussion Key Map](https://www.cs.cmu.edu/~music/cmp/archives/cmsip/readings/GMSpecs_PercMap.htm).
