### ISSUE TITLE
Feature Request: Custom note heads for percussion 

### ISSUE THREAD

**Issue by MisterY** [paulrosen/abcjs#613]
I'd like to make a proposal in parallel to the efforts to add this to the standard.

There is a need for additional note heads when percussion notation is used. Most of all, for drumset this is the x head. The next would be the circled x head, and there are other ones, like triangles and diamonds, even squares. 
However, let's focus on one or two at the moment to see how this goes. 

The page below can be used as a reference. It contains a lot of examples and matches the other notations I've seen. 

https://www.onlinedrummer.com/drum-key/

The suggestion is to add the x and circled x note heads when rendering the `clef=perc` scores. In percussion notation there are no sharp or flat notes, so these may be used as markers. It seems that this approach is also taken by some other software in the abc ecosystem. 

- ^ would render the x note head instead of the regular note with the # sign.
- _ would render the circled x note instead of the regular note with the flat sign.

The reference page is using only the x heads in the basic notation, so even just implementing this part may be enough to cover the majority of cases. Definitely covers all my cases. 

I would like to see what the authors and the community think about this customisation.

**Comment by paulrosen** [comment]
There is a little bit of support for this as a work around. Try this:
```
!style=harmonic!g !style=x!g "<("">)"c
```
A lot of this I don't support yet.

I see a "bold x" and both the regular weight and bold x can have a circle. A regular note can have a circle, too. There is also a "Z" through a stem. And beams that converge on a single point.

I can support all the note head shapes fairly easily by extending the above like `!style=square!`.

**Comment by MisterY** [comment]
Wonderful! Thank you!
I'd say this will suffice as a workaround. So far I have used only the last two types you listed. The X is used for pretty much all the cymbals and the snare rim click, and the parentheses for ghost notes.
The rest is rarely used, really. The differences in the note heads are so small that it is hard to sightread. It might be helpful for playback but not critical. This is also the first time that I zoomed in to see the difference between the X's. 😅 I don't think that anyone would notice that on the sheet. Since these are different instruments, the bold effect on the X makes no difference. I doubt anyone would draw them different by hand. 
Most of the exotic syntax can be substituted by the text above the score lines, anyway.

I'll go ahead with this syntax and see how it goes. Currently trying to get some feedback on the Facebook group, before writing the actual proposal.

**Comment by MisterY** [comment]
One more important syntax is for the open hi-hat. Both in the syntax and the playback. It can be mapped to the MIDI note with
```
%%MIDI drummap ^g 42 %closed hi hat
%%MIDI drummap _g 46 % open hi hat
```
This results in the flat sign before the note and that kinda looks like the little circle that is normally placed above the note.
In that case it is not necessary to actually draw the circle using the text notation "^o", for example.

**Comment by MisterY** [comment]
Hm, I'm just going through the Standard 2.2 and it seems that there are some redefinable symbols.
http://abcnotation.com/wiki/abc:standard:v2.2#redefinable_symbols

Now, with a definition:
```
U: k = !style=x! 
```
it is possible to redefine any letter H-W, h-w, and the ~ symbol to be the X note.
`kg` will then be used to draw the X note head. Too bad that the range ends just before the x. 😊
Nevertheless, this works and defines a handy shortcut for rim clicks or cymbals. 

Now, the more complex case would be to draw the open-hi-hat note, which is an X head with a small circle above. Macros to the rescue. 
http://abcnotation.com/wiki/abc:standard:v2.2#macros 

`m: o = "^o"k` would, technically, draw the circle and use the redefined k to draw the X head. It seems that macros are not yet implemented? Ah, yes, it says" ignored header". 

Alternatively, this can be achieved with `"^o"k_g`. This will also draw the flat sign in front. But the playback will be correct.
The midi note needs to be redefined but on the score it is the same note.
I'm out of ideas at the moment but I quite like the flat sign, so that will do for now.

**Comment by MisterY** [comment]
I actually got sidetracked by this discovery. My original question was: is it possible to define certain notes (i.e. g) to *always* be displayed with the X head?
So, a head definition.

So far I only see macros as a potential solution.

**Comment by paulrosen** [comment]
There is a different directive that might work:
```
%%percmap ^g Closed-Hi-Hat x
%%percmap _g Open-Hi-Hat x
```
That defines the note to always be the X head.

Then all the closed hi hats are `!+!^g` and the open hi hats are `!open!_g`.

There isn't a way currently to make that simpler. Neither macros or redefinable symbols does simple text substitution.

I can work on fixing any bugs in this.

**Comment by MisterY** [comment]
That might work well. 
This percmap definition is currently not doing anything that I can see. So I believe it is to be added / completed?
I might start converting my scores already as you have solved my main issues so far. Then I will provide further feedback in case I run into new ones.

**Comment by MisterY** [comment]
I see an interesting tune "Drum Kit" in the configurator site:
https://configurator.abcjs.net/analyze

It has tons of exotic syntax and looks like it is covering the whole standard. For example
`%%map drummap ^f   print=f heads=x_head   % ride cymbal 1 `

So, perhaps there's no need to reinvent the wheel and we can focus on that syntax? Do you remember where the directives in that tune come from? What is the history of that tune? 
I'm happy to test it in detail. Probably will look into source code soon. The issue with the offset is always confusing me when listening to the percussion score. :)
