### ISSUE TITLE
Feature Request: Macro Support 

### ISSUE THREAD

**Issue by MisterY** [paulrosen/abcjs#614]
The standard lists macros defined with m, as opposed to the Redefinable Symbols, U.

So, this issue is just to track the implementation of this feature.

References:

- http://abcnotation.com/wiki/abc:standard:v2.2#macros
- http://abcnotation.com/wiki/abc:standard:v2.2#redefinable_symbols

**Comment by MisterY** [comment]
The [original comment](https://github.com/paulrosen/abcjs/issues/613#issuecomment-775424153)

**Comment by paulrosen** [comment]
The macro definition doesn't change what is written, only what is played back. And redefinable symbols just work on the symbol part. So I think what you want is a third thing, which is simple text substitution. I don't think there is a standard way to do that in ABC.

**Comment by MisterY** [comment]
Ohhh. Yes, it says right there in the first sentence. But I didn't get it at first.
No worries! It's not that I want it but would have surely been a nice thing to have. 
The current functionality is already good. I was trying to see if it was also elegant. :D
Thanks!
