### ISSUE TITLE
How can I embed abcjs into Mediawiki?

### ISSUE THREAD

**Issue by serralex** [paulrosen/abcjs#62]
I want to have the same functionality of the abcjs wordpress plugin but in Mediawiki. How could I do it?

**Comment by paulrosen** [comment]
I don't use Mediawiki, but I see by the documentation here: https://www.mediawiki.org/wiki/Manual:Developing_extensions that it isn't hard to create an extension. I think you would want to create an extension that just loads in the abc-plugin library. Or perhaps include the abc-basic library and define a "manual tag extension".

**Comment by paulrosen** [comment]
If this is still an issue, please reopen.
