### ISSUE TITLE
npm install --save abcjs fails

### ISSUE THREAD

**Issue by jymen** [paulrosen/abcjs#624]
On macosx just after pulling mail branch 6.0.0-beta.27 running
npm install --save abcjs ends up with :
npm ERR! Cannot read property 'version' of undefined

**Comment by jymen** [comment]
Here bellow the execution in verbose mode :

jymen@jymen-MacBook abcjs % npm install --verbose --save abcjs
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/15.5.1/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--save',
npm verb cli   'abcjs'
npm verb cli ]
npm info using npm@7.5.4
npm info using node@v15.5.1
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/jymen/development/abcjs/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/Users/jymen/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 9ms
npm verb npm-session 7f60ba2abb8a1ac3
npm timing npm:load Completed in 36ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 1763ms
npm timing idealTree:userRequests Completed in 3ms
npm http fetch GET 304 https://registry.npmjs.org/abcjs 412ms (from cache)
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: midi@0.4.2
npm WARN node_modules/midi
npm WARN   peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from the root project
npm timing idealTree:#root Completed in 10936ms
npm timing idealTree:buildDeps Completed in 10946ms
npm timing idealTree:fixDepFlags Completed in 7ms
npm timing idealTree Completed in 12743ms
npm timing reify:loadTrees Completed in 12744ms
npm timing reify:diffTrees Completed in 17ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm timing reify:unpack Completed in 1ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 0ms
npm timing build:deps Completed in 0ms
npm timing build Completed in 1ms
npm timing reify:build Completed in 1ms
npm timing reify:trash Completed in 1ms
npm timing command:install Completed in 12786ms
npm verb stack TypeError: Cannot read property 'version' of undefined
npm verb stack     at Arborist.[saveIdealTree] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:875:33)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:39
npm verb stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:127:5)
npm verb stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
npm verb cwd /Users/jymen/development/abcjs
npm verb Darwin 20.3.0
npm verb argv "/usr/local/Cellar/node/15.5.1/bin/node" "/usr/local/bin/npm" "install" "--verbose" "--save" "abcjs"
npm verb node v15.5.1
npm verb npm  v7.5.4
npm ERR! Cannot read property 'version' of undefined
npm verb exit 1
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 421ms
npm timing auditReport:getReport Completed in 427ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 427ms
npm timing npm Completed in 13514ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jymen/.npm/_logs/2021-02-22T22_01_22_104Z-debug.log
jymen@jymen-MacBook abcjs %

**Comment by paulrosen** [comment]
I'm not sure, "it works on my machine", but could you try:
```
npm install --verbose --save abcjs@6.0.0-beta.27
```

**Comment by jymen** [comment]
thanks it works using : npm install --verbose --save abcjs@6.0.0-beta.27
with Some warnings issues about midi  : are those warnings important ? 
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: midi@0.4.2
npm WARN node_modules/midi
npm WARN   peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from abcjs@6.0.0-beta.27
npm WARN node_modules/abcjs
npm WARN   abcjs@"6.0.0-beta.27" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: midi@0.4.2
npm WARN node_modules/midi
npm WARN   peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from the root project


jymen@jymen-MacBook abcjs % npm install --verbose --save abcjs@6.0.0-beta.27
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/15.5.1/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--save',
npm verb cli   'abcjs@6.0.0-beta.27'
npm verb cli ]
npm info using npm@7.5.4
npm info using node@v15.5.1
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/jymen/development/abcjs/.npmrc Completed in 1ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/Users/jymen/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 9ms
npm verb npm-session fddcd40a719be032
npm timing npm:load Completed in 41ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 1815ms
npm timing idealTree:userRequests Completed in 4ms
npm http fetch GET 304 https://registry.npmjs.org/abcjs 4135ms (from cache)
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: midi@0.4.2
npm WARN node_modules/midi
npm WARN   peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from abcjs@6.0.0-beta.27
npm WARN node_modules/abcjs
npm WARN   abcjs@"6.0.0-beta.27" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: midi@0.4.2
npm WARN node_modules/midi
npm WARN   peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer midi@"https://github.com/paulrosen/MIDI.js.git#abcjs" from the root project
npm timing idealTree:#root Completed in 66074ms
npm timing idealTree:node_modules/abcjs Completed in 0ms
npm timing idealTree:buildDeps Completed in 66076ms
npm timing idealTree:fixDepFlags Completed in 12ms
npm timing idealTree Completed in 67933ms
npm timing reify:loadTrees Completed in 67933ms
npm timing reify:diffTrees Completed in 33ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 1ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 3749ms
npm timing auditReport:getReport Completed in 3754ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 3755ms
npm http fetch GET 200 https://registry.npmjs.org/abcjs/-/abcjs-6.0.0-beta.27.tgz 7312ms
npm timing reifyNode:node_modules/abcjs Completed in 7322ms
npm timing reify:unpack Completed in 7322ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 1ms
npm timing build:deps Completed in 2ms
npm timing build Completed in 3ms
npm timing reify:build Completed in 3ms
npm timing reify:trash Completed in 0ms
npm timing reify:save Completed in 1119ms
npm timing reify Completed in 76520ms

added 1 package, and audited 1421 packages in 1m

74 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 76534ms
npm verb exit 0
npm timing npm Completed in 76884ms
npm info ok 
jymen@jymen-M

**Comment by paulrosen** [comment]
That is an optional peer dependency. It is only needed if you are using the deprecated audio interface. Let me know if you have any further issues.
