### ISSUE TITLE
Current provided types/index.d.ts leeds to typescript errors

### ISSUE THREAD

**Issue by jymen** [paulrosen/abcjs#625]
For typescript users the currently provided types/index.d.ts  is too minimalistic and generates warning issues with typescript tsc compiler due to unprovided return type 

I have attached my own version that I used presently here it's not covering everything and still contains too much 'any' types but at least  it covers  visio and audio for 6.0.0 beta 27 and has a better coverage than the existing one
(renamed attachment to .txt for file tranfer compliance) 

[index.d.txt](https://github.com/paulrosen/abcjs/files/6043823/index.d.txt)

 (there should not be any side effects in integrating it instead of the existing one)

**Comment by paulrosen** [comment]
Supported in beta.30 - and the types will get more exact over time.
