### ISSUE TITLE
Multi-bar pause position

### ISSUE THREAD

**Issue by MisterY** [paulrosen/abcjs#627]
The position of the multi-bar pause line should be in the centre of the bar. Ideally, the size would cover the width. 
Right now, it is left-aligned. So much so, that the meter is covered. 

![Screenshot_20210226-213843_Firefox_Beta](https://user-images.githubusercontent.com/462445/109352546-4c384a00-787b-11eb-9fa2-825071df2798.png)

**Comment by paulrosen** [comment]
Fixed in beta.28
