### ISSUE TITLE
Midi is not showing in abcjs plugin

### ISSUE THREAD

**Issue by serralex** [paulrosen/abcjs#63]
I have embedded the abcjs pluguin version to my page. Everything is working properly. However, midi is not shown. I have followed the documentation and I've added the following lines. Why is not working? Am I missing something?

`<script type="text/javascript">
  ABCJS.plugin.show_midi = true;
</script>`

**Comment by paulrosen** [comment]
Your command looks right. 

Unfortunately midi is undergoing some change -- it originally depended on Quicktime using a technique that no longer exists in today's browsers. I'm experimenting with other ways to deliver midi, but don't have anything ready for prime time yet. It should have generated a "download midi" link, though. I'll look into why that isn't happening.

**Comment by paulrosen** [comment]
show_midi is now disabled. It may return sometime in the future.
