### ISSUE TITLE
Getting precise pixel offset of a note?

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#632]
Given a note returned during a callback event, is there a way to find it's precise location on screen in pixels?

I'm trying to implement a function to auto-scroll the abcjs view to a specific note horizontally, where most of the sheet music is hidden off screen.

However, I'm using a responsive layout, as described in issue #610, so I'm finding it difficult to calculate the rendering size of the notes.

**Comment by paulrosen** [comment]
I haven't tried this, but you could get the actual element from `eventCallback(ev)` with `ev.elements[0]`. Could you use `scrollTo` with that?

I'll look into this some more...

**Comment by chrisspen** [comment]
I ended up using your suggestion from the other issue to use the note's class to lookup the element, and then get it's absolute position with getBoundingClientRect().
