### ISSUE TITLE
Gracenotes are tied to notes

### ISSUE THREAD

**Issue by idontactuallyknow** [paulrosen/abcjs#637]
Hi! I have an issue where when I try to write gracenotes (e.g. a bar like, I don't know, | de{g}e{A}e {g}edcA |) they automatically get tied to the note right after them. I'm looking for a gracenote which stands on its own and does not tie to any other note. Is there a command for that?

Thanks!
— a weekly user of abcjs

**Comment by paulrosen** [comment]
If you want the grace note to not take up any time value you can use `{A}y`. If there is an invisible note you can use `{A}x`.

**Comment by idontactuallyknow** [comment]
Hi! I don't think you quite got what I meant, I meant it as in when you type gracenotes, they get tied to the note the come before. I was wondering if I write normal gracenotes, but without the ties.

Also as another question, I was wondering how to get gracenotes to be 32nd or 16th notes instead of 8ths. Thank!

**Comment by paulrosen** [comment]
Something like this:
```
%%graceSlurs false
{A}B {A2GF/2}B
```

**Comment by idontactuallyknow** [comment]
Hi! I don't know any kind of code, is this meant to go into the code or in the text box where I would put abc, like on your site?

**Comment by paulrosen** [comment]
This is the ABC string that is passed in. Here is a more complete example:
```
X:1
T:Grace Slurs
%%graceSlurs false
K:C
{A}B {A2GF/2}B |
```

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
