### ISSUE TITLE
Another Question :)

### ISSUE THREAD

**Issue by idontactuallyknow** [paulrosen/abcjs#638]
Hi! I just tried to make a WordPress site and add in the code for abcjs but it didn't work, here's what I did.

Went to your website and to this page: https://www.abcjs.net/#which, then clicked the WordPress plugin button, which opened up a bunch of text. Then I copied and put it into a new page on the website in a code block. But now it's just showing up as the code, no abc editor. Do you know what I'm doing wrong?

P.S. You can look at the issue on the site via this link: https://abcnotation.wordpress.com/the-editor/

Thanks again!

**Comment by asjl** [comment]
You need to use this:

https://wordpress.org/plugins/abc-notation/

Install the WordPress plugin in your site when logged in as the admin.

Then you can put your ABC text in between the [abcjs][/abcjs] tags as
described in the docs for the plugin.

There's a note that this plugin hasn't been used with more recent versions
of WordPress but I'm using it with 5.7

**Comment by idontactuallyknow** [comment]
A couple questions-
Is the plugin the tune that shows up in the customizable text box for writing abc, like Cooley's for your site?

Also, don't I need a paid account on wordpress to access plugins?

Thanks 🙂

**Comment by asjl** [comment]
On Mon, 15 Mar 2021, 07:32 Person McHuman, ***@***.***> wrote:

> A couple questions-
> Is the plugin the tune that shows up in the customizable text box for
> writing abc, like Cooley's for your site?
>
The plugin is extra code added to wordpress to allow you to display music
on your site.

See https://lpnz.org/intermediate/mountain-road-2/ for an example of it in
action.

> Also, don't I need a paid account on wordpress to access plugins?
>
You need to have admin rights on the WordPress site that you want to do
this on so that you can add the abcnotation plugin. If you have that then
there's no extra cost to download plugins.


Thanks 🙂

**Comment by idontactuallyknow** [comment]
thanks @asjl for the info!
I created the site, so that means I'm the admin I think.
And on the site you linked, it looked like just an abc display that cannot be edited by anyone on the site. I'm looking for something like this: http://clivew.com/abc.php

Thanks!

**Comment by paulrosen** [comment]
You can do that in WordPress but you would need a little bit of javascript. This is an example of doing it on a simple web page: https://cdn.rawgit.com/paulrosen/abcjs/master/examples/editor.html

You'd have to create a page in WordPress that mimics that.

**Comment by asjl** [comment]
I've been tinkering with the ABC Notation plugin for my own use as I wanted
to use the playback features of ABCJS 6.0.0. There's a lot of options in
the original plugin code that I don't need or am ever likely to but I
really wanted access to the new playback options from the latest (beta)
release. I've collected my tinkerings together in this GitHub archive and
I've changed the permissions on it to public just now.

This code is work in progress and has NOT been tested in any serious way
but if anyone wants to use it feel free. I've got no plans to make this an
official WordPress plugin in the near future.

Archive is at: https://github.com/slow-session/abcjsTools and you can see
an example of the three options at https://lpnz.org/abcjs-tools/

**Comment by paulrosen** [comment]
Thanks @asjl ! Coincidentally, I was just about to update the plugin. You have some interesting ideas here - including creating an editor shortcode which would solve the OPs request.

**Comment by paulrosen** [comment]
I updated the plugin and I created an example site here: https://wp.abcjs.net/ That might help get started.
