### ISSUE TITLE
Can't run the project in vue-cli

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#639]
Hi Paul 
I started a project by `vue-cli 3.0.5` on windows.
Then I installed abcjs by this command `npm install --verbose --save abcjs@6.0.0-beta.27` 
But when I run `npm run serve` I get this error: 
`Module not found: Error: Can't resolve 'midi/inc/AudioSupports' in 'E:\project\node_modules\abcjs\src\midi'`
I am new to abcjs and I do not want to use deprecated functions. Should I install something for MIDI?
Also I need new features that you have in the newer versions.

**Comment by ehsansh** [comment]
Oh sorry. The problem was this line in my vue file
`import abcjs from "abcjs/midi";` 
I changed it to 
`import abcjs from 'abcjs';`
And the problem is solved.

**Comment by paulrosen** [comment]
Yes, that other entry point has a peer dependency.

Note that the library is up to `beta.30` now.
