### ISSUE TITLE
Angular or React Support

### ISSUE THREAD

**Issue by dlombardi** [paulrosen/abcjs#64]
Are there any methods to use the abcjs plugin in frameworks such as angular or react?

**Comment by paulrosen** [comment]
Can you point me to an example that is failing? It might be a simple fix.

**Comment by freakimkaefig** [comment]
I'm using a workaround with [script-loader](https://www.npmjs.com/package/script-loader) and [exports-loader](https://www.npmjs.com/package/exports-loader) in react with webpack:

```javascript
import ABCJS from 'exports?ABCJS!script!../../lib/abcjs/bin/abcjs_basic_2.3-min.js';
```

In your react component you can then call abcjs:
```javascript
ABCJS.renderAbc('element', abcString, parserParams, engraverParams, renderParams);
ABCJS.renderMidi('element', abcString, parserParams, midiParams, renderParams);
```

The whole component is implemented in a custom project [here](https://github.com/freakimkaefig/melodicsimilarity/blob/master/src/components/AbcViewer.js).

**Comment by dlombardi** [comment]
thanks freakimkaefig! much appreciated.

**Comment by tinuF** [comment]
@dlombardi check my repo: https://github.com/tinuF/eTuneBook2. abcjs with angular 2.

**Comment by paulrosen** [comment]
I've created an npm version. I'd love to get your feedback about whether that works for you. You can now install it with "npm install abcjs --save".

**Comment by borisrorsvort** [comment]
@paulrosen Thanks. That would also be nice if it would be available as an es6 export so that we don't have to use @freakimkaefig webpack loader trick to make it work.

Btw: if you're trying to use it with a create-react-app project, the new syntax is: 
```
import ABCJS from 'exports-loader?ABCJS!script-loader!./../node_modules/abcjs/bin/abcjs_basic_2.3-min.js';
```

**Comment by paulrosen** [comment]
Thanks Boris. I'm hoping to get a chance to carve out some time soon to get back to this.
