### ISSUE TITLE
Animation in full-synth example

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#640]
Hi,
For animation in the documentation we have `TimingCallbacks` But in the full-synth example This function does not exist. It seems that `CursorControl` function makes the animation. Which one should we use TimingCallbacks or CursorControl? 
And also in synth-only there is `prime` function but in full-synth we don't have it. Why?
Another question: How could I find total time or total number of measures of the tune  after clicking any note?

**Comment by paulrosen** [comment]
The synth code wraps up `TimingCallback`, so it is being used under the surface.

So if you are doing animation without the synth - for instance if you are making a "bouncing ball" to help people perform, then use `TimingCallbacks`. If you are using the built in synth then you can pass your `CursorControl` instance in and get the callbacks at the right time.

The total time isn't passed back in the click listener. You can find that information by saving the object that is returned from `visualObj = renderAbc(...)[0]`. If you have started audio playback you'll see the attribute `visualObj.noteTimings` which is an array. Look at the last item in that. If `noteTimings` doesn't exist, you can create it with `visualObj.setTiming()`.

**Comment by ehsansh** [comment]
Thanks a lot.
I want the music to be played from any music note that I click. 
This code: `synthControl.seek( currentTime/totalTime )`  does not work all the time. I click on a note, cursor goes one note after.
It seems percentage in `seek` works well for measures not for the music notes. How could I fix it?

**Comment by ehsansh** [comment]
I have another question I want to have synth but start from a special measure. So when I write:
`
midiBuffer.init({
	audioContext: new AudioContext(),
	visualObj: visualObj,
	options: {
	}
}).then(function (response) {
	// console.log(response);
	if (synthControl) {
		synthControl.seek( startMeasureNum/ NUM_MEASURES )
		synthControl.setTune(visualObj, userAction).then(function (response) {
			console.log("Audio successfully loaded.")
		}).catch(function (error) {
			console.warn("Audio problem:", error);
		});
	}
}).
`
Then I get this error: `Audio problem: TypeError: Cannot read property 'setProgress' of null` 
Where should I put this line of code: `synthControl.seek( startMeasureNum/ NUM_MEASURES )`  ?

**Comment by paulrosen** [comment]
The seek should happen in the `then()` of `setTune`, so one line lower than you have it.

For the first question, I think I need to supply a new entry point because the percent isn't going to be exact. I put that on my list.

**Comment by ehsansh** [comment]
Thanks Paul,
I added this line of code 
```js
synthControl.setTune(visualObj, userAction).then(function (response) {
  synthControl.seek(0.6)
  console.log("Audio successfully loaded.")
})
```
to the full-synth.html in line 253 but I got the same error: `full-synth.html:257 Audio problem: TypeError: Cannot read property 'setProgress' of null`

**Comment by ehsansh** [comment]
Thanks Paul,
I added seek where you mentioned in the full-synth.html example but I got the same error. 
Even **seek to middle** button gives the same error. This button works only after playing the tune for one time. Why? How could I solve it? Is it related to activating audio context?

**Comment by paulrosen** [comment]
Yeah, that is related to the way things are initialized. Initialization can't happen until the user clicks something. There is some error checking that has to happen - since the user clicked something to seek to middle, that can first trigger the init. 

I have some ideas to streamline the API here but no time at the moment to work on it.
