### ISSUE TITLE
The last line of the music sheet is shorter

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#647]
I don't know why this happens.
![1](https://user-images.githubusercontent.com/3332025/112372165-12812480-8cfd-11eb-9ef9-4124943c7201.png)
But it does not happen for 6/8, 2/2 , etc
![2](https://user-images.githubusercontent.com/3332025/112372199-1dd45000-8cfd-11eb-98ec-ab17d8864137.png)

**Comment by paulrosen** [comment]
If you want the last line to stretch out, use the line
```
%%stretchlast
```
The idea is that if the last line is particularly short it looks weird to stretch it. This is part of the ABC standard.

**Comment by ehsansh** [comment]
Thanks.
