### ISSUE TITLE
Duration of the notes

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#649]
Hi,
I need to find duration of the notes in one measure whenever the user clicks and want to change something in that measure.
I use `noteTimings` to find notes of that measure then with `startChar` in `noteTimings` and `getElementFromChar` function I find the duration.
I thought to calculate the duration by analyzing the abc string of each note. But it seems a little bit tricky. 
Another way is to save duration of the all notes in a separate array.
Which way is better? Is there any function I am not aware of that?
I do appreciate your suggestion in this case.

**Comment by paulrosen** [comment]
The duration of the notes are in the visualObj that is returned from renderAbc.

This is not guaranteed to work in the future but it has been pretty stable - in that object there is the element `lines`. You can drill into that to find each staff in a line, and each voice on the staff, then each element in the voice. That element contains `duration` which is the fraction of a whole note.

I hope you don't have to analyze the abc string - there are pitfalls, like `>` that changes the duration and triplets.

**Comment by ehsansh** [comment]
Wow! Thanks Paul.
