### ISSUE TITLE
Triplets number disappears when first note is a rest

### ISSUE THREAD

**Issue by jorgemeletti** [paulrosen/abcjs#65]
Hello, 
I noticed that triplets numbers sometimes disappear if the first note is a rest. The number shows correctly if the rest is not in the first note, or if you put spaces between the notes do disconnect their stems. Here's an example:

```
X: 1
T: Tuplets
M: 4/4
L: 1/4
K: C
(3:2:3 c/2B/2c/2 (3:2:3c/2z/2c/2 (3:2:3 z/2B/2c/2 (3:2:3 z/2B/2 c/2 |
(3:2:3c/4z/4c/4d/2 (3:2:3z/4B/4c/4d/2 (3:2:3z/4B/4 c/4d/2 (3:2:3z/4B/4 c/4 d/2 ||
```

Thanks so much for this incredible library!

**Comment by paulrosen** [comment]
Sorry for the delay in getting back to you. I can recreate the bug and will look at it.

**Comment by paulrosen** [comment]
This had been fixed a while ago -- but I didn't close the issue here.
