### ISSUE TITLE
Why is length in OfflineAudioContext() multiplied by 2?

### ISSUE THREAD

**Issue by jtna** [paulrosen/abcjs#651]
Hi Paul,

In placeNote(), why is the length argument passed to OfflineAC multiplied by 2 at the end?

https://github.com/paulrosen/abcjs/blob/main/src/synth/place-note.js#L17
`var offlineCtx = new OfflineAC(2,Math.floor((len+fadeTimeSec)*sampleRate*2),sampleRate);`

I thought maybe it's because there are 2 channels, but if that's the reason then it's not needed:
https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/OfflineAudioContext
"where one sample-frame is a unit that can contain a single sample of audio data for **every channel** in the audio data"

Is this a bug, or is there another reason for the *2?
For what it's worth, I measured how long the prime() takes on a particular tune, and it went from 1.80s down to .49s. I didn't hear any differences in audio either.

If it's indeed a bug, then this is HUGE for me =). I've been struggling with some tunes taking 5s or more and this should reduce the priming time to almost a quarter!

**Comment by paulrosen** [comment]
Thanks!

I did a test and it does look like it is extra - it was put in for stereo, probably I was misinterpreting the spec.

I didn't see as dramatic a change in timing as you did, but it is probably related to the complexity of the music and the amount of resources available to the browser.

This will be in 6.0.0-beta.32.

**Comment by jtna** [comment]
Confirmed fixed, thanks!
