### ISSUE TITLE
Is it possible to add numbered musical notation?

### ISSUE THREAD

**Issue by watersoft123** [paulrosen/abcjs#652]
ABCjs is great,But I want to add numbered musical notation below or above the staff, I don’t know if there is this feature or it can be added in the future.

**Comment by paulrosen** [comment]
Do you mean tablature? I would like to support it but I don't at the moment, sorry. If someone wants to help program it that would help make it happen sooner.

If you mean just numbers, like fingering, you can put that in annotations, like this: `"^1"` or `"^2\n4"` just before the note that it should appear over.

**Comment by watersoft123** [comment]
Thank you paulrosen. Yes，I mean tablature for numbered musical notation.I found a free but not open source tool：[http://zhipu.lezhi99.com/Zhipu-index.html](url)，It basically followed the ABC format.
Here is the help document：[http://doc.lezhi99.com/zhipu](url)
