### ISSUE TITLE
How About An Automatic Saving Feature?

### ISSUE THREAD

**Issue by idontactuallyknow** [paulrosen/abcjs#653]
Hello again!
I think that an auto-saving feature on the drawthedots editor would be great, as I've lost over 2 hours of work in the past few weeks to the webpage randomly deciding to reload when I am working on something. I think that thesession.org has something where it automatically saves your work, even when you refresh or click on something and go back.
Anyway, it would be a great feature! Please consider adding this 😄

**Comment by paulrosen** [comment]
I'm sorry to hear that!

Do you mean drawthedots.com? I haven't updated that app in nearly a decade, I think.

Instead, I created editor.drawthedots.com that doesn't collect any info from you but saves your work to localStorage on your computer instead. I've been thinking of taking drawthedots.com down but it looks like some people find it useful so I haven't yet.

**Comment by asjl** [comment]
I built this:

https://editabc.session.nz/

You're welcome to use this as well and feel free to plunder the source code
at:

https://github.com/slow-session/editABC/

**Comment by paulrosen** [comment]
Nice job!

**Comment by idontactuallyknow** [comment]
Hi!
To @asjl and @paulrosen, I'm don't understand if either of those builders save automatically.
If I reload the page, will the abc notes still be there? I see that there are physical save buttons on the sites, which obviously I can learn to use but I have a bad habit of only saving my tunes once I've finished.
Thanks!

**Comment by asjl** [comment]
My code doesn't autosave the ABC and I don't believe that's a good idea nor
is it allowed by the browser see. Imagine a malicious website builder that
was able to automatically write data to your machine over and over simply
because you looked at their website. Looking at Paul's code he doesn't
autosave either.

And "reloading" a webpage means start again from scratch so it's not
surprising that your data disappears.

If you want that style of working with auto save then perhaps you need to
install an editor that supports ABC editing. I sometimes use Visual Studio
Code (https://code.visualstudio.com/) which has an ABC extension you can
install for that. But that may be a sledgehammer to crack a nut.

**Comment by paulrosen** [comment]
https://editor.drawthedots.com/ saves your progress in localStorage so if you refresh the browser it is still there. That's not a good long-term storage but you won't lose your work. There is a download button for saving it on your computer.

**Comment by idontactuallyknow** [comment]
Hi @paulrosen! Unfortunately, it seems as though my computer may be doing more than a refresh when the page "crashes." What happens is when I am writing abc, the site (or my browser/computer) decides to just reload the page without any action on my part. I know my way around doing stuff on computers but don't know real code or anything fancy, would you mind letting me know what localStorage is? Is it something I can access after the tab is closed? I just lost another hour of work 😬

**Comment by paulrosen** [comment]
localStorage is used by the app. You don't need to do anything. What is the exact URL you are using? 

If your browser is actually crashing regularly, I'd look into that first. I'm pretty demanding on both Chrome and Firefox and I rarely get a crash.

In the meantime, copy your work every few minutes to a text editor.

**Comment by idontactuallyknow** [comment]
I'm typing in editor.drawthedots.com and hitting return... I'm also using safari.
The actual browser doesn't crash, just the one webpage which reloads and doesn't close. Although I'm pretty sure that's not an issue with the site...

**Comment by paulrosen** [comment]
Auto saving is now done every 20 seconds.
