### ISSUE TITLE
Long annoatation results in weird spacing between notes

### ISSUE THREAD

**Issue by foxbunny** [paulrosen/abcjs#656]
I've run into this issue where a long-ish annotation causes a strange gap in connected notes.

For example:

```
"Long anotation" C^CCC
```

![image](https://user-images.githubusercontent.com/65413/113624886-7cd08800-9660-11eb-8469-89d93b79be5b.png)

I would expect the connected notes to render as if there weren't any annotations, like so:

![image](https://user-images.githubusercontent.com/65413/113625043-ae495380-9660-11eb-92e4-c62c128baad3.png)

Is there something I can do to work around this?

**Comment by paulrosen** [comment]
Try this:
```
"^Long anotation" C^CCC
```
Notice the caret I added. Without the caret the contents of the string are interpreted as a chord so it is attached to the note it appears with. With the caret the string is interpreted as an annotation and will not affect the note spacing.

**Comment by foxbunny** [comment]
Ah ok. That does the trick. Having said that, It is actually a chord, just that it's a bit long. I'll close this for now as your suggestion solves my problem.
