### ISSUE TITLE
Annotations at the end of the bar

### ISSUE THREAD

**Issue by foxbunny** [paulrosen/abcjs#657]
I have a need to write annotations at the beginning and at the end of a bar in order to create a blank chord sheet.

I've tried something like this:

```
"Em7b5" z4 "D7" |
```

But that results in this:

![image](https://user-images.githubusercontent.com/65413/113626230-2b28fd00-9662-11eb-966d-c576d9013a9e.png)

Is this a bug or by design? Also, how would I achieve what I want (which is for D7 to appear to the right of the rest and above the stave)?

**Comment by paulrosen** [comment]
You can create an invisible rest with "x", so the exact answer is this:
```
"Em7b5" z4 "D7" | x
```
But another way to do that is with slashes:
```
X:1
M:C
L:1/4
K:C style=rhythm
"Em7b5" B0 B0 "D7"B0 B0 |
```

**Comment by foxbunny** [comment]
Thanks, that does exactly what I needed!
