### ISSUE TITLE
Firefox: CSS-hidden engraving error causes tune not to render

### ISSUE THREAD

**Issue by cls0** [paulrosen/abcjs#66]
The following code:
`ABCJS.renderAbc("score_display", "X:1\nT:Testing\nR:reel\nK:C\nC8", {}, { add_classes: true }, {});`
together with the CSS `.meta-top{ display:none; }`
works in e.g. Chrome but not Firefox, where I find a pile of errors
`Unexpected value NaN parsing y attribute.`
and the entire rest of the tune then fails to render correctly.

This original error presumably happening because the undisplayed object (the engraving of the rhythm field) does not have a well-defined y attribute for some reason. It would be handy if this could be at least caught (or just entirely fixed!) so that the rest of the tune renders correctly.

**Comment by paulrosen** [comment]
I tried that on the master branch and didn't get an error. I used Firefox 47.0.1. The code I used was:
```
<div id="score_display"></div>
<script>
	ABCJS.renderAbc("score_display", "X:1\nT:Testing\nR:reel\nK:C\nC8", {}, { add_classes: true }, {});
</script>
<style>
.meta-top{ display:none; }
</style>
```
I saw the single note with no title.

**Comment by cls0** [comment]
Sorry for not being more explicit with the code sample - you need the CSS **before** the script, so that during rendering, the relevant SVG elements are hidden. The code sample you give does work for me. (I'm using FF 47.0 on Ubuntu/W10, and the 2.3 minified release.) The bug is in

`<html>
<head>
<script src="abcjs_basic_latest-min.js"></script>
</head>
<body>
<div id="score_display"></div>
<style>
 .meta-top{ display:none; }
</style>
<script>
 ABCJS.renderAbc("score_display", "X:1\nT:Testing\nR:reel\nK:C\nC8", {}, { add_classes: true }, {});
</script>
</body>
</html>`

**Comment by paulrosen** [comment]
I fixed this in the master branch -- not sure when I'll create a new release, but hopefully soon. Thanks for reporting this.
