### ISSUE TITLE
Sound on mobile browser?

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#660]
Is there any special setup or initialization required to get the midi player to work on a mobile browser? I can't get any sound on mobile.

Sound output works fine for me on desktop browsers, but I can't get any sound on mobile Chrome, and I can't find out why. I've even setup remote debugging to get a full dev console, and I'm not seeing any console errors that would hint at a cause.

**Comment by paulrosen** [comment]
My first guess is that the AudioContext is "suspended". Usually Safari is the pickiest for that. Does this happen on the examples or on your code? If that is the problem then you need to make sure that you create the AudioContext directly in a click handler (not in the response of a Promise). You can tell if that is a problem by putting the following console.log in:
```
var ac = new AudioContext();
...
console.log(ac.state)
```
My second guess is that your device is on mute. Again, this is something I've seen on mobile Safari, not on Chrome, but there is a bug where if you mute the phone ringer it also mutes WebAudio (but not if you use `<audio>` so it isn't all websites). That requires a workaround where you have to make a sound first. So the first thing in your click handler would be:
```
var buffer = ac.createBuffer(1, 1, 22050); // 1/10th of a second of silence
var source = ac.createBufferSource();
source.buffer = buffer;
source.connect(ac.destination);
source.start();
```

**Comment by chrisspen** [comment]
Thanks. That helped me exclude a few possibilities. The problem was a bug in my UI. I was showing sound as enabled when the setting was actually still disabled.
