### ISSUE TITLE
Control spacing between chord symbols and staves

### ISSUE THREAD

**Issue by foxbunny** [paulrosen/abcjs#661]
I find that chord symbols appear very high above the staves:

![image](https://user-images.githubusercontent.com/65413/114322270-768a5200-9b1f-11eb-8b6e-a9ef80694bf5.png)

Is there a way to either decrease the distance, increase the font size, or controls this in some other way? I was also going to look for a class I could use to manually override this in CSS but I don't see any.

**Comment by ehsansh** [comment]
It is possible by CSS.
You should add `{ add_classes: true }` . You can find class names of all elements [here](https://paulrosen.github.io/abcjs/visual/classes.html#class-names).
Class name for chord symbols is `abcjs-chord`

**Comment by paulrosen** [comment]
You can increase the font size with the `%%gchordfont` directive but that won't help with the spacing. The chords are all placed evenly horizontally and they clear other things like high notes and trills. You don't show the rest of the line but there might be something that extends above the staff.

You can see how the decisions are made by adding the following to the parameters that are passed into renderAbc: `showDebug: ["grid", "box"]`

**Comment by foxbunny** [comment]
Thank you both for your answers, and sorry about the delayed response.
