### ISSUE TITLE
 change-glyphs method for decorations?

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#662]
Is it possible to use change-glyphs method for decorations? Could I replace !snap! with my svg? If yes, then how?

**Comment by paulrosen** [comment]
You can use the method `ABCJS.setGlyph('accidentals.halfflat', koron);` for any glyph. You just need the name of it. The names are in src/write/abc_glyphs.js . So, looking in that file, I see snap is `scripts.snap`.

**Comment by ehsansh** [comment]
Thanks Paul.
