### ISSUE TITLE
Wrong pause marks?

### ISSUE THREAD

**Issue by MisterY** [paulrosen/abcjs#664]
With this syntax:

```
X: 0
T: Japan
M: C
Q: 100
U: I=!style=rhythm!
K: perc
[M:2/4] z4 |[M:C] "^hh" [Fa]2 g2 z2 g2 | z2 g2 z2 g2 | F2 g2 z2 g2 | FFgF z4
```
I'm getting

![image](https://user-images.githubusercontent.com/462445/114586182-ab63e980-9c84-11eb-9cde-d642eb3c02a3.png)

in the first, and

![image](https://user-images.githubusercontent.com/462445/114586143-a3a44500-9c84-11eb-98ef-48a5b1c55f9d.png)

in the last bar. The pause marks are the same (4/4) and I can't get the 2/4 pause (z4).
Also, if I use z4 and z8 in the first bar, they both produce the same sign.
The issue goes away if I remove the `[M:2/4]` mark at the beginning.

Perhaps I'm doing something wrong?

**Comment by paulrosen** [comment]
If a rest takes up a whole measure then it uses the whole rest as the symbol, no matter what the time signature is. That is odd, I know, but that is what is mentioned in "Behind Bars".
