### ISSUE TITLE
abcjs not installing on NPM v7.X

### ISSUE THREAD

**Issue by montblanc13** [paulrosen/abcjs#666]
**Error while installing** via command 

> npm i abcjs --save

**npm error** : 
> npm ERR! Cannot read property 'version' of undefined

Used NPM version `7.10.0`

**Comment by paulrosen** [comment]
Hi, thanks for the report - you need to install the beta version, which is not installed by default:
```
npm i abcjs@6.0.0-beta.32 --save
```

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
