### ISSUE TITLE
escaped \n characters instead of newlines in javascript string variables in your abcjs basic demo

### ISSUE THREAD

**Issue by DanielJRaine** [paulrosen/abcjs#67]
I noticed in your Javascript variables cooleys, chorus, and bigNotes that instead of having newlines which is standard for ABCnotation, you instead have '\n'  
How do you parse ABCnotation strings from having newlines to \n?

**Comment by paulrosen** [comment]
The notation "\n" creates a newline when put in a javascript string literal, so it ends up being the same thing, unless I'm misunderstanding your question.
