### ISSUE TITLE
How to change the size of note symbol and the space between any two lines?

### ISSUE THREAD

**Issue by watersoft123** [paulrosen/abcjs#672]
I use ABCjs on my phone, but the note is very small,I don’t want to change the width of the sheet by zooming.I just want to increase the note size and the distance between two line,what should I do? 
Another problem, when I use "%%vocalfont" to increase the fontsize of lyrics, the right side becomes out of alignment,maybe it is a bug.
![123333](https://user-images.githubusercontent.com/57562864/116349143-f273e200-a821-11eb-9768-a06baf1c6255.png)

**Comment by paulrosen** [comment]
You can change the scale by putting the following in the ABC string:
```
%%scale 2
```
I think that is what you mean about the first question. Let me know if that isn't the effect you are looking for.

For the second question, can you post an example ABC string so I can see what you mean?

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
