### ISSUE TITLE
Is there a way to use custom notehead for every black key?

### ISSUE THREAD

**Issue by alexkh** [paulrosen/abcjs#675]
Greetings!

I'm working on a shorthand notation, where there is no sharps/flats at all. Instead of G# I want to just place a custom notehead (for now, let it be x like in drum notation).

Now, I've seen this suggestion in another thread:

%%percmap ^g Closed-Hi-Hat x
%%percmap _g Open-Hi-Hat x

That might look like a starting point, but I could not get it to work. In the following example, g# still looks like a g with a sharp sign:

%%percmap ^g Closed-Hi-Hat x
%%percmap _g Open-Hi-Hat x
X: 1
T: Cooley's
M: 4/4
L: 1/8
R: reel
K: Emin
|:D2|EB{c}BA B2 EB|~B2 AB dBA^g|FDAD BDAD|FDAD dAFD|
EBBA B2 EB|B2 AB defg|afe^c dBAF|DEFD E2:|
|:gf|eB B2 efge|eB B2 gedB|A2 FA DAFA|A2 FA defg|
eB B2 eBgB|eB B2 defg|afe^c dBAF|DEFD E2:|

![screenshot](https://user-images.githubusercontent.com/1989909/117587679-ec92d080-b140-11eb-9e1a-e30280172d62.png)

What would be the best way to approach this problem?

Also, is there a way to make sure that accidentals only apply to a single note? This principle is already used in some modern music notation (in serial/atonal music). Is there already an option in abcjs to enable this behavior?

Best regards,

-Alexandre Kharlamov

**Comment by paulrosen** [comment]
The percmap only applies to the percussion clef, so unfortunately that won't help. You can change noteheads like this:
```
U:Q=!style=x!
```
Then use that for each note, like `G QG` would print the first note with a regular head and the second with an X.

That will make it look like you want it to but the automatic synth won't be what you want. If you don't care about synth that will be all you need.

If you do care about synth you would have to either keep a separate copy of the string in standard notation for the synth or modify the synth on the way out. There is a parameter `sequenceCallback` that will allow you to modify the synth and you can change the notes there.

**Comment by alexkh** [comment]
That does the trick for now! Thanks a lot!
