### ISSUE TITLE
Finding reference note?

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#676]
Is there any kind of interface for reporting what the scientific pitch or midi number is that corresponds to a specific line in the staff?

I have an application where I'm trying to render a circle above or below the note head depending on whether the note detected from the microphone is too high or too low.

I'm rendering the circle based on the bounding box of the svg element that corresponds to the note. However, since the note exists as a svg path and has no stand-alone element for the note head, I have to estimate where the note head is (about in the bottom 1/4 of the path's bounding box), and I also have to take into account when the note is flipped when the note is above the A4 on the regular treble clef (at which point it's be in the top 1/4 of the note's bounding box).

However, depending on the clef, I can't rely on A4 being the flipping point. I need to figure out what the effective note is for that row. If the treble clef is offset, like in an octave clef, it could off by 8 notes.

**Comment by paulrosen** [comment]
The next beta will help you - I'm working to separate the parts of the note so that you can find the pieces individually. Hopefully that will be fairly soon.

That sounds like a really interesting project.

**Comment by chrisspen** [comment]
That would be perfect. If I can target just the node head as a separate element, I can get it's bounding box, and I could easily fix the problem.

Thanks. My project is https://www.notescroller.com, a free tool to help students practice playing sheet music.

**Comment by paulrosen** [comment]
Fixed in bets 35
