### ISSUE TITLE
Fast Score Render, Slow Audio Play

### ISSUE THREAD

**Issue by rpattcorner** [paulrosen/abcjs#679]
I've got a (React Native) app in prerelease test that renders ABC in a webview, per #578 .  In the last few days (just in time to scare everybody) I've noticed a significant 3-5 second delay between pressing the "Play" control and actual sound from the synth.  However the score (complete with Play button) renders instantly.

I'm finding this puzzling because my understanding is that by the time the score and play button are visible, the GET from my server page that is rendered in the RNative WebView is entirely complete.

The slowdown comes and goes.

Can @paulrosen or another knowledgeable party confirm or deny that I can rule out any kind of serverside delay in this scenario.  That is, when a score and corresponding play button is entirely rendered, can we confirm that the playing of the score takes place entirely in the local browser?

If that's the case, as I suspect, and local rendering is at fault, are there tweakable parameters that might affect speed of audio rendering?

And (as always) if anybody has found a way to incorporate abcjs directly in React Native without pulling a page in a webview, I'd love to hear about it!

**Comment by paulrosen** [comment]
There are two sources of slowness with audio: each unique note needs to be downloaded. They are cached so if you have two songs with, say, a "G" note, the second one will be faster. But creating the buffer takes a little time - there is a lot of data to process. You can do a lot of that in advance as long as the user has interacted with the page. If the user hasn't interacted with the page the browser won't allow sound processing to avoid auto-play.

**Comment by rpattcorner** [comment]
Thanks!  The mystery remains, but the problem vanished in the morning with at least one other person verifying the issue with another R-N audio (not abc) app.

A quick question that might cut to the heart of the matter -- if the score is entirely rendered (and it was), is there any further processing to be done between the moment a user clicks the <Play> button and the sound of the first note?

**Comment by paulrosen** [comment]
The visual rendering of the score is different from the creation of the audio buffer. It does the following stages:
```
// Create the object that will process the sound - this is quick.
var midiBuffer = new ABCJS.synth.CreateSynth();
// Load all the notes that will required over the internet - this will be as slow as the internet,
// but all of the notes are cached so the second tune will be faster.
midiBuffer.init({ ... }).then(function (response) {
  // Create the audio buffer and write all the notes onto it - this is not instantaneous and depends on the number of notes and length of the tune.
  midiBuffer.prime().then(function (response) {
    // Now the buffer is ready and everything is fast to start and stop the audio.

```

**Comment by rpattcorner** [comment]
Thanks!  If, as I understand it, the CreateSynth call loads over the internet and is independent from score render, that would point strongly at a temporary internet (AWS) glitch.

Also, as a thought, it might be interesting for me to look at caching the first view of the page on the mobile app and using it over and over, as this would also cache the 'notes' that were downloaded in each rendition.  Be interesting to have a preload method that preloads notes over a couple of octaves - but that's for a far future day.

Appreciate the response, closing.
