### ISSUE TITLE
Subtitles with key changes before music begins causes crash

### ISSUE THREAD

**Issue by cls0** [paulrosen/abcjs#68]
Code like
```
X:1
T:Test
K:C
T:Subtitle
K:C
CDEF GABc
```
causes the error
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at window.ABCJS.data.Tune.appendStartingElement (abcjs_basic_2.3-min.js:17:6711)
    at window.ABCJS.parse.ParseHeader.parseHeader (abcjs_basic_2.3-min.js:28:4013)
    ...
```
in the stated version (Chrome, Windows).

This seems to only happen when
1. there is both a secondary T: and a secondary K: field; *and*
2. there is no line of music until after both the T: and K: fields.

This breaks certain ABC files (I've mainly seen this kind of format in the case of multiple tunes written within a single X: tag to become a set).

**Comment by paulrosen** [comment]
Thanks for the report. I fixed that in the master branch -- I haven't rebuilt the packages yet, but plan to soon.
