### ISSUE TITLE
Question - Call to ParseHeader

### ISSUE THREAD

**Issue by rpattcorner** [paulrosen/abcjs#680]
I've got a back-end node app (AWS Lambda FWIW) that retrieves ABC and wants to return a Tune object (for which I have a class).

I'd really like to use the Parser's ParseHeader() function to return just the header fields from the ABC string so I can populate the Tune object, but it's unclear to me how I might simply invoke it with an ABC string.  Is there an example floating somewhere?  

Also, no need to process the ABC further in this particular function beyond the header parse, so would the initialization of the library impose a significant processing-based time delay?  That would matter in a lambda!

Thanks, I know that's probably not a design goal, but the abcjs parser would be much better quality than a simple one I cobble together ...

**Comment by paulrosen** [comment]
Hopefully this will help: https://cdn.rawgit.com/paulrosen/abcjs/master/examples/analysis.html

I think there isn't much of a delay. I don't know if the size of the library matters. You would be carrying the whole library and just using a little bit.

**Comment by rpattcorner** [comment]
Thanks!  Looks too good to be true!  Looks like `var tuneBook = new ABCJS.TuneBook(abc)` does it all, and the rest is just picking attributes off the object.  A great service to humanity and far better than my bare bones "iterate over the lines" parser.  I'll give it a go and close on success.

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
