### ISSUE TITLE
Question - Bars on the edges of the staves

### ISSUE THREAD

**Issue by foxbunny** [paulrosen/abcjs#681]
I'm not sure how it's called, but I have a need to add bars on the edges of the staves. Here's an example of what I mean:

![image](https://user-images.githubusercontent.com/65413/119504400-3815c300-bd6c-11eb-92fc-a65da6f8d953.png)

I've tried adding `|` at the either end of each line, but that doesn't result in what's depicted in the image (the bar appears after the clef, for example, not before it). What settings/directives can be used to achieve this?

**Comment by paulrosen** [comment]
On multi-staff music there is a bar on the left side. I did an image search for "sheet music" and looked at a number of the single-staff examples. None of them have a bar on the left side. As far as I know there isn't an ABC command for that.

You can add it yourself right after the renderAbc() call, though. Something like:
```
var svg = document.querySelector("#paper");
var staves = document.querySelectorAll(".abcjs-staff")
for (var i = 0; i < staves.length; i++) {
  var staff = staves[i];
  var box = staff.getBBox();
  var el = document.createElementNS(svgNS, "line");
  el.setAttribute("x1", box.x);
  el.setAttribute("x2", box.x);
  el.setAttribute("y1", box.y);
  el.setAttribute("y2", box.y+box.height);
  svg.insertBefore(el, svg.firstChild);
}
```
I didn't test that, but it should be fairly close.

**Comment by foxbunny** [comment]
Yeah, I'm aware it's not extremely common. FRT, I'm collaborating with a Jazz musician and a teacher on a software project, and these are mostly requests coming from them. I promise I'm not making things up. :)
