### ISSUE TITLE
Flat chord 

### ISSUE THREAD

**Issue by jbouzi** [paulrosen/abcjs#682]
Seems like there is an issue with flat chords (using version abcjs_basic v6.0.0-beta.33). Please see chord Bb in attached image and ABC notation below. The playback also interpret the chord without being flat.
```
X:1
T:Amazing Grace
C:Trad.
Q:1/4=60
M:3/4
K:F
L:1/4
V:1
C | "F"F2 (A/F/) | "F7"A2 G | "Bb"F2 D | "F"C2 C | F2 (A/F/) | 
A2 G | c3- | c z A | "F"c2 (A/F/) | "F7"A2 G | 
F2 D | C2 C | "Dm7"F2 (A/F/) | "C7"A2 G | "F"F3- | F z |]
```

<img width="1167" alt="Screenshot 2021-05-26 at 20 28 27" src="https://user-images.githubusercontent.com/40691643/119712728-311cac80-be61-11eb-880c-597c99dfc423.png">

**Comment by paulrosen** [comment]
That is odd. I'm not seeing it. What OS and browser is this? Can you see what font is being used on the chord in the devtools? Can you select that element and copy the html code here. I see this:
```
<text stroke="none" font-size="16" font-style="normal" font-family="Helvetica" font-weight="normal" text-decoration="none" class="abcjs-chord abcjs-l0 abcjs-m0 abcjs-mm0 abcjs-v0" text-anchor="middle" x="134.83" y="76.12"><tspan x="134.83">B♭</tspan></text>
```

**Comment by jbouzi** [comment]
Mac OS X 11.2.3 - Chrome Version 90.0.4430.93 (Official Build) (x86_64), and I have the same issue on iPhone with Safari.

`<text stroke="none" font-size="16" font-style="normal" font-family="Helvetica" font-weight="normal" text-decoration="none" class="" text-anchor="middle" x="551.09" y="131.81"><tspan x="551.09">Bâ™­</tspan></text>`

Maybe I've done something wrong with encoding? I'm using UTF-8

**Comment by paulrosen** [comment]
The abcjs-basic-min.js file itself doesn't have the right encoding. I'm not sure how that happened but it doesn't match https://github.com/paulrosen/abcjs/blob/main/dist/abcjs-basic-min.js Look at the first line and you will see the copyright symbol and look at the file that you have on your website.
