### ISSUE TITLE
Crescendo and Diminuendo

### ISSUE THREAD

**Issue by 8633brown** [paulrosen/abcjs#683]
The crescendo `!<(!` and `!<)!` doesn't really work at all. 
I think the volume is capping out and not allowing the calculation to actully build up.

The diminuendo `!>(!` and `!>)!` works but doesn't reset the volume after finishing.
```latex
c !>(!c c c c !>)! c c
```
```latex
c !<(!c c c c !<)! c c
```

I quickly fixed the diminuendo with
```javascript
currentVolume = [105, 95, 85, 1];
voices[voiceNumber].push({ el_type: 'beat', beats: currentVolume.slice(0) });
```
at 
https://github.com/paulrosen/abcjs/blob/dad2abbcaa69c00fcf221bf15ccd8cd64b3c4c23/src/synth/abc_midi_sequencer.js#L465

I would imagine the crescendo will need the same at 
https://github.com/paulrosen/abcjs/blob/dad2abbcaa69c00fcf221bf15ccd8cd64b3c4c23/src/synth/abc_midi_sequencer.js#L452

I'm just not sure the best way to sort the crescendo volume

**Comment by paulrosen** [comment]
It's not supposed to reset the volume - whatever the last dynamic marking will continue until the next dynamic marking.

It definitely can top out. If you start with `!p!` then start the crescendo a note later does the volume increase?

**Comment by 8633brown** [comment]
My bad thats my music reading skills showing.

Yup using `!p!` drops the initial volume allowing it to crescendo properly.

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
