### ISSUE TITLE
Note lengths within chords not rendering correctly

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#687]
The lengths of notes within chords aren't rendered correctly when the notes don't all have the same length.

For example, given this exerpt from Tarrega's Study in E Minor:

    X:1
    L:1/8
    M:3/4
    K:G
    [eE,6]BG

it should be rendered like:

![Screenshot from 2021-05-29 20-56-05](https://user-images.githubusercontent.com/116631/120088639-b6ea6300-c0c0-11eb-86a7-ee5528081530.png)

but in the most recent version of the full-synth example in abcjs, it incorrectly renders all the notes the same length, like:

![Screenshot from 2021-05-29 20-56-24](https://user-images.githubusercontent.com/116631/120088646-cff31400-c0c0-11eb-9976-e1c2d916ed14.png)

**Comment by paulrosen** [comment]
According to the standard, the duration of the first note in a chord wins: https://abcnotation.com/wiki/abc:standard:v2.2#chords_and_unisons

I know it is a little weird, but that does take care of some ambiguous cases. For instance, if the chord had an eighth note and a quarter in it you wouldn't be able to tell by looking at it which was which.

**Comment by chrisspen** [comment]
Interesting. You're right.

"All the notes within a chord should normally have the same length, but if not, the chord duration is that of the first note."

That section also suggests the solution to my example, the voice overlay. So my abc should instead be written as:

    X:1
    L:1/8
    M:3/4
    K:G
    eBG & E,6

And that renders correctly in abcjs. Thanks.
