### ISSUE TITLE
Selected note counters line property

### ISSUE THREAD

**Issue by marina-ferreira** [paulrosen/abcjs#688]
On selecting a note on the third line, the `counters` object returned from the first param `abcelem` from `clickListener` returns`line: 0`:

```js
function clickListener(abcelem, tuneNumber, classes, analysis, drag, mouseEvent) { ... }

counters: {
  line: 0
  measure: 1
  measureTotal: 1
  note: 1
  voice: 0
}
```

<img 
  width=300
  src="https://user-images.githubusercontent.com/4058722/120105738-a671d100-c130-11eb-84c4-862299a155a6.jpg"
/>

**Comment by paulrosen** [comment]
Instead of using `counters` can you use `analysis` instead? The counters are used internally during music creation and might be in an odd state.

That said, I just tried it and it looks like it is giving me the correct line numbers in the counters object. I'm not sure why we are seeing different results.

I'm going to try to enhance this page to be clearer about which properties are safe to use: https://paulrosen.github.io/abcjs/visual/click-listener.html#abcelem It is a work in progress.

**Comment by marina-ferreira** [comment]
`analysis` is actually returning the same results as `counters` above. The classes in the svg all have `abcjs-l0`.
Maybe I'm doing something wrong in the initialization. Gonna look further into this. Thanks for the response.

**Comment by paulrosen** [comment]
If you post your abc string and the command you used to draw it, I'll look into it further.

**Comment by marina-ferreira** [comment]
This is how I'm rendering it:

```js
const abcOptions = {
  render_options: {
    oneSvgPerLine: true,
    responsive: 'resize',
    add_classes: true,
    staffwidth: 500,
    paddingtop: 120,
    wrap: { minSpacing: 1.8, maxSpacing: 2.8, preferredMeasuresPerLine: 4 },
    visualTranspose: 0
  },
  synth: {
    el: '#audio',
    options: {
      program: 40,
      chordsOff: true,
      displayLoop: true,
      displayRestart: true,
      displayPlay: true,
      displayProgress: true,
      displayWarp: true,
      midiTranspose: 0
    }
  }
}

const abcString = `X: 158
T: Tune 1
C: Traditional
M:2/4
L:1/16
Q: 120
K:Bb
%%MIDI transpose 0
(3FGA|B3d cBcd|Bdfb g2f2|bagf gfdB|cdcB G2F2|!
B3d cBcd|Bdfb g2f2|bagf gfdB|cBAc B2:|!
|:f2|g3a b2ag|fbdf BdF2|c=Bcd e2A2|BABc d2f2|!
g3a b2ag|fbdf BdF2|c=Bcd e2A2|B2cA B2:|!
`
const synth = new abcjs.synth.CreateSynth()
const audioContext = window.audioContext
const synthControl = new abcjs.synth.SynthController()

synthControl.load(
  abcOptions.synth.el,
  null,
  abcOptions.synth.options
)

const display = abcjs.renderAbc('#display', abcString, {
  ...abcOptions.render_options
})

synth.init({
  audioContext: audioContext,
  visualObj: display[0],
  options: abcOptions.synth.options
})

synthControl.setTune(display[0], true, {
  audioContext: audioContext,
  ...abcOptions.synth.options
})
```

**Comment by paulrosen** [comment]
I bet it is the `oneSvgPerLine` option, but I'll try it and see.

**Comment by paulrosen** [comment]
Yes, that is the problem. If you remove that then the lines come out right.

I usually only use `oneSvgPerLine` when I'm formatting for printing - that will keep the pagination from splitting a staff.

I'll definitely fix this in the next version, but I hope that is a work around for you.

**Comment by marina-ferreira** [comment]
This does work. Thanks for the help!

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
