### ISSUE TITLE
Bars do not sync up across voices

### ISSUE THREAD

**Issue by mf93** [paulrosen/abcjs#69]
In the piano pieces I am using, the bars do not sync up across voices. For reading piano music, this is extremely important, as the musical notation doesn't make any sense otherwise. Here are a few examples to copy paste into the editor demo which highlight what I mean, and puttiing them into easyabc will render them correctly:
X:1
T:Piano Sonata in C minor (KV. 457)
C:1
%%score { ( 1 2 ) | ( 3 4 ) }
L:1/4
Q:1/4=135.00
M:3/4
I:linebreak $
K:Eb
V:1 treble stafflines=5 
V:2 treble stafflines=5 
V:3 treble 
V:4 treble 
L:1/8
V:1
"^Allegro assai (" ((!>!g!p! | %1
 g) e c- | %2
 c .=B) (!>!!tenuto!a- | %3
 !tenuto!a g f- | %4
 f .e) (!>!g- | %5
 g!<(! c' _b- | %6
 b !tenuto!a g- | %7
 g f!<)! ^f-)!>(!!>)! | %8
!>(! ^f!>)! .g!p! (!>!G- | %9
 G E C- | %10
 C .=B,) (!>!A- | %11
 A G =F- | %12
 F .=E) (!>!_d-!mf! | %13
 d c!>(! B | %14
 A G!>)! ^F | %15
 ([EG]) [CE]!p! [D=B,]) | %16
 C z!f! (f/4e/4d/4c/4 | %17
 .g) [Gg] [Gg] | %18
 [Gg]2 (f/4e/4d/4c/4 | %19
 .g) [Gg] [Gg] | %20
 [Gg]2 (f/4e/4d/4c/4) | %21
 !arpeggio![d=Ba] z z | %22
 !arpeggio!!wedge![gce] z z | %23
 z !arpeggio![f=bd] !arpeggio![fbd'] | %24
 !arpeggio![gf'd'] z z | %25
 !fermata!z3[I:staff +1] | %26
[I:staff -1](!>!e3[I:staff +1]!p! | %27
[I:staff -1] ^F3 | %28
 G3/2!>%28! A/ G%29!)! | %29
 [GE]/ x3/2 [D=B,] | %30
 x23/16!f! x25/16 | %31
V:2
 x | x3 | x3 | x3 | x3 | %5
 x3 | x3 | x3 | x3 | %9
 x3 | x3 | x3 | x3 | %13
 x3 | x3 | x3 | x3 | %17
 x3 | x3 | x3 | x3 | %21
 x3 | x3 | x3 | x3 | %25
 x3 | x3 | x3 | x3 | %29
 ([FD] .[CE] x | %30
 .C) z (f/4e/4d/4c/4) | %31
V:3
 z | ([EC]3!p! | %2
 [FD]3) | ([D=B,]3 | %4
 [GC]3) | (G3 | A2 B | %7
 c3 | %8
[K:treble] c)[K:bass](.=B z | %9
 %28[E,C,]3 | [F,D,]3%29 | %11
 %28[D,=B,,]3 | %12
 [_B,,_D,]3%29 | %13
 G,2 !tenuto!C- | C3 | %15
 G, z [G,,F,]) | %16
[K:bass] [E,C,] z z | %17
 D E F | E E E | D E F | %20
 E E E | %21
 z !wedge![F,,F,] !wedge![FF,] | %22
 z [E,E,,] !wedge![EE,] | %23
 !wedge![DD,]!ff! z z | %24
 !wedge![=B,=B,,] z z | %25
 x3 | x3 | ([EC]3 | %28
 [=F=B,D]2 [EC]) | %29
 F, G, G,, | C, z z | %31
V:4
 x2 | x6 | x6 | x6 | %4
 x6 | E4 =E2 | F4 G2 | %7
 A4 =A2 | %8
[K:treble] G4[K:bass] x2 | %9
 x6 | x6 | x6 | x6 | %13
 =E,6 | F,2 G,2 A,2 | %15
 x6 |[K:bass] x6 | %17
 (=B,G,!tenuto!CG,DG, | %18
 !tenuto!CG,!tenuto!CG,CG,) | %19
 =B,G,!tenuto!CG,!tenuto!DG, | %20
 CG,CG,CG, | x6 | x6 | %23
 x6 | x6 | x6 | x6 | %27
 x6 | x6 | x6 | x6 | %31

NEXT ONE:

X:1
T:sheet music supplied by www.theperfectscores.com
C:J. S. BACH
C:(1685 - 1750)
L:1/4
Q:1/4=135.00
M:4/4
I:linebreak $
K:G
V:1 treble stafflines=5 
L:1/8
V:2 treble stafflines=5 
V:3 bass 
V:1
"^Allegro Vivace" .[bd]2 .[gB]2 | %1
 d2[Q:1/4=142.00](ef .g2"_1" .e2) | %2
 B4 .e2"_1" .c2 | %3
 (A2 Bc (4:6:3[Bd](1:1:2d2/3"_2" %284:6:1[cA] | %4
 cBAG"^1"!mf! .b2"_2""^5" .g2"_1""^4" | %5
 %28e2!<%28! %284:6:2e"_1"[fg] .g%29"_3""^5" .e2"_2""^3" | %6
 %28%28^c2"_1" d"_3"e %285:4:4f%29"_5"d"_2"ge%29"_3" x7/40!<%29! x5/8 | %7
 fd"^4" a2"^2""_1""^5" g"^4"f"^3" e"_1""^2"f | %8
 d4 | %9
"^Allegro Vivace" .[bd]2 .[gB]2 | %10
 d2[Q:1/4=142.00] %28ef .g2"_1" .e2) | %11
 B4 .e2"_1" .c2 | %12
 (A2 Bc (4:6:3[Bd](1:1:2d2/3"_2" (4:6:1[cA] | %13
 cBAG"^1"!mf! .b2"_2""^5" .g2"_1""^4" | %14
 (e2!<(! (4:6:2e"_1"[fg] .g)"_3""^5" .e2"_2""^3" | %15
 ((^c2"_1" d"_3"e (5:4:4f)"_5"d"_2"ge)"_3" x7/40!<)! x5/8 | %16
 fd"^4" a2"^2""_1""^5" g"^4"f"^3" e"_1""^2"f | %17
 d4 | .A2 .d2 | %19
 [fd]4 x/8"_5" x11/4"_2" x9/8 | %20
V:2
 x2 | A2 B G | F2 G A | %3
 F (4:6:1z A x/ | %4
 G z d B | %5
 (^c/ x/c/4 x/d/4) e c | %6
 A4 | A d2 ^c | d2 | %9
 x2 | A2 B G | F2 G A | %12
 F (4:6:1z A x/ | %13
 G z d B | %14
 (^c/ x/c/4 x/d/4) e c | %15
 A4 | A d2 ^c | d2 | %18
 F [AF] | %19
 A2 (g/f/e/d/) | %20
V:3
 .G,!f! .G | %1
 (F (F,)"_4" .E,"_5" .E | %2
 .D"_1" .D,"_4"!p! .C,"^5""_1" .C | %3
 .D"_1" .A, .F,"_5" .D, | %4
 .G, .D, (G,,/"_5"D,/)"_2"E,/"_1"F,/"_3" | %5
 G,/A,/G,/F,/ E,/"_4""_5"D,/E,/F,/"_4" | %6
 G,/A,/B,/^C/ .D"_1" .C) | %7
 .D (F,/!fff!G,/!>(! .A,)!mf! .A,,!>)! | %8
 D,2 | .G,!f! .G | %10
 (F (F,)"_4" .E,"_5" .E | %11
 .D"_1" .D,"_4"!p! .C,"^5""_1" .C | %12
 .D"_1" .A, .F,"_5" .D, | %13
 .G, .D, (G,,/"_5"D,/)"_2"E,/"_1"F,/"_3" | %14
 G,/A,/G,/F,/ E,/"_4""_5"D,/E,/F,/"_4" | %15
 G,/A,/B,/^C/ .D"_1" .C) | %16
 .D (F,/!fff!G,/!>(! .A,)!mf! .A,,!>)! | %17
 D,2 | .D!f! .A,"_3" | %19
 (G,/F,/E,/D,/ .A,)"_2""_1" .=C | %20

**Comment by paulrosen** [comment]
I don't think the music pasted in properly. Can you edit this and put the ABC inside a preformatted area?

From what I can see, though, it looks like there are different length measures. For instance, if you look at the first line for each voice, it looks like this:

`
V:1
"^Allegro assai (" ((!>!g!p! | %1
V:2
x | x3 | x3 | x3 | x3 | %5
V:3
z | ([EC]3!p! | %2
V:4
x2 | x6 | x6 | x6 | %4
`
The first voice has an 1/8 note and a bar line, the second voice has an 1/8 note, a bar line, and a number of other measures, the third voice has an 1/8 note and a bar line, and the fourth voice has a 1/4 note, a bar line, and a number of other measures.

Each voice should have the same number of beats and bar lines to line up.

**Comment by paulrosen** [comment]
If there is still a problem with this, I'll reopen it.
