### ISSUE TITLE
Fingering overlapping with triplet number

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#690]
Given the abc:

    X:1
    M:3/4
    K:C clef=treble-8
    L:1/8
    (3!4!^f!0!B!3!A (3!4!f!0!B!3!A (3!4!f!0!B!3!A & B,6 | (3!3!^f!0!B!2!A (3!4!g!0!B!2!A (3!3!f!0!B!2!A & ^A,6|(3!0!e!0!B!0!G (3eBG (3eBG & E2 B,2 G,2|[eBGE,]5 :|]

It incorrectly renders the fingering notation on top of the triplet notation, making both difficult to read. Some note stems also render in the incorrect direction, obscuring bass notes. e.g.

![Screenshot from 2021-06-03 05-14-52](https://user-images.githubusercontent.com/116631/120620356-e683cd00-c42a-11eb-9dc3-8717726cba21.png)

Ideally, it should render more like:

![Screenshot from 2021-06-03 05-15-23](https://user-images.githubusercontent.com/116631/120620369-eb488100-c42a-11eb-9946-7fef8f64d9b8.png)

**Comment by paulrosen** [comment]
For the stem directions, you should use voices instead of overlay, so try this:
```
X:1
M:3/4
%%score (1 2)
K:C clef=treble-8
L:1/8
V:1
(3!4!^f!0!B!3!A (3!4!f!0!B!3!A (3!4!f!0!B!3!A | (3!3!^f!0!B!2!A (3!4!g!0!B!2!A (3!3!f!0!B!2!A |(3!0!e!0!B!0!G (3eBG (3eBG |[eBGE,]5 :|]
V:2
B,6 | ^A,6 | E2 B,2 G,2 | x5 :|]
```
I'll put the triplet problem on the bug list. There is a work around - not ideal but it will work. You can use annotations instead of the fingerings:
```
X:1
M:3/4
%%score (1 2)
K:C clef=treble-8
L:1/8
V:1
(3"^4"^f"^0"B"^3"A (3"^4"f"^0"B"^3"A (3"^4"f"^0"B"^3"A | (3"^3"^f"^0"B"^2"A (3"^4"g"^0"B"^2"A (3"^3"f"^0"B"^2"A |(3"^0"e"^0"B"^0"G (3eBG (3eBG |[eBGE,]5 :|]
V:2
B,6 | ^A,6 | E2 B,2 G,2 | x5 :|]
```

**Comment by chrisspen** [comment]
Thanks.

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
