### ISSUE TITLE
Global Instrument Setting

### ISSUE THREAD

**Issue by rpattcorner** [paulrosen/abcjs#694]
Thanks to #449 and @chrisfargen my little app now has a way to select a more pleasing instrument setting (accordion is great for trad tunes), but  I'm inserting `%%MIDI program 21` into the ABC of each tune.  As an aside, for some reason the more legible `I: MIDI=program ${instrument}` has no effect, but that's a minor consideration.

More to the point, I'm uncomfortable hacking the abc on the fly and would much prefer to set a global default on the synth.  However I can find no way to do so ... the whole soundFont seems settable, but not the default instrument in it, which appears to be 0, a piano.

Is there a way to set a global default instrument for an app/page?

**Comment by paulrosen** [comment]
When you call the synth object you can specify it:
```
var midiBuffer = new ABCJS.synth.CreateSynth();
midiBuffer.init({
  visualObj: visualObj,
  options: {
    program: 21
  }
})
```

**Comment by rpattcorner** [comment]
Fantastic!  Many thanks!
