### ISSUE TITLE
Replacing annotations with new symbol

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#696]
I want to add many new symbols. So change-glyphs method does not work because I need decorations, accidentals that we have in abcjs and if I replace them with something else then I could not use them.

So I tried this method:
1. I make a annotation with some word like: "^mySymbol"
2. After `abcjs.renderAbc` I find all `tspan` tags that has `mySymbol` text
3. I make a new path tag for my symbol and use `replaceWith` to replace the new symbol with my annotation.

It works but is it a good method? Is there any better way?

**Comment by paulrosen** [comment]
I've done similar things. You might need to adjust the `%%annotationfont` to make sure there is enough room. Also don't use too long a string that you substitute so that the space reserved will be approximately right.
