### ISSUE TITLE
How to make a new glyph

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#698]
Dear Paul
I am looking at abc_glyphs file but I can't understand how to convert a svg path to array of numbers. Do you use special library?
I tried [this one](https://shinao.github.io/PathToPoints/) but it didn't work.

**Comment by paulrosen** [comment]
That's complicated - the original system was created by someone else and there is a folder called `font_generator` that has some helper code. I don't really understand it myself and I plan to replace it. Whenever I have to work with that I have to do some experimenting. The first step is what will be in the next beta - it stops processing the shapes. I think after that I can replace it with something more standard.
