### ISSUE TITLE
Validating Dirty abc

### ISSUE THREAD

**Issue by rpattcorner** [paulrosen/abcjs#699]
The phone app I'm writing does a lot of `abc` importing, and there's some really funky `abc` out there.  I'm doing pre-import cleanup on specific issues as I find them, but wonder if there is an already-existing `abc` validator.  There probably isn't, and if there was it might be slow enough to be unusable in an import tune scenario, but the current [abc editor's](https://editor.drawthedots.com/) warnings suggests such a thing might exist.

Can't find it in code though?  Paul or anybody seen one?

**Comment by paulrosen** [comment]
The return from rendering the tune has a method that contains the warnings it finds, so:
```
var visualObj = ABCJS.renderAbc(...)
console.log(visualObj.warn)
```
There is also a way to just do the parsing with `Tunebook.parseOnly()`. I don't have an example of that handy but I'll create one sometime.

I don't think it will be slow unless you have a huge number of tunes - the parsing is pretty fast.

**Comment by rpattcorner** [comment]
A few experiments suggest I'm out of luck here for an old reason ... I'm validating in back end code, and there's no DOM to supply an array of elements to the output parameter to visualObj.  Tried to fake it with an empty array, but visualObj is coming up undefined:
```
        // ... we're inside a lambda now, responding to a call that retrieved a single ABC and hoping to validate
        const ABCJS = require('./scripts/abcjs-basic.js');
        var visualObj = ABCJS.renderAbc([], abc_text, {
            responsive: "resize"
        })[0];
        console.log(visualObj.warn)
```
yields
` error: Cannot read property 'warn' of undefined`

Ah well.  Let me know if you have thoughts

**Comment by paulrosen** [comment]
Try this:
```
var visualObj = ABCJS.parseOnly(abc);
console.log(visualObj.warnings)
```
I steered you wrong with the "warn" parameter. It is really "warnings". Also, if you do `parseOnly` then it doesn't do anything near the DOM.

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
