### ISSUE TITLE
Remove lyrics/chords space between staves

### ISSUE THREAD

**Issue by iacchus** [paulrosen/abcjs#70]
Is there a way of removing extra space between staves?

See for example this tunebook https://iacchus.github.io/tunebook/

In [The Blacksmith](https://iacchus.github.io/tunebook/#the-blacksmith) I can see that the spaces are there for lyrics and chords, but most of the tunes don't have lyrics/chords and removing the space would make it fit better on the screen.

**Comment by paulrosen** [comment]
Try adding the following directive:
`%%staffsep 0`
