### ISSUE TITLE
Userscript needs to be uploaded to non-defunct site(s)

### ISSUE THREAD

**Issue by djbclark** [paulrosen/abcjs#700]
The doc mentions greasemonkey script from the era userscripts.org was operational. I've been unable to find the script via google or via any of the options listed at https://www.tampermonkey.net/scripts.php by searching for "abcjs".

**Comment by paulrosen** [comment]
I haven't kept up with this and I stopped building it automatically. I am not sure how much this is supported by browsers anymore. If you try this and it works: https://github.com/paulrosen/historical-abcjs-versions/blob/main/version-5/abcjs_plugin_5.12.0.user.js then I'll fix the documentation to point to it and put it back in the build. If not, then I'll remove it from the docs.

If it *almost* works, I'll gladly accept a pull request to fix it.

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
