### ISSUE TITLE
Display full-width ledger lines even when no notes or chords are rendered

### ISSUE THREAD

**Issue by prasenjitghoshcse** [paulrosen/abcjs#701]
First of all, this project is very useful for programmers like me who are interested to work in the field of music.

I am unable to find following features after going through the documentations.

1) I need to display the empty ledger lines.

2) I need to display the ledger lines even when no notes or chords are available

Am I missing something?

**Comment by paulrosen** [comment]
There isn't a way to do this directly, but you can draw the note then hide it. For instance, if you do something like:
```
ABCJS.renderAbc("a'", { add_classes: true })
```
Then look at the rendered svg, you'll see the note and the classes associated with it. Then you can just `display: none;` for the note.

**Comment by prasenjitghoshcse** [comment]
Thank you Paul for pointing to an alternative option to achieve what was needed. Your project is great. Cheers!
