### ISSUE TITLE
Click problems

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#702]
Dear Paul
When I click on any element I have a few problems.
1. In the `analysis.name` I see `undefined` but the element color changes to red (#ff0000). Is it as expected? 
2. After click there is a black rectangle around the element. Is there any way to remove that rectangle?
3. Clicking white and whole notes is difficult. Clicking on white areas does not have any effect.

I am using this version
`"abcjs": "https://github.com/paulrosen/abcjs#39ac46cd30bc98daa0db0f0a9a65e5c9d5bdc2a8",`

**Comment by paulrosen** [comment]
The selection color is red by default. You can change it with the option `{ selectionColor: "currentColor", }` if you don't want it to be visible, or to any valid CSS color name.

The rectangle is the outline for the currently selected item and is part of the browser's accessibility functionality. If you then click the tab key you'll see the outline move to the next selectable item.

What some people do is have a global keystroke handler and if the TAB key is detected add a class to the body that the user is navigating with the keyboard and not the mouse. For instance, add `<body class="tab-detected">` and in your CSS:

```
:focus {
  outline: none;
}

body.tab-detected :focus {
  outline: webkit-focus-ring-color auto 5px;
}
```

**Comment by paulrosen** [comment]
I'll look into the clicking of whole notes.

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
