### ISSUE TITLE
Erratic playback with multiple voices

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#703]
While trying to test the abcjs synth playback of this abc:

    X:1
    L:1/4
    M:3/4
    %%score (1 2)
    K:A clef=treble-8
    V:1
    z| Z3| !1!c !2!d !1!f|!0!e3|!1!f3|
    V:2
    x3|x2|z4|z A,A,|z A,A,|
    V:1
    !0!e3|!4!a!3!g!1!f|!3!g3|!0!e3|!2!d3|
    V:2
    z A,A,|z4|z E,E,|z E,E,|z E,E,

in the most recent 6.0.0 beta release, I find it renders correctly, but the playback is delayed and the cursor jumps around erratically.

Even if I rewrite it to use voice overlays, like:

    X:1
    L:1/4
    M:3/4
    K:A clef=treble-8
    z & x3| Z3 & x2| !1!c !2!d !1!f & z4|!0!e3 & z A,A,|!1!f3 & z A,A,|
    !0!e3 & z A,A,|!4!a!3!g!1!f & z4|!3!g3 & z E,E,|!0!e3 & z E,E,|!2!d3 & z E,E,|

it also renders correctly, but the playback and cursor is still wrong.

Is this a bug or is there something wrong with my abc?

**Comment by paulrosen** [comment]
That looks like a bug. I can reproduce.

**Comment by paulrosen** [comment]
There are a couple of problems here - the voices don't have the same durations. For instance, `!1!c !2!d !1!f & z4` has three beats in one voice and 4 beats in the other. Also in this measure `Z3 & x2`, the top voice is 3 measures (9 beats) and the bottom voice is 2 beats.

However, there is still a problem with the multimeasure rests. I'll fix that in the next beta but in the meantime you can write it out as `z3 | z3| z3|`

**Comment by paulrosen** [comment]
The following plays correctly but doesn't display correctly:
```
X:1
L:1/4
M:3/4
%%score (1 2)
K:A clef=treble-8
V:1
z| Z3| !1!c !2!d !1!f|!0!e3|!1!f3|
V:2
x|X3 |z3|z A,A,|z A,A,|
```
I think that is the most correct so I'll make that display correctly.

**Comment by chrisspen** [comment]
Yeah, the inconsistent durations is intentional on my part to fix a rendering issue. I used a z4, even though it should have been a z3, because the z3 wasn't rendering correctly and was causing everything in the second voice to be offset wrong.

**Comment by chrisspen** [comment]
Does every measure need to have the same number of voices through the entire file? I would think it shouldn't, but I found that only having a single voice in the first measure broke rendering in all the other measures, so I added an extra invisible rest for the second voice in the first measure, e.g. "z & x3".

**Comment by paulrosen** [comment]
Yeah, every measure in every voice needs to have the same duration.

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
