### ISSUE TITLE
Getting note statistics?

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#704]
Is there any way to aggregate some basic statistics on the notes in an abc file? I'm trying to find a quick way to find the total number of notes and their total sum relative time. For example, if a file has 4 quarter notes and 2 half notes, the values would be 6 and 4*.25+2*.5 = 2.

I think I could probably calculate this by starting a playback with a custom event callback, and just set an insanely high tempo so it runs almost instantly, and do the aggregation in the callback, but that feels a little hacky. Is there a better way?

**Comment by paulrosen** [comment]
If you have the SVG on the page and you use `add_classes: true` when rendering it, you can query for it, something like:
```
let svg = document.getElementById("canvas")
let numWhole = svg.querySelectorAll(".abcjs-d1").length
let numHalf = svg.querySelectorAll(".abcjs-d0-5").length
let numQuarter = svg.querySelectorAll(".abcjs-d0-25").length
```
That would count tied notes as separate notes. I don't know if that is a bug for your use case.

Another way to do this. You wouldn't have to go all the way to play the tune, you can get the sequence:
```
var visualObj = abcjs.renderAbc("paper", abc, {});
var flatten = visualObj[0].setUpAudio(options);
```
Then study the `flatten` object.

**Comment by chrisspen** [comment]
When using the css method, wouldn't that not take into account repeats? If there's 50 svg elements with classes representing notes, but 10 of them are in a repeat, then the count using a query selector will be 10 notes short.

I'll checkout flatten and see if that works.

**Comment by chrisspen** [comment]
Thanks, it looks like setUpAudio() is exactly what I need.
