### ISSUE TITLE
Unable to display full width ledger lines when a single note is displayed

### ISSUE THREAD

**Issue by prasenjitghoshcse** [paulrosen/abcjs#705]
Previously I logged issue #701 and it's resolved.

Now I am trying to display a single note on the staff but in that case, I cannot find a way to display fill-width ;ledger lines.

I am pretty sure the feature should be already available but, I am unable to find that following the documents.

**Comment by paulrosen** [comment]
I don't exactly understand what you are looking for. Can you draw a picture of how you want the music to look?

**Comment by prasenjitghoshcse** [comment]
Currently while displaying the CM chord, the ledger lines width is short, it doesn't fill up the whole view width. Following is the image of what we get:
![Staff_what_is_displayed](https://user-images.githubusercontent.com/75203368/124352133-29001b80-dc1c-11eb-966e-ca0149c2895f.png)


Following is the image what we want to achieve. The ledger lines fill the whole view width:
![Staff_what_is_needed](https://user-images.githubusercontent.com/75203368/124352118-0e2da700-dc1c-11eb-96b1-78c835b298fc.png)

**Comment by paulrosen** [comment]
Add `%%stretchlast 1` near the top of your ABC string.

**Comment by prasenjitghoshcse** [comment]
Thank you for the info. It worked.
