### ISSUE TITLE
viewBox rather than fixed height/width when generating svg

### ISSUE THREAD

**Issue by vshesh** [paulrosen/abcjs#71]
Hi, 

Really love the plugin, but I was really hoping to have the resultant svg take 100% of the container width rather than have a fixed width in pixels. This would make it scale nicely with resizing the screen.

In order to make this work manually, I go into Chrome devtools and remove the width/height coordinates in the element.style, and replace it with `viewBox="0 0 width height"` as an svg attribute. Then I set width=100%. This gives a resizeable box with proper aspect ratio/coordinate system with no overflow. 

However, I noticed that there is no way to overwrite the options to give width= 100% and use a viewBox instead of a fixed height/width. Can you tell me if this is possible? Otherwise, I feel like it would be a real improvement to not force the user of the library (eg, me) to have to deal with a fixed width box... 

Thank you!

**Comment by paulrosen** [comment]
That's a good idea. 

I tried to do the same hack you did so I could see what you are talking about, but I didn't get the effect. Can you paste the resultant div and svg line here so I can see if I understood you correctly?

**Comment by vshesh** [comment]
<img width="1440" alt="screen shot 2016-11-27 at 8 11 48 pm" src="https://cloud.githubusercontent.com/assets/2929957/20656089/c43aae32-b4dd-11e6-8e30-ca3c46a7f1cf.png">
original result - you can see that the music gets cut off.

Here is the hacked version (on Chrome):
<img width="1439" alt="screen shot 2016-11-27 at 8 13 30 pm" src="https://cloud.githubusercontent.com/assets/2929957/20656119/22c9af5c-b4de-11e6-88fb-fe49315f6c17.png">
You can see that all the music is visible. 

Hope that helps.

**Comment by vshesh** [comment]
bumping this - any luck with getting the hack to work?
I would really like to use abcjs on my website, but this issue is currently stopping me from doing so.

**Comment by paulrosen** [comment]
There's something a little confusing to me -- why is there an svg inside another svg? Can you post the html, js, and css that created your example?

And what is the desired effect? Would you like the music to magnify or reduce as you make the browser window larger or smaller?

**Comment by vshesh** [comment]
oh, that's my fault. 
I think I was trying to render the musicalabc notes to a svg tag by accident. I've changed it to a div. 
That being said, musicalabc still seems to put height and width on the div tag:
<img width="1440" alt="screen shot 2016-12-10 at 7 19 12 pm" src="https://cloud.githubusercontent.com/assets/2929957/21077844/a80d5fb8-bf0d-11e6-8ad6-005367f8476d.png">

Here is the associated html and js:
```html 
<div>
  <div id="musical-abc-73f5f344-c1a1-42d1-b033-616d5a7bc099"> 
    <script key="73f5f344-c1a1-42d1-b033-616d5a7bc099">     
       ABCJS.renderAbc(document.getElementById('musical-abc-73f5f344-c1a1-42d1-b033-616d5a7bc099'), "X: 1\nT: Notes\nM:C \nL: 1/4\nK: C\nC, D, E, F,|G,A,B,C|D E F G| A B c d | e f g a| b c' d' e' | f' g' a' b'\n")
    </script>
  </div>
</div>
```

**Comment by paulrosen** [comment]
I have a workaround for you that should work right away. I want to add a parameter that will support this, but I want to think though what it should look like. There are a number of ways to scale already, and I need to do some experiments. Anyway, does the following help? It will scale larger, but not smaller.

```
<script>
    $(function() {
        function setViewBox(selector) {
            var el = $(selector);
            var height = el.height();
            var width = el.width();
            el.removeAttr("style");
            var svg = el.find("svg");
            svg[0].setAttribute("viewBox", "0 0 " + width + " " + height);
            svg.removeAttr("height");
            svg.removeAttr("width");
        }

        ABCJS.renderAbc('musical-abc-73f5f344-c1a1-42d1-b033-616d5a7bc099', "X: 1\nT: Notes\nM:C \nL: 1/4\nK: C\nC, D, E, F,|G,A,B,C|D E F G| A B c d | e f g a| b c' d' e' | f' g' a' b'|\n");
        setViewBox("#musical-abc-73f5f344-c1a1-42d1-b033-616d5a7bc099");
    });
</script>
<div>
    <div id="musical-abc-73f5f344-c1a1-42d1-b033-616d5a7bc099">
    </div>
</div>
```

If you use this, but refine it, I'd love to see what you come up with.

**Comment by vshesh** [comment]
I made a version without jquery for myself (I don't normally include jquery in my website, and I didn't want to have to add it just for this):

```js
function getStyleProp(elem, prop){
    if(window.getComputedStyle)
        return window.getComputedStyle(elem, null).getPropertyValue(prop);
    else if(elem.currentStyle) return elem.currentStyle[prop]; //IE
}

function setViewBox(selector) {
  var el = document.querySelector(selector);
  
  var height = parseFloat(getStyleProp(el, 'height'));
  var width = parseFloat(getStyleProp(el, 'width'));
  el.removeAttribute('style');
  var svg = el.firstChild;
  svg.setAttribute("viewBox", "0 0 " + width + " " + height);
  svg.removeAttribute("height");
  svg.removeAttribute("width");
}

ABCJS.renderAbc(document.getElementById('musical-abc'), "X: 1\nT: Notes\nM:C \nL: 1/4\nK: C\nC, D, E, F,|G,A,B,C|D E F G| A B c d | e f g a| b c' d' e' | f' g' a' b'|\n");
setViewBox("#musical-abc"); 
```

Check it out in this [jsbin](http://jsbin.com/girudunigu/edit?js,output)
And why doesn't it resize in both directions for you? Works fine for me!

**Comment by paulrosen** [comment]
Not sure why it doesn't scale smaller -- it might have something to do with my outer css. But no matter. Let me know if that is the final code you end up using.

**Comment by vshesh** [comment]
This solution is great for static html situations, but if included in a React/mithril component it doesn't work well, since the svg is first rendered to the vdom where the `setViewBox` function can't find it.
As such, I still can't seem to use it.
I can manually get it to work by running the function afterwards in the console though. 

The best thing for me would be if the svg were just generated the right way from the start - custom DOM mangling is not a great solution in a view-library managed app (which is most of them, these days).

**Comment by paulrosen** [comment]
I'm just trying to get you a work around so that you can keep going now and we can see if you have any further issues. I'll incorporate this in the next version.

How come you can call document.getElementById('musical-abc') in the renderAbc line, but not something similar in the line following? Should you just store that value in a variable before calling renderAbc?

As another workaround, can you put the setViewBox in a setTimeout()?

**Comment by vshesh** [comment]
Actually you're right, the issue was querySelector vs getElementById. getElementById works :)

Thank you for all your help!
Here is the final code:

```js
function getStyleProp(elem, prop){
    if(window.getComputedStyle)
        return window.getComputedStyle(elem, null).getPropertyValue(prop);
    else if(elem.currentStyle) return elem.currentStyle[prop]; //IE
}

function setViewBox(selector) {
  var el = document.querySelector(selector);
  
  var height = parseFloat(getStyleProp(el, 'height'));
  var width = parseFloat(getStyleProp(el, 'width'));
  el.removeAttribute('style');
  var svg = el.firstChild;
  svg.setAttribute("viewBox", "0 0 " + width + " " + height);
  svg.removeAttribute("height");
  svg.removeAttribute("width");
}

ABCJS.renderAbc(document.getElementById('musical-abc'), "X: 1\nT: Notes\nM:C \nL: 1/4\nK: C\nC, D, E, F,|G,A,B,C|D E F G| A B c d | e f g a| b c' d' e' | f' g' a' b'|\n");
setViewBox("musical-abc"); 
```

**Comment by paulrosen** [comment]
Cool! I'm in the process of making everything more responsive. I will definitely use this as one of the choices, so maybe the next version will have a parameter to do the above.

**Comment by vshesh** [comment]
Awesome, looking forward to it.
