### ISSUE TITLE
Lyric Position

### ISSUE THREAD

**Issue by db5050** [paulrosen/abcjs#710]
I want to show some subnote words above the notes. Like Chord notation. Is there anything I can do in the abc script for this?

**Comment by SirPL** [comment]
From ABC Standard:

> General text annotations can be added above, below or on the staff in a similar way to chord symbols. In this case, the string within double quotes is preceded by one of five symbols `^`, `_`, `<`, `>` or `@` which controls where the annotation is to be placed; above, below, to the left or right respectively of the following note, rest or bar line. Using the `@` symbol leaves the exact placing of the string to the discretion of the interpreting program. These placement specifiers distinguish annotations from chord symbols, and should prevent programs from attempting to play or transpose them. All text that follows the placement specifier is treated as a text string.

I.e. `"^my text" C D "^other text" E F | G A B c |]` places words above `C` and `E` notes.

**Comment by db5050** [comment]
This is true for text. But I need to use it with "w:". In other words, I want to show the words written under the notes above the notes. I want to change the color of these notes. Unfortunately, I could not find how to make such adjustments.

**Comment by paulrosen** [comment]
Can you post a picture of what you want?

**Comment by db5050** [comment]
I want to write lyrics above and below the notes. And I want to change the colors of these words. That's all I want to do.

![Ekran Alıntısı](https://user-images.githubusercontent.com/4678849/126057999-ade11d36-b035-447f-afb0-ce6abeb7937b.PNG)

**Comment by paulrosen** [comment]
Try this for the music:
```
X:1
L:1/4
M:4/4
%%annotationfont "arial" 12
%%vocalfont "arial" 12
K:F
"^2""^SI"B
w: MER
w:DAG
```
And after the `renderAbc` statement:
```
var els = document.querySelectorAll(".abcjs-annotation")
for (var i = 0; i < els.length; i++) {
  els[0].setAttribute("stroke", "blue")
}
```

**Comment by db5050** [comment]
Thanks. It works.
