### ISSUE TITLE
`%%MIDI drum` is not audible on the last measure if it doesn't end with a barline

### ISSUE THREAD

**Issue by p-himik** [paulrosen/abcjs#713]
Consider this abridged score:
```
X: 1
T: Cooley's
M: 4/4
L: 1/8
R: reel
K: Emin
%%MIDI drum dddd 33 33 33 33 100 30 30 30
%%MIDI drumon
|D2|EBBA B2 EB|
```
It will voice the drums (which are used as a metronome here) perfectly.
However, if you remove the last `|`, they won't be audible anymore.

**Comment by paulrosen** [comment]
It figures out the drums (and the chords) per measure. If you don't want a bar line to show, though, you can use an invisible one like this: `[|]`.

**Comment by p-himik** [comment]
Ah, I see - thanks!

Given that there's a perfectly reasonable workaround, I'm not sure if this issue is useful or not, so I'll leave closing it up to you.
