### ISSUE TITLE
Chord playback settings?

### ISSUE THREAD

**Issue by frauber84** [paulrosen/abcjs#716]
Is there any setting to change the chord (ie, "Em") playback ? If not, where is it located in the abcjs source so I can tinker with it?
Also, is there any way to override the chord playback and write something else as a "hidden voice" ?

**Comment by paulrosen** [comment]
To have a hidden voice there are a couple of options. One simple way that might or might not mess up the visual implementation is to write the voice on the same staff but then hide it with CSS - look for `abcjs-v1` or whatever the voice number is and set `.abcjs-v1 { display: none; }` That will probably change the visual spacing some, though.

The accompaniment is in https://github.com/paulrosen/abcjs/blob/main/src/synth/abc_midi_flattener.js. Look for `resolveChords`. If you do make that code more sophisticated I'd love a pull request! There are some `%%` options that I haven't supported yet that might be useful to follow.

Another way would be to pass a function in by using the parameter `sequenceCallback`. That receives an array that contains the exact audio instructions. You can modify that anyway you want and return it.

I've wanted more flexibility on the accompaniment pattern, too.

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
