### ISSUE TITLE
What's the significance of ABCJS?If you convert the ABC notation string to musicXML, you can apply it to vexFlow/OSMD with more library resources.

### ISSUE THREAD

**Issue by dongzide** [paulrosen/abcjs#719]
If you convert the ABC notation string to musicXML, you can apply it to vexFlow or OSMD with more library resources.
What's the significance of ABCJS?

Does ABCJS use VexFlow? Part of it, or all of it?After all, Abcjs focuses more on ABC notation, and there is no professional music library for online scores.

**Comment by jepcolombia** [comment]
I started with vexflow/OSMD basically to be able to animate and playback but they fail to promise to develop those features on time . Now announced coming but as a non free pluging

**Comment by samuelbradshaw** [comment]
> Thank you. If ABC notation could use JS and MusicXML each other, its application scope would be greatly expanded. No JS libraries have been found to implement it

> I started with vexflow/OSMD basically to be able to animate and playback but they fail to promise to develop those features on time . Now announced coming but as a non free pluging

ABCJS is the best library I've been able to find for rendering ABC notation. MusicXML is different from ABC, though, and is a much more complicated format. I've been using a library called Verovio for a MusicXML-based project where I needed responsive sheet music, playback, etc. and it's been working really well so far. I integrated Verovio with WebAudioFont for MIDI playback. Verovio is advertised as a solution for the MEI format, but it can convert from MusicXML to MEI on the fly. I still use ABCJS for simpler music snippets where I have an ABC string to work with.

**Comment by dongzide** [comment]
> I started with vexflow/OSMD basically to be able to animate and playback but they fail to promise to develop those features on time . Now announced coming but as a non free pluging

Thanks. After research, I have abandoned VexFlow/OSMD and started to use ABCJS as the core of the program.
