### ISSUE TITLE
Possible midi download bug

### ISSUE THREAD

**Issue by dpaniukov** [paulrosen/abcjs#720]
Dear Mr. Rosen,

First, thank you so much for such a wonderful library! 

Second, I've been looking at your editor and it may have a problem with incorrect sound synthesis and/or save to the midi file. Here is the website: https://editor.drawthedots.com/ And here is the code to reproduce:
`Q: 100
L: 1/4
K: Cmaj
.C.D.E.F.G.F.E.D.C2|]`

The music should be in staccato. The play button correctly plays it. However, when I click the download Midi button, the file I get has a legato version. The wav file is correct, though. 

I would appreciate you looking into this issue.

**Comment by paulrosen** [comment]
Yes, that sounds like a bug. I'll look into it.

**Comment by paulrosen** [comment]
Fixed in version 6.0.0-beta.35
