### ISSUE TITLE
Using abcjs in revealjs

### ISSUE THREAD

**Issue by ericwongmusic** [paulrosen/abcjs#723]
I am a church musician that currently working on a project to show missal in the TV/Projector Screen. Our team is using revealjs to produce slides presentation. We want to include music notation for simple short melody. Does anyone can suggest how can we use abcjs inside revealjs? I am not a programmer or developer, just able to follow and modify existing code to work.

**Comment by paulrosen** [comment]
I've never used revealjs but I just glanced at the docs for it. The following might work:
1) add the minimized version of abcjs to the top of your html page.
```
<script src="/wherever/you/put/this/abcjs-basic.js" type="text/javascript"></script>
```
2) add a placeholder in a slide:
```
<div id="slide-3-music"></div>
```
2) wait for a slide to load then call abcjs:
```
Reveal.on( 'slidetransitionend', event => {
    ABCJS.renderAbc("slide-3-music", "cBABccc2|");
});
```

**Comment by paulrosen** [comment]
Closed for inactivity - if there is anything else for me to look at comment and I'll reopen.
