### ISSUE TITLE
beta 34 and safari

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#724]
using abcjs beta 34 and safari 15.0 is not working together anymore, loading the notes stays at "pending" but will not go any further.
In Google Chrome it works as before

![Skärmavbild 2021-09-25 kl  08 51 17](https://user-images.githubusercontent.com/18282700/134761981-95df4235-23c9-44f9-b892-3707acaf1cd9.png)
e

**Comment by paulrosen** [comment]
I just downloaded safari 15 on one computer so I'll explore this. It seems like every version of safari breaks something. Thanks for the report.

**Comment by musikboden** [comment]
> In Safari 15 I loaded this page https://paulrosen.github.io/abcjs/examples/full-synth.html and clicked the play button and it worked with no console messages.
> 
This same page give me this "pending" as well


![Skärmavbild 2021-10-14 kl  22 34 08](https://user-images.githubusercontent.com/18282700/137391748-b16437c6-9c1b-4b0c-848a-f38417d5a391.png)

**Comment by musikboden** [comment]
Hmm, that is strange, I'm on a macbook pro with Catalina system.
I'll investigate some more, thank you for checking.

**Comment by paulrosen** [comment]
There has been a little rearrangement of the note loading code. If you are still having a problem with beta.38 let me know.
