### ISSUE TITLE
html file instead of .js

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#725]
I must not understand how git works? I was thinking I could just download the abcjs-basic.js file I wanted from the dist folder, but that one is a large html file instead of a js file and results in an error. Downloading via the zip file works though.

**Comment by samuelbradshaw** [comment]
GitHub loads JavaScript and other source files embedded in HTML. To get the direct source of a JavaScript in a format that your browser can save/download directly, click the "Raw" button in the top right (see screenshot).
<img width="1331" alt="Screen Shot 2021-10-02 at 11 57 38 AM" src="https://user-images.githubusercontent.com/7323052/135727210-079e3ad5-f606-4cf5-9bbe-fedfebb9349c.png">
