### ISSUE TITLE
Using abcjs in moodle with "generico" plugin

### ISSUE THREAD

**Issue by nmarafo** [paulrosen/abcjs#726]
It is impossible to play the audio importing the library through the usual CDNs since "abcjs_basic-min.js" or "abcjs_editor-min.js" do not include the "ABCJS.synth" method.

**Comment by paulrosen** [comment]
What CDN are you using? It must not be updated to use the latest.

**Comment by paulrosen** [comment]
I'm not sure where that came from. I didn't submit anything to it. Can you try https://cdn.jsdelivr.net/npm/abcjs@6.0.0-beta.33/dist/abcjs-basic-min.js ? That reflects the npm package.

**Comment by nmarafo** [comment]
Indeed, it works with any compiler such as codepen.io rendering, editing and playback. Therefore, the orientations that you indicated to me are correct. Thanks!! I thought that version 6.0.0-beta33 would work with the "Generic" moodle plugin. However it does not work and it does with version 3.1.1. Therefore it is not a failure of the abcjs library, but of the conversion that the moodle plugin performs. I have opened an issue in [Justin Hunt's project](https://github.com/justinhunt/moodle-filter_generico/issues/27) to see if he can offer any solutions.
