### ISSUE TITLE
soundFontVolumeMultiplier cannot be set to 0

### ISSUE THREAD

**Issue by foxbunny** [paulrosen/abcjs#729]
In the synth options, the `soundFontVolumeMultiplier` is only [tested for truthiness](https://github.com/paulrosen/abcjs/blob/main/src/synth/create-synth.js#L46), which means that a value of 0 cannot be used at all. I think the test should either be `if (params.soundFontVolumeMultiplier != null)` or `if (typeof params.soundFontVolumeMultiplier === 'number')`.

EIDT: I did not mention the use case. I'm using the feature to trigger the animation only without the sound, and could not find a better place to mute the audio.

**Comment by paulrosen** [comment]
Will be fixed in version 6.0.0-beta.36

**Comment by foxbunny** [comment]
Thanks, all of your suggested options are great! :)
