### ISSUE TITLE
Adding left handing fingering numbers to notes?

### ISSUE THREAD

**Issue by chrisspen** [paulrosen/abcjs#739]
Is there any way to add left hand fingering numbers for guitar music, where the number is right next to the note?

![An Example](https://user-images.githubusercontent.com/116631/144168940-8ecde131-7af3-4b7b-90c0-73e7965f1597.png)

**Comment by paulrosen** [comment]
You can add an annotation in an absolute place with `"@-10,-16 3"` for instance.

That is:
```
"@-10,-16 0"G "@-10,-16 1"A
```
The first number is the x position, the second number is the y position. Notice there needs to be a space or the fingering number will be part of the positioning.

**Comment by chrisspen** [comment]
Interesting. I'm guessing that syntax is specific to Abcjs? If I convert my abc to musicxml and view it in Musescore, it renders the raw positioning numbers:

![Screenshot from 2021-12-03 22-24-20](https://user-images.githubusercontent.com/116631/144695226-38a1b6c3-8fbf-42d0-b508-e4eb267b4ee4.png)

**Comment by paulrosen** [comment]
It is part of the abc standard but that doesn't mean it is recognized in musicxml. There is also the syntax `"<1"` which might be clearer and might be supported by musicxml.

Here is the section in the standard: https://abcnotation.com/wiki/abc:standard:v2.2#annotations

**Comment by chrisspen** [comment]
Perfect, thanks. That accomplishes nearly the same thing, but seems to have wider support.
