### ISSUE TITLE
ABCJS.startAnimation doesn't follow "Repeat sign" rule

### ISSUE THREAD

**Issue by lin11220206** [paulrosen/abcjs#74]
According to the issue,
I find that when call startAnimation, the movement doesn't follow 'Repeat sign' rule.

**Comment by paulrosen** [comment]
Thanks for the report. You're right, It should. The particular use case this was developed for did not have repeats and I just didn't think about it. I will look at this soon -- but I can't give you a time frame, sorry.

**Comment by groovy9** [comment]
Here's another vote for fixing this.  The animate works great aside from repeats.

**Comment by paulrosen** [comment]
Will be fixed in version 4.0.1
