### ISSUE TITLE
Cannot read properties of undefined (reading 'CreateSynth')

### ISSUE THREAD

**Issue by Paquinho1** [paulrosen/abcjs#740]
Hello, i'm trying to play some basic chord progression using the provided synthetizer example, but I keep getting this error "Cannot read properties of undefined (reading 'CreateSynth')"

I even copied the basic example on the page without success. 

Maybe the CreateSynth() method is outdated or I'm missing something?

Thanks in advance

![image](https://user-images.githubusercontent.com/18297657/144317812-b43249cb-a981-4b05-b0bf-a7757dc055ad.png)

**Comment by paulrosen** [comment]
Yes, that is a really old version of the library. Try this: https://cdn.jsdelivr.net/npm/abcjs@6.0.0-beta.35/dist/abcjs-basic-min.js

**Comment by Paquinho1** [comment]
Thanks for your answer, now apparently it's working but I get no sound because the online library provided it's down on the net. I tried with my own piano soundfont but it doesnt work.

**Comment by paulrosen** [comment]
Was that because of the AWS outage? Because it works for me now. For your own soundfont, it needs to be in the same format that the default one is.

**Comment by paulrosen** [comment]
Let me know if this is still a problem
