### ISSUE TITLE
render to a string instead of a DOM element?

### ISSUE THREAD

**Issue by benlieb** [paulrosen/abcjs#742]
Hi Paul,

Is it possible to render to a string instead of a DOM element?

Or said, another way, how do I get a string representation of what would be rendered?

**Comment by paulrosen** [comment]
The problem is text - when I'm laying out everything I need to know how big the text is to leave room. The only way I could figure that out was to put it in an SVG and ask it how big it is.

Other than that, the process gets to the very end before it touches SVG. It is an array of things to do.

But you are asking about rendering to a string instead of SVG - I'm not sure but I'll research. 

One thing I can do is create a scratch SVG for trying out text. That still requires a real element. I don't know if that is possible. It would be able to be done on server side.

I think I could probably replace the file `svg.js` with one that constructs the markup directly. That still doesn't solve the text problem. Is that useful if we still don't know how big the text is?

**Comment by paulrosen** [comment]
Another thing is that text is affected by css so I don't assume anything - I put the text in the svg with the classes to be sure that's what it will look like.

**Comment by benlieb** [comment]
Thanks for getting back. I just want to clarify to make sure it's clear what I'm asking. By "string" I meant a string representation of the markup, which sounds like it's just svg. 

I haven't actually loaded this library to see how it is on the user side. I guess I somehow thought it would be responsive in a browser, responding to width changes etc. 

I personally was wanting to use it in a react context where there may be multiple renders in different keys. Also the UI colors and layout is malleable in my app and it sounds like maybe the only way to use this is the re-render to a dom element every time react renders a specific component?

I think my suppositions just might have been off.

**Comment by paulrosen** [comment]
Just to be sure, when you say string you mean you'd like an interface like:
```
const output = abcjs.renderAbc("X:1\n...");
console.log(output) // "<svg xmlns:xlink="http://www.w3.org/1999/xlink">...</svg>"
```
Then you would be putting it on the page yourself?

It can be responsive in a browser. Here's a simple demo: https://paulrosen.github.io/abcjs/examples/responsive.html Also: https://paulrosen.github.io/abcjs/examples/zoom-to-fit.html

There are some choices for layout built into abc, like the staffwidth and the scaling and the line breaks. I know you were looking for bar lines to line up. I've got that on my list but haven't done that yet. If there is anything else let me know.

For colors, there are a number of classes on different types of elements so you can do whatever css can do. This shows some of that: https://paulrosen.github.io/abcjs/examples/animation.html

You do have to render after the container element is put on the page. That is really fast especially for the typical 32-bar tunes that it looks like you're doing. Even 10 years ago I never saw performance problems until you start rendering Bach.

If you go to https://editor.drawthedots.com/ and click the hamburger icon over the textarea you'll see "Visual Transpose" at the bottom. Try changing that number and look at the music. I think it redraws pretty fast. That is a Vue app.

**Comment by benlieb** [comment]
If I have to render after the container is on the page, then there's no benefit for me to have the rendered string. I'll have to do what the other gentleman is doing and use a side-effect outside of the React standard rendering flow. 

It seems it can be responsive in the way I expect, too, and allow for css styling. Looking forward to implementing this!

**Comment by paulrosen** [comment]
I guess this is resolved. If there is more to do, let me know and I'll reopen.
