### ISSUE TITLE
Meter always 4/4

### ISSUE THREAD

**Issue by russc** [paulrosen/abcjs#75]
I'm using Using abcjs basic with ABCJS.render() inside a react component.  Everything is working fine except for the Meter is always rendering to 4/4 even when I put M: none.

**Comment by paulrosen** [comment]
Can you post a sample ABC string?

**Comment by russc** [comment]
This renders in 4/4...
```
X:
L:1/4
M:3/4
K: C clef=treble
|C D E|
```
![screen shot 2017-02-10 at 3 09 43 pm](https://cloud.githubusercontent.com/assets/738104/22844277/11d23f02-efa3-11e6-8040-ccfbc09ba07d.png)

**Comment by paulrosen** [comment]
That is very strange. I'm not seeing that. What version of the library are you using? And I've got a React app that uses abcjs, too. Can you post the line where you load the library and also the line where you call ABCJS?

**Comment by russc** [comment]
I'm using react-async-script-loader
```
export default scriptLoader(
  [
    'https://abcjs.net/abcjs_basic_2.3-min.js',

  ],
)(Note);
```

Once the component mounts successfully, I run this render function...
```
renderNote() {
    this.note = `X:1
               L:1/4
               M:none
               K: C clef= ${this.props.clef}
               ${this.props.abc}`;

    ABCJS.renderAbc(this.props.cell, this.note, {}, {
        scale: this.props.scale,
      });
     document.getElementById(this.props.cell).style.width = this.props.width;
  }
```
This is my Note component.
```
<Note cell="testNote" abc="|[K:Eb]|" clef="perc stafflines=0"   width="250px"  scale={1} />
```
Everything renders as expected except for the meter...
![screen shot 2017-02-10 at 10 34 35 pm](https://cloud.githubusercontent.com/assets/738104/22851240/3218adb2-efe1-11e6-850b-4d6d9e461e9b.png)

**Comment by paulrosen** [comment]
Well, first, you shouldn't be getting the library from abcjs.net. That is not guaranteed to remain there - in fact, as soon as I get around to another release, I'll go back and change the file name. You should take the code from here: https://raw.github.com/paulrosen/abcjs/master/bin/abcjs_basic_3.0-min.js and serve it locally from your server.

That's also a newer version.

It looks like there are spaces before the M: command. In ABC, "M:" must be the first and second characters on a line to be recognized. Try hardcoding the following instead of passing this.note:

```
"X:1\nL:1/4\nM:none\nK:Eb\nEFG\n"
```
If that works, then it is a formatting issue with your string. If that doesn't work, try the following and let me know what the results are:
```
var abcParser = new ABCJS.parse.Parse();
abcParser.parse(this.note, {});
var warnings = abcParser.getWarnings();
console.log(warnings);
```

**Comment by russc** [comment]
Thank you!   I did as you suggested with the hardcoding, and it worked.  I then went back and adjusted this.note accordingly and all is working with the abcjs.net 2.3 version.
```
this.note = `X:1\nL:1/4\nM:none\nK: C clef= ${this.props.clef}\n${this.props.abc}`;
```

Unfortunately, I have issues when I try to load the newer 3.0 file locally.  I downloaded it and served it locally, but ended up with this error:

![screen shot 2017-02-11 at 10 23 48 am](https://cloud.githubusercontent.com/assets/738104/22855318/3f73619c-f044-11e6-9673-10f89e57c567.png)

**Comment by russc** [comment]
All issues have been solved.  The abcjs issue was as @paulrosen noticed with the spaces.  The script loading issue was not related to abcjs, rather it was due to my misunderstanding of how Meteor loads local js files.  [I did this and solved the problem right away.](https://forums.meteor.com/t/loading-external-javascript-libraries-solved/9933)
