### ISSUE TITLE
One line take all width space

### ISSUE THREAD

**Issue by airdev-web** [paulrosen/abcjs#754]
Hello there!

I have some notes that only takes one line. But there is always kind of second line that is empty..
How can my single line takes only one row and take all the available width ?

![image](https://user-images.githubusercontent.com/85546423/150162384-0ee0d994-da7b-4d1b-8e7f-9d7b8b6f0ed7.png)

Thanks!

**Comment by paulrosen** [comment]
What is the ABC string you input? I'm guessing that the last line of your ABC string is not empty.

**Comment by paulrosen** [comment]
I guess you figured this out so I'm closing it. If you have any other problems let me know.
