### ISSUE TITLE
First chord doesn't play together

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#755]
A small thing, but if you go to this page and play the hymn, the first chord, the first time played, is disconnected.
https://gospelriver.com/believershymnbook/?hymnal=101&hymn=400
I'm guessing it may have something to do with the fact that I'm using 4 voices,  %%score (S A) (T B) ?

**Comment by paulrosen** [comment]
That is really curious. If you replay it there is no arpeggio. I don't think it has to do with the number of voices. I looked at the network activity and all the notes have been loaded before play is hit.

I haven't the slightest idea on this one. Can you post the ABC string that you used into https://editor.drawthedots.com/ and see if it happens there?

My first hypothesis is that it has to do with when you are loading everything. You shouldn't do anything with sound until a user clicks something on your page. You'll notice all the `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu` messages. What I've done sometimes is put up a splash screen welcoming the user with a "start" button. Then in the start button handler I get the audiocontext and pass it to abcjs.

It was flakier on Firefox so maybe that is a clue. 

I was thinking perhaps you weren't waiting for the audio to be set up before playing, but looking at your code I see `then` in the right places so I think that is ok.

**Comment by nbruley** [comment]
Um, what are we doing wrong in the ABC? It displays the notation but does not play for me.  It shows now ABC errors but there is a browser error "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'w')" along with the audio context stuff (which never seemed to make any difference).

```
%%abc-charset utf-8

X:1
T:Tranquility
T:8.7.8.5 D w/Refrain
C:James Mountain, 1876
L:1/8
Q:1/4=100
M:4/4
K:G
%%score (S A) (T B)
V:S clef=treble middle=B stem=up
V:A clef=treble middle=B stem=down
V:T clef=bass,, stem=up
V:B clef=bass,, stem=down
[V:S]D2>D2 E2 D2 | E2 F2 F2 G2 || 
D2>D2 E2 D2 | F2 G2 A4 || 
B2>A2 c2 B2 | A2 G2 G2 E2 || 
D2 G2 G2 F2 | G8 ||
A2>A2 ^G2 A2 | B2 A2 A2 G2 || 
F2>F2 E2 c2 | B2 A2 G2 F2 || 
F2>F2 G2 A2 | B2 c2 d2 B2 || 
D2 G2 G2 F2 | G8 || 
"[Refrain]"D2>D2 E2 D2 | E2 F2 F2 G2 || 
D2>D2 E2 D2 | F2 G2 A4 || 
B2>A2 c2 B2 | A2 G2 G2 E2 || 
D2 G2 G2 F2 | G8|]
[V:A]B,2>B,2 C2 B,2 | C2 C2 D2 D2 || 
D2>D2 C2 D2 | C2 B,2 D4 || 
D2>D2 G2 G2 | F2 G2 E2 C2 || 
D2 B,2 D2 D2 | D8 ||
F2>F2 =F2 ^F2 | F2 F2 D2 D2 || 
^D2>D2 E2 E2 | E2 E2 D2 F2 || 
D2>D2 D2 D2 | D2 D2 D2 D2 || 
B,2 D2 C2 D2 | D8 || 
B,2>B,2 C2 B,2 | C2 C2 D2 D2 || 
D2>D2 C2 D2 | C2 B,2 D4 || 
D2>D2 G2 G2 | F2 G2 E2 C2 || 
D2 B,2 D2 D2 | D8|]
[V:T]G,2>G,2 G,2 G,2 | G,2 A,2 A,2 B,2||
G,2>G,2 G,2 G,2 | D,2 D,2 F,4 ||
G,2>A,2 G,2 D2 | C2 B,2 C2 G,2 ||
G,2 G,2 B,2 A,2 | B,8 ||
C2>C2 B,2 C2 | D2 C2 C2 B,2 ||
A,2>A,2 G,2 A,2 | ^G,2 A,2 B,2 A,2 ||
A,2>A,2 G,2 F,2 | G,2 F,2 G,2 G,2 ||
G,2 B,2 A,2 C2 | B,8 ||
G,2>G,2 G,2 G,2 | G,2 A,2 A,2 B,2||
G,2>G,2 G,2 G,2 | D,2 D,2 F,4 ||
G,2>A,2 G,2 D2 | C2 B,2 C2 G,2 ||
G,2 G,2 B,2 A,2 | B,8|]
[V:B]G,,2>G,,2 G,,2 G,,2 | C,2 A,,2 D,2 G,2||
B,,2>B,,2 C,2 B,,2 | A,,2 G,,2 D,4 ||
G,2>F,2 E,2 D,2 | ^D,2 E,2 C,2 C,2 ||
B,,2 G,,2 D,2 D,2 | [G,8G,,8] ||
D,2>D,2 D,2 D,2 | D,2 D,2 G,2 G,2 ||
B,,2>B,,2 C,2 A,,2 | B,,2 C,2 D,2 A,2 ||
C,2>C,2 B,,2 A,,2 | G,,2 A,,2 B,,2 G,,2 ||
D,2 D,2 D,2 D,2 | G,8 ||
G,,2>G,,2 G,,2 G,,2 | C,2 A,,2 D,2 G,2||
B,,2>B,,2 C,2 B,,2 | A,,2 G,,2 D,4 ||
G,2>F,2 E,2 D,2 | ^D,2 E,2 C,2 C,2 ||
B,,2 G,,2 D,2 D,2 | [G,8G,,8] |]


```

**Comment by paulrosen** [comment]
That's a bug. It will work if you remove the subtitle - `T:8.7.8.5 D w/Refrain`. I'll fix that soon.

**Comment by paulrosen** [comment]
And, I'm curious if you've ever used the pan feature. I see `// pan: [ -0.5, 0.5 ]` commented out which is probably from the example. If you add a little separation between voices does it help? Does it keep the soprano from getting overpowered? For instance, try something like `pan: [ -0.3, -0.1, 0.1, 0.3 ]`

And second, where did you get the Fluid soundfont? I recently updated the one in my repo to match the improvements that had been made upstream so if you got them from https://github.com/paulrosen/midi-js-soundfonts please update and let me know.

**Comment by nbruley** [comment]
Re bug, Thank you. It seems to work fine on editor site for me, so maybe it's something with my code.
Interesting/cool about pan, I didn't know anything about the pan feature... I tried adding it and it doesn't seem to do anything. Maybe I have implemented it wrong.

```
return createSynth.init({
	visualObj: visualObj,
	audioContext: audioContext,
	options: {
		chordsOff: true,
		soundFontUrl: "soundfont/FluidR3-GM/",
		soundFontVolumeMultiplier: .8,
		program: musicProgramNumber,
		midiTranspose: transposeAmount,
		millisecondsPerMeasure: visualObj.millisecondsPerMeasure(),
		pan: [ -0.3, -0.1, 0.1, 0.3 ]
	}
}).then(function (response) {

```

I wondered about changing the fluid soundfont... I updated the acoustic piano mp3 files to the latest version.

I have updated [the link ](https://gospelriver.com/believershymnbook/) to my latest code with the changes above.  The player is now under the function playABC and just a button.  The other player stuff is just commented out for now.

**Comment by paulrosen** [comment]
I fixed something in the area but I'm not sure if it is your bug. Would you try the new version? And can you use the non-minified version for the moment so I can debug if there is still a problem? https://github.com/paulrosen/abcjs/blob/v6.0.0-beta.37/dist/abcjs-basic.js

I also couldn't try the hymn that failed because it looks like you removed the subtitle.

For panning, I stepped through and see the variable getting used. I wonder if the effect is just too subtle at those numbers. Just as an experiment, try `[ -1.0, 1.0, 1.0, 1.0 ]` that should push the soprano all the way to the left and everything else all the way to the right. If that doesn't work then I'll debug that, too.

**Comment by nbruley** [comment]
I'm not sure those changes did anything yet... I posted the test file here:
https://gospelriver.com/believershymnbook/test.html?hymnal=101&hymn=253
Yes the subtitle was being removed but I commented out that line so you can see it in the test file.

**Comment by paulrosen** [comment]
I went to that page and don't see any errors. I can hear it in Chrome, Firefox, and Safari on MacBookPro. What browser and device are you using?

**Comment by nbruley** [comment]
Sorry, I think the Title bug must be fixed; the notation shows correctly.
You're saying you hear the pan effect? Is it supposed to move the soprano to the left ear only? 
I do still hear a broken chord when it starts out...

**Comment by paulrosen** [comment]
I see the bug in the pan, I think - a work around until the next release is to add an extra item to the array: `[-1.0, 1.0, 1.0, 1.0, 0]`

The broken chord thing I haven't tracked down.

**Comment by nbruley** [comment]
That did definitely fix the pan issue. I added [ -0.3, -0.1, 0.1, 0.3, 0 ] to test.html. Not sure I notice much of a difference, unfortunately...

I also tried removing the soundFontUrl option to pull from your soundfont and that didn't seem to make any difference either.

Here's my current code:
```
if (ABCJS.synth.supportsAudio()) {
	audioContext.resume().then(function () {  // In theory the AC shouldn't start suspended because it is being initialized in a click handler, but iOS seems to anyway.
		// createSynth.init preloads and caches all the notes needed. There may be significant network traffic here.
		return createSynth.init({
			visualObj: visualObj,
			audioContext: audioContext,
			options: {
				chordsOff: true,
				soundFontUrl: "soundfont/FluidR3-GM/",
				soundFontVolumeMultiplier: .8,
				midiTranspose: transposeAmount,
				millisecondsPerMeasure: visualObj.millisecondsPerMeasure(),
				pan: [ -0.3, -0.1, 0.1, 0.3, 0 ],
				program: musicProgramNumber, //https://soundprogramming.net/file-formats/general-midi-instrument-list/ subtract 1  | https://github.com/paulrosen/midi-js-soundfonts/tree/gh-pages/FluidR3_GM
			}
		}).then(function (response) {
			// console.log(response); // this contains the list of notes that were loaded.
			// createSynth.prime actually builds the output buffer.
			return createSynth.prime();
		}).then(function () {
			// At this point, everything slow has happened. createSynth.start will return very quickly and will start playing very quickly without lag.
			createSynth.start();
			timer.start();
			return Promise.resolve();
		}).catch(function (error) {
			if (error.status === "NotSupported") {
				alertOK(translate("Audio not supported","text"),translate("OK","text"));
			} else
				console.warn("synth error", error);
		});
	});
} else {
	alertOK(translate("Audio not supported","text"),translate("OK","text"));
};
```

**Comment by paulrosen** [comment]
Please check the new release - I think the arpeggiated first chord problem is fixed.

For the pan, I suggested it to see if it helped in the case where the soprano is an octave or two above the other voices - that was the case where the soprano got lost in the overtones. If it doesn't help, then oh, well.

I think all the issues in the bug report are fixed. Let me know if I missed something.

**Comment by nbruley** [comment]
Wonderful! we're not hearing the same issues now.
