### ISSUE TITLE
Is it possible to increase the singing function?

### ISSUE THREAD

**Issue by watersoft123** [paulrosen/abcjs#756]
For various reasons, I haven't been here for a long time.Recently discovered a singing voice synthesis system that can convert notes and lyrics into sing voice,whether abcjs adds such a function? I think it is very interesting.
Home:  http://www.sinsy.jp/
Open c++ source:  http://sinsy.sourceforge.net/
Open js source:  https://github.com/oov/emsinsy/tree/gh-pages

**Comment by paulrosen** [comment]
That is amazing! As far as incorporating it, I think it is server-based and abcjs is completely client-based. It is also written in c++ instead of javascript. 

A server could be set up that contains synsy and an abc to musicxml converter and outputs the synth but I don't think it can be done in someone's browser.

Thanks for finding this!

**Comment by watersoft123** [comment]
> That is amazing! As far as incorporating it, I think it is server-based and abcjs is completely client-based. It is also written in c++ instead of javascript.
> 
> A server could be set up that contains synsy and an abc to musicxml converter and outputs the synth but I don't think it can be done in someone's browser.
> 
> Thanks for finding this!

Thanks
It's just my personal idea, it's difficult for me to implement.
Now I have another question, I have pictures of about 1200 hymns in Chinese notation.last year I used sinriscoredrawer.js 
 [https://github.com/sinri/SinriScoreDrawer](url) to encode them, reducing the size of the hymn database by 90%,and greatly improving the display effect. Next, I am going to use ABCjs to encode them.This is a tough job. In order to speed up the progress, I first use PhotoScore to convert the score image to midi format, and then use midi2ABC to export the ABC format, but the content of the original image is very different after loading with ABCjs.I don't know if there is a good way to perfectly convert the sheet music image to ABCjs format?

**Comment by paulrosen** [comment]
That's a hard problem to go from midi to written notation. Can PhotoScore output other formats? If it can output musicXML there is also a tool for converting that to abc. But the output won't be pixel-perfect in any case. ABC doesn't contain enough information to exactly typeset. You should be able to get the same information displayed, though, even if it looks a little different. I can't read the Sinri page so I'm not sure exactly what the output looks like, but it might be that you could write your own utility to convert that to ABC - depending on how many different elements are present in your music it might not be too overwhelming.

**Comment by watersoft123** [comment]
PhotoScore can output musicXML format, but it is not perfect after opening in musicxml, and requires a lot of manual changes.My music sheet has four-part harmony,I want to be able to play each part individually，can do %%staves (T1 T2) (B1 B2) with abcjs，but the musicxml generated by PhotoScore doesn't seem to meet my requirements.So I'm going to take the time to manually convert the notes to abc format one by one.It took me a year to complete the conversion of Numbered musical notation,it may take more time to convert staves to abc format, until I find the perfect tool, it seems that I can only do this.

Sinriscoredrawer is a js lib like abcjs: [SinriScoreDrawer-master.zip](https://github.com/paulrosen/abcjs/files/7967937/SinriScoreDrawer-master.zip)

1. Hymn in original image format：
![Orgin](https://user-images.githubusercontent.com/57562864/151735302-2d6cbcc2-4676-45c6-a8fa-a999f9135132.jpg)

2. Coding with Sinriscoredrawer format：
![Encode](https://user-images.githubusercontent.com/57562864/151735330-bab4808c-ccf3-4b5b-b2ca-4e570cdc0660.jpg)

3. Rendering with Sinriscoredrawer：
![render](https://user-images.githubusercontent.com/57562864/151735431-4773f808-4424-41b3-a628-32d6815f6653.jpg)

**Comment by paulrosen** [comment]
This is cool stuff, but I don't have time to do anything with it at the moment. If someone wants to do a pull request let me know.
