### ISSUE TITLE
Tablature added , no sound

### ISSUE THREAD

**Issue by user51501** [paulrosen/abcjs#757]
Based on your code in help files I was able to add Tab to a demo file that had playback, but this code interfered with the sound as it would not play the score.  When removed code it would play with sound.  

A demo of staff/tab with playback, set with guitar would be great, as also (Based on help) do not understand how to change instrument.

Thank You

**Comment by brianshano** [comment]
I found this too. 
New tab feature is awesome by the way!

![image](https://user-images.githubusercontent.com/5247913/152599898-bbeeabf4-a3c3-48ac-b785-7e9dbe11cf1d.png)

**Comment by paulrosen** [comment]
Yep, looks like a bug. I'll fix it in the next version, coming soon.

**Comment by paulrosen** [comment]
Fixed in beta 38
