### ISSUE TITLE
Metronome Sound not sync with rhythm

### ISSUE THREAD

**Issue by pandya293** [paulrosen/abcjs#761]
Hi @paulrosen 
Thanks for very good library for music-note.

I am using abcjs library version abcjs_basic_6.0.0_beta_21.js
I am facing issue to play metronome sound synch with rhythm sound.

`X: 1
M: 4/4
L: 1/8
Q:1/4=60
K:clef=perc stafflines = 1
%%equalbars 1
%%stretchlast 0.6
%%partsbox 1
%%MIDI channel 10
%%MIDI program 0
%%MIDI drumon
%%MIDI gchordoff
%%MIDI drum dddd 76 77 77 77 60 60 60 60
V:1

A/A/xz/A/ z/4A/4A/4A/4xz2/3A/4 A2/3A/4xz/A/ (3AA/2x(3A/2A |
A/2A/2A (3z/2Ax(3xA/2A z/z/4A/4xA/4A2/3 z/A/4A/4xz/4A/4A/4A/4 |
A/4A/4A/xA/4A/4A/4A/4 A/4A/4A/xA2/3A/4 A/A/xz2/3A/4 (3zA/2x(3xAA/2|`

I have tried this same abc-note on https://editor.drawthedots.com/ 
this also not play metronom for each bit. 

Please helps me for correct abc note.

**Comment by paulrosen** [comment]
What are all the invisible rests for? That is, all of the "x" characters in the music? That will throw the rhythm off.

**Comment by paulrosen** [comment]
Also, there are some odd rhythms. For instance `z2/3`. How would you write that?

I can't help a whole lot more because I'm not sure what it is supposed to look like.

**Comment by pandya293** [comment]
@paulrosen 
I am attached music-note. please check attachment
<img width="884" alt="Screenshot 2022-02-10 at 10 41 33 AM" src="https://user-images.githubusercontent.com/199303/153352081-29bac145-f3ff-4803-a7af-45298c35ae33.png">

**z/4A/4A/4A/4xz2/3A/4** is called **Demisemiquavers** in UK notation and **Thirty-second notes** in US notation
<img width="821" alt="Screenshot 2022-02-10 at 12 28 54 PM" src="https://user-images.githubusercontent.com/199303/153354831-4fdac16c-590f-4f71-9205-4e89eee8fa04.png">

let me know if anything wrong in this symbol.

**Comment by pandya293** [comment]
@paulrosen 
Do I need to change metronome velocities depend on Q:1/4=60 param in music note ?

%%MIDI drum dddd 76 77 77 77 60 60 60 60
<img width="586" alt="Screenshot 2022-02-10 at 12 36 49 PM" src="https://user-images.githubusercontent.com/199303/153355445-5933a8ec-a640-4180-82f9-0fb50996de5e.png">

Please guide me, how to set drum's program and velocities.

http://manual.freeshell.org/abcmidi/abcguide.txt

**Comment by pandya293** [comment]
@paulrosen  Thanks for you reply!
Yes above rhythm music-cote image is output from abcjs.

we have used 'x' for creates gap between two notes.
our client want to display all combination of Demi-Semi Quavers. It have 2^8 = 256 number of notes
I am attaching screenshot of PDF file that our client send us and they want to display all combination of Demi-Semi Quavers. 
<img width="1311" alt="Screenshot 2022-02-15 at 11 49 28 AM" src="https://user-images.githubusercontent.com/199303/154003899-7ad28f2f-b0f1-432b-9513-45df67a4c2d5.png">

**z/4 A/4A/4A/4 x z2/3 A/4**
menas
<img width="1339" alt="Screenshot 2022-02-15 at 12 16 13 PM" src="https://user-images.githubusercontent.com/199303/154008648-35f2ed35-91cb-422a-a7b1-ec4b08b14eb2.png">

In case if we remove "x" then display TWO lines. and creates different rhythm note.
ABC string
`X: 1
M: 4/4
L: 1/8
Q:1/4=60
K:clef=perc stafflines = 1
%%equalbars 1
%%stretchlast 0.6
%%partsbox 1
%%MIDI channel 10
%%MIDI program 0
%%MIDI drumon
%%MIDI gchordoff
%%MIDI drum dddd 76 77 77 77 60 30 30 30
V:1
z/4A/4A/4A/4xz2/3A/4
z/4A/4A/4A/4z2/3A/4`
<img width="855" alt="Screenshot 2022-02-15 at 12 28 27 PM" src="https://user-images.githubusercontent.com/199303/154009248-799d054d-7a09-4118-9d29-1ecc37d70fe2.png">
created above image from abcjs website https://configurator.abcjs.net/interactive/


Please check below combination of some note from  2^8 Demi-Semi Quavers
<img width="1300" alt="Screenshot 2022-02-15 at 12 46 07 PM" src="https://user-images.githubusercontent.com/199303/154012702-ea289153-b4b8-40e8-a98a-0ef6edd0154a.png">

Hope I am able to explain you why I am taking 'x' and 'z2/3' value in abc string.

**My Question is about metronome speed**
I want to play Metronome drum sound 4 times in 1 music bar. Can I change **dddd** value combination  ?
%%MIDI drum **dddd** 76 77 77 77 60 30 30 30

What is difference between below two drum string value ?
**dddd** 76 77 77 77 60 30 30 30
**d2dd2ddz** 76 77 76 77 77 60 30 60 30 30
for same 4/4 Masure
as shown in below screenshot
 
Can I get more help about this drum string ?
<img width="1329" alt="Screenshot 2022-02-15 at 1 00 59 PM" src="https://user-images.githubusercontent.com/199303/154013958-33c09df8-b896-42d1-97b7-94e8fc3609c3.png">

**Comment by pandya293** [comment]
@paulrosen  when you get time, can you please help me to under stand %%MIDI option in abc string ?
different combination for M: 4/4 measure 
for Q: 1/4=150 drum sound will not play continuous in proper measurement time 
For Q: 1/4=60 drum sound play proper,
how to increase and decrease drum speed according to Q in abcstring

**Comment by paulrosen** [comment]
Instead of using `x` and `z2/3` try doing this for that phrase: `A/4A/4A/4yz3/4A/4`.

Notice the `y` instead of `x`. `y` is a spacer and does not take up time. `x` is an invisible rest and DOES take up time.

For the rest, you want the rest to take up the same space as three 32nd notes. One 32nd note is `z1/4`. Therefore three of them are `z3/4`.

**Comment by paulrosen** [comment]
For `%%MIDI drum` I don't have any insight except the page that you posted. For `dddd` it will take that total length and put it in a measure so it is one sound per beat in 4/4. For the second example, that is showing a more complex rhythm. That rhythm is `A2AA- AA Az`.

**Comment by paulrosen** [comment]
If you have any other issues let me know and I'll reopen this.
