### ISSUE TITLE
Somes issues & questions 😄 

### ISSUE THREAD

**Issue by airdev-web** [paulrosen/abcjs#762]
Hi again!

So since I started to learn this beautiful library, I created a new website using it : https://daily-drum.com/lang/en 

So I have some questions to improve my website :

- Playing generated audio is not supported for iOS ? When I play it, there is no sound, I have to click twice on the rewind button to make it works. On other bowser (like Safari) it's working without any problem.
- Some users asked me if it's possible to start a four 4 click metronom sound before launching the generated sound from abc string. If possible, this 4 click sound should be runned only once, when you start the audio (so it's not played again when it's looped after the first time). Also, if it could be an option to enable/disable, it would be great!
- About the cursor that can follow the played sound. How can I trigger to start it when the audio is played from the sound player ? I didn't find any exemple/docs about this
- Is it possible to generate an image of the abcnote and auto-save it in the storage of the website ? (more like a backend feature)

Thanks for the time you'll take to answer me ! And thanks again for this great library 😄

**Comment by paulrosen** [comment]
iOS changes their rules for audio in every release - what version of Safari are you testing on? It's possible that the way you are initializing the audioContext doesn't meet their requirements or it might be that Safari broke something in abcjs again. I'll see if I can get a minimal demo working to narrow it down.

Yes, the 4 click is possible - there is a parameter that can be passed in for `drumIntro` and that is the number of measures to count in.

Are you using abcjs's audio control with the "displayLoop" option? I don't remember if that replays the intro, but it probably shouldn't. If you are using your own buttons to start the audio and doing the repeat by watching the "finish" callback, you can just call `seek(4, "beats")` to start after the prep beats.

And example of the cursor control on the sound player is here: https://paulrosen.github.io/abcjs/audio/synthesized-sound.html#cursorcontrol-object.

Once the music is on the page it is an SVG element. You can do whatever you want with that, like reference `innerHTML` and save it as a string. That's outside of this library, though.

**Comment by airdev-web** [comment]
Thanks, I will have a look on other points.

But about Safari version, I guess I'm using the lastest one that works with iOS 15.2.1 (can't figure where I can find this version of Safari)

**Comment by paulrosen** [comment]
Would you check version 6.0.0-beta.39 on your device? It might be resolved.

**Comment by airdev-web** [comment]
_Yes, the 4 click is possible - there is a parameter that can be passed in for drumIntro and that is the number of measures to count in._

Yes, it leaves a blank time but without any sound. Is it possible to have kind of a metronome sound ?

```js
synths[div_id].init({ visualObj: visualObj[0] }).then(function () {
    synthControllers[div_id].setTune(visualObj[0], false, {
        drumIntro: 1
    }).then(function () {
        console.log("Audio successfully loaded.")
    }).catch(function (error) {
        console.warn("Audio problem:", error);
    });
}).catch(function (error) {
    console.warn("Audio problem:", error);
});
```

**Comment by airdev-web** [comment]
_Would you check version 6.0.0-beta.39 on your device? It might be resolved._

It works like a charm !

**Comment by airdev-web** [comment]
2 news things : 

- About playing open-hi-hat with percmap, is it possible to show a "round" above the symbol ?
I'm currently using ``%%percmap ^g open-hi-hat x`` but it only shows the "x" symbol
![image](https://user-images.githubusercontent.com/85546423/153779408-dab0a789-82ba-4f14-b142-1c82c0b33800.png)

- If you want to play a "flam" note like that ``F2F2 {c/}c4 F2F2 {c/}c4`` it plays a whistle sound before playing the snare sound.. I tried to add something like that ``%%percmap {c/}c acoustic-snare`` but it doesn't seems to work !
![image](https://user-images.githubusercontent.com/85546423/153779480-dd9c9150-d701-42a7-ba4d-9056f6ba8680.png)

**Comment by paulrosen** [comment]
For the first thing, that symbol isn't directly supported but you can get the point across with "^o" just before the note. That is: `"^o"^g`. The support of percussion isn't complete - partly because there doesn't seem to be a definitive standard on what it should look like.

For the second thing, that is probably a bug that I'll look into. Can you post the entire string so I can see the %%percmap lines and see if there is anything else relevant?

**Comment by airdev-web** [comment]
First thing, works perfectly ! 👍 

Second thing : Here is a string example 
```
X:1
%%percmap D  pedal-hi-hat x
%%percmap F  bass-drum-1
%%percmap F  acoustic-bass-drum
%%percmap A  low-floor-tom
%%percmap A  high-floor-tom
%%percmap B  low-tom
%%percmap ^B tambourine   triangle
%%percmap c  acoustic-snare
%%percmap {c/}c acoustic-snare
%%percmap _c electric-snare
%%percmap ^c low-wood-block   triangle
%%percmap =c side-stick x
%%percmap d  low-mid-tom
%%percmap ^d hi-wood-block    triangle
%%percmap e  hi-mid-tom
%%percmap ^e cowbell      triangle
%%percmap f  high-tom
%%percmap ^f ride-cymbal-1
%%percmap g  closed-hi-hat x
%%percmap ^g open-hi-hat x
%%percmap a  crash-cymbal-1  x
%%percmap ^a open-triangle     triangle
M:4/4
L:1/16
K:C perc
V:1 stem=up clef=perc
Q:1/4=96
F2F2 {c/}c4 F2F2 {c/}c4
```

Other thing, it was about the extra line that I mentionned in other issue. So, if you take the strings in this same comment, basically I put an extra "\n" + "x". Why ? Because otherwhise the last line will not take all the width space.
![image](https://user-images.githubusercontent.com/85546423/153940175-d1883e39-cd09-4e0e-abae-1a0431cc034a.png)

Adding only "\n" at the end doesn't solve it.

The idea is to get all the space takes all available width of the div without adding an extra line.
![image](https://user-images.githubusercontent.com/85546423/153940335-0b847e4f-00b6-42fa-8430-2110bdb7e7a2.png)

Thanks ! 😄

**Comment by airdev-web** [comment]
It's me again ! About ghost note and accentuated note ! 
So I have this exemple here :
![image](https://user-images.githubusercontent.com/85546423/153948623-ebe97a83-92a5-4c94-877b-4e7275f36552.png)

With this abc notation : 
```
X:1
%%percmap D  pedal-hi-hat x
%%percmap F  bass-drum-1
%%percmap F  acoustic-bass-drum
%%percmap A  low-floor-tom
%%percmap A  high-floor-tom
%%percmap B  low-tom
%%percmap ^B tambourine   triangle
%%percmap c  acoustic-snare
%%percmap {c/}c acoustic-snare
%%percmap _c electric-snare
%%percmap ^c low-wood-block   triangle
%%percmap =c side-stick x
%%percmap d  low-mid-tom
%%percmap ^d hi-wood-block    triangle
%%percmap e  hi-mid-tom
%%percmap ^e cowbell      triangle
%%percmap f  high-tom
%%percmap ^f ride-cymbal-1
%%percmap g  closed-hi-hat x
%%percmap ^g open-hi-hat x
%%percmap a  crash-cymbal-1  x
%%percmap ^a open-triangle     triangle
M:4/4
L:1/16
K:C perc
V:1 stem=up clef=perc
Q:1/4=130
"^>"c"^>"c"<("">)"c"<("">)"c "<("">)"c"<("">)"c"^>"c"^>"c "<("">)"c"<("">)"c"<("">)"c"<("">)"c "^>"c"^>"c"<("">)"c"<("">)"c | 
"<("">)"c"<("">)"ccc "<("">)"c"<("">)"c"<("">)"c"<("">)"c cc"<("">)"c"<("">)"c cc"<("">)"c"<("">)"c |
```

How can I set the level of sound of the note to be lower or higher depending if it's a ghost note or an accentuated note ?

**Comment by paulrosen** [comment]
Add this line towards the top: `%%stretchlast` That will make the last line take up all the room. You could also control how wide the staff is with `%%staffwidth 500` with the number being the number of pixels.

The rest of it I'll answer later.

**Comment by paulrosen** [comment]
The whistle sound will be fixed in beta 40

**Comment by paulrosen** [comment]
For animating a cursor, see https://paulrosen.github.io/abcjs/examples/animation.html

**Comment by paulrosen** [comment]
For the volume of ghost notes, it will take a little programming on your part. You'll need to intercept the audio after it is mapped out and before it is produced. Here's an example you can modify: https://paulrosen.github.io/abcjs/examples/modify-synth-input.html

**Comment by airdev-web** [comment]
Okay just found my answer about my last comment. It's just the ``sequenceCallback`` param that should be not in an ``options`` object.. Maybe you should update your doc about this 😃 

Then no need to create a synth before, because it will be created into the SynthController !

```js
synthControllers[div_id] = new abcjs.synth.SynthController();
synthControllers[div_id].load('#'+div_id,
    cursorControl,
    {
        displayLoop: true,
        displayRestart: true,
        displayPlay: true,
        displayProgress: true,
        displayWarp: true,
    },
);

synthControllers[div_id].setTune(visualObj[0], false, {
    sequenceCallback: function() {
        console.log('Callback')
    }
}).then(function () {
    console.log("Audio successfully loaded.")
}).catch(function (error) {
    console.warn("Audio problem:", error);
});
```

**Comment by airdev-web** [comment]
Just created a way to change volume for ghost and accentuated note. So you need to use the visualObj to check how the note is written. Feel free to correct me if there is an easier way to do it.

```js
function isGhostNote(elem) {
    if (elem.chord && elem.chord[0].name == '(' && elem.chord[1].name == ')')
        return true;

    return false;
}

function isAccentuatedNote(elem) {
    if (elem.chord && elem.chord[0].name == '>')
        return true;

    return false;
}

function adjustVolume(visualObj, track) {
    var index = 0;
    visualObj.lines.forEach(function (line) {
        line.staff.forEach(function (staff) {
            staff.voices.forEach(function (voice) {
                voice.forEach(function (elem) {
                    if (elem.el_type == 'note' && elem.pitches) {
                        // Just to reset the note volume
                        track[index].volume = 100

                        if (isGhostNote(elem)) {
                            track[index].volume = 15
                        }

                        if (isAccentuatedNote(elem)) {
                            track[index].volume = 200
                        }
                        index++;
                    }
                })
            })
        })
    })
}

function renderMidi(div_id, visualObj) {
    document.getElementById(div_id).innerHTML = ''

    synthControllers[div_id] = new abcjs.synth.SynthController();
    synthControllers[div_id].load('#'+div_id,
        cursorControl,
        {
            displayLoop: true,
            displayRestart: true,
            displayPlay: true,
            displayProgress: true,
            displayWarp: true,
        },
    );

    synthControllers[div_id].setTune(visualObj[0], false, {
        sequenceCallback: function(tracks) {
            tracks.forEach(function (track) {
                adjustVolume(visualObj[0], track)
            })
        }
    }).then(function () {
        console.log("Audio successfully loaded.")
    }).catch(function (error) {
        console.warn("Audio problem:", error);
    });
}
```

**Comment by airdev-web** [comment]
I have a tempo input editor that allows user to change the tempo without the % wrap of the player.
![image](https://user-images.githubusercontent.com/85546423/154352272-88efd8db-84e5-43b4-8130-c275085cffcc.png)

I want to stop the synthController when there is a new input to regenerate everything after. using ``stop()`` method of synthController do not work, but using ``destoy()`` yes.

But then it throws an error (it's working btw, but just weird I've got that)
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'init')
    at app.js?id=51503f1c2f0bd4af8fa3fb79475aab8c:14080:27
```
```js
return activeAudioContext().resume().then(function (response) {
    return self.midiBuffer.init({
        visualObj: self.visualObj,
        options: self.options,
        millisecondsPerMeasure: millisecondsPerMeasure
    });
```

**Comment by paulrosen** [comment]
I think you're on the right track. You're right that it could be easier and this is a good case to play with that. I have some ideas for improving the synth interface and I think you are running into a lot of them!

I want to jump on the uncaught exception. If you have the dev tools open, does it stop when that error is encountered? I'd like to know what line that is happening on and I think the dev tools will use the map and make it readable.

**Comment by paulrosen** [comment]
If there is still a problem let me know and I'll reopen.
