### ISSUE TITLE
Can't decode sound

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#775]
I just noticed that I got an error in Safari on my mac computer when trying to play audio
"Can't decode sound at soundfont/FluidR3-GM/acoustic...mp3" -- abcjs.basic.js
abcjs-basic v6.0.2
Safari version 15.1

Works fine on my iPhone as well as Windows, so not sure what Safari's problem is now...

**Comment by paulrosen** [comment]
Safari is now at 15.4. There have been a lot of audio bugs, but I think they might be fixed now.

**Comment by nbruley** [comment]
Upgrading Safari fixed this issue.
