### ISSUE TITLE
is it possible to set an instrument for a fragment of a tune ?

### ISSUE THREAD

**Issue by dbq817** [paulrosen/abcjs#776]
Hi, all

I just wanna select an instrument (program) for a piece of the whole tune, say the default instrument is giant piano, and set accordion for just a couple of measures. I've no idea if this is possible

any information is appreciated!

Best regards,
Ben

**Comment by paulrosen** [comment]
Try this:
```
X:1
T:change instrument
L:1/4
Q:1/4=120
M:4/4
K:D
%%MIDI program 1
DEFG|
%%MIDI program 22
DEFG|
%%MIDI program 1
DEFG| [I:MIDI program 40]ABcd| [I:MIDI program 1]ABcd|

```

**Comment by dbq817** [comment]
so many thanks, @paulrosen, this works!

well, if it is possible to restore the instrument after those special measures ? 

since my app can change the default instrument for any tune, I just wanna specify fixed instrument for some measures, and after those measure I hope the default instrument can be restored. But this is good enough, I think I can work out a solution to this anyway.

**Comment by dbq817** [comment]
I made it by refactoring the abc file, this post is closed, thanks @paulrosen and your abcjs!!!
