### ISSUE TITLE
A tie between two C's is not displayed

### ISSUE THREAD

**Issue by p-himik** [paulrosen/abcjs#779]
To reproduce, go to https://editor.drawthedots.com/ and replace the notes with `C- C`.

This is how it ends up being rendered:
![image](https://user-images.githubusercontent.com/4410314/163874175-b62a202d-f086-48bf-bbf6-ddc11cfff991.png)

The cause is the SVG's `viewBox` having a height that's too small - it cuts off the tie. So adding some padding underneath the SVG doesn't help.

**Comment by paulrosen** [comment]
I can reproduce. Thanks for the bug report. It will be fixed in the next version.

**Comment by paulrosen** [comment]
fixed in 6.0.4
