### ISSUE TITLE
Visual transpose bug

### ISSUE THREAD

**Issue by Erin122** [paulrosen/abcjs#787]
- Visual transpose does not work properly when there is a key transposition in the song.
- Visual transpose seems to work only before the key transposition.
- There seems to have been a related issue #210 before, but has it not been resolved yet?
- Is there any temporary workaround to solve this?

Thanks for awesome package! I really wait for reply ❤

**Comment by paulrosen** [comment]
Can you post an example ABC string? I can probably create one from your description and I'll look into it.

**Comment by paulrosen** [comment]
I can reproduce if the key change is embedded in the line:
```
K: C
|:CDEF GABc| [K:D] defg abc'd'|
```
It appears to work if the key change is on a separate line, like:
```
K: C
|:CDEF GABc|
K:D
defg abc'd'|
```
(Except for the hint at the end of the first line - that stays at two sharps.)

**Comment by Erin122** [comment]
> I can reproduce if the key change is embedded in the line:
> 
> ```
> K: C
> |:CDEF GABc| [K:D] defg abc'd'|
> ```
> 
> It appears to work if the key change is on a separate line, like:
> 
> ```
> K: C
> |:CDEF GABc|
> K:D
> defg abc'd'|
> ```
> 
> (Except for the hint at the end of the first line - that stays at two sharps.)

Thanks ! I solved this problem :)
