### ISSUE TITLE
Rhythm placement

### ISSUE THREAD

**Issue by hwellmann** [paulrosen/abcjs#793]
After upgrading from 5.x to 6.x, the rhythm is misplaced and may overlap the clef.

Example:
```
X: 1
T: Layout bug
M: 4/4
L: 1/8
R: reel
K: Emin
defg|
```

Rendered as:
<img width="230" alt="Bildschirmfoto 2022-06-21 um 09 56 04" src="https://user-images.githubusercontent.com/875768/174747012-05b4c314-73de-4c53-9987-44538e97db8e.png">

Workaround:

Add an empty chord: `""defg`.

**Comment by paulrosen** [comment]
Thanks for the bug report! It will be fixed in the next version.
