### ISSUE TITLE
slur cut off at bottom of line

### ISSUE THREAD

**Issue by garfieldnate** [paulrosen/abcjs#804]
The slur below is cut off in the output:

    (A, B,2)

Output on the demo site:

<img width="143" alt="image" src="https://user-images.githubusercontent.com/778453/184125327-53ef99aa-d361-4e98-afde-c175efff5f87.png">

![MBE](https://user-images.githubusercontent.com/778453/184125530-8263fce5-f9c1-4f0f-9003-67ade9572457.svg)

**Comment by paulrosen** [comment]
I recently fixed that - but it looks like I didn't update http://editor.drawthedots.com. Is that the demo site you are talking about? I'll go through and make sure I'm using the latest library on all my sites.

**Comment by garfieldnate** [comment]
Ah yes, that's the one. Thanks!

**Comment by paulrosen** [comment]
Fixed in v6.1.0
