### ISSUE TITLE
Draggable compability with Tablet's Touch (instead of mouse click event)

### ISSUE THREAD

**Issue by johnnyteoh** [paulrosen/abcjs#811]
Hi, just wondering if anyone has tried to implement the draggable notation with a tablet scenario, specifically using the draggable for notation transposition purpose?  

Thanks heaps for any advise!

**Comment by paulrosen** [comment]
No, I haven't. I think it should be similar to the desktop version - I think the touch dragging should be the same event as the mouse dragging. I'm not sure. Please keep me posted if you find you need to do something special.

**Comment by johnnyteoh** [comment]
Can you point me to the code where draggable event is handled? Maybe we need to add the same to handle the touch event?

**Comment by paulrosen** [comment]
Look at `src/write/selection.js`. To activate it, you need to pass some parameters that allow selection for the type of elements you want to drag. Look at the example https://paulrosen.github.io/abcjs/examples/dragging.html for an idea how it works.

I'd love to flesh this out some more so let me know any ideas you have.

**Comment by johnnyteoh** [comment]
@paulrosen we made the modification to the code to add support for the TouchEvents.

**Comment by paulrosen** [comment]
Will be in versino 6.1.1
