### ISSUE TITLE
Is the problem solved with broken tie when onesvgperline? 

### ISSUE THREAD

**Issue by Erin122** [paulrosen/abcjs#814]
Thanks for your project. 
I have issue with printing the score. 
I want to use onesvgperline, but broken tie occurs. 
Below link is related issue. Is this problem solved ? 
https://github.com/paulrosen/abcjs/issues/554#issue-742528360

**Comment by paulrosen** [comment]
Oh, sorry. I think this one fell through the cracks. I bumped it up on my todo list - I am planning a minor bug fix version soon.

**Comment by Erin122** [comment]
Really thanks :) I really love following up this project. (Latest transposition feature is very awesome !)

**Comment by paulrosen** [comment]
Fixed in 6.1.1.

Let me know if you see any problems since my approach to this feature changed a little.
