### ISSUE TITLE
Possible to have empty staff fill rest of width?

### ISSUE THREAD

**Issue by Nickno95** [paulrosen/abcjs#818]
I have a decorative use case where I want to be able to write a line with some notes, but at the end of the last measure the staff continues empty to fill the rest of the width of the parent?

**Comment by paulrosen** [comment]
If I understand you correctly, you should add this line to your string: `%%stretchlast`

You can also make the staff line shorter in general if that is what you are asking: `%%staffwidth 400` where you can experiment with the number.
