### ISSUE TITLE
Annotations draw over each other

### ISSUE THREAD

**Issue by iacchus** [paulrosen/abcjs#82]
[abcjs 2.3](https://iacchus.github.io/musiceditor/), the code:

```
X: 1
M: 4/4
L: 1/4
K: A
"^4" "^3" "_1" "_1"[A,Eca']
```

Draws the fingering below (both 1) over each other. Is this a bug or maybe I am doing something wrong?

**Comment by paulrosen** [comment]
That's a bug. It also happens with:
`
"^4" "^3" "_1\n1"[A,Eca']
`
I'll look at it.

**Comment by paulrosen** [comment]
This is fixed in the master branch and will be in version 3.1.2
