### ISSUE TITLE
Backing track sound

### ISSUE THREAD

**Issue by airdev-web** [paulrosen/abcjs#822]
Hi !

When creating the drum notation, then the audio player. Is it possible to add a backing track sound ? (For exemple an mp3)

So it would be synchronised with the drum sound,

If you see what I mean,

Thanks,
Romain

**Comment by paulrosen** [comment]
You can't do that directly, but you can play more than one thing at the same time. You queue up both audio buffers and start them right after each other. That's why the audio is broken up into different calls - the last call to play is really fast and will be synchronized with another buffer.
