### ISSUE TITLE
Moving annotations

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#824]
How do I move annotations above the score without affecting annotations within the score?
![image](https://user-images.githubusercontent.com/1113368/193492437-fca4dcb7-e96f-4c1e-92aa-3aeee222a8c3.png)
The Refrain is entered like this:
```
"[Refrain]"A | c> c c c2 B/ c/ | d> c B A2||
```
I note the css classes are the same...

**Comment by paulrosen** [comment]
There are different types of annotations. If it is a simple string inside quotes, it's actually a "chord symbol". You can also start with a caret `"^something"`, an underscore `"_something"`, or an at symbol with a relative position `@-4,-4something"`. (The font for chord symbols is controlled separately from the other styles of annotation, too, BTW.)

I'm not sure what you're trying to do here, but I guess you are seeing some overlap with the line above? That looks like a general bug so if you post a full example I'll look at that.

**Comment by nbruley** [comment]
Well, here's the code. I'm not sure if this would be easy to fix automatically but you can give it a whirl. We're doing it this way because we need to be able to switch out the lyrics with different lyrics but keep the same ABC.

```
%%abc-charset utf-8

X:1
T:11.8.11.8 w/ Refrain
C:William J. Kirkpatrick, 1890
L:1/8
Q:1/8=100
M:6/8
K:D
%%score (S A) (T B)
V:S clef=treble middle=B stem=up
V:A clef=treble middle=B stem=down
V:T clef=bass,, stem=up
V:B clef=bass,, stem=down
[V:S]"_1. A WONDERFUL Saviour is Jesus my Lord,"A | A> G F F E D | B> B B A2||
"_   A wonderful Saviour to me;"A | A> G F F G F | E3-E2||
"_He hideth my soul in the cleft of the rock,"A | A> G F F E D | B> B B d2||
"_   Where rivers of pleasure I see."B | A> A A A G E | D3-D2 ||
"_He hideth my soul in the cleft of the rock""@0,40[Refrain]"A | c> c c c2 B/ c/ | d> c B A2||
"_   That shadows a dry, thirsty land;"A|G F G | E B A | F3-F2||
"_He hideth my life in the depths of His love,"A| d> d d d2 d/ d/ | e> d d d2 ||
"_   And covers me there with His hand,"B | A> A A A A A | A3-A2 ||
"_   And covers me there with His hand."B | A> F D G> C C | D3-D2|]
[V:A]F | F> E D D D D | G> G G F2||
F | F> E D D E D | C3-C2||
G | F> E D D D D | G> G G G2||
G | F> F F C C C | D3-D2 ||
A | G> G G G2 G/ G/ | F> A GF2||
F|E ^D E | C C C | D3-D2||
F | F> F FF2 F/ F/ | G> G G G2 ||
G | F> F F E F G | F2 G A2||
G | F> D D C> A, A, | A,3-A,2|]
[V:T]A, | A,> A, A, A, G, F, | D D D D2||
A, | A,> A, A, A, A, A, | A,3-A,2||
C | D> A, A, A, G, F, | D> D D B,2||
D | D> A, F, E, E, G, | F,3-F,2||
A, | E> E E E2 A,/ A,/ | A,> A, D D2||
A, | A, A, A, | A, A, A, | A,3-A,2||
A, | A,> A, A, A,2 A,/ A,/ |G,> G, G, G,2 || 
D | D> D D C D E | D2 C D2||
D | D> A, F, E,> G, G, | F,3-F,2|]
[V:B]D, | D,> D, D, D, D, D, |G,, G,, G,, D,2||
D, | D,> D, D, D, C, D, | A,,3-A,,2||
A,, | D,> D, D, D, D, D, |G,,> G,, G,, G,,2||
G,, | A,,> A,, A,, A,, A,, A,, | D,3-D,2||
A, | A,> A, A, A,2 A,/ A,/ | D,> D, D,D,2||
D, |A,, A,, A,, | A,, A,, A,, | D,3-D,2||
D, |D,> D, D, D,2 D,/ D,/ |B,> B, B, B,2 || 
G, | A,> A, A, A,, A,, A,, | D,2 E, F,2||
G,, | A,,> A,, A,, A,,> A,, A,, | D,3-D,2|]
```

**Comment by paulrosen** [comment]
In that particular case, the word "Refrain" is absolutely placed. I experimented with that and moved it out of the way with `"@0,20[Refrain]"`. 

I have a feeling I'm not understanding your question, though.

**Comment by nbruley** [comment]
Thanks for pointing that out, since I honestly forgot about the manual placement option that we are doing programatically and didn't realize that your code otherwise automatically adjusts the placement properly. I'm trying to remember why we didn't go with "^[Refrain]" instead of absolute placement. I will go back to using ^ instead of absolute placement because that appears to fix the overlap issue. Without the ^ it changes the note spacing too much.

I guess the only remaining question would be if it would be possible to adjust ^ or _ or @ with CSS separately from the rest of the annotations, but at this point it doesn't look like we need that feature.
