### ISSUE TITLE
How to get lyrics in directive w:

### ISSUE THREAD

**Issue by johnlsg** [paulrosen/abcjs#836]
Is there any method in this library I can parse an musicABC to get its lyrics?

Using this as example, I want to get the all the text stated with "w:", which is "Rock-y did-nt like that"
X:1
T:alternate heads
M:C
L:1/8
U:n=!style=normal!
K:C treble style=rhythm
"Am" BBBB B2 B>B | "Dm" B2 B/B/B "C" B4 |"Am" B2 nGnB B2 nGnA | "Dm" nDB/B/ nDB/B/ "C" nCB/B/ nCB/B/ |B8| B0 B0 B0 B0 |]
%%text This translates to:
[M:C][K:style=normal]
[A,EAce][A,EAce][A,EAce][A,EAce] [A,EAce]2 [A,EAce]>[A,EAce] |[DAdf]2 [DAdf]/[DAdf]/[DAdf] [CEGce]4 |[A,EAce]2 GA [A,EAce] GA |D[DAdf]/[DAdf]/ D[DAdf]/[DAdf]/ C [CEGce]/[CEGce]/ C[CEGce]/[CEGce]/ |[CEGce]8 | [CEGce]2 [CEGce]2 [CEGce]2 [CEGce]2 |]
GAB2 !style=harmonic![gb]4|GAB2 [K: style=harmonic]gbgb|
[K: style=x]
C/A,/ C/C/E C/zz2|
w:Rock-y did-nt like that

**Comment by paulrosen** [comment]
There is no built in way to do this, but you can do it in one of two ways - you can do it with pure text processing - look for `"\nw:"` in the string and extract that line, or if you want to get the syllables that are parsed you can traverse the rendered object. I did a little test and the following works:
```
var visualObj = ABCJS.renderAbc("paper", abc);
var words = []
for (var i = 0; i < visualObj[0].lines.length; i++) {
	var line = visualObj[0].lines[i]
	if (line.staff) {
		for (var j = 0; j < line.staff.length; j++) {
			var staff = line.staff[j];
			for (var k = 0; k < staff.voices.length; k++) {
				var voice = staff.voices[k]
				for (var l = 0; l < voice.length; l++) {
					var element = voice[l]
					if (element.lyric) {
						for (var m = 0; m < element.lyric.length; m++) {
							var lyric = element.lyric[m]
							words.push(lyric.syllable)
						}
					}
				}
			}
		}
	}
}
console.log(words)
```

**Comment by johnlsg** [comment]
Thank you very much
