### ISSUE TITLE
no sound on ios15.7

### ISSUE THREAD

**Issue by watersoft123** [paulrosen/abcjs#840]
A friend of mine have an iphone with ios version 15.7,and I sent him [the URL](https://editor.drawthedots.com/) to test ,but it's no sound,I don't know where is the problem?

**Comment by paulrosen** [comment]
What version of iPhone? There have been reports of sound problems with various combinations of phones and safari versions. As far as I know they were fixed in Safari 16.1.

**Comment by samuelbradshaw** [comment]
Is his phone on silent for notifications? Unlike other audio, MIDI doesn't override the silent switch, so if his phone is on silent, he won't hear anything.

**Comment by paulrosen** [comment]
Oh, yeah, I remember that gotcha. There is some file I found once that is an "ios mute defeater". If you run that code it creates a regular `<audio>` tag and plays a short piece of silence, but that is enough to confuse the iPhone into playing all audio.

**Comment by watersoft123** [comment]
> paulrosen

Paul rosen, thank you. This is not a bug in ABCjs, but the ring switch of my friend's mobile phone is not turned on, and I can hear the sound after turning it on. But sometimes it's really strange, the same js code, Android, PC and even Mac are all OK, except for the iPhone.
