### ISSUE TITLE
percmap not mapping for c'

### ISSUE THREAD

**Issue by leocaseiro** [paulrosen/abcjs#846]
Hi there, I was able to map all songs I wanted to, following the reference from https://github.com/paulrosen/abcjs/issues/753#issuecomment-1014637775

However, the only note that I'm trying to map, and it's not working is the `c'`, perhaps it could be an issue with the `'` sign.

I haven't investigated much, but you can test the issue as the example:

```
X:1
T:Bug when mapping c'
%%percmap D  pedal-hi-hat x
%%percmap E  bass-drum-1
%%percmap F  acoustic-bass-drum
%%percmap G  low-floor-tom
%%percmap A  high-floor-tom
%%percmap B  low-tom
%%percmap ^B tambourine   triangle
%%percmap c  acoustic-snare
%%percmap _c electric-snare
%%percmap C low-wood-block   triangle
%%percmap =c side-stick x
%%percmap d  low-mid-tom
%%percmap ^d hi-wood-block    triangle
%%percmap e  hi-mid-tom
%%percmap ^e cowbell      triangle
%%percmap f  high-tom
%%percmap a ride-cymbal-1     x
%%percmap _a ride-bell     harmonic
%%percmap g  closed-hi-hat      x
%%percmap ^g open-hi-hat      x
%%percmap b  crash-cymbal-1  x
%%percmap ^c' crash-cymbal-2  x
%%percmap C crash-cymbal-2  x
%%percmap ^a open-triangle     triangle
K:C perc
V:ALL stem=up
c' c' c' c'
C C C C
```

The `C` is playing the correct sound (`crash-cymbal-2`), whereas the `c'` is playing something else.

**Comment by paulrosen** [comment]
You're right! It is because of the apostrophe. This will be fixed in the next version.
