### ISSUE TITLE
Sample attack sound

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#850]
Is there some sort of algorithm that adjusts the attack dynamics of the sampled sound to ramp up slower than the recorded music? When I use my own sampled strings that don't appear to start out soft and get louder through the sample, the playback has a crescendo effect that makes the sound sound more fake...

**Comment by paulrosen** [comment]
I'm not exactly sure what you mean but there isn't anything complicated happening in abcjs. The notes are all individual mp3 that are loaded in and placed in a buffer. I do set the overall volume of each sample (for `!p!` and `!f!` for instance) but nothing within the note. So I guess the sound font is doing that. I can't say much more without hearing what you are hearing.

**Comment by nbruley** [comment]
Thanks, that's helpful. I'm curious how the programming ends the note, is there a fade or does it just play the mp3 for the duration of the note and just cut it off at that point?

**Comment by paulrosen** [comment]
The note fades out after the end time. This is 200 milliseconds by default but can be set in the `synthOptions`:
```
| fadeLength | 200 | The number of milliseconds to fade out each note after its has played for the correct length. The gain will go from 100% to 0% in this number of milliseconds. | 
```

**Comment by nbruley** [comment]
I love how you make things so customizable. Changing the fade length makes what we were hearing much less noticeable, so I'm calling this resolved. Much appreciated.
