### ISSUE TITLE
Sound Renderer plays wrong notes when using minor scales

### ISSUE THREAD

**Issue by DannyDane** [paulrosen/abcjs#858]
First of all thank you for creating this wonderful library!

I'm encountering a strange issue though: When playing notes in the minor scale, which can have both minor or major sixths and sevenths, **abcjs** has trouble playing the correct notes.

For example when my notation is this:

**L: 1/4
K: Fmin 
V:1
c2 d2 f2**

**abcjs** will play the _d_ (the major sixth in the f minor scale) as a _d flat_ (a minor sixth). So the sound engine will playing something different than the notation.

Is there something I have to indicate in the key signature to have it play correctly?

Thanks in advance.

**Comment by DannyDane** [comment]
I think I have discovered what I did wrong.

I'm creating a melodic dictation exercise and at the beginning of each question a I IV V I chord sequence is played. 
If the chord sequence has for example minor sixth in it (the third of the IV chord) then every sixth in the exercise is automatically played as a minor sixth, even though in the abc notation it's written as a major sixth.

I don't know if this is normal behavior or not though.

**Comment by paulrosen** [comment]
I'm not sure I follow unless there is more ABC than you've shown.

In the example above there is a flat on the "D" line in the key signature so all of the "D" notes are supposed to be flat. If you want a natural you have to specify it with `=d`.

I don't know of any examples of melodic minor that doesn't have that explicitly notated.
