### ISSUE TITLE
Hide audio if there is nothing to play

### ISSUE THREAD

**Issue by m7vm7v** [paulrosen/abcjs#859]
Hi. Is there a way to add a listener to check if the sheet is playable and then show the audio bar, otherwise hide it?

For example, if we have just lyrics then it's not playable and the library would still show the text - 

```
T: Holy Holy Holy
C: Worship
W:Holy, holy, ho - ly, Lord God Al - mighty
W:Early in the morn - ing my song shall rise to Thee
W:Holy, holy, ho - ly, merciful and mighty
W:God in three Per - sons, blessed Trini - ty
```

**Comment by paulrosen** [comment]
You would have to do that yourself.

Right after you render you will get an object, something like:
```
const visualObj = abcjs.renderAbc(...)
const firstTune = visualObj[0]
const numLines = firstTune.lines.length
```
If `numLines` is zero then there is nothing to play and you can put `display: none` on the audio div.
