### ISSUE TITLE
It should handle field continuation

### ISSUE THREAD

**Issue by ghost** [paulrosen/abcjs#86]
See [here](http://abcnotation.com/wiki/abc:standard:v2.1#field_continuation) for specification.

For example : 
````
w:Sa-ys my au-l' wan to your aul' wan,
+:will~ye come to the Wa-x-ies dar-gle?
````
The **+:** means that it continues the previous line, without adding the `\n`.

It should works for A, B, C, D, F, G, H, N, O, R, S, T, W, w and Z

**Comment by paulrosen** [comment]
I'm closing some old issues due to inactivity. I have this feature on my list to do when I have time.
