### ISSUE TITLE
How to access to the synth control of the interactive editor

### ISSUE THREAD

**Issue by computermusicneix** [paulrosen/abcjs#862]
Hi

Hi have the interactive editor like this:

``
abcjsEditor = new ABCJS.Editor("abc", {                            canvas_id: "paper",
        warnings_id: "warnings",
        synth: {
          el: "#audio",
          options: { displayLoop: true, displayRestart: true, displayPlay: true, displayProgress: true, displayWarp: true,soundFontUrl: selected_soundfont[1]}                           },                                                         abcjsParams: {                                               add_classes: true,                                         clickListener: clickListener,                              staffwidth : "740",                                        responsive: "resize",                                      oneSvgPerLine: true,                                       wrap:{ minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 }
        },
        selectionChangeCallback: selectionChangeCallback   });

``

And I wants acces to synthcontrol for play and download wav programmatically.

I tried with ABCJS.synth.play()  ABCJS.synth.synthControl.play() etc but no results. Any idea?  Thanks!

PD: And thanks for ABCJS lib!!!

**Comment by paulrosen** [comment]
So you want both the synth control that the user can press AND to do it programmatically? 

With what you tried you are getting the javascript classes, but you need the instantiated object instead. That is inside the editor.

Try this:
```
const abcjsEditor = new ABCJS.Editor("abc", {
        canvas_id: "paper",
        synth: {
          el: "#audio",
          options: { displayLoop: true, displayRestart: true, displayPlay: true, displayProgress: true, displayWarp: true }
        },
      });
abcjsEditor.synth.synthControl.play()
```

**Comment by computermusicneix** [comment]
> So you want both the synth control that the user can press AND to do it programmatically?
> 
> With what you tried you are getting the javascript classes, but you need the instantiated object instead. That is inside the editor.
> 
> Try this:
> 
> ```
> const abcjsEditor = new ABCJS.Editor("abc", {
>         canvas_id: "paper",
>         synth: {
>           el: "#audio",
>           options: { displayLoop: true, displayRestart: true, displayPlay: true, displayProgress: true, displayWarp: true }
>         },
>       });
> abcjsEditor.synth.synthControl.play()
> ```

It works! thank you.  I have had some problems with the assignment, for some reason it gives me an error with const, but with let there is no problem.

Again, thanks for the abcjs
