### ISSUE TITLE
Adding URL links to notes?

### ISSUE THREAD

**Issue by iantresman** [paulrosen/abcjs#87]
Is it possible to add a URL to each note displayed? I'd like to let people click on a note, and then display an instrument fingering chart for each one.

I couldn't see a solution in [The abc music standard 2.1](http://abcnotation.com/wiki/abc:standard:v2.1)

**Comment by paulrosen** [comment]
You can add a listener for when the user clicks on a note. Here's an example using the editor, but it is similar when using the basic version:

```
<script type="text/javascript">
	function selectionCallback(abcelem) {
		console.log(abcelem);
	}

	function initEditor() {
		new ABCJS.Editor("abc", { paper_id: "paper0",
			render_options: {
				listener: { highlight: selectionCallback }
			}
		});
	}

	window.addEventListener("load", initEditor, false);
</script>
```

**Comment by paulrosen** [comment]
There is now an example of this here: https://github.com/paulrosen/vue-abcjs-callback-demo
