### ISSUE TITLE
CSS styling of measure

### ISSUE THREAD

**Issue by programmer323** [paulrosen/abcjs#870]
When adding a style to the 1st measure of a line, it does work, but if you have tablature enabled it will also highlight the tab of the entire line.  

 
![measureCSSbug-css](https://user-images.githubusercontent.com/122573158/212189798-4069a935-94d3-400b-97d9-51aff0183252.jpg)

![measureCSSbug-score](https://user-images.githubusercontent.com/122573158/212189815-feebadfa-16ea-4ab5-9912-2ea46e470e62.jpg)

**Comment by paulrosen** [comment]
That's definitely a bug. Thanks for reporting it!

And sorry.

**Comment by paulrosen** [comment]
Will be fixed in v6.1.8
