### ISSUE TITLE
Rests in the 1st Measure cause offset of player

### ISSUE THREAD

**Issue by programmer323** [paulrosen/abcjs#871]
If you add a rest in the 1st measure (as 1st note) it causes an offset of the  the note coloring in the TAB. It seems to be off by the duration of the rest.  Also, the animated lines plays ok for a few measure, then gets out of sync and jumps around, see screen shot.

![rest offeset 1](https://user-images.githubusercontent.com/122573158/212191230-74e88bc2-db29-47a3-9cfa-df5ec20fb50b.jpg)

![rest offeset 2](https://user-images.githubusercontent.com/122573158/212191351-211ac1ad-d012-4250-bdd1-1e6dae7f6496.jpg)

![rest offeset 3](https://user-images.githubusercontent.com/122573158/212191356-0481117c-d8be-45a8-bfce-42d221f38c7f.jpg)

**Comment by paulrosen** [comment]
Thanks for the bug report!

**Comment by paulrosen** [comment]
I duplicated this. It looks like it is just happening when the tab is present. I'll research.

**Comment by paulrosen** [comment]
Fixed in 6.1.8
