### ISSUE TITLE
measure CSS does not highlight tab

### ISSUE THREAD

**Issue by programmer323** [paulrosen/abcjs#872]
measure CSS does not highlight tab, see screen shots:

![measureClassNotHiliteTab-css](https://user-images.githubusercontent.com/122573158/212195485-39f4c84b-ac87-4cbb-bd7e-adc115fa219b.jpg)

![measureClassNotHiliteTab-ex](https://user-images.githubusercontent.com/122573158/212195508-0aae5882-5510-4f4b-a212-db19d72b8543.jpg)

**Comment by paulrosen** [comment]
Definitely a bug. I'll look into it.

**Comment by paulrosen** [comment]
I fixed a couple of these issues in the dev branch. It will be in v6.1.8. I'll try to get that out soon.

**Comment by paulrosen** [comment]
Will be fixed in v6.1.8
