### ISSUE TITLE
Sharp then regular note does't play correctly.

### ISSUE THREAD

**Issue by felix-care-planner** [paulrosen/abcjs#873]
Consider this abc:

```
a ^a
zz
^a a
```

The first line goes from a lower note to a higher note.
The second line (ignoring the pause) repeats the same note twice.

Why?

I have read: "The symbols ^, = and _ are used (before a note) to notate respectively a sharp, natural or flat. Double sharps and flats are available with ^^ and __ respectively. "

So an equals before the last a would fix it - but shouldn't the caret only apply to the note directly after it?

**Comment by paulrosen** [comment]
An accidental applies until the end of the measure, so when you put a sharp on the `A` line all of the notes on that line will be sharp until a bar line. Here's an explanation: https://www.doremistudios.com.au/how-accidentals-work-music/

**Comment by felix-care-planner** [comment]
@paulrosen thanks for the feedback and educating me!
