### ISSUE TITLE
Tab - low notes interfere  with Player

### ISSUE THREAD

**Issue by programmer323** [paulrosen/abcjs#874]
low notes TAB gets cut off 

![lowNotes-notTab](https://user-images.githubusercontent.com/122573158/212569622-1ff4ebe4-a125-45e4-8064-84d12f0c3b70.jpg)

![lowNotes-withTab](https://user-images.githubusercontent.com/122573158/212569625-85cdca93-03f2-4682-bf7a-a46ffd16e673.jpg)

**Comment by paulrosen** [comment]
Will be fixed in v6.1.8
