### ISSUE TITLE
Tab - natural notes flattened by key signature not reflected  in TAB

### ISSUE THREAD

**Issue by programmer323** [paulrosen/abcjs#875]
If a note is sharped in the key signature it does render correct, problem is if note is made natural then is it stills show modified fret in Tab, when it should be its  original  fret.  The natural note is played correctly in the sound player.

![natural notes](https://user-images.githubusercontent.com/122573158/212569714-90462aab-5efc-4bcf-87f8-eff57a6bf27f.jpg)

**Comment by paulrosen** [comment]
This seems to happen only when it is in the key signature. I'll research further.

**Comment by paulrosen** [comment]
Will be fixed in v6.1.8
