### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by j127** [paulrosen/abcjs#877]
I stumbled across this project today and was looking through the docs. On [the MIDI.js page](https://paulrosen.github.io/abcjs/upgrading/midijs.html#notes-for-version-5-8-0) where it says:

> See [Synth Documentation](https://paulrosen.github.io/abcjs/synth.html) for details.

the link to https://paulrosen.github.io/abcjs/synth.html appears to be broken.

**Comment by paulrosen** [comment]
Thanks! Will be fixed in the next version. In the meantime, the correct link is: https://paulrosen.github.io/abcjs/audio/synthesized-sound.html
