### ISSUE TITLE
Broken view

### ISSUE THREAD

**Issue by holden321** [paulrosen/abcjs#878]
Tried to display notes from MuseScore and got a broken look.

MuseScore => xml => xml2abc => abc => abcjs

MuseScore: http://joxi.net/V2VBGbDfd3j3q2
xml2abc: http://joxi.net/D2PD6zKIqKLKa2
abcjs: http://joxi.net/krDO7zLHKvDvwA

xml2abc: https://wim.vree.org/js/xml2abc-js.html
abcjs: https://paulrosen.github.io/abcjs/examples/editor.html

xml: https://pastebin.com/raw/FbBH7z6s
abc: https://pastebin.com/raw/508QGEWu

**Comment by paulrosen** [comment]
Can you post the ABC string that you used? I'll get to the bottom of this.

**Comment by paulrosen** [comment]
I see the abc string in your initial report now. Sorry I missed it before. The reason that the second voice is on two lines that there is a new line in the second voice. That is, the last two lines are:
```
 C,E,G,E, C,E,G,E, | D,F,B,F, C,E,G,E, |: F,A,CA, C,E,G,E, |1 D,F,A,F, C,E,G,E, :|2 %4
 D,F,A,F, [C,E,G,]4 |] %5
```
So 4 bars are on the first line and 1 bar is on the second line. If you remove that new line it will be on one line:
```
 C,E,G,E, C,E,G,E, | D,F,B,F, C,E,G,E, |: F,A,CA, C,E,G,E, |1 D,F,A,F, C,E,G,E, :|2 D,F,A,F, [C,E,G,]4 |] %5
```
