### ISSUE TITLE
Add new abc 2.2 (draft) decorations

### ISSUE THREAD

**Issue by marcustrp** [paulrosen/abcjs#880]
I noticed abcjs doesn't have support for the all new abc 2.2 (draft) decorations. The !^! and !marcato! seem to be supported if I read the abcjs code correctly, but not the rest. According to the abcnotation website:

6th Jul 2015: Decorations !^!, !marcato!, !D.C.alcoda!, !D.C.alfine!, !D.S.alcoda! and !D.S.alfine! have been [added]
16th Jul 2015: Decorations !editorial! and !courtesy! have been [added]

Would be nice to have support for these. One thing I'm currently working on is a library for calculation the form of tunes, would be nice to get al Coda and al Fine for that... Well, also con rep. and such things, but that's not part of the ABC spec, so...

By the way – big thanks for this excellent library!

**Comment by paulrosen** [comment]
Ok, I think I can at least get the first line in fairly quickly, and I'll push out a release for that.

**Comment by marcustrp** [comment]
Great, thanks!

**Comment by paulrosen** [comment]
What do you mean by "con rep. and such things"? If those are similar markings, they can be added.

As a workaround, you could add whatever you want using the `"^con rep."` notation. That will never be interpreted as meaningful, but it will appear on the music and you could look for it in your own code.

Notice that it uses double quotes plus the caret character `^`.

**Comment by marcustrp** [comment]
As far as I can see, it's not part of the abc spec., adding "senza rep" or "con rep" to D.C. or D.S. I've seen both "D.C. con rep al Fine" (between D.S./D.C. and "al...") and "D.C. al Fine con rep" (append to end).

I'll try the "^..." out, having some typescript errors after updating to latest npm version of abcjs, though, so got to look at that first.

**Comment by marcustrp** [comment]
Typescript errors fixed, just my project providing a class as first parameter to abcjs.Editor instead of string | HTMLElement.

Using the "^..." method places it above the D.C. statement, instead of after.

Also, the !D.S....! decorators seem to be left-aligned to start at the barline, and not taken into account when calculating the width of the rendering.

<img width="459" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/56577412/218713226-58774e04-286a-4509-80b2-6488d8aef6f9.png">

I'm no expert on all the possible ways of positioning a D.S., but I usually put it right-aligned with the barline.

**Comment by paulrosen** [comment]
Ok, I can put it right-aligned. Are there any other of these that should be right aligned? Perhaps all of the D.S. and D.C decorations?

For extensions to the standard, I guess it would be useful to have all of these:
```
D.C. con rep al Fine
D.C. al Fine con rep
D.S. con rep al Fine
D.S. al Fine con rep
D.C. senza rep al Fine
D.C. al Fine senza rep
D.S. senza rep al Fine
D.S. al Fine senza rep
```
Is that right? Or are only some of those actually legal?

I can add decorations beyond the standard. Anything that is not recognized by other software will just be harmlessly ignored.

**Comment by marcustrp** [comment]
Those seems fine, but I'll check some literature on the subject to see if there is a consensus on the precise order of the words.

**Comment by paulrosen** [comment]
The positioning of the DS is now right-aligned in version 6.2.0
