### ISSUE TITLE
Using drumIntro Fails to execute 'createBuffer' on 'BaseAudioContext': 

### ISSUE THREAD

**Issue by leocaseiro** [paulrosen/abcjs#883]
Hi there,

I've been trying to setup the metronome with my player, but I found 3 issues.

1) it only works if we set the metronome as part of the midiBuffer promise init (It doesn't work as part of the renderAbc).
eg:
```js
var midiBuffer = new abcjs.synth.CreateSynth();
    midiBuffer
      .init({
        visualObj: visualObj[0],
        millisecondsPerMeasure: 800
      })
      .then(function () {
        synthControl.setTune(visualObj[0], false, {
          // drumIntro: 1, // It shows a bug
          drum: "dddd 76 77 77 77 80 60 60 60"
        });
      });
```

2) The metronome doesn't play on rests, only on notes:

Eg:
```
z z z z | [Fg]g [cg]g [Fg][Fg] [cg]g | [Fg]g [cg]g [Fg]g [cg]g |
```

3) If I try to use the drumIntro, it fails showing the following error:

> Failed to execute 'createBuffer' on 'BaseAudioContext': The number of frames provided (0) is less than or equal to the minimum bound (0).

You can see my tests here on this codesandbox:
https://codesandbox.io/s/abcjs-drumintro-bugs-3834qg

**Comment by paulrosen** [comment]
I'm investigating, but one thing I notice right off is that you don't have a time signature, so the ABC string should contain `M:4/4`. That didn't fix it, though.

**Comment by paulrosen** [comment]
It is a bit finicky when there aren't complete measures. For one thing, it doesn't start the metronome until the first full measure (that is, it skips the pickup notes) so when I changed the last line to:

```
z2 z2 z2 z2 | [Fg]g [cg]g [Fg][Fg] [cg]g | [Fg]g [cg]g [Fg]g [cg]g |
```
It started immediately.

Also, you can put the metronome in the abc string if you'd like:
```
%%MIDI drum dddd 76 77 77 77 50 50 50 50
%%MIDI drumon
z2 z2 z2 z2 | [Fg]g [cg]g [Fg][Fg] [cg]g | [Fg]g [cg]g [Fg]g [cg]g |
```
but the way you're doing it should work.

**Comment by paulrosen** [comment]
I fixed the crash in `createBuffer` and it will be in version 6.1.9

**Comment by leocaseiro** [comment]
Thank you so much!!! You are awesome!
