### ISSUE TITLE
Feature Request: audio parameter for the "chords" instrument?

### ISSUE THREAD

**Issue by deusoz** [paulrosen/abcjs#888]
Feature request
How hard to get another parameter for the instrument used by "chords" I found it in the code and can have fun manually tweaking the value there,, so why not,, it would be a adding a nice and very substantial dimension to the playback prowess.

**Comment by paulrosen** [comment]
Is what you want to tweak covered by one of the `%%MIDI` commands described here? https://abcmidi.sourceforge.io/#gchord It's possible what you want to do has been described but isn't implemented yet.

In any case, can you describe a little bit more what you are trying to do? I'm not sure what stage of the sound production you are interested in. It could be during the mapping of what notes go where, it could be in the details of the volume or the length of the notes, or perhaps some other thing.

**Comment by deusoz** [comment]
wow, no, on the document, first time seeing that.  Do ANY of those MIDI functions work with your Javascript? 

AS for what I'm looking for. I can do better than describe it, I've already did my own "hack" .   There's a certain line in your javascript file that gives the voice of the chords.  I simply made that a variable.  LINE 11057
  var chordInstrument = ChordInsurgent; //herebe the chordinstrument
  var drumInstrument = 128;
  Then send it in as a global that defaults to 1, and can be set using 2nd parameter after "qp" 
 Here I've implemented from your examples the instrument switcher, the playback controls, with on/off for chords and a GET type parameter with CodeIgniter to supply the chord voice ... I just did this just now to answer your question, so there's no mention of it yet.
 This link plays my choice of bagpipe for this tune that can be changed with the instrument selector using the audio parameters, as well as chords on/off using audio params, by default with the Accoustic Piano playing chords
https://melodypedia.com/home/qp/91/
NOW here it uses the electric_piano_2  (program #5) but needs a complete page refresh; does not using audio params
https://melodypedia.com/home/qp/91/5

Request is to add an audio param for that line 11057 "chordInstrument"

**Comment by deusoz** [comment]
So now I have your javascript able to play my two select voices.  It's awesome! Incredible... 

HEY the next logical step... How to configure the playback so separate voices are assigned  to different synth programs? Haven't explored that one yet, but that's on my list.

**Comment by deusoz** [comment]
Hiya Paul,
   
   I'm very excited and have to tell you right away.. I fixed the grace notes midi playback.
   
   Grace notes.. even considering them to be up to 1/2 the size of the main note is way to big.. they hardly exist.. but the MAIN thing is they always come before the main note .. they should never push the main note off it's position forward . that was completely messing up playback for any passage with grace notes.
   
   So I was just tinkering around.. I removed the "shift" of the start main note to accomodate for the grace notes, and then reversed the way the start happens shifting the backwards instead fo forward and also reducing the lengths and with some cockamamie numbers, I just come up with stuff, not by formula but by guesswork, the main thing is it's 200% better now.. so  to see what I mean, check out this Bulgarian piece how it plays on my site now, and take the abc and drop into your player and compare...  
   
   I just have a non-minified version of the abc-basic on the site you can download, you can search "SSEDIT" for where I did stuff.. but ignore anything about trills, I have to fix those next,, I've just disabled them on this player, only pay attention to the grace note code changes, just a few lines and listen to the results... that "Tango Accordion" is one of my favorites with "dulcimer" doing the chords.  https://melodypedia.com/home/qp/19/15
   
  
    
   
  
   BEst regards,
   
  
   Stuart

**Comment by paulrosen** [comment]
Wow! That is amazing. It sounds great.

Grace notes vary in different styles of music so there probably needs to be a setting about how long the grace notes are and where they are placed.

**Comment by deusoz** [comment]
HI Paul, IMO, NO.... grace notes are grace notes, always come before the note is my experience.  I played violin off broadway  in NYC, 30+ years in professional Celtic and Italian folk music bands, volunteer orchestras doing classical music,  plus I am adept at Slavic, Greek and Middle Eastern folk styles.. for all of that there is no variation on duration or where grace notes belong.   Mordents, turns, trills, etc.. they extend beyond the beat, but a grace note should be complete BEFORE the beat... is my humble opinion.  I think I have it set quite well now,, maybe the grace notes could be just a smidjin longer, or a very tiny smidgin more set "back" in time.

**Comment by deusoz** [comment]
This here, is a classical piece with grace notes, and they almost sound like a slight trill, so this tells me they need to go back in time just a smidjin more as they are conflicting slightly with the main note.  https://melodypedia.com/home/qp/186
I'll look at that later and if I arrive at a better adjustment I will send you my code.

**Comment by deusoz** [comment]
HOWEVER,,, with Irish rolls, sometimes indicated with grace notes. .. those are NOT actual grace notes, it's just the best way we have to show what is happening.. With Celtic  music rolls the graces notes as they show in scores sometimes, more or less represents a slight "cut" in the sound using the notes lower and higher than pitch,, to achieve a triplet effect.. this comes from bagpipe technique as a bagpiper cannot "blow" a triplet, so he has to affect it with quick finger snap cuts,,.. so these are not normal grace notes,, but our best approximation of how it should sound.  https://melodypedia.com/home/qp/109

**Comment by deusoz** [comment]
that all being said however, I'm not testing on all possibilities,, not sure if that duration might go up to 1/2 of the note it precedes, I think that's what is happening,, however, a grace note should always be the equivalent of say a 1/32 note .. or less if lots of them

**Comment by paulrosen** [comment]
I think the original issue is resolved in 6.2.0. - `%%MIDI bassprog, %%MIDI bassvol, %%MIDI chordprog, %%MIDI chordvol` are now all implemented.
