### ISSUE TITLE
ABC Chords affected by WordPress Shortcodes?

### ISSUE THREAD

**Issue by iantresman** [paulrosen/abcjs#89]
Is this the correct behaviour when using the Wordpress plugin? On the bottom staff, the flat, sharp and d and e notes, are all correctly spaced. On the top two staffs, the d is appearing after the e, is that correct, and if so, how can I get the d note to display first without the gap?

```
[abcjs]
X:1
K:C
L:1/1
M:none
| [^d'_e'] |
| [^d_e] |
| [^D_E] |
[/abcjs]
```

Image: http://pasteboard.co/3RQcblSP2.jpg

I'm running Wordpress 4.7.3 with ABC Notation 3.0.1 using abcjs_basic_midi_3.0.1-min.js (I've also tried the current version abcjs_basic_midi_3.1.1-min.js)

**Comment by paulrosen** [comment]
That is a bug and it's still in the latest version. Interestingly enough, it only happens on whole notes, and only above B. I'll fix it soon and re-release the WP plugin.

**Comment by iantresman** [comment]
Thanks for confirming, looking forward to it.

**Comment by iantresman** [comment]
I'm also wonder whether the sharp symbol should come before the flat, as the notes are specified in that order, or does convention dictate otherwise?

**Comment by paulrosen** [comment]
I think that would look better. I'll change that, too.

**Comment by paulrosen** [comment]
I'm closing some old issues due to inactivity. I have this feature on my list to do when I have time.
