### ISSUE TITLE
Grace notes render oddly on Safari

### ISSUE THREAD

**Issue by seisiuneer** [paulrosen/abcjs#893]
When rendering grace note ornaments on Desktop Safari (Mac OS Monterey 12.5.1), (but not mobile Safari on iOS 16.1.2 on iPhone and iPad), grace notes are often rendered oddly.

Here's the test ABC:

X: 1
T: Muireann's
C: Niall Vallely
R: Jig
M: 6/8
L: 1/8
K: Bmin
|:dBA {d}BAB|def {f}ede|{e}f2e {ef}ede|faf ea/f/e|
dBA BAB|def {f}ede|fba fed|{e}f2e {f}edB:|
|:BAB {d}e3|{d}BAB {a}fef|Bba fed|{e}f2e {f}edB|
BAB {d}e2B|{d}BAB f3|baf a2b|fa/f/e {f}edB:|
|:BAF {G}E2G|{A}FDE FDE|FAA ABB|Bdd {f}edB|
{d}BAF {G}E2G|{A}FDE FDE|FAB def|1 ff/e/d {f}edB:|2 ff/e/d efg||
|:{a}fef b3/2b/b|{a}fef a3/2a/a|fba fed|{e}f2e {ef}ede|
fef b2f|f{f}ef a2(3e/f/a/|baf a2b|1 f/g/fe {ef}ede:|2 f/g/fe {f}edB|] 

Here's the result on Chrome, Firefox, and mobile Safari (iOS 16.1.2 on iPhone and iPad):

![image](https://user-images.githubusercontent.com/7969711/220985286-55ff02af-b8ab-4362-a73e-18ba3931c250.png)

and here's what I get on Safari (Mac OS Monterey 12.5.1):

![image](https://user-images.githubusercontent.com/7969711/220985580-691e403f-df99-41de-bd28-2a673273247b.png)

This is the only rendering issue I've encountered on Safari.

Again, thanks for an amazing library!

**Comment by paulrosen** [comment]
I'd love to track this down but I didn't reproduce it on Safari 16.1 on my macbook Ventura 13.0.

Is the above at a public URL that I can look at? There might be some weird interaction with your CSS or timing of your JS. That's just a shot in the dark but I can see if it happens on my computer with your code.

**Comment by seisiuneer** [comment]
Hi Paul,

I just tried it again this morning, and I can't recreate it.  It was like that for many days, but apparently something I've changed in my utility.  I'll re-submit an issue report if I can recreate it in the future.
