### ISSUE TITLE
Remark [r: ] raises errors in abcjs: Quick Editor

### ISSUE THREAD

**Issue by revad** [paulrosen/abcjs#894]
A remark may be put the middle of the tune according to the abc 2.1 standard section 2.2.5:
`DEF [r:and this is a remark] FED:|`

This raises several errors (4 per remark) and causes a brief pauses in the playback. 

The reason I want these is to mark where I have excised something.

**Comment by paulrosen** [comment]
Interesting - I was not aware of that syntax!

I will get that in the next version.

**Comment by paulrosen** [comment]
Fixed in 6.2.0
