### ISSUE TITLE
Adding SVG text

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#899]
This is probably just me not knowing how to work with SVG, but I'm trying to manually add author text after generating the notation rather than supplying it in the ABC. I'm getting little flat lines instead of text. If I go into the browser's html editor and just edit the svg a little, it sometimes shows up perfectly. Not sure what I'm missing...

using abcbasic v6.1.7

```
const svgns = "http://www.w3.org/2000/svg";
const newLinkSVG = document.createElementNS(svgns, "a");
newLinkSVG.setAttributeNS(svgns,"href","https://gospelriver.com");
const newTextSVG = document.createElementNS(svgns, "text");
newTextSVG.setAttributeNS(svgns,"stroke","none");
newTextSVG.setAttributeNS(svgns,"font-size","19");
newTextSVG.setAttributeNS(svgns,"text-anchor","start");
newTextSVG.setAttributeNS(svgns,"x","0");
newTextSVG.setAttributeNS(svgns,"y","58");
newTextSVG.setAttributeNS(svgns,"font-style","italic");
newTextSVG.setAttributeNS(svgns,"height","50");
newTextSVG.setAttributeNS(svgns,'font-family','Times New Roman');
newTextSVG.setAttributeNS(svgns,"class","abcjs-meta-top abcjs-composer");
newTextSVG.textContent = ("text"); 
newLinkSVG.appendChild(newTextSVG);
$('#insertNotationHereABC svg text.abcjs-composer').parent().append(newLinkSVG);
```

**Comment by nbruley** [comment]
This is what it looks like: 
![image](https://user-images.githubusercontent.com/1113368/224578448-b7eed384-daa9-41c7-ba8a-e6e35d8419a2.png)

If I change the font size within the browser after it is rendered, it shows fine.

![image](https://user-images.githubusercontent.com/1113368/224578520-0dba6831-026b-4bb8-a6b5-a802e7f29ab2.png)

**Comment by samuelbradshaw** [comment]
This doesn't directly solve your problem – but since you're rendering it on a web page, it may be easier to use HTML for the text above and below the music notation. SVG handles various types of text, but it's not as flexible as HTML.

**Comment by nbruley** [comment]
Thanks-- the difficulty is positioning the text in the proper location when the location is over SVG. I could use margin CSS or something to try to hack it but there are so many variables to try to get it positioned in exactly the right spot when the SVG behind it is changing. If all else fails I may have to insert the text manually using the ABC file itself but then not sure I can create a link... I could position it below or above the SVG in a nonstandard position, but was hoping to not have to do that.

**Comment by paulrosen** [comment]
I might be able to debug it if I saw the actual webpage. I have a couple stabs in the dark:
1) have you tried doing all the styling with css instead?
2) what if you put the text in the ABC file with `R:text`? I think that will put the item on the page where you are indicating. You can then target the element with the class `abcjs-rhythm`.
3) I guess you want this to be a link element. You might need to use `foreignObject`. So, after drawing, search for the element with `abcjs-rhythm` and replace it with a foreignObject that contains your link.

**Comment by nbruley** [comment]
Well, I certainly can't expect you to debug my code for me, but I did reproduce the issue at my test playback page [here]:(https://gospelriver.com/play_abc/)

1. I don't really think it's a CSS thing... maybe I'm not understanding.
2. I could do that, although we have almost 1000 ABC files to do that with, and I'm not sure that the link would work doing it that way... maybe it would.
3. I tried foreignObject instead of text but must be doing something wrong because I didn't even get the horizontal lines that way.

**Comment by paulrosen** [comment]
That is baffling. I'm not sure, but it looks like a purely SVG problem. I do see the lines you are talking about. 

I switched the `text` and `a` elements and it showed up:
```
<text stroke="none" font-size="19" text-anchor="start" x="0" y="58" font-style="italic" height="50" font-family="Times New Roman" class="abcjs-meta-top abcjs-composer"><a href="https://gospelriver.com">text</a></text>
```
But I'm not sure that is the correct solution.

You could append the link to the `<div>` that the music is drawn into, instead. Add `position:relative` to that and use:
```
<a href="https://gospelriver.com" style="
    position: absolute;
    left: 15px;
    top: 100px;
">text</a>
```
For positioning, that is tricky. That's why I was suggesting using the `R:` line so that it would get positioned for you, but I see how that would be hard with so many files. You could hack that line in just before drawing it, though.

**Comment by nbruley** [comment]
Thank you for looking into this. I agree it's pretty baffling, and likely an SVG thing. I changed around the <a> to be under the text and got the same issue as before, so not sure how you managed that. I also tried using existing text and using 
```
$('#insertNotationHereABC svg text.abcjs-composer').html(newLinkSVG);
```
to replace it and the text shows up fine, but the link doesn't work.

Given SVG is giving such difficulty, HTML would certainly be easier... though I have some fancy zoom stuff going on in the actual implementation so we will see how that goes. At least I know it's not just me.

**Comment by nbruley** [comment]
I tried alignment-baseline to no avail also, but good thought. The lines do reside at the very top of the svg like you say. My guess is it would work if you did it because you're not trying to change the svg after creation. I think my problem is I'm trying to modify it after it has already been generated, and I need some way to refresh it or something... Not quite sure. I will keep playing with it.

**Comment by samuelbradshaw** [comment]
You could try adding a `dy` attribute to the text element:
newTextSVG.setAttributeNS(svgns,"dy","58");

I'm not sure exactly what the difference is between `y` and `dy`, but that seems to make it visible in my browser.

The link isn't clickable, though. I'm not sure why (I'm not very familiar with links in SVG).

**Comment by nbruley** [comment]
Unfortunately dy doesn't do it either for me. If you're making changes in the browser's editor, it will appear that changes fix the issue, but in reality I think it only works because the change forces the page to redraw the svg. I think since I'm adding a new element to an existing svg with javascript, it's still not showing me the element, even though the exact same code works when a change is made via the browser.

**Comment by samuelbradshaw** [comment]
Could you force the SVG to redraw by setting
`document.getElementById('paper0').innerHTML = '';`
then
`document.getElementById('paper0').innerHTML = document.getElementById('paper0').innerHTML;`
?

**Comment by samuelbradshaw** [comment]
Possibly also helpful:
https://stackoverflow.com/questions/3642035/jquerys-append-not-working-with-svg-element

**Comment by nbruley** [comment]
YES!!  This works
```
document.getElementById("paper0").innerHTML += "";
```

I think that just may get me to where I want to be, thank you :)

**Comment by paulrosen** [comment]
I guess this is resolved - I created an issue for myself to natively support the `<a>` tag in the information fields, so that might eventually be built in.
