### ISSUE TITLE
Ghost note for grouped note, but only one should be showed ghosted

### ISSUE THREAD

**Issue by airdev-web** [paulrosen/abcjs#903]
Hi @paulrosen,

Hope you're doing well :)

Again with my drum notation editor : I would like, in a group of multiple notes (eg. `[gcF]`) make only one to be ghosted, maybe the `g`.
So I note it like that : `"<("">)"[gcF]` but all the note are then considered as ghosted and I can't separate and know which note should be quieter in the sound render.

I tough maybe write it like that `["<("">)"gcF]` but then it's not working in the render :
![image](https://user-images.githubusercontent.com/85546423/226751956-3fdefb00-2cd8-4d88-92d1-e361915e63b1.png)

Also, when ghosting a group of note, the visualisation in the notation `( ... )` is going in the average height of the note, and indeed, does not apply on the select note I desire.
![image](https://user-images.githubusercontent.com/85546423/226752211-5171e40f-4c3e-4945-bd9b-44de5eb927bf.png)

What do you think I should to to properly select only one (or two, or more...) ghost note of a note group ?

Thanks in advance!
Wish you the best

**Comment by paulrosen** [comment]
This isn't well supported, but there is a hack - you can put the annotations wherever you want with this notation:
```
"@-10,15(""@10,15)"[gcF]
```
you just have to experiment to figure out what works.

**Comment by airdev-web** [comment]
Niiiiice, it become to be messy... but whatever, nice hack! 👍 

![image](https://user-images.githubusercontent.com/85546423/227747033-4fca504e-e9a0-431c-8692-0e9810d123fc.png)

**Comment by paulrosen** [comment]
I'm glad that helped. You can also add `y` in places to give the music a little more room like `c/yc/` at the end of the first measure.
