### ISSUE TITLE
Tablatures break with multiple parts in one voice

### ISSUE THREAD

**Issue by DennisCiba** [paulrosen/abcjs#911]
Hi,

it seems that rendering tablatures when there are multiple parts in one voice (using the `&` syntax) is broken.

For instance this short piece

```abc
X:1
T:Guitar Tablatures
M:3/8
L:1/8
K:Cm
C3 & xEc |]
```

produces this result when rendered with tablatures:

![localhost_5173_ (1)](https://user-images.githubusercontent.com/73284509/231889872-11ba36c3-ea8a-4590-a8af-094ddd757b09.png)

For comparison, this is how it looks with just one part:

```abc
X:1
T:Guitar Tablatures
M:3/8
L:1/8
K:Cm
CEc |]
```

![localhost_5173_ (2)](https://user-images.githubusercontent.com/73284509/231890138-cfda93bf-c46f-48d8-8c2b-7fc6972224d4.png)

**Comment by paulrosen** [comment]
I'm not able to reproduce this. I also tried it here: http://michaeleskin.com/abctools/abctools.html and it looks ok.

Do you have a publicly accessible URL where this happens? I can debug it from there.

Thanks for the report

**Comment by paulrosen** [comment]
closed for inactivity. If this is still a problem, let me know and I'll reopen.
