### ISSUE TITLE
Support Mandolin tablature

### ISSUE THREAD

**Issue by SimplGy** [paulrosen/abcjs#912]
Nothing fancy, just since ABC is commonly used for traditional music, maybe make it point to the violin setup. (consider: "fiddle" also?)

**Comment by paulrosen** [comment]
That sounds like a good idea, but I think we can just declare "mandolin" and "fiddle" as synonyms for "violin". I think I can do that with just a couple lines of code.

**Comment by SimplGy** [comment]
Ah, great! I was trying to figure out how to do it as a synonym but couldn't quite see it. I'll keep my eyes peeled for your change.

**Comment by paulrosen** [comment]
In version 6.2.2
