### ISSUE TITLE
Tablature repeats the same note, although actual note changes

### ISSUE THREAD

**Issue by SimplGy** [paulrosen/abcjs#914]
Could be a music theory thing I'm not getting, but I did some script to generate a Gm blues scale, and it annotates `c ^c` as tab stop 4 and 4 on the 3rd mandolin/violin string, rather than tab stop 3 and 4.

Minimal repro:

```music-abc
{ "tablature": [{ "instrument": "violin" }] }
---
K:Gm
^C D F G ^A c ^c d
```
```
          1 4  4 5
```

It is "fixed" if you remove the first `^C` from this sequence

My observation:

![image](https://user-images.githubusercontent.com/548809/232349307-e458e254-fe10-44ff-996f-3330f160d713.png)
(note the double "4"s near the end)

**Comment by paulrosen** [comment]
A sharp stays in effect for the rest of the measure that it is in. So to get the C natural you need to use the natural symbol. It would look like this:
```
^C D F G ^A =c ^c d
```

**Comment by SimplGy** [comment]
Ah, I see, sorry about that, and thanks so much for the answer. this is then a limitation with the [scale generation](http://jsfiddle.net/markheath/uL26wvmy/) jsfiddle I was playing with.
