### ISSUE TITLE
TS type for MidiBuffer does not contain property `isRunning`

### ISSUE THREAD

**Issue by SimplGy** [paulrosen/abcjs#915]
[LOC reference](https://github.com/paulrosen/abcjs/blob/da2e9eb529d4fb0462b95fdc26dfb58401df528c/types/index.d.ts#L1143)

Runtime contains `isRunning: boolean`, looks useful for a toggle play feature. Probably I'm doing it wrong, but the AudioContext keeps in state 'running' even though the midiBuffer is stopped.

**Comment by paulrosen** [comment]
AudioContext state is a separate thing - that refers to whether the browser will allow audio.

The isRunning variable would be useful - but I'd rather expose a function. That was intended to be a private variable to the class and I wouldn't want external code writing to it.
