### ISSUE TITLE
Play Multiple Instruments Simultaneously

### ISSUE THREAD

**Issue by iRambax** [paulrosen/abcjs#919]
Hello! Thank you for this great library. I'm wondering if the synth player supports playing multiple instruments simultaneously? Currently, when I add the "%%MIDI program" directive for each voice, only one voice seems to be played at a time. Is there a way to have multiple voices playing together using different instruments? e.g. in the following notation it plays both voices with violin

X:1
T: Multiple instruments
L:1/4
Q:1/4=120
M:4/4
K:D
%%MIDI program 0
%%MIDI program 40
V:1 name="Piano" clef=treble
V:2 name="Violin" clef=treble
[V: 1] DEFG|
[V: 2] gfed|

Thank you!

**Comment by paulrosen** [comment]
You can rearrange the ABC so that the parts are all in a row instead of interweaving them. So, for instance, in your example it would look like this:
```
X:1
T: Multiple instruments
L:1/4
Q:1/4=120
M:4/4
V:1 name="Piano" clef=treble
V:2 name="Violin" clef=treble
K:D
V: 1
%%MIDI program 0
DEFG|
DEFG|
DEFG|
V: 2
%%MIDI program 40
gfed|
gfed|
gfed|
```

**Comment by iRambax** [comment]
Wow, thank you so much. Such a fantastic library!
