### ISSUE TITLE
Audio is not supported in Java webview☹

### ISSUE THREAD

**Issue by watersoft123** [paulrosen/abcjs#925]
I use java webview to open the web page [https://www.abcjs.net/], it show error:"Audio is not supported in this browser". I want webview to load the audio component separately to solve the problem,so I want to know which audio libraries need to be loaded?
![1](https://github.com/paulrosen/abcjs/assets/57562864/87225c69-219c-4514-821a-9f0b6cde64af)

**Comment by paulrosen** [comment]
It is looking for AudioContext. The browser needs to support the following:

```
ac = new AudioContext()
ac.resume()
```
I don't know if there is a permission thing that can be set in webview or not.

**Comment by watersoft123** [comment]
> It is looking for AudioContext. The browser needs to support the following:
> 
> ```
> ac = new AudioContext()
> ac.resume()
> ```
> 
> I don't know if there is a permission thing that can be set in webview or not.

Thanks, I did some digging and found that javafx's webview doesn't seem to support AudioContext.
