### ISSUE TITLE
abcElem.midiPitches in ClickListener function is "undefined" 

### ISSUE THREAD

**Issue by AppleIsCute** [paulrosen/abcjs#928]
Hi! Thank you for making this extremely helpful library ! I'm currently making a web app for displaying score for teaching purpose. 
I have encounter a problem that when I want to know the exact midi pitches of the clicked note on the staff (sometimes multiple notes if its a chord), so I call the clickListener function, but the "abcElem.midiPitches" value shows "undefined" when printed out in console.log(), calliing "abcElem.midiGraceNotePitches" shows also "undefined".

Here is my code:  
 ```js
function clickListener(abcElem, tuneNumber, classes, analysis, drag, mouseEvent) {console.log(abcElem.midiPitches);}
ABCJS.renderAbc("target", abcString, {
               clickListener: clickListener,
		staffwidth: 760,
		minSpacing: 2, maxSpacing: 2 , preferredMeasuresPerLine: 2,
		selectionColor: "blue",
}); 
```

I tried printing the whole "abcElem", those two Params are also nowhere seen:

Are these params deprecated or am I using it wrong ? If they are  deprecated, is there another way to get the midi pitches of the clickd notes in this lib ?

**Comment by EvanPartidas** [comment]
I believe midi pitches aren't available until you use synthesizers. However, you can access pitches via the `pitches` array on `abcElem`. I'm not sure how it was intended to be used but C4 = 0, D4 = 1, E4 = 2, D5=8, etc. You can check whether it's flat or sharp under the `accidental` member of each member in the pitches array.

**Comment by AppleIsCute** [comment]
Hi, Evan, thanks for answering ! I've tried the method that you suggested, it works and is close to what I'm looking for.
However, this method seems to only return one single note at a time, so when I'm clicking on a chord, it only returns the value of the root note, even when clicking on other notes of the chord, it still returns the root note.  The ``abcElem.midiPitches`` seems able to return multiple notes at once.

**Comment by paulrosen** [comment]
You don't have to use the synthesizer - just call the set up for it. You can do this:
```
const visualObj = ABCJS.renderAbc(etc...)
visualObj[0].setUpAudio()
```
Unfortunately, that won't tell you which note of the chord was clicked on, but it will give you all the midi pitches. 

I'll investigate a little more to see if you can tell the actual note head that was clicked. That's probably a bit complicated and hacky.

**Comment by paulrosen** [comment]
Look at `analysis.clickedName`. There is still a little work to do: For instance, if you have `[Bdb]` in the key of Bb and the user clicks on the lower B note, you might get the following in `midiPitches`:
```
[
{"cmd":"note","pitch":70,"volume":75,"start":10.588237,"duration":0.5,"instrument":0,"startChar":525,"endChar":539,"gap":0},
{"cmd":"note","pitch":74,"volume":75,"start":10.588237,"duration":0.5,"instrument":0,"startChar":525,"endChar":539,"gap":0},
{"cmd":"note","pitch":82,"volume":75,"start":10.588237,"duration":0.5,"instrument":0,"startChar":525,"endChar":539,"gap":0}
]
```
and `B` in clicked name. You would have to know that B could be anywhere from 69 (__B) to 73 (^^B). Therefore 70 is a possibility.

**Comment by AppleIsCute** [comment]
Thanks for answering, I'll try !
