### ISSUE TITLE
How to set Cursor in the mode of Interactive Editor?

### ISSUE THREAD

**Issue by watersoft123** [paulrosen/abcjs#930]
In the example of editor-synth.html,I want  Cursor to follow the playback like In the example of full-synth.html. In the documentation about Interactive Editor,I see cursorControl is the property of Synth,I tried but couldn't work.
![Snipaste_2023-07-27_16-47-12](https://github.com/paulrosen/abcjs/assets/57562864/1ddbf6bb-b164-4c3c-b93b-f720f5980afe)

**Comment by watersoft123** [comment]
Refer to abcjs-editor wrote by Paul in Github, basically solved this problem, but it is still not good enough, I sincerely hope Paul can add this feature in the example of editor-synth.html. Thank you very much!

**Comment by watersoft123** [comment]
In addition, I have another problem. How do I set  AudioParams when using interactive Editor? 
For example, AudioParams = {chordsOff: true, voicesOff: [1,2,3]}; 
Where do I put it?

**Comment by paulrosen** [comment]
For the cursor, I'm not sure what you need. The parameter that you point refers to a callback that gets called for various events when playing back. It is your responsibility to draw whatever you want then. One example is in the abcjs-editor code and that's all I've ever needed.

For the second, your example already shows the `options` attribute, and that's where it goes. If you mean, how to change them on the fly, you can call `abcjsEditor.synthParamChanged(options)` at any time.

**Comment by watersoft123** [comment]
> For the cursor, I'm not sure what you need. The parameter that you point refers to a callback that gets called for various events when playing back. It is your responsibility to draw whatever you want then. One example is in the abcjs-editor code and that's all I've ever needed.
> 
> For the second, your example already shows the `options` attribute, and that's where it goes. If you mean, how to change them on the fly, you can call `abcjsEditor.synthParamChanged(options)` at any time.

Now it works,the cursor issue is also resolved.Thank you very much! Paul.
