### ISSUE TITLE
Bass support in tablature

### ISSUE THREAD

**Issue by Kadweirdo** [paulrosen/abcjs#934]
Hi Paul,

It would be wonderful if tablature would also support bass guitar. The [documentation](https://paulrosen.github.io/abcjs/visual/tablature.html) currently only mentions support for violin, mandolin, fiddle and guitar.

I've tried using guitar tab, including the tuning option, but any note below E (open string) just gets rendered as a question mark.

For reference, I'm trying to write out a 5-string bass part tuned BEADG (BBB, EE, AA, D, G).

Here's a small example with some notes that fall within and out of the range: 
![afbeelding](https://github.com/paulrosen/abcjs/assets/53981502/f0c27e4b-ac7e-4732-a5fb-0cd9c5dc7685)

**Comment by brLuther** [comment]
Taking advantage of the issue of Tablature for Bass.

I made a bass tablature and the positions that were left as notes turned out to be very bad shape.

Is it possible to determine the shape of the scale, to improve in these cases?

**Comment by Kadweirdo** [comment]
Adding extra commas did resolve the issue. It is surprising since now all strings are tuned one octave too low, at least when comparing to Wikipedia and a few other sources. For example, the E string on a bass guitar is "E1" or "E,", but in the tab it is now denotated as "E,,". 

Anyway, the feature now works - thanks for your help!

```music-abc
{
  "tablature": [{
	  "instrument": "guitar",
	  "tuning": ["B,,,", "E,,", "A,,", "D,", "G,"]
  }]
}
---
X:1
T:Example
C:Example
L:1/8
Q:1/4=88
M:4/4
K:A
V:1 bass nm="5-str. Electric Bass"
V:1
|:$"^Chorus" F,,F,,C, F,2 E, F,/E,/C, | F,,F,,C, F,2 E,C,B,, | %16
 A,, A,,2 z/4 !slide!F,-F,3/4 E,2 C, | A,, A,,2 C,2 D,2 ^D, |$ E, E,2 z/4 !slide!B,-B,3/4 A,2 E, | %19
 ^E, E,2 z/4 !slide!B,-B,3/4 A,2 E, | F,F,C F2 E/ z3/4{/E} F/4E/C | F,F,C F2 E^EF :|$ %22
```
