### ISSUE TITLE
Tonality changes do not render properly

### ISSUE THREAD

**Issue by francoisschwarzentruber** [paulrosen/abcjs#939]
Thank you for the work! abcjs is really great project. The inline instruction `[K:G]` renders perfectly. You see "#" appearing on the staff. But `[K:F#]` does not do anything; same for `[K:C#]`. Am I doing something wrong?

**Comment by paulrosen** [comment]
It is working for me. If you are still having problems, paste a complete example. This is what I did:
```
X: 1
T: The Kesh
M: 6/8
L: 1/8
K: G
|:GAG GAB|ABA ABd| [K:F#]edd gdd|edB dBA|
```
