### ISSUE TITLE
Half-accidentals

### ISSUE THREAD

**Issue by francoisschwarzentruber** [paulrosen/abcjs#940]
`\^G` or `\_G`(half-accidentals) render as `^G` or `_G`. What about adding the rendering of half-accidentals?

**Comment by paulrosen** [comment]
The syntax I'm using is this:
```
^/G   _/G
```
That is, a forward slash after the accidental.

**Comment by francoisschwarzentruber** [comment]
Thank you! 
PS: Actually, I do not remember where I found the notations `\^G` etc. probably in some documentation, but I can find it again.
