### ISSUE TITLE
renderABC modifies the title of the HTML page

### ISSUE THREAD

**Issue by francoisschwarzentruber** [paulrosen/abcjs#943]
`renderABC` has a side effect: it modifies the title of the HTML page in `Sheet music`. How do we avoid that?

**Comment by paulrosen** [comment]
I'm not sure what you mean. Do you mean the `<head><title>etc..</title></head>` part of the page? It doesn't modify that, so I'd need to see an example if you are seeing that.

**Comment by francoisschwarzentruber** [comment]
I am actually using abc.js in https://francoisschwarzentruber.github.io/abcd/ and it is changing the title of my webpage. Btw, abcd is a proposal for a more easier language to describe music (see https://www.youtube.com/watch?v=LbuEGCJSX0U) It uses abc.js because abcd is compiled into abc notation.

I think it is the function `renderAbc` that is changing the title using the title given in the abc code.

**Comment by paulrosen** [comment]
Interesting. You are missing `<title>` attribute in the head and I guess the browser is looking for the first `<title>` in the body. That is there for accessibility. Can you add the attribute to the head?

**Comment by francoisschwarzentruber** [comment]
Thank you! You are right. It works properly now.
