### ISSUE TITLE
"startingMeter is undefined" for a sheet with metadata only

### ISSUE THREAD

**Issue by Schnark** [paulrosen/abcjs#95]
Steps to reproduce:
1. Go to https://abcjs.net/abcjs-editor.html
2. Select all the notes (i.e. everything after the line `K: Emin`) and delete them.

Expected result:
The title and an empty staff (with clef, meter, and key) should be shown.
Or, at least, no JS error should occur.

Actual result:
A JS error is shown in the console: `TypeError: startingMeter is undefined`
Adding the notes back again will not make them show up again in the rendered sheet.

**Comment by tchandelle** [comment]
I think it's already solved by 62fe7da3b2e3104a1f8f965a1dd8086568580351, but it's yet to be released in v4.

**Comment by Schnark** [comment]
I manually cherry-picked that commit into my project where I first encountered this issue, and can confirm that this indeed fixes the problem.
