### ISSUE TITLE
Navigable Data Structure Accessible?

### ISSUE THREAD

**Issue by jkanel** [paulrosen/abcjs#952]
Is there a method to get a navigable data structure interpreted from ABC notation, e.g., XML or JSON?  I'm hoping that some sort of data structure is generated prior to rendering.

My goal is to do feature engineering on ABC in order to predict chords and access to this information would help immensely.

Thank you,
Jeff K.

**Comment by paulrosen** [comment]
Yes, you can get a lot of info here:
```
const visualObj = abcjs.renderAbc(...)
```
More info will be added to the above by then doing:
```
visualObj[0].setUpAudio({})
```
WARNING: The info in that object is pretty stable but it isn't guaranteed to be exactly the same from release to release. I use it in some of my apps without problem.

You'll have to explore the object to see what's in it, but basically look at `visualObj[0].lines` for all the note info. After calling `setUpAudio` there will be an attribute `midiPitches` that is probably useful.

If you want to just parse but not display music, use `"*"` as the element to print to and it will skip the printing part.

**Comment by jkanel** [comment]
Thank you!
