### ISSUE TITLE
Create blank staves?

### ISSUE THREAD

**Issue by abalter** [paulrosen/abcjs#956]
Is there a way I could trick absjs into printing a staff that has no notes in it? For instance, have the melody and a blank staff below to type in harmony by hand. Like with a pencil :)

**Comment by paulrosen** [comment]
Use `%%stretchlast` in the header, then have a line that just contains:
```
y
```

**Comment by abalter** [comment]
Awesome! Thank you!

![image](https://github.com/paulrosen/abcjs/assets/5349876/f11bde8b-3824-4cdb-9956-9f262dbc0324)
