### ISSUE TITLE
Which events of renderMidi method?

### ISSUE THREAD

**Issue by hoanvo** [paulrosen/abcjs#96]
I'm using renderMidi to play the sheetmusic, and the animation will active base on that renderMidi. So, I want to know the events of renderMidi's status, such as: start, finish.... Can anyone helps me? Thank you alot!

**Comment by paulrosen** [comment]
The best thing to do is to create a callback and console.log the parameters that are passed to you. Note that I'm in the process of expanding the info sent to the call. I don't know when that will be released. If it turns out that there is info that you would like returned let me know.

**Comment by hoanvo** [comment]
Thanks Paulrosen. I hope you will release soon. I ask that question because the cursor is mismatched while playing midi, and the cursor don't repeat when it meet the repeat sign. I don't know how to control the the cursor, I think if there events from renderMidi, maybe I can have a good solution.

**Comment by paulrosen** [comment]
There is now an example here: https://github.com/paulrosen/vue-abcjs-midi-demo
