### ISSUE TITLE
Receiving "strict-origin-when-cross-origin" when i am trying to fetch music of the node from the api

### ISSUE THREAD

**Issue by muzakkirHussain** [paulrosen/abcjs#964]
When i am requesting this api " https://paulrosen.github.io/midi-js-soundfonts/FluidR3_GM/acoustic_grand_piano-mp3/A1.mp3" i am receiving "strict-origin-when-cross-origin" 404 and i am using abcjs 6.2.3 version

**Comment by paulrosen** [comment]
I am not seeing that. Do you have a public URL that shows the problem?

**Comment by paulrosen** [comment]
Closed for inactivity - if this is still a problem I'll reopen.
