### ISSUE TITLE
Feature request: display abc text on demand

### ISSUE THREAD

**Issue by cbfiddle** [paulrosen/abcjs#97]
It would be useful to be able to display the abc notation without the abc text but still give the user the option to see the abc text. I imagine the UI being similar to the current "show" link that is used when there are more tunes than the auto render threshold. I don't have a strong preference regarding how the abc text is displayed, as long as the user is able to copy the text to the clipboard.

**Comment by paulrosen** [comment]
Which version of the library are you using? Basic, Editor, or Plugin?

**Comment by cbfiddle** [comment]
Sorry… I’m using the plugin.

**Comment by paulrosen** [comment]
If I understand you correctly, you can place this right after including the plugin js file:
```
<script type="text/javascript">
  ABCJS.plugin.hide_abc = false;
</script>
```

**Comment by cbfiddle** [comment]
I guess I am not being clear. I want a web page to initially display all of the tunes in the page without the abc text showing. But for each tune, I want some sort of visible control (e.g. button) that the user can click to reveal the abc text for that tune (and to click again to hide the abc text). I'm talking about the user looking at the web page, not a web page author.

**Comment by paulrosen** [comment]
Oh, sorry - that isn't built in. It does seem like a useful feature. I don't have a timetable for when I'd get to it, though.

**Comment by paulrosen** [comment]
I'm closing some old issues due to inactivity. I have this feature on my list to do when I have time.
