### ISSUE TITLE
ABC Notation Wordpress plugin: add Midi player?

### ISSUE THREAD

**Issue by iantresman** [paulrosen/abcjs#98]
I don't think I can just enable it, but it would be nice if I can optionally display a media Midi player after the score.

**Comment by paulrosen** [comment]
To create a midi version, use the following shortcode:
`
[abcjs-midi]
`
You will need to repeat the same ABC string inside that shortcode.

The hard part is that you will have to add the `soundfont` folder to the top level of your WordPress installation.
