### ISSUE TITLE
Adjust the tempo compared to the ABC

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#982]
I searched through the various requests relating to tempo and documentation but I wasn't able to find how to change the tempo (in the latest version) on the fly. I would like to create a "fast" and "slow" tempo selection and adjust the setting in the ABC by a percentage.  Can I do it in here somewhere?

``
audioContext.resume().then(function () {  
createSynth = new ABCJS.synth.CreateSynth();
return createSynth.init({
	visualObj: visualObj,
	audioContext: audioContext,
	options: {
		chordsOff: true,
		soundFontUrl: "soundfont/FluidR3-GM/",
		soundFontVolumeMultiplier: soundFontVolumeMultiplierToUse,
		midiTranspose: transposeAmount,
		fadeLength: 400,
		millisecondsPerMeasure: visualObj.millisecondsPerMeasure(),
		program: musicProgramNumberToUse 
	}
}).then(function (response) {
	return createSynth.prime();
}).then(function () {
	createSynth.start();
	timer.start();
	return Promise.resolve();
}).catch(function (error) {
	if (error.status === "NotSupported") {
		alertOK(translate("Audio not supported","text"),translate("OK","text"));
	} else
		console.warn("synth error", error);
});
});
} else {
alertOK(translate("Audio not supported","text"),translate("OK","text"));
};
``

**Comment by paulrosen** [comment]
No, you can't change it on the fly - I create the entire buffer in advance so it will use the tempo at the point of creation. However, I've done that to good effect (at least for pieces that are under a minute in length).

In code, when the user requests a tempo change, pause the playback and record the paused position (in percentage). Then create the new buffer and start it at that paused position. In my experience that is fast enough to not be annoying for the user.

**Comment by nbruley** [comment]
That's fine, I guess I didn't really mean "on the fly" but just a setting to change the tempo without using the player. What code do I use for that?

**Comment by paulrosen** [comment]
This is untested, but I think something like:
```
const pauseTime = createSynth.pause()
const pausePercent = pauseTime / createSynth.duration
// then recreate the synth at the new tempo - just like above
createSynth.seek(pausePercent, "percent")
```

**Comment by nbruley** [comment]
Thank you... I may use this also, but I'm actually looking for the code for how to play at a different tempo than what is given in the ABC... how do I recreate the synth at the new tempo? I've been using the tempo within the ABC. Or do I have to alter the ABC instead of having some sort of tempo alteration like what is provided in the built-in ABC player?

**Comment by nbruley** [comment]
It shouldn't be difficult to parse the ABC and change the Q value to a percentage of what it was, so I will plan to just do that...

**Comment by paulrosen** [comment]
I forgot this was there: [`setWarp(percent)`](https://paulrosen.github.io/abcjs/audio/synthesized-sound.html#setwarp-percent). That might do what you want.

**Comment by nbruley** [comment]
Sorry, I should have mentioned that function as seen here
https://github.com/paulrosen/abcjs/issues/585
but I don't know how to use it. For example, this returns an error TypeError: ABCJS.synth.setWarp is not a function
```
createSynth = new ABCJS.synth.CreateSynth();
ABCJS.synth.setWarp(50);
```

**Comment by paulrosen** [comment]
That's true. Sorry.

Does the following work?
```
createSynth.init({ millisecondsPerMeasure: 1000, etc... })
```

**Comment by nbruley** [comment]
I have the same issue as is mentioned at https://github.com/paulrosen/abcjs/issues/598 - nothing changes when I change that setting.

**Comment by nbruley** [comment]
Something like this seems to be working for me:
```
var tempoPercent = 120;
var ABCTempo = TuneABC.match(/Q:([\S]*)=([0-9]{1,4})/i,"$2")[2];
var newTempo = ABCTempo*tempoPercent/100;
TuneABC = TuneABC.replace(/Q:([\S]*)=([0-9]{1,4})/i,"Q:$1="+newTempo); //change the tempo
```
