### ISSUE TITLE
slur direction

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#988]
Though I'm not a music theory expert, it would seem to me that the slur here would be better going up.
![image](https://github.com/paulrosen/abcjs/assets/1113368/c61e9e1d-90fc-4508-b9fa-4cbabe4637c1)
Is there a way to do that?
One ABC reference seems to indicate that an apostrophe can be used to force the direction, but that doesn't work...
('EFG)
I'm using abcjs-basic v6.2.2

**Comment by paulrosen** [comment]
I think, according to Gould, the slur is in the right direction but it should be outside the beam. The rules are complicated, which is why you are finding a lot of odd cases. If I can fix this particular case quickly I'll squeeze it into the next minor release.

**Comment by nbruley** [comment]
Would love to have the slur placement fixed as it will make our scores look much better; I recognize the programming for that is likely quite complicated.

**Comment by nbruley** [comment]
Thank you so much! It is certainly improved. 

I know you didn't anticipate that it would solve all issues, but just a few comments:

1. Is there a way for me to space out the staves more so the words are not covered?
![image](https://github.com/paulrosen/abcjs/assets/1113368/57fa5879-6db8-47a6-bf9a-0b7fcff98145)

2. I don't understand why there would be a difference in the placement here...
![image](https://github.com/paulrosen/abcjs/assets/1113368/3e38bbb0-4bbd-4eda-8901-1e17922c28aa)

```
%%abc-charset utf-8

X:1
T:Knecht
T:7.6.7.6
C:Justin Heinrich Knecht(1791)
L:1/8
M:4/4
Q:1/4=100
K:D
%%score (S A) (T B)
V:S clef=treble middle=B stem=up
V:A clef=treble middle=B stem=down
V:T clef=bass,, stem=up
V:B clef=bass,, stem=down
[V:S]D2|D2 (CD) E2 E2| E2 D4||
F2|F2 (EF) G2 E2|C6||
D2|D2 E2 E2 F2|G2 B4||
B2|A2 F2 E2 E2|D6|]
[V:A]A,2|A,2 (A,A,) C2 C2| C2 A,4||
D2|D2 (C=C) B,2 B,2|A,6||
A,2|A,2 C2 C2 =C2|B,2 D4||
G2|F2 D2 C2 C2|A,6|]
[V:T]F,2|F,2(F,F,)A,2G,2|G,2F,4||
A,2|A,2(G,A,)G,2G,2|G,6||
F,2|F,2A,2G,2A,2|G,2G,4||
G,2|A,2A,2A,2G,2|F,6|]
[V:B]D,2|D,2(D,D,)A,,2A,,2|A,,2D,4||
D,2|D,2(A,,A,,)G,,2G,,2|A,,6||
D,2|D,2A,,2A,,2D,2|G,,2G,,4||
G,,2|D,2D,2A,,2A,,2|D,6|]

```

**Comment by paulrosen** [comment]
The first is definitely a bug where the slur doesn't add to the height of the staff. I will take another pass at that.

The second is a mystery! I'll have to debug that.

**Comment by nbruley** [comment]
Doesn't look like the staff height is adjusted in version 6.4.2 yet... I will be patient :)

**Comment by paulrosen** [comment]
Sorry! I've had limited time lately so I decided I had to release what was ready.

**Comment by nbruley** [comment]
Understood! I appreciate all your efforts, particularly when you receive so little in return. Let me know how many hours you spend on these improvements.

**Comment by paulrosen** [comment]
Will be fixed in 6.4.3.

It's hard to say how many hours on all the slur improvements or anything else - it did take me about 4 hours to track down why space wasn't reserved for the slur in your example.

**Comment by paulrosen** [comment]
If there are still issues, either reopen this or open a new issue.

**Comment by nbruley** [comment]
#1 is fixed, thank you very much!
#2 still looks the same as it did.

**Comment by nbruley** [comment]
I did just send a small gift to show I appreciate this library and your continued support of it!
