### ISSUE TITLE
plugin does not render the second line of the abc text

### ISSUE THREAD

**Issue by cbfiddle** [paulrosen/abcjs#99]
The second line of the abc text is effectively deleted by being concatenated onto the X: line.

I suspect the problem is here:
`        abctext += text.replace(/\n+/,"");`
where the "" should be "\n"

<img width="773" alt="screen shot 2017-06-11 at 8 25 29 am" src="https://user-images.githubusercontent.com/6628505/27012158-9d2e3bb0-4e7f-11e7-850e-09c6fdf3464c.png">

<img width="771" alt="screen shot 2017-06-11 at 8 25 39 am" src="https://user-images.githubusercontent.com/6628505/27012157-9d23afba-4e7f-11e7-8c0c-1cecb9d1093c.png">

**Comment by cbfiddle** [comment]
The test case:

[testTitleBug.html.zip](https://github.com/paulrosen/abcjs/files/1066551/testTitleBug.html.zip)

**Comment by paulrosen** [comment]
Thanks for the example. I think that line is designed for another case. I'll figure out what that was so I don't introduce a different bug. I think it was designed to remove a leading new line but is missing the "^".

**Comment by cbfiddle** [comment]
I have looked at the code and I believe you are correct about the missing "^". Using the debugger, I see that this is the line that removes the newline between the first and second lines of text.

It would be really good to get this fixed. It is a serious bug!

**Comment by paulrosen** [comment]
Fixed in 3.1.3
